### ISSUE TITLE
Game freezes and payday process stops responding

### ISSUE THREAD

**Issue by doiy815** [simon-wh/PAYDAY-2-BeardLib#10]
Hi,

I was using BeardLib for some time but I started to have issues for 2 weeks now. My game started to freeze while joining others games. It happens mostly during loading heist/next day but sometimes it happens also during game. It doesn't happen 100% times but I would say 70-80% when joining other lobbies. Didn't have that issue when I was hosting.
When I disable Beardlib everything works fine and game doesn't freeze and has never freezed before.

Cheers

**Comment by simon-wh** [comment]
Do you get a crash log when it freezes? Are you sure that the issue isn't related to a mod that requires BeardLib?

**Comment by doiy815** [comment]
No, I don't get crashlogs. Payday process stops responding and I have to manually close it via task manager. I think I have left PerfectViewModel mod. I will test without it and will see if I my game freezes.

**Comment by simon-wh** [comment]
By any chance would it be lobbies that are hosting custom heists?

**Comment by simon-wh** [comment]
I've been constantly joining lobbies for 20 minutes and haven't been able to replicate the issue.

**Comment by doiy815** [comment]
I think Perfect View Model mod was causing those freezes. I was playing for some time now with BeardLib enabled and with some mods that require it and didn't get any freeze.

**Comment by simon-wh** [comment]
Oh, that's good that you got it sorted out!
