### ISSUE TITLE
LocalizationModule crash

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#102]
Crash.txt: https://pastebin.com/VnZqM6Np
Log: https://pastebin.com/GFg8zx13
Latest BLT + Latest BeardLib and BeardLib Editor...
I can't event turn on PAYDAY 2, it's crashing on loading... I did reinstal, and I only have BLT and BeardLib & BeardLib Editor, nothing else

**Comment by MiamiCenterPL** [comment]
If someone has the same issue, there's FIX -> Uninstal maps, becouse they're crashing it, I'm closing this thread, I was trying to fix it for one week, and when I gived up and writed it, I found fix, damn me...

**Comment by Luffyyy** [comment]
Some people don't know how to write a json file and so you get these errors.
there are online json editors not hard to write them and plenty of guides for dummies.
