### ISSUE TITLE
Game Crashes when Joining as a Client with Standalone Music mods installed

### ISSUE THREAD

**Issue by Nepi-Chan** [simon-wh/PAYDAY-2-BeardLib#104]
(EDIT: It crashes when your the host as well)
(EDIT2: The cause was from a custom HUD, Never mind)
Application has crashed: C++ exception
[string "lib/managers/musicmanager.lua"]:195: attempt to concatenate field 'current_track' (a nil value)

SCRIPT STACK

recreate_right() lib/managers/hud/newhudstatsscreen.lua:250
init() lib/managers/hud/newhudstatsscreen.lua:82
new() core/lib/utils/coreclass.lua:35
_setup_stats_screen() lib/managers/hudmanagerpd2.lua:1044
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
show_stats_screen() lib/managers/hudmanagerpd2.lua:1054
_setup_player_info_hud_pd2() @mods/Void UI/lua/HudManager.lua:221
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
init_finalize_original() lib/managers/hudmanager.lua:169
init_finalize_actual() @mods/KillFeed/killfeed.lua:333
init_finalize() @mods/ContourWorkaround/hudmanager.lua:4
init_finalize() lib/setups/gamesetup.lua:622
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:422

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlAcquireSRWLockExclusive                          
                         ntdll  (???)     RtlNtStatusToDosErrorNoTeb                          
                         ntdll  (???)     RtlTryEnterCriticalSection                          
                         ntdll  (???)     RtlAcquireSRWLockExclusive                          

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.79.387.
	CPU : Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0 
	GPU : NVIDIA GeForce 7900 GS / nv4_disp.dll[6.14.10.8440]
	Language : english
	Memory :     5957MB 280KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
I'm not entirely sure how BeardLib could cause it, but does it still happen?
