### ISSUE TITLE
Doesn't detect mod updates

### ISSUE THREAD

**Issue by AnoosSebeDerniPes** [simon-wh/PAYDAY-2-BeardLib#105]
Beardlib stopped detecting mod updates, despite several of them being outdated. Also, when pressing the 'View page' button, the Steam overlay throws an 'Invalid SSL Certificate' error. I'm guessing this has something to do with modworkshop transferring to a different host

**Comment by Luffyyy** [comment]
problems with modworkshop for now.

**Comment by MazNova** [comment]
I have the same problem, but I can access the mod page normally, seeing that a mod is updated, but Beardlib didn't detect it (telling me all mods are up-to-date).

**Comment by Luffyyy** [comment]
Please read, the issue is known, this is an issue with mws, I'm positive that in a few days it will be resolved, sorry for the long wait.

**Comment by MazNova** [comment]
No problem, I just wanted to add the fact the mods pages are accessible now. But I understand it's not related to the "mod" itself

**Comment by Luffyyy** [comment]
Fixed!
