### ISSUE TITLE
Game Crashes on trying to enter a heist (Host or not)

### ISSUE THREAD

**Issue by Capricoat** [simon-wh/PAYDAY-2-BeardLib#106]
Whenever i attempt to enter a heist, the game crashes on the loading screen (where bain/the broker usually speaks) and it leaves me with this error message

09:37:15 PM Lua: [BeardLib] Could not find any source for track track_14 and event nil current custom track is nil
09:37:15 PM Lua: [BeardLib] Could not find any source for track nil and event music_heist_setup current custom track is nil

Any idea how i can fix this?

**Comment by Luffyyy** [comment]
I need a crashlog.

**Comment by Capricoat** [comment]
How do i manage getting that? Sorry, im not exactly adept at stuff like this

**Comment by Capricoat** [comment]
Nvm. Dont worry about it. I found the logs and the issue seems to be with a particular mod i have installed, in opposed to BeardLib itself, my apologies.
