### ISSUE TITLE
Got a crash with musicmanager?

### ISSUE THREAD

**Issue by joshwist55** [simon-wh/PAYDAY-2-BeardLib#107]
Idk if it is from Beardlib but if it is then that's an issue that needs to be fixed.
Here is my log:
----------------------------------------------------------------------

Fri Oct 27 21:50:01 2017

Application has crashed: C++ exception
[string "lib/managers/musicmanager.lua"]:195: attempt to concatenate field 'current_track' (a nil value)

SCRIPT STACK

recreate_right() lib/managers/hud/newhudstatsscreen.lua:250
init() lib/managers/hud/newhudstatsscreen.lua:82
new() core/lib/utils/coreclass.lua:35
_setup_stats_screen() lib/managers/hudmanagerpd2.lua:1057
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
show_stats_screen() lib/managers/hudmanagerpd2.lua:1067
_setup_player_info_hud_pd2() @mods/Void UI/lua/HudManager.lua:221
setup() 4
setup() lib/managers/hudmanager.lua:269
load_hud() lib/managers/hudmanager.lua:256
init_finalize() lib/managers/hudmanager.lua:169
init_finalize() lib/setups/gamesetup.lua:621
init_finalize() lib/setups/networkgamesetup.lua:15
core/lib/setups/coresetup.lua:422

-------------------------------

**Comment by joshwist55** [comment]
Nevermind it was a hud mod...Guess I'll stick with vanilla for now

**Comment by Luffyyy** [comment]
I doubt it's a hud mod, try using music module crash fix.
