### ISSUE TITLE
BeardLib Music module not loading

### ISSUE THREAD

**Issue by IronAlpha10** [simon-wh/PAYDAY-2-BeardLib#108]
For the past few days I have been working with a few people on the Payday 2 Modding steam discussion section on trying to figure out why custom music wasn't working in my game, after awhile the only thing we could come up with is that the Music Module is not loading on startup at all. Its even supported by the info in the log links. I wanted to bring this over to here to see if it was just a problem with my game or it was something wrong with BeardLib itself.

(Link for info and log file links [here](http://steamcommunity.com/app/218620/discussions/15/2381701715713941656/))

**Comment by Luffyyy** [comment]
As I said I have no idea what is your issue, you have either something wrong with your game, or you installed something incorrectly.
Your beardlib as it seems does not load anything and I can't find a reason for it.
