### ISSUE TITLE
Game keeps telling me a mod needs update while it doesn't

### ISSUE THREAD

**Issue by MazNova** [simon-wh/PAYDAY-2-BeardLib#110]
Everything works fine ! except for this thing, the BeardLib mods manager keeps telling me a mod needs update, but when I go to the mods page, it's the same version as the one installed.

So everytime I load the game, I have like 100ish mods to update, from which like 90-95 are already.

That's not a big issue, just wanted to point it out.

BeardLib version 2.62.

**Comment by Luffyyy** [comment]
I need a mod name that has that issue

**Comment by MazNova** [comment]
I'm sorry, it seems the problem disappeared, perhaps just a mis-loading.

Nevermind you can close this.
