### ISSUE TITLE
ive been anally blasted by a crash so please fix with a crashfix

### ISSUE THREAD

**Issue by TheBoneJuiceMan** [simon-wh/PAYDAY-2-BeardLib#112]
Tue Nov 14 14:23:16 2017

Application has crashed: C++ exception
[string "lib/managers/weaponfactorymanager.lua"]:65: attempt to index a nil value

SCRIPT STACK

_setup() lib/managers/weaponfactorymanager.lua:26
init() lib/managers/weaponfactorymanager.lua:9
new() core/lib/utils/coreclass.lua:35
original() lib/setups/setup.lua:341
init_managers() @mods/base/req/core/Hooks.lua:260
init_managers() lib/setups/menusetup.lua:229
core/lib/setups/coresetup.lua:379

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
                      _setup()  lib/managers/weaponfactorymanager.lua:26            
                        init()  lib/managers/weaponfactorymanager.lua:9             
                         new()  core/lib/utils/coreclass.lua:35                     
                    original()  lib/setups/setup.lua:341                            
               init_managers()  @mods/base/req/core/Hooks.lua:260                   
               init_managers()  lib/setups/menusetup.lua:229                        
                                core/lib/setups/coresetup.lua:379                   

-------------------------------

System information:
Application version : 1.82.440.
CPU : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
DirectX : 12.0 
GPU : NVIDIA GeForce GTX 1050 Ti / nvldumd.dll[23.21.13.8792]
Language : english
Memory :     8075MB 348KB
OS : 6.2.9200 () 0x300-0x1 (64 bits)
Physics : threaded
Renderer : DX9 threaded
Sound : Realtek Semiconductor Corp. (Speaker/Headphone (Realtek High Definition Audio))

And even worse, I've also uninstalled mods related to this crash. And I've tried restarting my payday 2 several times, removing mods that had this weaponfactorymarket.lua thing. And it still crashed, at least tell me how to fix this or have Beardlib fixed. Also I reinstalled Beardlib manually on github and modworkshop. So I'm basically fucked

**Comment by Luffyyy** [comment]
[beardlib.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1472605/beardlib.zip)
Sadly you'll need to provide more information for me to fix it as I myself don't have that issue.
extract the file inside the zip to your beardlib folder and inside 'Hooks' folder, it should ask to replace an existing file.

after that you'll need to run the game, crash and send me the log file(mods/logs/[date].txt)
hopefully I'll be able to do something with it, if not I'll try more.

**Comment by TheBoneJuiceMan** [comment]
Tue Nov 14 16:58:05 2017


Application has crashed: C++ exception
mods/BeardLib/Hooks/Fixes.lua:43: attempt to index a nil value



SCRIPT STACK

_setup() lib/managers/weaponfactorymanager.lua:26
init() lib/managers/weaponfactorymanager.lua:9
new() core/lib/utils/coreclass.lua:35
original() lib/setups/setup.lua:341
init_managers() @mods/base/req/core/Hooks.lua:260
init_managers() lib/setups/menusetup.lua:229
core/lib/setups/coresetup.lua:379


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main
Script stack:
                      _setup()  lib/managers/weaponfactorymanager.lua:26            
                        init()  lib/managers/weaponfactorymanager.lua:9             
                         new()  core/lib/utils/coreclass.lua:35                     
                    original()  lib/setups/setup.lua:341                            
               init_managers()  @mods/base/req/core/Hooks.lua:260                   
               init_managers()  lib/setups/menusetup.lua:229                        
                                core/lib/setups/coresetup.lua:379                   

-------------------------------

System information:
	Application version : 1.82.440.
	CPU : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 Ti / nvldumd.dll[23.21.13.8792]
	Language : english
	Memory :     8075MB 348KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speaker/Headphone (Realtek High Definition Audio))

too bad the fix also crashes

**Comment by Luffyyy** [comment]
after that you'll need to run the game, **crash** and **send me the log file(mods/logs/[date].txt)**

**Comment by TheBoneJuiceMan** [comment]
oh ok

https://ufile.io/f3gty

**Comment by TheBoneJuiceMan** [comment]
Hey luffy, did you read the crash log that I sent you?

**Comment by Luffyyy** [comment]
[beardlib.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1473474/beardlib.zip)
Do the same thing, it might resolve the crash, but still send me the log file.

**Comment by Luffyyy** [comment]
[beardlib.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1473575/beardlib.zip)
I had to go to sleep, this should solve the issue but still send me the BLT log file like before for any chance.

The main issue was that a custom weapon had a custom weapon mod that didn't "exist"

> [BeardLib] [Info] Mod at path 'assets/mod_overrides/GiTS Carry Handle Sight' is disabled!

it did exist but was not loaded because it's disabled, some mod apparently uses a really bad method to find a mod(ie: checking if it exists in mod overrides)

**Comment by TheBoneJuiceMan** [comment]
Also one other thing, it's that I can't install the update to Beardlib and
to the many mods I have with it. As they're all stuck in the "waiting for a
response" limbo.

**Comment by Luffyyy** [comment]
Not sure to be honest, update the update from modworkshop, if it keeps happening open a new issue.
