### ISSUE TITLE
Friends keep crashing.

### ISSUE THREAD

**Issue by Criken956** [simon-wh/PAYDAY-2-BeardLib#12]
My friends who join my lobby crash on some heists like Mallcrashers or when going to the next day of a heist with this crashlog:

**Comment by Criken956** [comment]
Mon Oct 31 22:32:00 2016


Application has crashed: C++ exception
[string "core/lib/managers/coresequencemanager.lua"]:4002: attempt to index local 'body' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
Application version : 1.56.66
CPU : AMD Phenom™ II X4 965 Processor (2 cores); SSE; SSE2; SSE3
DirectX : 10.0 
GPU : AMD Radeon HD 7700 Series / aticfx32.dll[8.17.10.1474]
Language : @ID94cca2fdaccfc2cd@
Memory :     16370MB 532KB
OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
Physics : threaded
Renderer : DX9 threaded
Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by LBLuffy** [comment]
Are you sure its BeardLib causing?

**Comment by Criken956** [comment]
Beardlib is the only mod they have installed that has the core/lib/managers/coresequencemanager.lua hook. Same on my end too.

**Comment by LBLuffy** [comment]
Well according to the crash you sent to me it does not point 100% at BeardLib remember that other mods might have links to the script file it might look like they are not touching it but they are, In any way, Whoever is crashing can give their list of mods including any custom weapons in mod_overrides?

**Comment by Criken956** [comment]
They only have BeardLib installed.

**Comment by simon-wh** [comment]
I've gotten that crash with 0 mods installed on the client and the server.
I'm pretty sure it is a game issue, not BeardLib.

**Comment by Criken956** [comment]
Ah okay, thank you.
