### ISSUE TITLE
Crashing when restarting custom heist after Update 2.76

### ISSUE THREAD

**Issue by Shad0wlife** [simon-wh/PAYDAY-2-BeardLib#121]
There seens to be an issue with the file conversion or something with 2.76.
I played Eclipse Research Facility, trying to fix crashes with access violations I had, but instead on mission restart, the crash I got was from BeardLib:

`Application has crashed: C++ exception
[string "--mods/BeardLib/Classes/CustomPackageManager...."]:119: attempt to call field 'ext_convert' (a table value)

SCRIPT STACK

Unload() @mods/BeardLib/Modules/AddFilesModule.lua:33
unload_packages() @mods/BeardLib/Hooks/CoreWorldDefinition.lua:44
core/lib/setups/coresetup.lua:648`

This seems to originate from the 2.76 update which changed that line from
`local ids_ext = Idstring(typ)`
to
`local ids_ext = Idstring(self.ext_convert[typ] or typ)`

and ext_convert is what caused the crash according to crashlog.

**Comment by Luffyyy** [comment]
Fixed already(the code you posted is actually after I fixed it) I just added a new module and needed people to test it and someone weirdly told me about an issue but never explained it fully so I had to hold it.
