### ISSUE TITLE
Crashes when starting Payday 2 with this and SuperBLT

### ISSUE THREAD

**Issue by BreakinBenny** [simon-wh/PAYDAY-2-BeardLib#124]
Now that you've fixed the BeardLib-Editor problem with previewing vanilla levels, it's somehow made BeardLib crash Payday 2 shortly after booting it. Check out the crash dump:

`Sun Dec 31 15:45:03 2017

Application has crashed: C++ exception
mods/BeardLib/BeardLibInit.lua:20: attempt to index field 'dialog' (a nil value)

SCRIPT STACK

Call() @mods/base/req/core/Hooks.lua:109
init() @mods/base/lua/MenuManager.lua:10
new() core/lib/utils/coreclass.lua:35
original() lib/setups/setup.lua:363
init_managers() @mods/base/req/core/Hooks.lua:260
init_managers() lib/setups/menusetup.lua:269
core/lib/setups/coresetup.lua:379

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
                        Call()  @mods/base/req/core/Hooks.lua:109                   
                        init()  @mods/base/lua/MenuManager.lua:10                   
                         new()  core/lib/utils/coreclass.lua:35                     
                    original()  lib/setups/setup.lua:363                            
               init_managers()  @mods/base/req/core/Hooks.lua:260                   
               init_managers()  lib/setups/menusetup.lua:269                        
                                core/lib/setups/coresetup.lua:379                   

-------------------------------

System information:
	Application version : 1.86.496.
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960 / nvldumd.dll[23.21.13.8871]
	Language : english
	Memory :     8132MB 48KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Högtalare (High Definition Audio Device))`

**Comment by Luffyyy** [comment]
I need full blt log.

**Comment by Iamgoofball** [comment]
using latest beardlib and superblt, can't reproduce

did you update your superblt to the latest from https://superblt.znix.xyz

**Comment by BreakinBenny** [comment]
@Iamgoofball I went ahead and got the latest version from that website, my problem is then solved!

(Heh, guess it's consideration time to include that link on GitLab!)

**Comment by Luffyyy** [comment]
Alright, good that your issue is solved.
