### ISSUE TITLE
Bug list

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib#129]
Edit: This is editor bugs mostly I think, whoops wrong place
-Bug: Environment/Sound units cannot be seen while the visual option is enabled.

-Bug: Holding right click on a unit and then holding shift while letting go of right click will cause the cursor to continue selecting things.

-Bug: Moving elements when selection starts with a unit will cause the elements position to not update on save and reload.

-Bug: (kinda): Beardlib package paths need to be updated to show newer heist packages, currently its a struggle to load in anything past diamond heist.

-Bug: Moving a unit from one continent to another (using the dropdown) will not properly move it to the other continent file or change its id number to the correct continent.
Eg. Moving this money bundle from Bdrop to World did not change its 400000 'Bdrop' id to the 100000 'World' id

**Comment by Luffyyy** [comment]
1. those two options seem to do their job correctly. 
![image](https://user-images.githubusercontent.com/11510099/36664681-181f2826-1aee-11e8-8aad-4d66e59f08ac.png)

2. Not sure, I tried doing this and nothing happens, do you have 'Keep mouse active while flying' option on maybe?

3. Weirdly not happening to me.

4. I was sure I did update for diamond heist ... I'll try again.

5.Will fix.

**Comment by RexTheWho** [comment]
1. Works now

2. Disabled at all times, unsure what would be causing it.

3. Try moving large amounts of elements, save, reload

**Comment by Luffyyy** [comment]
Repost suggestions in editor issues tab, please
