### ISSUE TITLE
Crash when clicking Contract Broker

### ISSUE THREAD

**Issue by NerdVenom** [simon-wh/PAYDAY-2-BeardLib#13]
Unless I have the mod "Restoration Mod", I crash everytime I try to use the Contract Broker. I've tried getting fresh copies of both BLT and BeardLib but I still crash. I noticed that removing BeardLib fixes the crash. This is only running BLT and BeardLib along with some mod_overrides.

Crash.txt is attached
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/577765/crash.txt)

**Comment by simon-wh** [comment]
You have Out of Frame installed which will crash the game if Restoration Mod is not present
