### ISSUE TITLE
Custom Package issues

### ISSUE THREAD

**Issue by steam-test1** [simon-wh/PAYDAY-2-BeardLib#132]
If you load a normal map and then try to load a custom map with custom packages the game will crash before loading

```
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
        _create_statics_unit()  core/lib/utils/dev/editor/coreworlddefinition.lua:921  
                      create()  core/lib/utils/dev/editor/coreworlddefinition.lua:522  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:587                        
                                core/lib/setups/coresetup.lua:402 
```

The map loads if it's the first map you load

Also can custom packages be used outside of maps

**Comment by Luffyyy** [comment]
How did you load a normal map and custom map? did you use the editor? 
also can I have the custom map to test this?

Yeah, just call PackageManager:load like you'd load a normal package > https://github.com/simon-wh/PAYDAY-2-BeardLib/wiki/PackageModule

**Comment by steam-test1** [comment]
I loaded a normal map and then quit the map, then tried to load the custom map
The map
https://modworkshop.net/mydownloads.php?action=view_down&did=21918

**Comment by Luffyyy** [comment]
Jesus why does the mod still have the old music module, it can seriously break the latest BeardLib.

I'm gonna assume that some units have some assets that are being unloaded by the normal heist(there are some units that already exist in the game or were loaded by the editor a long time ago when it exported the model and texture which is now unrequired). So here what I'm gonna, I'll clean the mod a bit and send it to you, you can reupload the mod fully and I can give you permission to do so.

**Comment by Luffyyy** [comment]
Here https://www.dropbox.com/s/0p51n8mai1pp1um/No%20Mercy.7z?dl=0 the issue should be gone.

**Comment by steam-test1** [comment]
Thanks for optimizing the map it loads quicker now
