### ISSUE TITLE
Beardlib Crashing Safehouse Raids

### ISSUE THREAD

**Issue by LuciousTPK** [simon-wh/PAYDAY-2-BeardLib#133]
While I am new to the whole modding process of Payday 2 I am very certain I have pin pointed Beardlib to be cause of safehouse raids to be unplayable (Mainly by deleting everything, or rather pulling out of file, that wasnt superblt or beardlib). Regardless of whether or not mods are in play doesnt seem to effect that raid until I pulled beardlib, then it started working. Even to double check I put every mod back in (except obviously mods that required beardlib, just three custom mask and Id say a selection of 15 custom heist tracks) and it still worked.

I can't say for certain but I also get crashes when loading player created maps when beardlib is around, but those crashes aren't consistent enough to really blame on beardlib and could just be something else, its hard to say. The same goes for occasional crashes while spreeing in a lobby, again I am unsure.

If I could get help that would be great! It took a lot of effort to figure out how to actually get custom heist tracks to play with beardlib!

**Comment by Luffyyy** [comment]
Let's just learn something about PD2, the game is 32 bit which means it cannot use more than 4GB of RAM and most likely would crash around 3GB of RAM usage.

Safehouse/Safehouse raid are two heists that are extremely heavy for the game as they load far too much content for the game to hold without crashing.

You also can't blame BeardLib for crashing custom heists as it's the thing that runs them, most custom heists require you to play on medium settings so your RAM usage wouldn't be as high, I've done a lot of work to try optimizing custom heists, but I'm reaching the limits on what I can do.

As to why BeardLib might be crashing, you might be running some BeardLib mods(maybe didn't notice), I don't think BeardLib does anything RAM demanding without it needing to load anything.

**Comment by LuciousTPK** [comment]
Alrighty
