### ISSUE TITLE
Custom music not loading

### ISSUE THREAD

**Issue by notlelel** [simon-wh/PAYDAY-2-BeardLib#147]
When selecting "custom heist playlist" as the current heist's music, custom music will sometimes not load.
I couldn't reliably replicate the bug, but it seems it only happens with non-SuperBLT music.

**Comment by notlelel** [comment]
Also the game will sometimes crash when restarting mid-game.

```
Application has crashed: access violation

...

Current thread: Main
Script stack:
                  set_switch()  @mods/base/req/core/Hooks.lua:260                   
          check_music_switch()  core/lib/managers/coremusicmanager.lua:83           
                    at_enter()  lib/states/ingamewaitingforplayers.lua:439          
                  trans_func()  lib/states/gamestate.lua:22                         
            _do_state_change()  core/lib/utils/game_state_machine/coregamestatemachine.lua:124  
                  end_update()  core/lib/utils/game_state_machine/coregamestatemachine.lua:104  
                  end_update()  lib/setups/setup.lua:891                            
                  end_update()  lib/setups/gamesetup.lua:775                        
                  end_update()  lib/setups/networkgamesetup.lua:33                  
                                core/lib/setups/coresetup.lua:583     
```

**Comment by Luffyyy** [comment]
Sorry for the long reply, was busy with school project.

The thing is, most people have them working just fine and the cases where it doesn't work is mainly not BeardLib's fault.
the only thing I can suggest is running entirely clean with SBLT + BeardLib and trying the custom musics again.

**Comment by Luffyyy** [comment]
Joining this to #164 same thing applies to you, if the issue still persists I recommend adding me in discord. Luffy#9999.
