### ISSUE TITLE
Attempting to restart Custom Heists with voicelines crashes

### ISSUE THREAD

**Issue by Omen267901** [simon-wh/PAYDAY-2-BeardLib#148]
Attempting to restart any custom heist that adds voicelines via Beardlib causes a crash.

**PAYDAY 2 Crash log**

    Application has crashed: C++ exception
    mods/BeardLib/Classes/Elements/ElementCustomSound.lua:58: attempt to index field '_ws' (a nil value)
    SCRIPT STACK
    play_secondary() @mods/BeardLib/Classes/Elements/ElementCustomSound.lua:81
    on_executed() @mods/BeardLib/Classes/Elements/ElementCustomSound.lua:163
    execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
    _trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
    on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
    on_executed() lib/managers/mission/missionscriptelement.lua:18
    on_executed() core/lib/managers/mission/coreelementarea.lua:121
    f() core/lib/managers/mission/coreelementarea.lua:220
    update() core/lib/utils/coreevent.lua:158
    update() core/lib/managers/mission/coremissionmanager.lua:529
    update() core/lib/managers/mission/coremissionmanager.lua:160
    core/lib/setups/coresetup.lua:503
    -------------------------------
    Callstack:
             payday2_win32_release  (???)     ???                                                 
             payday2_win32_release  (???)     zip_get_name                                        
             payday2_win32_release  (???)     zip_get_name                                        
    -------------------------------
    Current thread: Main
    -------------------------------
    System information:
    	Application version : 1.89.554.
    	CPU : AMD FX(tm)-6300 Six-Core Processor (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
    	DirectX : 12.0 
    	GPU : NVIDIA GeForce GTX 950 / nvldumd.dll[23.21.13.9101]
    	Language : english
    	Memory :     12286MB 1008KB
    	OS : 6.2.9200 () 0x100-0x1 (64 bits)
    	Physics : threaded
    	Renderer : DX9 threaded
    	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

BLT log attached if needed.
[2018_04_02_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1868334/2018_04_02_log.txt)

**Comment by Luffyyy** [comment]
Please try the latest commit.

**Comment by Omen267901** [comment]
This has fixed it for me.
