### ISSUE TITLE
BeardLib. Custom weapon. Akimbo crash.

### ISSUE THREAD

**Issue by Hamsterrhino** [simon-wh/PAYDAY-2-BeardLib#16]
I installed some custom weapons, one of the was akimbo. As soon as I shoot from it, Game crashes.
Application has crashed: C++ exception
[string "lib/units/weapons/akimboweaponbase.lua"]:85: bad argument #1 to 'insert' (table expected, got nil)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      AcXtrnal  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.63.1
	CPU : Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 1070 / nvd3dum.dll[10.18.13.6839]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8190MB 504KB
	OS : 6.1.7600 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))
Really upset with it.

**Comment by Luffyyy** [comment]
May I know which mod is it? It's probably that the mod is at fault.

**Comment by Luffyyy** [comment]
No information given, therefore, I am closing issue.
