### ISSUE TITLE
Unnecessary case sensitivity with implementing the sounds module

### ISSUE THREAD

**Issue by VxWolf** [simon-wh/PAYDAY-2-BeardLib#161]
This works
``
<Sounds directory="assets">
    <sound id="soundid" path="sound.ogg">
</Sounds>
``
This doesn't (and frankly should)
``
<sounds directory="assets">
    <sound id="soundid" path="sound.ogg">
</sounds>
``
Notice <**S**ounds> vs <**s**ounds>

**Comment by Luffyyy** [comment]
Something I plan in the future but not now, for now module headers should be uppercase.
