### ISSUE TITLE
Crash on removing levelin project manager.

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib#168]
Removing a map here shows "nil" also.
![image](https://user-images.githubusercontent.com/26837908/40317188-4da3b4a6-5d53-11e8-8fba-dd3f8b3a7f9e.png)

Crashlog.

Application has crashed: C++ exception
mods/BeardLib-Editor/Classes/MapProjectManager.lua:453: bad argument #1 to 'pairs' (table expected, got string)

SCRIPT STACK

@mods/BeardLib-Editor/Classes/MapProjectManager.lua:453
clbk() 178
RunCallback() 485
MousePressed() 87
MousePressed() 162
mouse_press() 410
lib/managers/mousepointermanager.lua:339

-------------------------------

**Comment by Luffyyy** [comment]
editor issue
