### ISSUE TITLE
Crash on selecting vanilla level lootbag spawner

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib#169]
Application has crashed: C++ exception
.../BeardLib-Editor/Classes/Map/Elements/lootbagelement.lua:28: attempt to perform arithmetic on field 'spawn_dir' (a nil value)

SCRIPT STACK

update() @mods/BeardLib-Editor/Classes/Map/MissionEditor.lua:115
update() @mods/BeardLib-Editor/Classes/MapEditor.lua:550
func() @mods/BeardLib-Editor/Core.lua:312
Call() @mods/base/req/core/Hooks.lua:109
original() @mods/base/lua/GameSetup.lua:6
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540

-------------------------------

**Comment by Luffyyy** [comment]
STOP POSTING HERE

**Comment by RexTheWho** [comment]
My bad
