### ISSUE TITLE
Access Violation Crash With Beardlib 3.05

### ISSUE THREAD

**Issue by billybobsatan** [simon-wh/PAYDAY-2-BeardLib#177]
I'm only running beardlib/superblt and I receive the following crash whenever the buildup phase occurs:

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
        _create_statics_unit()  core/lib/utils/dev/editor/coreworlddefinition.lua:921  
                      create()  core/lib/utils/dev/editor/coreworlddefinition.lua:522  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:638                        
                                core/lib/setups/coresetup.lua:405                   

-------------------------------

System information:
	Application version : 1.91.619.
	CPU : AMD A12-9800 RADEON R7, 12 COMPUTE CORES 4C+8G (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon R7 Graphics / aticfx32.dll[21.19.524.768]
	Language : english
	Memory :     11715MB 60KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Doubt BeardLib causes it. Try verifying your files, you might also have Maps/mod overrides mods.

**Comment by billybobsatan** [comment]
Oh, silly me. It seems one of my enemy reskin mods broke it. Thanks for reminding me about mod_overrides, I completely forgot to clear it!
