### ISSUE TITLE
Custom heist are still not syncing the id properly on crimenet

### ISSUE THREAD

**Issue by Nepgearsy** [simon-wh/PAYDAY-2-BeardLib#178]
As in you see others playing maps that arent the one they really play.

**Comment by Luffyyy** [comment]
![image](https://user-images.githubusercontent.com/11510099/43145406-f9c45d4e-8f67-11e8-89e5-f00b39d82540.png)

**Comment by Matthelzor** [comment]
![image](https://user-images.githubusercontent.com/17231936/44682846-cf774b80-aa44-11e8-967e-d2bae5dc8b13.png)
