### ISSUE TITLE
Custom Sights with Fixed (non-changeable) Reticles crash game in VR

### ISSUE THREAD

**Issue by GreenGhost21** [simon-wh/PAYDAY-2-BeardLib#179]
```
Application has crashed: C++ exception
[string "lib/units/cameras/scopecamera.lua"]:70: attempt to index local 'material' (a nil value)



SCRIPT STACK

link_scope() lib/units/beings/player/states/vr/playermenu.lua:194
set_scope_enabled() lib/units/weapons/scopebase.lua:22
original() lib/units/weapons/menuraycastweaponbase.lua:127
done_cb() @mods/base/req/core/Hooks.lua:260
clbk_part_unit_loaded() lib/managers/weaponfactorymanager.lua:852
assemble_from_blueprint() lib/managers/weaponfactorymanager.lua:631
assemble_from_blueprint() lib/units/weapons/menuraycastweaponbase.lua:98
spawn_weapon() lib/managers/menu/menuscenemanager.lua:2697
spawn_item_weapon() lib/managers/menu/menuscenemanager.lua:2704
done_cb() lib/managers/blackmarketmanager.lua:4643
update() lib/managers/blackmarketmanager.lua:1948
update() lib/setups/setup.lua:845
update() lib/setups/menusetup.lua:336
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:540


-------------------------------

Callstack:

      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlRestoreLastWin32Error                            


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.1.1
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 [Video:3072,Sys:0,Shared:1023,Vendor:0x10de]
	Language : english
	Memory :     16338MB 728KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX11 threaded
	Sound : Oculus VR, LLC (Headphones (Rift Audio))
```

Some examples of what I mean:
[US Optics ST-10 Scope](https://modworkshop.net/mydownloads.php?action=view_down&did=19427)
[SIGTac CP1 Prismatic Scope](https://modworkshop.net/mydownloads.php?action=view_down&did=19156)
[ELCAN M145 Sight](https://modworkshop.net/mydownloads.php?action=view_down&did=17388)

I understand if this won't be a top priority, since VR is kind of a niche thing, but it'd still be nice to see a fix.

(Also, come to think of it, I'm not sure if the crash is because of the lack of customizable reticles, or because the scope should've had dual rendering but didn't)

**Comment by Luffyyy** [comment]
does the issue still happen? I don't exactly have a headset to test these.

**Comment by Luffyyy** [comment]
Hopefully I'll get a Rift S in the close month or two and I'll be able to test this.

**Comment by GreenGhost21** [comment]
I just got back into Payday 2, apologies for the radio silence.

I'll test it once I boot the game up in VR again, which _should_ be soon.

**Comment by Luffyyy** [comment]
Well good timing, my headset arrived today. Sadly though, payday 2 doesn't seem to like one of my mods. So it just shows loading without allowing me to control anything.

**Comment by Luffyyy** [comment]
And confirmed working. You most likely used an old version of a custom weapon/weapon mod. I used m416 with coyote sight and it worked just fine. 
![20190722165836_1](https://user-images.githubusercontent.com/11510099/61639587-79d30f80-aca4-11e9-94be-c948d4e0e0c9.jpg)

This means that if any of the weapon parts do crash, it's most likely not BeardLib's fault.

**Comment by GreenGhost21** [comment]
IIRC the issue occurred only with weapons that didn't have a red-dot, like the ones I listed. Ones that had a red-dot (like the Coyote sight you're using in your example) work just fine.
