### ISSUE TITLE
Custom music playlist issue still happening.

### ISSUE THREAD

**Issue by notlelel** [simon-wh/PAYDAY-2-BeardLib#182]
So apparently the issue with custom music sometimes not playing when chosen at random still happens. I had no custom song in my playlist for a while, but then I decided to see if the bug was still there, and it was.
Also it doesn't seem like I'm the only one either.
https://steamcommunity.com/app/218620/discussions/15/1729828401662334389/

**Comment by Luffyyy** [comment]
Perhaps really late but checking again there's no real issue. And since there aren't many people reporting this I'm closing it for now.
