### ISSUE TITLE
Game crashes when loading into any level

### ISSUE THREAD

**Issue by H2ADIL** [simon-wh/PAYDAY-2-BeardLib#183]
The game crashes whenever I try to load into any level, whether it be online or offline. I don't see any error messages popping up. The only thing that happens is that the game just closes itself, as if I alt + F4 the application. I tried removing any mods, especially custom music mods, just to be safe. The only ones I have are music replacer mods for An Unexpected Call, and VoidUI. 

EDIT: I have SuperBLT installed.
EDIT 2: I found the problem, and it looks like VoidUI is causing the problem. I don't know why it is, and I hope you do find a solution, because the look and feel of VoidUI is just too good to let go. But if there isn't any, then I'll make do.

**Comment by Luffyyy** [comment]
I'm clearly not the creator of VoidUI.
