### ISSUE TITLE
broke.

### ISSUE THREAD

**Issue by LithTheKitten** [simon-wh/PAYDAY-2-BeardLib#184]

**Comment by LithTheKitten** [comment]
either beardlib hates everything or something broke, I got super blt on, silent assassin, carry stacker reloaded, wolfhud mastered, oh no even more skillsets, and this bearlib. idk wth is wrong but I cant even use a ton of gun mods anymore and even with them removed its still crashing the damn game when I try to launch a heist.

**Comment by Luffyyy** [comment]
No information given.

**Comment by LithTheKitten** [comment]
idk wtf to put.

**Comment by Luffyyy** [comment]
You have no proof BeardLib is causing the issues. You need to provide a crashlog which is found in %localappdata%/payday 2/crash.txt
