### ISSUE TITLE
Assets don't load when using the use_clbk parameter with the AddFilesModule

### ISSUE THREAD

**Issue by steam-test1** [simon-wh/PAYDAY-2-BeardLib#185]
Example code
```
<AddFiles file="add.xml" use_clbk="self:Loadassets"/>

function ModNameCore:Loadassets()
	if modname and modname.Options:GetValue("assetcheck") then
		return true
	else
		return false
	end
end
```

No assets in that file load, even when the function returns true

use_clbk works with PackageModule

**Comment by Luffyyy** [comment]
Seems to work in my case

**Comment by steam-test1** [comment]
Could provide an example or the project that you got it to work on?

**Comment by steam-test1** [comment]
If the option is on the saws on Green Bridge should be a solid yellow
https://github.com/steam-test1/temp/blob/master/PDTH%20HUD%20use_clbk.zip

**Comment by Luffyyy** [comment]
Yeahhh I had enough with this. I'll update PDTH HUD to use the newest format and merge assets with mods this is getting out of hand.

**Comment by steam-test1** [comment]
You don't need to update the Hud
The public version doesn't use that feature it was just example
As you can't replicate the issue it's not a issue

**Comment by Luffyyy** [comment]
Either way, the mod is using a very old format.
I'm gonna update the public version, the use_clbk on add files will get a small change.

**Comment by steam-test1** [comment]
Can you only re enable the equipment sequence manager stuff
As the other equipment stuff in the assets folder was just experimental and not for release

**Comment by Luffyyy** [comment]
Not sure which you mean. But here 
https://puu.sh/BlmWG/c8656c29bf.zip
-Updated format (wait for beardlib 3.1 update/use latest commit)
-Moved mod overrides to the mod itself
-Mod should be able to have auto updating now. ID is set to "19900". All you need to do is set a desired version number (or keep at 1.0) can be also a string and set it in the mod page itself too.
-Had a small issue with my hud mod so I quickly shortened objectives code to use a simple post hook (this can probably be done to some more hud elements, this lowers the chance of the mod breaking each update).
