### ISSUE TITLE
Incorrect pocket ecm amount if that user has BeardLib mod installed

### ISSUE THREAD

**Issue by PJzuza** [simon-wh/PAYDAY-2-BeardLib#186]
I can confirm this is a BeardLib issue. The BeardLib user will have 3 pockets ecm for other people's view. For more information in a full details. Please check [This thread](https://steamcommunity.com/app/218620/discussions/15/1736588252405374602/)

**Comment by Luffyyy** [comment]
Try the latest commit

**Comment by PJzuza** [comment]
It worked I think though you may need to test more as I normally don't use BeardLib mod btw.

**Comment by Luffyyy** [comment]
Nah I'm pretty sure that was it.

**Comment by PJzuza** [comment]
Nevermind. My friend said I still have 3 pocket ecm on his view. Here is the version I'm using.
![Pic](https://steamuserimages-a.akamaihd.net/ugc/958592564576235956/B0B779FE5FC0B1252DCB5E671958B9EB40A27D28/)

**Comment by Luffyyy** [comment]
That's what you are not meant to do. The version to update should've showed 3.05 which is smaller than 3.1 so you downgraded.

**Comment by PJzuza** [comment]
@Luffyyy understandable. Though people may do the same as I did so you may have to find a way to fix it.

**Comment by Luffyyy** [comment]
I don't know if you realize that I released the version already.

**Comment by PJzuza** [comment]
Nope. Since I'm quite busy checking some bugs via reading a mission script with my friends so I have no idea xD
