### ISSUE TITLE
add_special_equipment called incorrectly when BeardLib is installed.

### ISSUE THREAD

**Issue by PixelMirror** [simon-wh/PAYDAY-2-BeardLib#189]
For some reason it seems that whilst BeardLib is running it causes the function "add_special_equipment" to be ran attempting to add other player's equipment to your client. On the default HUD this doesn't show but the function is still ran even though it isn't when BeardLib isn't loaded. But on HUDs such as the PDTH Hud it causes incorrect special equipment such as keycards and crowbars to be shown as yours. These cannot be used and cause confusion. The issue doesn't occur when joining from the start but rather only when joining an in-game session.

Doing a traceback in the add_special_equipment function returns this for the instances where it incorrectly adds special equipment.

```
        [string "lib/managers/hudmanagerpd2.lua"]:418: in function 'add_teammate_special_equipment'
        [string "lib/managers/playermanager.lua"]:3325: in function 'set_synced_equipment_possession'
        [string "lib/network/handlers/unitnetworkhandler.lua"]:2778: in function <[string "lib/network/handlers/unitnetworkhandler.lua"]:2774>
```

**Comment by Luffyyy** [comment]
afaik, BeardLib does not touch special equipments. Are you sure you don't have a mod that uses BeardLib that causes it?

**Comment by PixelMirror** [comment]
I continued testing and it happened without any additional mods but rather only the base of BLT. It seems that unless I press ready in an in-progress lobby prior to my loading finishing I.E waiting a bit whilst others play it'll run the function again giving me any special equipment that presumably the host has, this effect is only client side and I don't actually have them. This should be an issue with the base game too but seeing as it doesn't show it in the vanilla HUD regardless of the function running I doubt a lot of people notice.

If anyone would be willing to help figure out how to fix it regardless of insignificance to BeardLib that would be great though.
