### ISSUE TITLE
BeardLib causes armor skins not to show up for other players.

### ISSUE THREAD

**Issue by Kuziz** [simon-wh/PAYDAY-2-BeardLib#19]
No crash logs or error logs, some function is just outdated probably.

Removing BeardLib restores proper vanilla functionality.

**Comment by Luffyyy** [comment]
Are you sure this is BeardLib's fault? I tested and found out this happens even without **BLT**.

**Comment by Kuziz** [comment]
As soon as I removed BeardLib, my armor skin would synchronise for my crew members. I tried removing all the other mods I had and the problem persisted until BeardLib's removal.

**Comment by venomousbeetle** [comment]
It's definitely beardlib, I just went through and deactivated all my mods and they could see them again, reactivated about 6 (including beardlib) and they couldnt see anymore, then I figured the only thing that sounds like it could conflict was beardlib and when I removed beardlib it worked again.

I did this before seeing this github report page so no bias

**Comment by Kuziz** [comment]
I went through various hooks and pinpointed NetworkPeer to being the one causing the issue.

**Comment by Luffyyy** [comment]
Oh I made a mistake when I was testing, I thought if you had beardlib then you can't see the armors but yeah I'll look into it.

**Comment by Luffyyy** [comment]
I found out the issue is because of BlackMarketManager:outfit_string_from_list()
Seems like overkill didn't bother to support armor skin value there..
