### ISSUE TITLE
After last update crashes

### ISSUE THREAD

**Issue by chromKa** [simon-wh/PAYDAY-2-BeardLib#196]
Crashes after intro - PRESS ANY KEY

`Application has crashed: C++ exception
[string "lib/managers/blackmarketmanager.lua"]:4082: attempt to index a nil value

SCRIPT STACK

_aquire_weapon() lib/managers/upgradesmanager.lua:445
_aquire_upgrade() lib/managers/upgradesmanager.lua:395
aquire() lib/managers/upgradesmanager.lua:356
aquire_from_level_tree() lib/managers/upgradesmanager.lua:152
load() lib/managers/experiencemanager.lua:970
_load_cache() lib/managers/savefilemanager.lua:1071
_load_done() lib/managers/savefilemanager.lua:912
lib/managers/savefilemanager.lua:1485`

**Comment by Luffyyy** [comment]
Did you get it solved?
