### ISSUE TITLE
Reproducable Music Module crash

### ISSUE THREAD

**Issue by NSACloud** [simon-wh/PAYDAY-2-BeardLib#201]
I'm having issues with the music module and a music pack I'm making. The pack itself works fine most of the time, but I have found some scenarios that will cause the game to repeatedly crash upon getting to the loadout/ready screen on some heists. The pack consists of both menu and heist tracks. I'm fairly certain that I've set up the .ogg and .xml files properly.

One situation that I've found that will cause a crash will happen when any of the custom songs are selected under the soundtrack tab. Some heists such as Firestarter will work without issues, however,  Shacklethorne Auction and Reservoir Dogs will immediately crash upon getting to the loadout screen. Other heists may crash when loading the second day. Sometimes the game will freeze completely on loadout and not even crash to desktop.

At first I thought the pack was too large in file size, so I compressed the audio from ~270 MB to ~80 MB. This did not solve the issue. I have tested this on 2 of my PC's and I had a friend test it, yet all of them still crash at the same points.  The only mods I run are VoidUI and Simple Toggle Interact, but I uninstalled them and the problem still persists.

All clients were running the latest SuperBLT and BeardLib.

I have attached the 3 crash.txts from the different systems I tested on, as well as the pack itself. If you need any more information, let me know.

[pc1crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/2781060/pc1crash.txt)
[pc2crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/2781061/pc2crash.txt)
[pc3crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/2781062/pc3crash.txt)

Google Drive Download Link:
https://drive.google.com/open?id=1l7GlZsg9fFtP7afzY5p23HMXnQjfXyqp

**Comment by NSACloud** [comment]
As a workaround, I converted everything to the old .movie format and it now works fine with no crashes.

**Comment by Luffyyy** [comment]
Welp not much that I could do if I had to assume it's SBLT's fault.
