### ISSUE TITLE
Log spam when Instance added into main.xml and map

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#207]
This does nothing to the game itself, but when you're searching for issues in Logs, that's just not looking good;
`03:10:54 PM Lua: [BeardLib] [WARNING] Script Mod with ID: 'unknown', Path:'Maps/Golden Cruise 2.0/levels/cruise_room/world/world.continent' may potentially overwrite changes from other mods! Continuing...`

And the log.txt file looks like this; 
https://i.imgur.com/rhHDqec.png

It should type that only once.

**Comment by Luffyyy** [comment]
Pretty old issue, may you give me a mod that has this issue?

**Comment by MiamiCenterPL** [comment]
I've sent you the map over discord.
