### ISSUE TITLE
WeaponModModule: Unable to give add-on weapon mods custom global values

### ISSUE THREAD

**Issue by the-almighty-carl** [simon-wh/PAYDAY-2-BeardLib#208]
Not a game-breaking issue as much as a missing/broken feature. With add-on melee weapons, you're able to define a custom global value to be displayed in the inventory by adding these parameters in the main <Melee> tag:

`dlc="global_value_id" global_value="global_value_id"`

However, this same method doesn't seem to work as intended with add-on weapon mods. Adding both the "dlc" parameter and the "global_value" parameters to a <WeaponMod> tag results in the given weapon mod correctly displaying the intended global value, but becoming unavailable for purchase in the inventory regardless of whether or not "drop" and "is_a_unlockable" are set to "true" or "false," and omitting the "global_value" parameter and not the "dlc" parameter has the same effect.

The interesting thing is what happens when the "dlc" parameter is omitted but the "global_value" parameter is not - when this is done, it leads to the given weapon mod actually showing up twice in the inventory - once with the generic "THIS IS A MODDING COMMUNITY ITEM!" global value, and once with the intended global value. Furthermore, if you equip the instance of the weapon mod that has the intended global value onto your weapon and then leave the customization screen, said weapon instantly becomes "locked by one or more weapon mods" and thus unequipable.

I suspect that a good place to look as far as a fix is concerned would be whatever handles global values, "dlc" bundles, and/or just the weapon mod module.

**Comment by Luffyyy** [comment]
Github dumb

**Comment by the-almighty-carl** [comment]
lol

**Comment by Luffyyy** [comment]
Seems like for now global values only will work on drop-able items
drop value did seem to get stuck on 'true' (causes double, one drop and one "available") which I fixed.
