### ISSUE TITLE
Game crashes when someone joins my game/when I join someone's game

### ISSUE THREAD

**Issue by ArmandoKilombo** [simon-wh/PAYDAY-2-BeardLib#22]
I've been using BeardLib for a while, but recent updates make my game crash when I join someone's game or when someone joins me, also, when you (the Dev) reverted the fix, my game worked how it was supposed to, but now I can only play with the AI. Here's the crash log:

----------------------------------------------------------------------

Thu Apr 13 20:33:35 2017

Application has crashed: C++ exception
mods/BeardLib/Classes/utils.lua:244: attempt to concatenate field 'armor_skin' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.66.1
	CPU : Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 940MX / nvd3dum.dll[21.21.13.7319]
	Language : @ID4176958b9b2622ce@
	Memory :     3985MB 928KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoz/Auricular (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
I haven't updated BeardLib yet because I was pretty tired when doing the commit and asked some people to test it before I will release it.
