### ISSUE TITLE
Custom packages on vanilla levels with clients issue

### ISSUE THREAD

**Issue by steam-test1** [simon-wh/PAYDAY-2-BeardLib#221]
When using custom packages on vanilla levels can cause problems with clients see below for more information
https://github.com/payday-restoration/restoration-mod/issues/68

**Comment by Luffyyy** [comment]
Testing on my pc + laptop this doesn't seem to happen. To me at least.

**Comment by steam-test1** [comment]
I'll close this and open again if more information comes available

**Comment by steam-test1** [comment]
Did you try loading a map with custom packages as the first map you loaded
As the issue only occurs on the first load

**Comment by Luffyyy** [comment]
Yes I'm pretty sure that I've tried that

**Comment by steam-test1** [comment]
Could it be something to do with the following code
https://github.com/mwSora/payday-2-luajit/blob/d6e6983ca868eb61d50403f0bea00a7d152155b2/pd2-lua/core/lib/managers/coresequencemanager.lua#L6225
https://github.com/mwSora/payday-2-luajit/blob/d6e6983ca868eb61d50403f0bea00a7d152155b2/pd2-lua/core/lib/managers/mission/coreelementspawnunit.lua#L15

**Comment by Luffyyy** [comment]
At best I think this will just not activate the element or do the callback. Best you can do is leave exact procedures that always make this happen. Including map, additional mods of concern etc.

**Comment by steam-test1** [comment]
Update
Increasing the client connection and loading level timeouts in the mod seems to have reduced the chance of it happening
