### ISSUE TITLE
Recent update breaks game

### ISSUE THREAD

**Issue by VinierAardvark1** [simon-wh/PAYDAY-2-BeardLib#223]
Just installed the apparent new update and am now getting this crash when I try to launch:

Application has crashed: access violation
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                

-------------------------------
Current thread: Main
Script stack:
                        init()  @mods/base/req/core/Hooks.lua:267                   
                         new()  core/lib/utils/coreclass.lua:35                     
                    original()  lib/tweak_data/weapontweakdata.lua:6000             
   _init_data_player_weapons()  @mods/base/req/core/Hooks.lua:260                   
                    original()  lib/tweak_data/weapontweakdata.lua:26               
                    old_init()  @mods/base/req/core/Hooks.lua:260                   
                    old_init()  @assets/mod_overrides/Weapon                        
                                Descriptions                                        
                           Aww                                                      
          Yeah/hooks/lua.lua:4  init()                                              
                                @assets/mod_overrides/Full                          
                          auto                                                      
                    conversion  attachments/Hooks/weapontweakdata.lua:4             
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  lib/tweak_data/tweakdata.lua:531                    
                         new()  core/lib/utils/coreclass.lua:35                     
                                lib/tweak_data/tweakdata.lua:3084                   
                     require()                                                      
                          =[C]  OrigRequire()                                       
                                @mods/base/base.lua:151                             
                     require()                                                      
   @mods/BeardLib/Core.lua:222  lib/setups/setup.lua:35                             
                     require()  =[C]                                                
                 OrigRequire()  @mods/base/base.lua:151                             
                     require()  @mods/BeardLib/Core.lua:222                         
                                lib/setups/menusetup.lua:1                          
                     require()                                                      
                          =[C]  OrigRequire()                                       
                                @mods/base/base.lua:151                             
                     require()                                                      
   @mods/BeardLib/Core.lua:222  lib/entry.lua:13                           ?

**Comment by Luffyyy** [comment]
You should try verifying whether it's BeardLib causing. Try to remove some mods.

**Comment by VinierAardvark1** [comment]
Well, the issue only started when I updated BeardLib manually since I thought the in-game updater was broken

**Comment by Luffyyy** [comment]
The only thing I can suggest is to remove mods and see what causes it. The crash here isn't very helpful. I searched it and found you had the same issue before but a little different.

By the way, what is this mod "WeaponDescriptionsAwwYeah"?

**Comment by VinierAardvark1** [comment]
https://modworkshop.net/mydownloads.php?action=view_down&did=24554

**Comment by Luffyyy** [comment]
Can you send your log file? It's located in mods/logs and a file with a date as a name.

**Comment by Luffyyy** [comment]
Reopen issue if it becomes relevant again.
