### ISSUE TITLE
Crash when opening the Custom Achievement menu with Sora's Template.

### ISSUE THREAD

**Issue by AkiraDaishiyuExe** [simon-wh/PAYDAY-2-BeardLib#224]
Application has crashed: C++ exception
[string "--mods/BeardLib/Classes/CustomAchievementMana..."]:208: attempt to index a nil value

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
InitPackages() 230
SetEnabled() 518
@mods/BeardLib/Hooks/BeardLibModsMenuButton.lua:98
run_return_on_all_live_components() lib/managers/menu/menucomponentmanager.lua:337
mouse_pressed() lib/managers/menu/menucomponentmanager.lua:1752
original() @mods/base/lua/MenuComponentManager.lua:24
mouse_pressed() @mods/base/req/core/Hooks.lua:260
mouse_pressed() lib/managers/menu/menurenderer.lua:399
mouse_press() lib/managers/menu/menuinput.lua:570
lib/managers/mousepointermanager.lua:339

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

**Comment by Luffyyy** [comment]
Are you sure you have the latest version?

**Comment by AkiraDaishiyuExe** [comment]
Yes

**Comment by AkiraDaishiyuExe** [comment]
Yes, and i tried a manuel update but it still crash.

**Comment by mwSora** [comment]
Strange, I'm not having this issue

You extracted the template folder to mod_overrides?
Tried to delete, and reinstall it?

**Comment by AkiraDaishiyuExe** [comment]
I made some tests :
With nothing, the menu open correctly.
I reisntall both Beardlib and the template, result in crash.
I delete my beardlib options and CA progress, the menu open correctly.

**Comment by Luffyyy** [comment]
Perhaps send your progress?

**Comment by AkiraDaishiyuExe** [comment]
s_ach_complete.json
{	"amount":0,	"date_unlocked":0,	"completed":false}

s_ach_connected.json
{	"amount":3,	"date_unlocked":0,	"completed":false}

s_ach_finish_10_heists.json
{	"amount":0,	"date_unlocked":0,	"completed":false}

s_ach_game_launcher.json
{	"amount":9,	"date_unlocked":0,	"completed":false}

**Comment by AkiraDaishiyuExe** [comment]
But i guess it's not from that. I tried to create package and i got some trouble with the names, descriptions and objectives not displaying in the CA menu. I change the package id. Since the achievements are the same between the two package ID. I guess that didn't go well.

**Comment by Luffyyy** [comment]
I'll need the custom achievements as well I gues

**Comment by mwSora** [comment]
The crash leads to the package description, which is quite weird, if you're not giving one it should returns an empty string

**Comment by AkiraDaishiyuExe** [comment]
This is where my problem is but it's not part from the crash i got earlier.
![20190710200600_1](https://user-images.githubusercontent.com/31536447/60993176-3c8a8b80-a34e-11e9-9413-348299516634.jpg)

**Comment by mwSora** [comment]
Well this clearly shows that your localization file have a problem.

**Comment by AkiraDaishiyuExe** [comment]
Oh my god, i'm so dumb.
This is the dumbest thing i could do and i knew it.
The last line on my Json have a coma and it not suppose to have one. Now it's working !
Well, now i have to figure out how to use statisticsmanager.lua to register kill for the achievements because i don't know, i know how it's work with the old API but i'm lost.
Any suggestions or tutoriel ?
