### ISSUE TITLE
Custom menu tracks not playing in Heist Result Screen, Heist Failed Screen, and Pick Card Screen

### ISSUE THREAD

**Issue by HauntOfTheEagle** [simon-wh/PAYDAY-2-BeardLib#226]
Since late last year, I've noticed my custom menu tracks have stopped playing in the Heist Result Screen, Heist Failed Screen, and Pick Card Screen. I am currently using this template for adding custom music https://modworkshop.net/mydownloads.php?action=view_down&did=18106

I've tried switching to the ogg template to see if that was the problem, but still no luck.
https://modworkshop.net/mydownloads.php?action=view_down&did=21651

I also noticed someone had reported this issue on steam last december, however no one answered.
https://steamcommunity.com/app/218620/discussions/15/1745605598723609486/

From personal experience, I can say I noticed this issue occurred when either payday 2 or beardlib updated. I've narrowed it down to those two. Either that, or the custom music templates need an update.

**Comment by Luffyyy** [comment]
Can't believe I never noticed this issue.
