### ISSUE TITLE
Using the Beardlib 3 format is there a way to inject new options into the options table using another mod 

### ISSUE THREAD

**Issue by steam-test1** [simon-wh/PAYDAY-2-BeardLib#229]
As it removed the global from core.lua

**Comment by Luffyyy** [comment]
What do you mean

**Comment by steam-test1** [comment]
The following mod
https://modworkshop.net/mydownloads.php?action=view_down&did=25379
Adds to the options table of the following mod
https://modworkshop.net/mydownloads.php?action=view_down&did=20088

**Comment by Luffyyy** [comment]
I don't see any interaction with the options table. Are you talking about a different thing? Because I'm thinking of OptionsModule.
The global is still available if you set global_key

**Comment by steam-test1** [comment]
OptionsModule
Extract from logs using the same global_key
https://pastebin.com/ktG3Wk0w

**Comment by Luffyyy** [comment]
Well I don't know what you wrote there because I'm looking in the old code

**Comment by steam-test1** [comment]
The new code below
[NewGradientFilterChanger.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/3412721/NewGradientFilterChanger.zip)

**Comment by Luffyyy** [comment]
It really depends how you code your things. From what I see some things are pretty pointless being tweakdata but if you insist you can turn off `auto_load` and that should stop OptionsModule from automatically loading. Although, I may think of changing the module to load from some menu hook so tweakdata should have time. Still though, it depends on your code.

**Comment by Luffyyy** [comment]
By the way, name="Options" is redundant I think.

**Comment by Luffyyy** [comment]
I'm going to add 3 new values: `auto_init`, `auto_post_init` and `auto_register_hook` which you can guess what they can do. After turning `auto_post_init` on the module you can manually call the post init using Mod.Options:PostInit()

**Comment by steam-test1** [comment]
OptionModule._auto_post_init = false Added the options
But adding gradient_filter.Options:PostInit(). still caused the assertion error

**Comment by Luffyyy** [comment]
That's a module parameter not a variable. Put these values inside the OptionsModule XML.

**Comment by steam-test1** [comment]
Added auto_post_init to options node
Where is gradient_filter.Options:PostInit() suppose to go as I putting it tweakdata causes the same error

**Comment by Luffyyy** [comment]
After tweakdata initialization from what I understand.

**Comment by Luffyyy** [comment]
Since the version is still in development, there were a few issues which were resolved in the last commit. That should work now. Put the post init in the tweakdata hook.

**Comment by steam-test1** [comment]
It now displays
[BeardLib] [ERROR] Unable to get an option table for option Grading
It now loads the value from the save file, but crashes when clicking on options menu with the 
[string "lib/managers/menu/items/menuitemmultichoice.lua"]:274: attempt to index a nil value

**Comment by Luffyyy** [comment]
Oops, try now

**Comment by steam-test1** [comment]
Thanks it now works
