### ISSUE TITLE
Suggestion: Allow Beardlib mods to use custom environments

### ISSUE THREAD

**Issue by steam-test1** [simon-wh/PAYDAY-2-BeardLib#230]
Without overriding as existing environment

**Comment by Luffyyy** [comment]
Why not override existing? If you want to modify specific levels you can try TweakModify module to change the environments through the XML.

**Comment by Luffyyy** [comment]
And add your file through add files. iirc you can actually add new ones using script data replacement

**Comment by steam-test1** [comment]
The idea was to allow you to pick from a list of environments without loading packages
It only applies to custom maps using the levels/mods folder or it crashes with not in the preload_environment

**Comment by Luffyyy** [comment]
pretty sure it's possible already.

**Comment by Luffyyy** [comment]
You can load any environment pretty much. If it needs a scene to be loaded (use load="true"), you load that. Textures don't need loading. If you load through AddFiles, the files gotta be compiled.  You should be able to use scriptdata to load raw xmls if you need that.

**Comment by steam-test1** [comment]
Here an example
The format is binary
```
<environment path="environments/pd2_indiana_diamond_room/pd2_indiana_diamond_room" force="true"/>
<scene path="core/environments/skies/sky_2003_dusk_blue/sky_2003_dusk_blue" load="true" force="true"/>
```
When calling the environment the game closes
https://pastebin.com/XFVK81ZX

**Comment by Luffyyy** [comment]
Give me the files

**Comment by steam-test1** [comment]
[tDayNightChangesFull.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/3425504/tDayNightChangesFull.zip)

**Comment by Luffyyy** [comment]
If you open the scene you'll find "materials" inside it. That's also required.

**Comment by Luffyyy** [comment]
Alternatively if you don't wish to load scenes you may want to try sky texture feature of beardlib. The editor let's you make environments like that. The scene is the default scene. "core/environments/skies/default/default"

**Comment by Luffyyy** [comment]
![image](https://user-images.githubusercontent.com/11510099/61781295-cf2a3080-ae0c-11e9-8907-7aa25db81dc0.png)

**Comment by Luffyyy** [comment]
![image](https://user-images.githubusercontent.com/11510099/61781335-dfdaa680-ae0c-11e9-9bfc-2928cdb9f703.png)

**Comment by steam-test1** [comment]
Could you provide your main.xml

**Comment by Luffyyy** [comment]
I didn't do anything really I just saw inside the scene that it uses things

**Comment by steam-test1** [comment]
here my assets 
 ```
<environment path="environments/pd2_indiana_diamond_room/pd2_indiana_diamond_room" force="true"/>
<scene path="core/environments/skies/sky_2003_dusk_blue/sky_2003_dusk_blue" load="true" force="true"/>
<material_config path="core/environments/skies/sky_2003_dusk_blue/sky_2003_dusk_blue" force="true"/>
<model path="core/environments/skies/sky_2003_dusk_blue/sky_2003_dusk_blue" force="true"/>
 <texture path="core/environments/skies/sky_2003_dusk_blue/sky_2003_dusk_blue" force="true"/>
<texture path="environments/cubemaps/cubemap_bank_01" force="true"/>
```
Could you zip the stuff you changed as it still crashes
