### ISSUE TITLE
Music Module: Crash on Shacklethorne Auction

### ISSUE THREAD

**Issue by TheRouko** [simon-wh/PAYDAY-2-BeardLib#235]
Hello, seems like this module makes that specific heist to crash. (I didn't use the rest of the features, just the music) The multiples times I checked the crash log was for a different reason but one caused by the music module. I lost that file, but when I deleted BeardLib the problem was gone, so I'll try to put my crashes here:

Application has crashed: C++ exception
[File] Cannot read from file "D:\SteamLibrary\steamapps\common\PAYDAY 2\assets\all_23.bundle" => error code 998: Se realizó un acceso no válido a la ubicación de memoria. (d:\jenkins\shared-workspace\diesel\engine\dieselx\dieselx\blobs\../utility/Archive.cpp:2470)

SCRIPT_STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: FileStreamer

-------------------------------

**Comment by Luffyyy** [comment]
Would be useful if you provided the mod in question.

**Comment by Suukiro** [comment]
> Would be useful if you provided the mod in question.

https://modworkshop.net/mydownloads.php?action=view_down&did=24893

**Comment by Luffyyy** [comment]
There are a few there, which specifically?

**Comment by TheRouko** [comment]
> There are a few there, which specifically?

All the heist ones, I also forgot this: https://modworkshop.net/mydownloads.php?action=view_down&did=24870

**Comment by Luffyyy** [comment]
This mostly happens because of many music mods being loaded at once and since the game is 32bit it reaches the 32bit memory limit.
I'll try something.

**Comment by Luffyyy** [comment]
The fix isn't perfect but it will have a small slowdown for each song load. I'm thinking either making it an option or having it turn on when a certain number of songs is reached.

**Comment by TheRouko** [comment]
> The fix isn't perfect but it will have a small slowdown for each song load. I'm thinking either making it an option or having it turn on when a certain number of songs is reached.

ok, thanks for the help :D
