### ISSUE TITLE
Potential crash issue?

### ISSUE THREAD

**Issue by Jowy12** [simon-wh/PAYDAY-2-BeardLib#24]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                @mods/BeardLib/Hooks/CoreSystem.lua:24              
                            ()  =(tail                                              
                      call):-1                                                      
core/lib/utils/dev/editor/coreworlddefinition.lua:921  ()                                                  
                        =(tail  call):-1                                            
                      create()  core/lib/utils/dev/editor/coreworlddefinition.lua:522  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:577                        
                                core/lib/setups/coresetup.lua:402                   
                            ()  =(tail                                              
                      call):-1

Tried to play custom map, received this crashlog.

**Comment by Luffyyy** [comment]
Like past issues: https://github.com/simon-wh/PAYDAY-2-BeardLib/wiki/What-is-BeardLib%3F#my-game-is-crashing-and-the-script-stack-says-modsbeardlibhookscoresystemlua-lxx

**Comment by Luffyyy** [comment]
Also this custom heist is probably the cause of the crash so PLEASE report the issue to them instead.

**Comment by Jowy12** [comment]
Thanks for the info..!
