### ISSUE TITLE
BeardLib now working/installed (?)

### ISSUE THREAD

**Issue by HexusX** [simon-wh/PAYDAY-2-BeardLib#242]
I downloaded BeardLib about a week ago and I followed the steps of installing (putting it in the mods folder). But whenever I check the Updates Manager, BeardLib doesn't pop up. I came to the conclusion that there may be a problem when I installed it but I could be wrong. How do I fix this?

**Comment by Luffyyy** [comment]
If BeardLib is properly installed, you should see this section near the profile info:
![image](https://user-images.githubusercontent.com/11510099/63962320-4fdaed00-ca9b-11e9-96b5-4f1dabcf9233.png)
If you don't see it, you'll have to upload your blt log (found in mods/logs and a file with today's date). Make sure that inside the mods folder you have a folder named "BeardLib".

**Comment by HexusX** [comment]
Yeah I don't have that icon anywhere. I placed the "BeardLib" folder directly in the mods folder.
[2019_09_01_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/3563279/2019_09_01_log.txt)

**Comment by HexusX** [comment]
So what should I do now?

**Comment by Luffyyy** [comment]
Try to download the GitHub version.

From what I can see you're running a pirated version of the game or somehow running with old BLT. The version in GitHub does fix a typo in the mod.txt that caused it to fail to start (while SBLT doesn't seem to care).

BeardLib and many mods today don't support the old BLT nor cheat/pirating mods such as pirate perfection. So I will not be solving any issues beyond issues that exist in SBLT (in this case it was)

**Comment by HexusX** [comment]
Unfortunately, the game crashes whenever I placed the BeardLib file in the mods folder

**Comment by Luffyyy** [comment]
You can give me the crashlog and see if it's a problem that exists in SBLT.
Found in %localappdata%/payday 2

**Comment by HexusX** [comment]
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/3569792/crash.txt)

**Comment by HexusX** [comment]
And here's the crash log as well 
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/3569803/crashlog.txt)

**Comment by Luffyyy** [comment]
Updated again something, try again.

**Comment by HexusX** [comment]
Should I download the files again?

**Comment by Luffyyy** [comment]
Yes..?

**Comment by HexusX** [comment]
Nope. Still crashes

**Comment by Luffyyy** [comment]
Crash.txt again I can't guess the reason

**Comment by HexusX** [comment]
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/3570380/crash.txt)

**Comment by Luffyyy** [comment]
Hmm odd. Send the BLT log now. (mods/logs/ today's date text file)

**Comment by HexusX** [comment]
[2019_09_03_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/3570392/2019_09_03_log.txt)

**Comment by Luffyyy** [comment]
Welp that's it.
11:57:34 PM FATAL ERROR: mods/BeardLib/Classes/Utils/FileIO.lua
11:57:34 PM FATAL ERROR: mods/BeardLib/Classes/Utils/FileIO.lua:55: attempt to index global 'BLT' (a nil value)

This very simply means that you have BLT older than 2.0 so you will not be able to run BeardLib at all.
However, even that may not work (I did not test it since it doesn't work anymore on the steam version). So try the one here https://paydaymods.com/download/

**Comment by HexusX** [comment]
Well this time, the BLT doesn't install in the game. It was worth a try
