### ISSUE TITLE
BeardLib not starting on blt4l (BLT for Linux)

### ISSUE THREAD

**Issue by CamperSamu** [simon-wh/PAYDAY-2-BeardLib#243]
Intalling BeardLib on Linux causes a black screen and the game won't start

**Comment by Luffyyy** [comment]
Can you send me your BLT log? Found in mods/logs
Also which version are you running?

**Comment by Luffyyy** [comment]
Heads up - if you're using blt4l, please switch to SBLT as it supports Linux and should work with custom maps.
