### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by Jowy12** [simon-wh/PAYDAY-2-BeardLib#25]
Application has crashed: C++ exception
mods/BeardLib/Hooks/NetworkPeer.lua:32: attempt to index a nil value

The game crashed as soon as i left a game. (Was playing as client).

**Comment by Luffyyy** [comment]
Does it repeatedly happens?

**Comment by Jowy12** [comment]
Nope it doesn't and i think it was the first time it happened.

**Comment by ThisGuyOrDatGuy** [comment]
I have the same problem but my game always crashes.

**Comment by Luffyyy** [comment]
Any updates on this?
