### ISSUE TITLE
Custom heist crash

### ISSUE THREAD

**Issue by kiroakashima** [simon-wh/PAYDAY-2-BeardLib#250]
So I was attempting to play some of the custom heists I downloaded. It is Shadow Raid+, though I get the same issue on Golden Grin Casino+, and Ukrainian Job+, but when I try to buy the mission in crime net online it will hang at "Creating lobby please wait". It will never load any further then that. When it gets here I have to close the game. I was able to force a crash by buying a default mission and then swapping the lobby over to the custom mission again.
I worked with the mod author a bit and removed all of my custom heists (all 5 anyway) and even recreated the Maps folder. The crash pointed at beardlib so I updated it, got the error again, and did a delete and reinstall of BeardLib. So I figure I'd ask here and try my luck at resolving the problem.
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/3587142/crash.txt)

**Comment by Luffyyy** [comment]
Yes it seems the issue is in BeardLib. I pushed a commit in the repo if you want to try it. It should do the trick.

**Comment by kiroakashima** [comment]
As a noob how do I do that?

**Comment by kiroakashima** [comment]
Actually was easy, just had to reinstall notepad++. Will test it later tonight when buddies are on to try it. But i was able to make the lobby and go in game without issue. You are the best.

**Comment by Luffyyy** [comment]
You just download the repo and replace it with your installation.
