### ISSUE TITLE
the hud's i play are broken and it fell's like the new updates are to blame

### ISSUE THREAD

**Issue by edekhudoley** [simon-wh/PAYDAY-2-BeardLib#251]
so i play with bl 2 HUD one of the new first updates had a problem where the ammo type shown 
was saw blades for the weapon that's used at the moment and the weapon that isn't used shows sniper rounds  then on the second update all of the numerical showings of the HUD where gone 
and then on the third update it just crashes 

.

**Comment by Luffyyy** [comment]
This probably has nothing to do with BeardLib. I tested the HUD and it didn't crash.
You may be using an older version of the HUD mod use this one: https://modworkshop.net/mydownloads.php?action=view_down&did=23623 If the issue still persists, then probably some mod is conflicting.
