### ISSUE TITLE
Game crashes when clicking Contract broker

### ISSUE THREAD

**Issue by D3cryptedoof** [simon-wh/PAYDAY-2-BeardLib#253]
my Game crashes when clicking Contract broker/Contract buyer

**Comment by Luffyyy** [comment]
Provide crashlog please

**Comment by D3cryptedoof** [comment]
Application has crashed: C++ exception
[string "lib/managers/menu/contractbrokergui.lua"]:603: attempt to index field 'data' (a nil value)



SCRIPT STACK

sort() =[C]
filters_clbk() lib/managers/menu/contractbrokergui.lua:602
_setup_filters() lib/managers/menu/contractbrokergui.lua:391
setup() lib/managers/menu/contractbrokergui.lua:110
init() lib/managers/menu/contractbrokergui.lua:55
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:5214
set_active_components() lib/managers/menu/menucomponentmanager.lua:481
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
update() lib/setups/setup.lua:854
update() lib/setups/menusetup.lua:340
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:540

**Comment by D3cryptedoof** [comment]
Bump

**Comment by D3cryptedoof** [comment]
bump

**Comment by Luffyyy** [comment]
Oh right, some map you have is probably causing problems. Uninstall one of them.

**Comment by D3cryptedoof** [comment]
Removed my one map and it's still crashing ( the map was hardware store or somthing)

**Comment by Luffyyy** [comment]
Not much to say other than keep removing mods and see what works, I am 99.99% sure that BeardLib doesn't cause this inherently.
