### ISSUE TITLE
Out of nowhere crashes today

### ISSUE THREAD

**Issue by VinierAardvark1** [simon-wh/PAYDAY-2-BeardLib#257]
I've been able to play PAYDAY 2 without issue until today, where I get this load of BS;

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  181                                                 
                      Update()  206                                                 
                        func()  @mods/BeardLib/Core.lua:158                         
                        Call()  @mods/base/req/core/Hooks.lua:109                   
                      update()  @mods/base/lua/MenuSetup.lua:7                      
                                core/lib/setups/coresetup.lua:540                   

-------------------------------

**Comment by Luffyyy** [comment]
This doesn't tell me much. Like when you get the crash. I'll suggest removing some mods to see which crashes the game.

**Comment by VinierAardvark1** [comment]
The problem is, I've had the same mods installed for a while now and they've worked perfectly fine up until now, so I'm very confused...

**Comment by VinierAardvark1** [comment]
After removing every single mod from the game, I have come to the conclusion that BeardLib itself and StatTrak mods are what causes crashing.

**Comment by Luffyyy** [comment]
Tell me exactly how you're crashing, where. Running BeardLib only (No mod overrides, no maps) And make sure you send me a crashlog.

**Comment by VinierAardvark1** [comment]
Running BeardLib only doesn't cause any crashes

**Comment by Luffyyy** [comment]
Well here is your answer.
