### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tormarod** [simon-wh/PAYDAY-2-BeardLib#26]
After today's update game crashes on startup. Removing BeardLib fixes the issue, Here's the crashlog:

Sun Apr 30 19:18:07 2017

Application has crashed: C++ exception
[string "lib/managers/weaponfactorymanager.lua"]:65: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.216
	CPU : Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD Radeon R9 200 Series / aticfx32.dll[22.19.157.3]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8127MB 920KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoces (Realtek High Definition Audio))

**Comment by tormarod** [comment]
Here's a previous crash with more stuff in the log, don't know if it might help you:

Sun Apr 30 19:15:21 2017


Application has crashed: C++ exception
[string "lib/managers/weaponfactorymanager.lua"]:65: attempt to index field '?' (a nil value)



SCRIPT STACK



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     ZwCreateFile                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.216
	CPU : Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD Radeon R9 200 Series / aticfx32.dll[22.19.157.3]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8127MB 920KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoces (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Could you pass your log file(mods/logs and today's date)
also today's update was related completely to network so I am really confused on how this can be caused by the update

**Comment by tormarod** [comment]
Last night I was playing without issues, all the mods loaded correctly, no crashes, nothing unusual. This morning after launching the game it prompted an update for beardlib, and a few override mods i use (like custom weapons, and mods for those weapons) and it crashed right when it's supposed to play the first intro. I deleted BeardLib from the mods folder and it launched correctly (although without access to the mods that require it). Here's today's log, let me know if you need anything esle.

[2017_04_30_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/966995/2017_04_30_log.txt)

**Comment by Luffyyy** [comment]
try removing some said custom weapons I think it would make more sense that they cause it.
because again today's update has nothing to do with custom content or anything that starts at startup

**Comment by tormarod** [comment]
Is there any way to know which one is causing it? Cause I have quite a few.

**Comment by tormarod** [comment]
Nevermind, Sniper IronSights was causing it it seems.
