### ISSUE TITLE
Crashing When Selecting Melees after the Cartel/New Interface Update

### ISSUE THREAD

**Issue by LithTheKitten** [simon-wh/PAYDAY-2-BeardLib#261]
Game crashed when I tried to open up the melee inventory. Wiped the gamefiles down to stock and found out it was Beardlib. I dont know what this stuff means but the new update already hates beardlib. 

Thu Nov 07 09:30:06 2019

Application has crashed: C++ exception
[string "lib/managers/menu/blackmarketgui.lua"]:9216: attempt to index field 'override_slots' (a nil value)

SCRIPT STACK

init() lib/managers/menu/blackmarketgui.lua:144
new() core/lib/utils/coreclass.lua:35
_setup() lib/managers/menu/blackmarketgui.lua:2101
init() lib/managers/menu/blackmarketgui.lua:1912
new() core/lib/utils/coreclass.lua:35
create_blackmarket_gui() lib/managers/menu/menucomponentmanager.lua:2853
create() lib/managers/menu/menucomponentmanager.lua:2844
set_active_components() lib/managers/menu/menucomponentmanager.lua:481
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
update() lib/setups/setup.lua:851
update() lib/setups/menusetup.lua:352
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:556

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.93.844.
	CPU : AMD Ryzen 5 3600 6-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2060 SUPER / nvldumd.dll[26.21.14.3615]
	Language : english
	Memory :     16333MB 472KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (2460G4 (2- High Definition Audio Device))

It was just with the melees however, the game didn't crash when I checked my gun inventories, but for now melees arnt accessible unless you remove beardlib.

**Comment by stealthy-1** [comment]
Yeah this happened to me too

----------------------------------------------------------------------

Mon Oct 28 17:57:18 2019


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
          _create_carry_unit()  lib/units/beings/player/huskplayermovement.lua:392  
            set_visual_carry()  lib/units/beings/player/huskplayermovement.lua:364  
            set_carrying_bag()  @mods/Better                                        
                                Bots/betterbots.lua:498                             
                     link_to()                                                      
lib/units/props/carrydata.lua:857  _update_throw_link()                                
                                lib/units/props/carrydata.lua:145                   
lib/units/props/carrydata.lua:45  
-------------------------------

System information:
	Application version : 1.92.790.
	CPU : AMD Ryzen 5 3600 6-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : AMD Radeon RX 5700 XT / aticfx32.dll[26.20.13031.5006]
	Language : german
	Memory :     16315MB 496KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Advanced Micro Devices (1 - C27F390 (2- AMD High Definition Audio Device))



----------------------------------------------------------------------

**Comment by Luffyyy** [comment]
Fixed in 6fbf02cfc6ef8043e76e86643c3839752dd7ed52
