### ISSUE TITLE
the mod options will not show up

### ISSUE THREAD

**Issue by qryptc** [simon-wh/PAYDAY-2-BeardLib#266]
i have fully updated both beardlib manually and i am using blt v2,
however when i go into settings, there are no mod options

![image](https://user-images.githubusercontent.com/57727339/68795739-785d9680-0649-11ea-852f-58b8910003e0.png)

**Comment by Luffyyy** [comment]
> and i am using blt v2
Here's your problem.

Uninstall BLT, Install SuperBLT. https://superblt.znix.xyz/
