### ISSUE TITLE
Restoration Mod can't be disabled

### ISSUE THREAD

**Issue by steam-test1** [simon-wh/PAYDAY-2-BeardLib#267]
The lua part stays enabled, but the assets are disabled
In the Beardlib mod manager settings the enabled setting can't be changed

**Comment by Luffyyy** [comment]
BLT mods cannot be disabled by BeardLib. You must disable them directly from BLT, BeardLib **should** then disable loading for the mod.

**Comment by steam-test1** [comment]
The mod was disabled in BLT mod manager, but it still loads
