### ISSUE TITLE
[Dialogue] Crash when using "force quit current" for Custom Dialogues.

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#269]
This crash happens when you play Voice Line with Dialogue element and then another Dialogue element with "force_quit_current = true" get executed while the 1st one is still playing.

In that situation we have 2 voice lines played at the same time, and bugged subtitles, but what's the most important thing - crash after 1-2 seconds.

Here's a crash.txt:
`Application has crashed: C++ exception
[string "lib/managers/dialogmanager.lua"]:115: attempt to index field '_current_dialog' (a nil value)

SCRIPT STACK

_callback() lib/units/dramaext.lua:68
callback() 45
next_in_queue() 54
update() 140
update() @mods/base/req/xaudio/XAudio.lua:34
func() @mods/base/req/xaudio/XAudio.lua:43
Call() @mods/base/req/core/Hooks.lua:109
original() @mods/base/lua/GameSetup.lua:6
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:556

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------`

**Comment by Luffyyy** [comment]
You'll have to provide me with a BLE project as I cannot replicate it.

**Comment by MiamiCenterPL** [comment]
With latest BeardLib it's working fine, guess someone already fixed it. 
But it was an real issue back when I posted this issue. Did the same steps as when I first testes this issue, and now it is working completely fine. Thanks !
