### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by mcproprot** [simon-wh/PAYDAY-2-BeardLib#27]
when i start the game

Application has crashed: C++ exception
mods/base/req/json.lua:366: Unexpected character at Line 1 character 1: 

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   

-------------------------------

Current thread: Main

**Comment by Luffyyy** [comment]
Are you sure this is caused by BeardLib?

**Comment by Luffyyy** [comment]
No information given, closed.
