### ISSUE TITLE
Custom Heists crashing Local Players

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#270]
This happens when you join to the lobby that have custom heist set.
`Application has crashed: C++ exception
[string "lib/network/base/handlers/basenetworkhandler.lua"]:46: attempt to index local 'rpc' (a nil value)

SCRIPT STACK

sync_game_settings() lib/network/base/handlers/connectionnetworkhandler.lua:312
continue_sync() @mods/BeardLib/Hooks/NetworkPeer.lua:134
func() @mods/BeardLib/Hooks/NetworkPeer.lua:166
Call() @mods/base/req/core/Hooks.lua:109
ProcessSinglePeer() @mods/base/req/core/Networking.lua:198
ProcessChatString() @mods/base/req/core/Networking.lua:179
func() @mods/base/req/core/Networking.lua:165
Call() @mods/base/req/core/Hooks.lua:109
_receive_message() @mods/base/lua/ChatManager.lua:12
receive_message_by_peer() lib/managers/chatmanager.lua:68
lib/network/base/handlers/connectionnetworkhandler.lua:662

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------`

I however fixed this crash for myself commenthing this 3 lines, maybe that'll point you to the issue somehow;
BeardLib/Hooks/Fixes.lua:280
MenuInput:2
MenuManager:93

I might broke much things doing that, but atleast I can play with friends.
Idk if I wrote the Hook file changes correct, soo I pin here my version of BeardLib - maybe it'll help.
https://www.dropbox.com/s/r1livkc8vvd0v2p/BeardLib-temporary_fix.zip?dl=0

**Comment by Luffyyy** [comment]
Fixed in https://github.com/simon-wh/PAYDAY-2-BeardLib/commit/f71b762eebfd00d2a95cee827036a3280415f0b1
