### ISSUE TITLE
crash on start 

### ISSUE THREAD

**Issue by repoman728** [simon-wh/PAYDAY-2-BeardLib#271]
Hi 
 i don't know if it is beardlib but maybe somebody points me in write direction -
  
Application has crashed: C++ exception
[string "lib/managers/statisticsmanager.lua"]:819: bad argument #1 to 'pairs' (table expected, got nil)

SCRIPT STACK

_table_contains() lib/managers/statisticsmanager.lua:819
publish_equipped_to_steam() lib/managers/statisticsmanager.lua:884
verify_dlc_items() lib/managers/blackmarketmanager.lua:7530
give_dlc_and_verify_blackmarket() lib/managers/dlcmanager.lua:162
func() lib/managers/dlcmanager.lua:176
dispatch() core/lib/utils/coreevent.lua:212
_on_load_sequence_complete() lib/managers/savefilemanager.lua:255
update() lib/managers/savefilemanager.lua:240
update() lib/setups/setup.lua:850
update() lib/setups/menusetup.lua:352
update() @mods/base/lua/MenuSetup.lua:6
orig__update() core/lib/setups/coresetup.lua:556
trainer/tools/pubinfloopv2.lua:141

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

thanks

**Comment by Luffyyy** [comment]
Doesn't look like BeardLib.
