### ISSUE TITLE
Crash after recent PD2 update

### ISSUE THREAD

**Issue by MaxyB** [simon-wh/PAYDAY-2-BeardLib#273]
Hi, I hope you can help me fix my crashing problem.
Every time I try to load into a session / heist the game crashes after loading the map.
This is the crashlog I get:

Mon Nov 25 18:32:16 2019

Application has crashed: C++ exception
[string "lib/units/weapons/newnpcraycastweaponbase.lua"]:19: attempt to index a nil value

SCRIPT STACK

spawn_unit() =[C]
add_unit_by_factory_blueprint() lib/units/beings/player/huskplayerinventory.lua:144
add_weapons() lib/units/player_team/teamaimovement.lua:59
post_init() lib/units/enemies/cop/copmovement.lua:454
post_init() lib/units/player_team/teamaibase.lua:7
lib/units/player_team/teamaisound.lua:5
spawn_unit() =[C]
spawn_one_teamAI() lib/managers/group_ai_states/groupaistatebase.lua:2944
fill_criminal_team_with_AI() lib/managers/group_ai_states/groupaistatebase.lua:3084
spawn_players() lib/network/base/basenetworksession.lua:1526
update() lib/states/ingamewaitingforplayers.lua:277
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
update() lib/setups/setup.lua:873
update() lib/setups/gamesetup.lua:715
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:556

I updated SuperBLT and Beardlip to the newest version, but it still crashes...
Thank you for your help,
 
 Maxy

**Comment by Luffyyy** [comment]
I'm assuming it's an issue with some custom weapon mod. Does it still happen?

**Comment by MaxyB** [comment]
Yep, it still does

**Comment by Luffyyy** [comment]
Try uninstalling mods until it fixes itself. Mods like custom weapons are the first suspect.

**Comment by MaxyB** [comment]
Yeah, the only question is, how do I remove them?
Just removing all the stuff from my mods folder didn't fix it

**Comment by Luffyyy** [comment]
Mod overrides folder?

**Comment by MaxyB** [comment]
no, just the regular mods folder
should the mods override one go too?

**Comment by Luffyyy** [comment]
Custom weapons are in mod overrides so yeah

**Comment by MaxyB** [comment]
ok, I will try that, I might have an idea which mod is causing the problem

**Comment by MaxyB** [comment]
Yep, found the mod that crashed it, atleast it works like nromal now
it was the "AK-47" mod: https://modworkshop.net/mod/23409
I had problems with it before already, so I got rid of it. Thank you for your help!
