### ISSUE TITLE
I can't download the file

### ISSUE THREAD

**Issue by Thiago-Lopes-tvlp** [simon-wh/PAYDAY-2-BeardLib#276]
Everytime I try to download the file it starts to download a html file that doesn't do anything besides opening a useless web page.

file name: mydownloads.php

**Comment by Luffyyy** [comment]
I don't know what you're talking about, it works for me.

**Comment by Thiago-Lopes-tvlp** [comment]
> I don't know what you're talking about, it works for me

thanks for the help
