### ISSUE TITLE
Own custom map crashing.

### ISSUE THREAD

**Issue by LeoZsuper** [simon-wh/PAYDAY-2-BeardLib#279]
**I created a map, added some scripts and now it crashes with this error. It's not the first time, this happens to me. I've tried removing all mods, doesn't help either. Also I have the latest Beardlib and Beardlib-editor.**

Application has crashed: C++ exception
[string "lib/managers/navigationmanager.lua"]:3105: attempt to get length of a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.93.850
	CPU : Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 940MX / nvldumd.dll[26.21.14.4166]
	Language : english
	Memory :     16257MB 924KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (2- Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
This doesn't help me much, I need the project.

**Comment by LeoZsuper** [comment]
**Here is the map:**
https://drive.google.com/drive/folders/1gt2NzJbTQDzFgXWXVr7XQl0Ss4BnoT2c?usp=sharing

**Comment by Luffyyy** [comment]
If you go to World > AI you'll find a button called build navigation data, press it and wait until it's done. It will reload the editor and it will work. I am not sure at the moment what's causing it, but my assumption is this is an issue with the game when you have an oudated navigation data.

**Comment by LeoZsuper** [comment]
Thank you, it actually worked.
