### ISSUE TITLE
Beardlib crashes when checking mod updates.

### ISSUE THREAD

**Issue by AlAlvarez1992** [simon-wh/PAYDAY-2-BeardLib#281]
As the name says, It says it needs updates, but I can't update it or know what it is that needs updating, as checking the mod manager crashes the game, I have re-downloaded and replaced beardlib, and the issue still persists. Mods still work as usual.

**Comment by Luffyyy** [comment]
Please provide a crashlog

**Comment by AlAlvarez1992** [comment]
[2020_03_18_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4352243/2020_03_18_log.txt)

**Comment by Luffyyy** [comment]
That's the BLT log not crashlog

**Comment by AlAlvarez1992** [comment]
Oh. Sorry, where can I find the crash log again?

**Comment by Luffyyy** [comment]
%localappdata%/payday 2 in file explorer.

**Comment by AlAlvarez1992** [comment]
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4369430/crash.txt)
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4369431/crashlog.txt)

**Comment by Luffyyy** [comment]
Honestly I'm not sure this is not an issue others are having so most likely something in your game. Are you sure the mod manager you're checking isn't BLT's?

**Comment by Luffyyy** [comment]
Could you maybe record yourself (with everything updated as of now) crashing?

**Comment by Luffyyy** [comment]
Reopen issue if it returns.
