### ISSUE TITLE
BeardLib making lobbies dissapear

### ISSUE THREAD

**Issue by nickwick08** [simon-wh/PAYDAY-2-BeardLib#282]
Hello, i have tried to join my friends game or even join a public lobby and i cant see any of the lobbies. I removed my mods folder and added beardlib by itself to see if it was the issue and it was. ive reinstalled in a few times to make sure ive put it in correctly and i have.

**Comment by Luffyyy** [comment]
BeardLib doesn't do that. It's possible your friends have the game unmodded which makes it so you can't join if you're modded.

**Comment by nickwick08** [comment]
i removed my all my mods but only have beardlib in that mods folder and the lobbies are not showing up

**Comment by Luffyyy** [comment]
Did you like ignore the part where I said the game itself filters the lobbies based on modded/unmodded client? The game detects BLT/SBLT and instantly marks it as a modded client.
