### ISSUE TITLE
Steam could not authenticate ID for Host Error When I Try to Join The game

### ISSUE THREAD

**Issue by VitaLocke** [simon-wh/PAYDAY-2-BeardLib#286]
I Can't Join into Playing Lobby. But making a lobby or Joining someone's Lobby is okay. i have a 305 Override Modes. I Think Pre-Loading or Pre-Authenticate Before loading should be added. Because I Think It'll Reduce a Authenticate ID Issue Significantly. My game won't crash. but Maybe a Slow loading could cause this. Pre-Loading Mod_Overrides Before Loading,or authenticate ID for Host Before Loading could fix this.

**Comment by Luffyyy** [comment]
What led you to believe BeardLib is the sole reason for this

**Comment by VitaLocke** [comment]
Because Optimization is needed to do this.
