### ISSUE TITLE
Frequent Access violation Crash By Beardlib.

### ISSUE THREAD

**Issue by VitaLocke** [simon-wh/PAYDAY-2-BeardLib#288]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  181                                                 
                   LoadAsset()  203                                                 
                   unit_data()  @mods/BeardLib/Hooks/CoreSystem.lua:61              
                                core/lib/managers/coresequencemanager.lua:681       

-------------------------------

System information:
	Application version : 1.94.862
	CPU : Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 660 / nvldumd.dll[26.21.14.4274]
	Language : english
	Memory :     8037MB 8KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CORSAIR (헤드셋 이어폰(CORSAIR VOID ELITE USB Gaming Headset))

It seems Beardlib and SuperBLT Is Crashing the game for Some times. Can you fix it?

**Comment by Luffyyy** [comment]
No because BeardLib doesn't cause it by itself. Check your mods.
