### ISSUE TITLE
CoreSequenceManager crash

### ISSUE THREAD

**Issue by Endy1412** [simon-wh/PAYDAY-2-BeardLib#289]
Hello , so everytime at preplanning when my loading comes to 98% the game freezes for a second and just crashes. And here is the crashlog : 

Application has crashed: C++ exception
[string "core/lib/managers/coresequencemanager.lua"]:5019: attempt to index local 'obj' (a nil value)

SCRIPT STACK

load_element_data() core/lib/managers/coresequencemanager.lua:905
core/lib/units/coreunitdamage.lua:862

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                      atiumdag  (???)     XdxInitXopAdapterServices                           
                           ???  (???)     ???

**Comment by Luffyyy** [comment]
And why is BeardLib being blamed for it?

**Comment by Luffyyy** [comment]
Closed for inactivity.
