### ISSUE TITLE
Random crashes when I join, load, or hosting

### ISSUE THREAD

**Issue by Phaisel** [simon-wh/PAYDAY-2-BeardLib#29]
My game can randomly crash when I'm in preplanning screen and loading the game,
It can randomly crash after finished loading and try to enter the game when the screen turns black,
It can also randomly crash when I host a game and someone is joining me.

These are all random, I can never tell when the game will crash or not, it's a lot of times the same and other times not, it happens in all the maps and in none of them, 
and every time it happens the crash log blames beardlib.
I don't know if the lua numbers that in the crash log are always identical.
Please help me, what can I do to solve the problem?
I tried to delete beardlib, but when I do that the game crashes on start (press any key screen).
Any kind of help would be much appreciated. 
thank you and have a good day. :)
P.S: please note that I am kinda new to modding, so I don't understand much of what I see here.

crash log:

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                  spawn_unit()  @mods/BeardLib/Hooks/CoreSystem.lua:24              
        _spawn_and_link_unit()  lib/managers/weaponfactorymanager.lua:851           
                      _spawn()  lib/managers/weaponfactorymanager.lua:771           
                                lib/managers/weaponfactorymanager.lua:787           
                            ()  =(tail                                              
                      call):-1  load()                                              
lib/managers/dynamicresourcemanager.lua:123  _add_part()                                         
lib/managers/weaponfactorymanager.lua:748                                                      
lib/managers/weaponfactorymanager.lua:619  ()                                                  
                        =(tail  call):-1                                            
                            ()  =(tail                                              
                                call):-1                                            
     assemble_from_blueprint()                                                      
lib/units/weapons/newraycastweaponbase.lua:139  add_unit_by_factory_blueprint()                     
                                lib/units/beings/player/huskplayerinventory.lua:119  
    add_unit_by_factory_name()                                                      
lib/units/beings/player/huskplayerinventory.lua:103  lib/units/beings/player/playerinventory.lua:626     
                            ()  =(tail                                              
                                call):-1                                            
                    original()                                                      
lib/managers/enemymanager.lua:580  _update_queued_tasks()                              
                                @mods/base/req/hooks.lua:258                        
                      update()                                                      
lib/managers/enemymanager.lua:48  lib/setups/gamesetup.lua:648                        
                            ()  =(tail                                              
                                call):-1                                            
                      update()                                                      
lib/setups/networkgamesetup.lua:21  core/lib/setups/coresetup.lua:537                   
                            ()  =(tail                                              
                                call):-1                                            

-------------------------------

System information:
	Application version : 1.69.220
	CPU : Intel(R) Core(TM) i3 CPU 550 @ 3.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 650 / nvd3dum.dll[21.21.13.7653]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     3957MB 404KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by Luffyyy** [comment]
https://github.com/simon-wh/PAYDAY-2-BeardLib/wiki/What-is-BeardLib%3F#my-game-is-crashing-and-the-script-stack-says-modsbeardlibhookscoresystemlua-lxx 
Got any custom weapons?

**Comment by Phaisel** [comment]
Yes, I do have a few, that's why I have beardlib, but how can I tell which one of them is causing it?
because when I remove all custom weapons the game will crash on start,
I understand that it may not be beardlibs fault, but is there something I can do to fix the problem?

**Comment by Luffyyy** [comment]
Didn't you say your game crashes if you remove BeardLib?
removing the weapons should do the trick I think..
If not then try one by one

**Comment by Phaisel** [comment]
Yes, I tried a few things im sorry if I wasnt clear,
I Removed beardlib, saw that game crashes on start,
and when i installed beardlib again, I tried to play without the mods, to maybe leave beardlib so my game wont crash on start, and not install the mods so it wont crash while playing, xd
anyway it didnt help, I will try now to delete the mods 1 by 1.

**Comment by Phaisel** [comment]
ok deleted 1 joined and left joined and left to see if crashing, and continued to do so until i got no more custom weapon mods at all, so with only beardlib right now I still crash randomally..

**Comment by Luffyyy** [comment]
Could you give me your mods list if you have any?
and try temporarily removing mod_overrides(can rename it and then back to mod_overrides)

**Comment by Phaisel** [comment]
I just edited my previous comment, I think the problem is solved now, I was able to delete beardlib and by some magical way it is no longer crashing on start, I hope it will stay that way,
anyway, I do have mods, and I think it's quite a lot, so I don't wanna burden you too much if I can live without it,
If you insist I will give you a list anyway, 
I thank you for replying and willing to help me :)

**Comment by Luffyyy** [comment]
Alright have a nice day/night.
