### ISSUE TITLE
Beardlib can´t load custom models on Linux using SuperBLT

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [simon-wh/PAYDAY-2-BeardLib#291]
Beardlib can’t simply load custom models in-game.
It loads instead, for the case of custom weapons for example, their ¨non modded¨ replacement (How it appears in an online game, for someone who don’t have the mod installed).

The native port of Payday 2 is being used.
The latest version of SuperBLT his being used (At this time of writing, version 1.1.6.0). The binaries file hasn’t been directly compiled on my machine, however, due to dependencies issues. (I’m on Arch, and I can’t find some names for the depicted Debian dependency on their documentation)
Steam is using the native runtime installed on my machine, meaning it doesn’t use the LTS steam runtimes (Which could cause issues with the libcurl4 dependency, which now, instead, use the latest 7.69.1-1 installed locally, lib32 version included).
Payday 2 is launched correctly, with the SuperBLT preloader set-up (`gamemoderun env LD_PRELOAD="$LD_PRELOAD ./libsuperblt_loader.so" %command%` as Steam Launch options)
[Here's one of the latest logs file of one of my game](https://wtf.roflcopter.fr/paste/?c5aea3dfa9484e58#6tZg55YViKUTQ1GkevsJ6tneDmxQGHjuyRGXRLNAE34p). If needed, I can make a more concise log file. (Like, only launching the game, accessing some menus, interacting with some mod features, and just close it)

**Comment by Luffyyy** [comment]
Seems to me like s SuperBLT issue. It doesn't do anything with DB:has which BeardLib uses on Windows to know if a file is loaded.

**Comment by PoorPocketsMcNewHold** [comment]
![Screenshot_20200415_141921](https://user-images.githubusercontent.com/13170204/79336512-2b495d80-7f24-11ea-8117-35f1eda7b437.png)
I see, as from the Beardlib mod loading, It didn’t seem to be able to access assets correctly from their mods folders, despite being able to load everything, script-wise.
I’ll report that on the SuperBLT repo, and re-open the issue if needed.
Thanks for the prompt response.
