### ISSUE TITLE
Application has crashed: C++ exception [string "lib/units/weapons/raycastweaponbase.lua"]:499: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by arsium** [simon-wh/PAYDAY-2-BeardLib#293]
Sat Apr 18 22:46:26 2020

Application has crashed: C++ exception
[string "lib/units/weapons/raycastweaponbase.lua"]:499: attempt to perform arithmetic on a nil value

SCRIPT STACK

orig_fire() lib/units/weapons/raycastweaponbase.lua:456
fire_original() @mods/AFSF2/AutoFireSoundFix.lua:56
fire() @mods/pjal3urb-burstfire-64bef3a47c59/BurstFire.lua:86
trigger_held() lib/units/weapons/newnpcraycastweaponbase.lua:203
update() lib/units/enemies/cop/actions/upper_body/copactionshoot.lua:349
_upd_actions() lib/units/enemies/cop/copmovement.lua:646
original() lib/units/enemies/cop/copmovement.lua:609
update() @mods/base/req/core/Hooks.lua:185
lib/units/player_team/teamaimovement.lua:436

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.94.862
	CPU : Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2070 / nvldumd.dll[26.21.14.4141]
	Language : french
	Memory :     16305MB 308KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : DFX (Haut-parleurs (DFX Audio Enhancer))

----------------------------------------------------------------------

**Comment by Luffyyy** [comment]
No
