### ISSUE TITLE
nil value

### ISSUE THREAD

**Issue by arsium** [simon-wh/PAYDAY-2-BeardLib#294]
Mon Apr 20 15:06:46 2020

Application has crashed: C++ exception
[string "lib/units/weapons/raycastweaponbase.lua"]:499: attempt to perform arithmetic on a nil value

SCRIPT STACK

fire() lib/units/weapons/raycastweaponbase.lua:456
fire() @mods/BeardLib/Hooks/Fixes.lua:399
trigger_held() lib/units/weapons/newnpcraycastweaponbase.lua:203
update() lib/units/enemies/cop/actions/upper_body/copactionshoot.lua:349
_upd_actions() lib/units/enemies/cop/copmovement.lua:646
original() lib/units/enemies/cop/copmovement.lua:609
update() @mods/base/req/core/Hooks.lua:185
lib/units/player_team/teamaimovement.lua:436

**Comment by Luffyyy** [comment]
No information given and no reason to believe BeardLib is the sole cause.
