### ISSUE TITLE
Menu Music not working

### ISSUE THREAD

**Issue by kevkild** [simon-wh/PAYDAY-2-BeardLib#298]
Latest update of BeardLib causing this to break.
Previous verision worked fine, now any menu music in the options will simply not even play.

**Comment by aradiel** [comment]
Also having this issue, heist tracks seen to be working fine, but menu tracks don't play at all, and it will also prevent official songs from playing until I play a heist track. I'm in a fresh new install of Beardlib/SuperBLT, so it can't be another mod messing things up.

**Comment by Luffyyy** [comment]
I don't have this issue

**Comment by Luffyyy** [comment]
You'll have to send me your BLT log

**Comment by aradiel** [comment]
I've actually managed to get a lead on the problem. Basically, older custom menu tracks from the time the music module wasn't included don't work, and it turns out that I had only downloaded tracks from back then. A newer track worked perfectly. Is it supposed to be like that? Older heist tracks still work from what I'm testing, it's happening only with menu tracks

**Comment by aradiel** [comment]
[2020_04_26_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4534611/2020_04_26_log.txt)
The logs, in case you can see anything wrong in them

**Comment by kevkild** [comment]
Seems the update has fixed this issue; thank you.
I took the latest log file (before the update) to test and confirm it was not working. 
[2020_04_27_log(beforeupdate).txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4542268/2020_04_27_log.beforeupdate.txt)
But the update seems to be working great, thank you again.

**Comment by aradiel** [comment]
In that case, it seems the issue with the mods I'm using is unrelated. Should I make a new issue to investigate it further? Or maybe it's not worth investigating/working as intended?

**Comment by Luffyyy** [comment]
Not entirely sure I haven't tried to fix it nor confirm the existence of the issue with old menu music.

**Comment by aradiel** [comment]
It seems to have partially fixed my issue. It's honestly really odd, it's the mod that adds three versions of the "[Stonecold](https://modworkshop.net/mod/18442#description)" menu theme from PD:TH's alpha. All of them worked by the time I stopped playing, now with this update only one of them came back. The XML configs all of them the same way, and my download doesn't seem corrupted or anything like that
`<table name="Stonecold">
    <Localization directory="Loc" default="EN.txt"/>
	
    <Music id="stonecold" directory="music/stonecold" source="original" menu="true" /> 
    <Music id="stonecold_alternate" directory="music/stonecold" source="alternate" menu="true"/> 
    <Music id="stonecold_alternate_intro" directory="music/stonecold" source="intro_only" menu="true"/> 
	

</table>`
In-game, only the alternate works, the others show the same behaviour than before the commit. And it doesn't seem to be an issue with the files, RAD Tools can open all of them just fine. If it's not too much, can you test it and see if it's a problem on my end?
