### ISSUE TITLE
Add chinese language support

### ISSUE THREAD

**Issue by SummonHIM** [simon-wh/PAYDAY-2-BeardLib#299]
[chinese.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4536980/chinese.txt)

it's tested,  fully running on ver 3.50.

**Comment by Luffyyy** [comment]
You can go here https://github.com/simon-wh/PAYDAY-2-BeardLib/tree/master/mods/BeardLib/Localization click on create new file and just paste it and name it chinese.txt
