### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by BlackHawkTP** [simon-wh/PAYDAY-2-BeardLib#30]
Application has crashed: C++ exception
[string "lib/utils/game_state_machine/gamestatemachi..."]:601: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.69.224
	CPU : Intel(R) Pentium(R) 3556U @ 1.70GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 820M / nvldumd.dll[22.21.13.8189]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     4019MB 280KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp.

This happens on Henchman beta update, not sure about the non-beta version.

**Comment by BlackHawkTP** [comment]
Figured out... it was editor. Will help if someone has the same issue.

**Comment by Luffyyy** [comment]
This is probably the old editor(what we currently have in github master branch) uninstall it please.
