### ISSUE TITLE
update 199.3 breaks beardlib

### ISSUE THREAD

**Issue by Colotov-Mocktail** [simon-wh/PAYDAY-2-BeardLib#302]
Update 199.3 has broken Beardlib, as running Super BLT and having beardlib installed, will cause the game to crash on the initial black loading screen

**Comment by Djboy6921** [comment]
My game says that it is running for like 30 seconds and then steam does not respond for like 5 seconds then when it responds the game has crashed.

**Comment by Luffyyy** [comment]
You did not include crashlog. How do you know it's BeardLib specifically? It runs fine sfter you manually update SuperBLT.

**Comment by Colotov-Mocktail** [comment]
I know its Beardlib, because removing beard lib from mods, the game launches, and runs fine. with beard lib installed, it crashes. And yes, im using the updated super blt. 3.2.1

**Comment by Luffyyy** [comment]
Okay, where's the crashlog though? I can't do anything without it

**Comment by ninjaganja2021** [comment]
> Okay, where's the crashlog though? I can't do anything without it

Application has crashed: C++ exception
[string "lib/units/vehicles/vithelicoptersync.lua"]:14: attempt to index local 'player' (a nil value)



SCRIPT STACK

_function() core/lib/managers/coresequencemanager.lua:4545
activate_callback() core/lib/managers/coresequencemanager.lua:4538
activate() core/lib/managers/coresequencemanager.lua:2017
activate_callback() core/lib/managers/coresequencemanager.lua:2814
activate() core/lib/managers/coresequencemanager.lua:2017
activate_callback() core/lib/managers/coresequencemanager.lua:5209
start_time_callback() core/lib/managers/coresequencemanager.lua:2030
update_start_time_callbacks() core/lib/managers/coresequencemanager.lua:537
update() core/lib/managers/coresequencemanager.lua:479
core/lib/setups/coresetup.lua:494


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlSetLastWin32Error                                
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     LdrCallEnclave                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.94.878.
	CPU : Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 440 / nvldumd.dll[23.21.13.9135]
	Language : russian
	Memory :     6077MB 676KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VIA Technologies, Inc. (Динамики (VIA HD Audio(Win 10)))

**Comment by ninjaganja2021** [comment]
its randomly crash on mission, in briefing, no matter, i checked all mods and has a result that it a beardlib something lua-file source of problem, but what this file exactly do i dont know, hope you can find out what is problem

**Comment by Luffyyy** [comment]
@ninjaganja2021 Remember that BeardLib is a library it doesn't add much content on itself. That being said, I doubt this is caused by BeardLib.

**Comment by ninjaganja2021** [comment]
okay then, what is the problem though?

**Comment by Iamgoofball** [comment]
@ninjaganja2021 Can you reproduce the crash with ***just beardlib and superblt installed***? And can you make reproduction steps?

**Comment by ninjaganja2021** [comment]
> @ninjaganja2021 Can you reproduce the crash with _**just beardlib and superblt installed**_? And can you make reproduction steps?

yeah, wait 20 min

**Comment by ninjaganja2021** [comment]
it crashes when i go to checking blt mods update

**Comment by Iamgoofball** [comment]
so, you had nothing in your mods or mod overrides folder aside from Beardlib and the superBLT base mod? What crash log did it generate?

**Comment by ninjaganja2021** [comment]
Application has crashed: breakpoint

-------------------------------

Callstack:

                    KERNELBASE  (???)     DebugBreak                                          
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Renderer

-------------------------------

**Comment by ninjaganja2021** [comment]
i think its more superblt problem, because i cant check update blt mods

**Comment by ninjaganja2021** [comment]
i figured what the source of problem, i not deleted old blt base

**Comment by ninjaganja2021** [comment]
Application has crashed: C++ exception
[string "lib/managers/menu/menucomponentmanager.lua"]:4619: attempt to index field '_fullscreen_ws' (a nil value)



SCRIPT STACK

set_scene_template() lib/managers/menu/menuscenemanager.lua:2688
at_enter() lib/states/menumainstate.lua:14
trans_func() lib/states/gamestate.lua:22
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:921
end_update() lib/setups/menusetup.lua:365
core/lib/setups/coresetup.lua:600


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.94.878.
	CPU : Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 440 / nvldumd.dll[23.21.13.9135]
	Language : russian
	Memory :     6077MB 676KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VIA Technologies, Inc. (Динамики (VIA HD Audio(Win 10)))


there another crash

**Comment by ninjaganja2021** [comment]
i solved the old problem, i should update base of blt

**Comment by Luffyyy** [comment]
If anyone has issues reopen an issue. Each person may have different problems.
