### ISSUE TITLE
Update 199.3 Broke BeardLib

### ISSUE THREAD

**Issue by Djboy6921** [simon-wh/PAYDAY-2-BeardLib#303]
My game says that it is running for like 30 seconds and then steam does not respond for like 5 seconds then when it responds the game has crashed.

_Originally posted by @Djboy6921 in https://github.com/simon-wh/PAYDAY-2-BeardLib/issues/302#issuecomment-621470917_

**Comment by Luffyyy** [comment]
You did not include crashlog. How do you know it's BeardLib specifically? It runs fine sfter you manually update SuperBLT.

**Comment by Djboy6921** [comment]
Nvm it is super blt
