### ISSUE TITLE
BeardLib failing to show up (Update 199.3)

### ISSUE THREAD

**Issue by ZeroJyllmeiko** [simon-wh/PAYDAY-2-BeardLib#304]
Sadly, I have no idea what can cause this. BeardLib fials to show up. I updated the SuperBLT, and still nothing.

**Comment by ZeroJyllmeiko** [comment]
Oh, I reset the settings file when I went into VR for the first time in months. Skins and Armor stopped showing, couldn't load a level. This isn't good.

**Comment by Luffyyy** [comment]
Send BLT log.

**Comment by ZeroJyllmeiko** [comment]
I may have uninstalled PAYDAY
