### ISSUE TITLE
Crash upon starting the game with the latest version of beardlib

### ISSUE THREAD

**Issue by Ernestin123** [simon-wh/PAYDAY-2-BeardLib#305]
hello, as the title says, my game crashes when after starting it using the latest version, the game opens but it closes automatically before reaching the intro movie, this is my crash log 

Application has crashed: C++ exception
mods/BeardLib/Hooks/CoreSystem.lua:16: attempt to call method 'ShouldGetScriptData' (a nil value)

SCRIPT STACK

load_core_settings() core/lib/managers/controller/corecontrollermanager.lua:493
init() core/lib/managers/controller/corecontrollermanager.lua:94
init() lib/managers/controllermanager.lua:14
new() core/lib/utils/coreclass.lua:35
core/lib/setups/coresetup.lua:361

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
          load_core_settings()  core/lib/managers/controller/corecontrollermanager.lua:493  
                        init()  core/lib/managers/controller/corecontrollermanager.lua:94  
                        init()  lib/managers/controllermanager.lua:14               
                         new()  core/lib/utils/coreclass.lua:35                     
                                core/lib/setups/coresetup.lua:361                   

-------------------------------

System information:
	Application version : 1.94.878
	CPU : AMD A4-7210 APU with AMD Radeon R3 Graphics (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : AMD Radeon(TM) R3 Graphics / aticfx32.dll[22.19.163.2560]
	Language : spanish
	Memory :     7125MB 376KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoces (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
...That's not the latest version. You downloaded the version found in releases from **2016**. I was thinking whether or not to remove it and I knew it.

Get stable release here always https://modworkshop.net/mod/14924
