### ISSUE TITLE
BeardLib says updates for mods are installed

### ISSUE THREAD

**Issue by Nathan-Binkley** [simon-wh/PAYDAY-2-BeardLib#306]
Mods install properly in the UI, but fail to be present in the game upon reload. If i play a heist, BeardLib shows the mod isn't downloaded and needs to be re-installed.

**Comment by Luffyyy** [comment]
Can you screenshot this? I'm not sure what you are referring to

**Comment by Nathan-Binkley** [comment]
There was simply an issue with that particular custom heist
