### ISSUE TITLE
Crash just after starting the game (in main menu)

### ISSUE THREAD

**Issue by Lusien26** [simon-wh/PAYDAY-2-BeardLib#307]
Hello. I have a problem. Immediately after starting the game, in a short time, crash happens. This happens shortly after the game starts, usually in the main menu. This is not due to mods (does not write to the log). It happens every time, I don’t know what is the reason.
__________________________________________________________________________________________________________
---
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  181                                                 
                   LoadAsset()  203                                                 
                   unit_data()  @mods/BeardLib/Hooks/CoreSystem.lua:61              
                                core/lib/managers/coresequencemanager.lua:681       

-------------------------------
__________________________________________________________________________________________________________

**Comment by Luffyyy** [comment]
That's not really a reason to blame BeardLib for it.
Install this https://modworkshop.net/mod/27575, crash, zip the contents of "EnterHere" in TroubleShooter and send it here.

**Comment by Lusien26** [comment]
In general, I was hoping only for an explanation of what is written in this crash log so that I myself try to do something, but okay

**Comment by Luffyyy** [comment]
From the looks of it, the game seems to try getting data of a unit (game object) and then fails and crashes (classic diesel). 

Drop this in BeardLib/Hooks, crash, and do what I said in my first comment. This should hopefully lead us to the cause.
[CoreSystem.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4619048/CoreSystem.zip)

**Comment by Lusien26** [comment]
Thanks for the help
