### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by stan9901** [simon-wh/PAYDAY-2-BeardLib#309]
Hi,
my game crash when I starting it. I check me crashlog and find this:
Application has crashed: C++ exception
mods/BeardLib/Classes//Utils/Table.lua:231: attempt to index local 'parent_tbl' (a nil value)

SCRIPT STACK

script_merge() @mods/BeardLib/Classes//Utils/Table.lua:189
@mods/BeardLib/Classes//Utils/Table.lua:189
script_data() @mods/BeardLib/Classes//Managers/FileManager.lua:68
load_data() @mods/base/lua/CoreMenuData.lua:8
register_menu() core/lib/managers/menu/coremenumanager.lua:27
init() lib/managers/menumanager.lua:72
init() @mods/base/lua/MenuManager.lua:9
new() core/lib/utils/coreclass.lua:35
original() lib/setups/setup.lua:384
init_managers() @mods/base/req/core/Hooks.lua:260
original() lib/setups/menusetup.lua:285
init_managers() @mods/base/req/core/Hooks.lua:260
core/lib/setups/coresetup.lua:399

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name

**Comment by Luffyyy** [comment]
Do not download directly from the repo, it contains wip stuff.

**Comment by Luffyyy** [comment]
https://modworkshop.net/mod/27575 but if you can, download this install, crash with it, go to the folder of that mod, zip the EnterHere folder and send it here. That would help a lot.

**Comment by stan9901** [comment]
And where EnterHere folder contains? In Beardlib or in this mod.

**Comment by stan9901** [comment]
[EnterHere.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4673560/EnterHere.zip)
 Ок, in magical way the payday work again, but please check this zip. Maybe later problem return.

**Comment by stan9901** [comment]
![Screenshot_21](https://user-images.githubusercontent.com/65825159/82755123-4f794380-9dda-11ea-86c7-87c9c4c34d82.jpg)

**Comment by Luffyyy** [comment]
Yeah, that's normal.
