### ISSUE TITLE
PAYDAY 2 CRASH!

### ISSUE THREAD

**Issue by XTaskmaster** [simon-wh/PAYDAY-2-BeardLib#31]
Look: I uninstalled the game like 5 times, and verified cache like 7 times... And it crashes everytime I try to start a heist (loading screen) even in offline. Look:

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
          check_music_switch()  core/lib/managers/coremusicmanager.lua:83           
                    at_enter()  lib/states/ingamewaitingforplayers.lua:400          
                                lib/states/gamestate.lua:22                         
                            ()  =(tail                                              
                      call):-1  _do_state_change()                                  
core/lib/utils/game_state_machine/coregamestatemachine.lua:124  end_update()                                        
core/lib/utils/game_state_machine/coregamestatemachine.lua:104  end_update()                                        
      lib/setups/setup.lua:747  end_update()                                        
  lib/setups/gamesetup.lua:712  end_update()                                        
lib/setups/networkgamesetup.lua:33                                                      
core/lib/setups/coresetup.lua:580  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

System information:
	Application version : 1.70.234
	CPU : Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0 
	GPU : Intel(R) HD Graphics Family / aticfx32.dll[8.17.10.1230]
	Language : @ID4176958b9b2622ce@
	Memory :     6546MB 280KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoces (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
And your reason that you assume BeardLib is at fault?
Do you have any other mods?
Do you have any mods that use BeardLib?

**Comment by XTaskmaster** [comment]
I have instaled (before) only blt, beardlib, custom hitmakers, and music control. How can I fix it? Thanks for your comment.

**Comment by Luffyyy** [comment]
music control maybe?

**Comment by XTaskmaster** [comment]
Yeah but the problem is that the crashes still. Cant play anything. I uninstalled the game & verificated game cache more than 5 times. And crashes still happening. Also, before installing beardlib all worked just fine.

**Comment by Luffyyy** [comment]
Just gonna say that uninstalling the game mostly isn't the solution,
and verifying the game is mostly for when installing pdmods.

Does this happen without any mods?
Does this happen with BLT and BeardLib only?

**Comment by XTaskmaster** [comment]
It crashes with no mods and with mods (mods: blt and beardlib)

**Comment by Luffyyy** [comment]
Then here we have it, not caused by BeardLib.
Have any mod_overrides mods?

**Comment by XTaskmaster** [comment]
Before I had some custom weps, but uninstalled long time ago (removed the folder)

**Comment by XTaskmaster** [comment]
I installed only blt now and there are no longer heavy loads (to start a heist only a few secs) but still crashes when trying to start a heist.

**Comment by XTaskmaster** [comment]
Sat May 13 14:26:54 2017


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
          check_music_switch()  core/lib/managers/coremusicmanager.lua:83           
                    at_enter()  lib/states/ingamewaitingforplayers.lua:400          
                                lib/states/gamestate.lua:22                         
                            ()  =(tail                                              
                      call):-1  _do_state_change()                                  
core/lib/utils/game_state_machine/coregamestatemachine.lua:124  end_update()                                        
core/lib/utils/game_state_machine/coregamestatemachine.lua:104  end_update()                                        
      lib/setups/setup.lua:747  end_update()                                        
  lib/setups/gamesetup.lua:712  end_update()                                        
lib/setups/networkgamesetup.lua:33                                                      
core/lib/setups/coresetup.lua:580  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

System information:
	Application version : 1.70.234
	CPU : Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0 
	GPU : Intel(R) HD Graphics Family / aticfx32.dll[8.17.10.1230]
	Language : @ID4176958b9b2622ce@
	Memory :     6546MB 280KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Altavoces (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
https://modworkshop.net/mydownloads.php?action=view_down&did=20502
