### ISSUE TITLE
Beardlib hides the Custom Color backgrounds

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib#311]
Beardlib Installed:
![image](https://user-images.githubusercontent.com/26837908/83940488-121fa780-a817-11ea-9991-b4a8fd389a27.png)
Beardlib Uninstalled.
![image](https://user-images.githubusercontent.com/26837908/83940490-14820180-a817-11ea-9a77-71ff6dbbbabd.png)

**Comment by Luffyyy** [comment]
Huh? What's a custom color background?
