### ISSUE TITLE
Crash when TeleportPlayer element is executed

### ISSUE THREAD

**Issue by Makowo** [simon-wh/PAYDAY-2-BeardLib#313]
Isn't a editor issue as it will happen without it
i believe this to be caused by 68275e9 

quick test map, also crashes on kino der minetoten
[test.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/4833673/test.zip)

Application has crashed: C++ exception
[string "lib/units/beings/player/playermovement.lua"]:1414: attempt to perform arithmetic on local 'fade_in' (a nil value)

SCRIPT STACK

on_executed() lib/managers/mission/elementteleportplayer.lua:22
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
on_executed() core/lib/managers/mission/coreelementarea.lua:121
_check_amount() core/lib/managers/mission/coreelementarea.lua:275
f() core/lib/managers/mission/coreelementarea.lua:235
update() core/lib/utils/coreevent.lua:158
update() core/lib/managers/mission/coremissionmanager.lua:531
update() core/lib/managers/mission/coremissionmanager.lua:160
core/lib/setups/coresetup.lua:520

**Comment by Luffyyy** [comment]
Reverted the wrong fucking thing
