### ISSUE TITLE
creash with costum map

### ISSUE THREAD

**Issue by mcproprot** [simon-wh/PAYDAY-2-BeardLib#32]
Sat May 13 00:46:16 2017

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                @mods/BeardLib/Hooks/CoreSystem.lua:24              
                            ()  =(tail                                              
                      call):-1                                                      
core/lib/utils/dev/editor/coreworlddefinition.lua:921  ()                                                  
                        =(tail  call):-1                                            
                      create()  core/lib/utils/dev/editor/coreworlddefinition.lua:522  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:580                        
                                core/lib/setups/coresetup.lua:402                   
                            ()  =(tail                                              
                      call):-1  
-------------------------------

System information:
	Application version : 1.70.234
	CPU : Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) HD Graphics 4600 / igdumdim32.dll[20.19.15.4531]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     24437MB 956KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Lautsprecher (G510s Gaming Keyboard))

**Comment by Luffyyy** [comment]
https://github.com/simon-wh/PAYDAY-2-BeardLib/wiki/What-is-BeardLib%3F#my-game-is-crashing-and-the-script-stack-says-modsbeardlibhookscoresystemlua-lxx

This is the map's fault.
