### ISSUE TITLE
Beardlib turning gloves invisible.

### ISSUE THREAD

**Issue by AnadWhi** [simon-wh/PAYDAY-2-BeardLib#320]
Im sorry to bother you with this but beardlib is making my hands invisible everytime I try to equip a glove, I can equip outfits but can't equip any gloves, also when I equip an outfit with default gloves the hands still invisible. I don't get any crashes.

**Comment by connorprice** [comment]
Would it be possible for you to provide a list of any other mods you may have installed?

**Comment by AnadWhi** [comment]
> 
> 
> Would it be possible for you to provide a list of any other mods you may have installed?

BLT mods:
1 SuperBLT | 1.1.6.0
2 RestorationMod | 9.7.1
3 Additional PocoHud Trackers | 13
4 CustomFOV | 1.0.0
5 Stop the crimespree loss on crash | 
6 HoloInfo | 1.0
7 Cheater Kicker | 2.1
8 No Duplicated Bullets | 5
9 Rainbow Laser | 1.0
10 Newbies go back to overkill | 76
11 PocoHud3 | based on v0.35 (r467)
12 Skill Tree Background Restoration | 2
13 Music Control | R28
14 Lobby Player Info | 67
15 Free Flight Camera | 1.0
16 tast PD2 Day/Night Changes Reborn Updated | 5
17 Low Violence Mode | 3
18 Drag and Drop Inventory | 23
19 Fix for hud and armor size | 1.0
20 Enhanced Hitmarkers | 36
21 The Fixes | 11

PAYDAY 2/Maps:
1 Zdann_Enemy_Spawner

PAYDAY 2/assets/mod_overrides:
1 AA12 skull
2 Ace Of Spades For Matever
3 Better Bloodsample Icons
4 BFS
5 Bodhi's V8.5
6 Breaker 12G Skull
7 Chrome Immortal Python Skin
8 Chrome Immortal Python Skin Icons
9 Drive Jacket
10 Driving Gloves Black - Wick Replacer
11 Enhanced Hitmarkers
12 Entropic Shotgun Soundpack
13 Goliath
14 Hawks_soundpack
15 Heist music
16 HI - ValentinesSuitPack3
17 Izhma skull
18 Jarey's Zeals
19 John Wick Mod
20 John Wick soundpack
21 Joseph Joestar
22 Jou OU - Skull
23 Kimber 1911 Southern Cross
24 KSG Skull
25 LC_MacroPack_HoxtonBreakoutEvidenceBox
26 LC_MacroPack_Smoke
27 M1014 Skull
28 Menu music
29 Metallic Immortal Python
30 Mosconi 12G skull
31 mosin pink
32 Old Medic Dozer
33 Old Minigun Dozer
34 One Handed Sprint
35 OwO Dozer REBORN
36 Pain, Shells, and Tears
37 Portal First-Aid Cake
38 Rage 2 Gun Sound
39 Reinfeld, Loco - Skull
40 RPG Skull
41 Senpai Dozer - Skulldozer
42 Senpai Minigun Bulldozer
43 Silent Killer - Old model
44 Skull Gloves
45 Skull GSPS 12G
46 Skull Judge
47 Smokin_Barrels
48 Spin
49 Spinny Unequip
50 Star Wars Guns (No M4.bnk)
51 Star Wars Guns (with  M4.bnk)
52 Suijin's Black+Red Suit for Clover
53 Sunshot For Bronco
54 Sydney's skeleton gloves
55 The Hollywood Shootout Mod
56 The Professional Hud
57 trash
58 Vienix's John Wick's All Black Suit
59 [Aday - Loot Bag - RussMetro LL]
60 [COMMON Buildings
61 [COMMON] Rest room
62 [COMMON] Streets
63 [COMMON] Vegetation
64 [EQUIPMENT] Player
65 [HEIST] Bank
66 [HEIST] Big Bank
67 [HEIST] Big Oil
68 [HEIST] Diamond Store
69 [HEIST] Escapes
70 [HEIST] Firestarter
71 [HEIST] Gellery
72 [HEIST] Go Bank
73 [HEIST] Hotline Miami
74 [HEIST] Hoxton Breakout
75 [HEIST] Jewlery Store
76 [HEIST] Mall Crasher
77 [HEIST] Murky Station
78 [HEIST] Nightclub
79 [HEIST] Rats
80 [HEIST] Safehouse

**Comment by connorprice** [comment]
As far as I have tested, I cannot seem to personally recreate this. This may be a incompatibility with one of your mods.

**Comment by Luffyyy** [comment]
Re-open issue if it still persists.
