### ISSUE TITLE
Silent Modded Songs

### ISSUE THREAD

**Issue by Momocrisps** [simon-wh/PAYDAY-2-BeardLib#321]
Hello!

I keep having an issue with beardlib where, with it set to random, the game seems to choose a modded song most of the time, and about 60% of the time it chooses a modded song, that song will be completely silent. My beardlib is at the latest update. I did a little study, and out of 5 restarts on Firestarter Day 1 (not that heist matters), all 5 songs were modded, and only the 5th one actually played correctly. It's really random too, sometimes the songs will work, sometimes they won't. I run Advanced Movement Standalone, which seems to be the only other mod that Beardlib runs apart from modded songs on my game, and after disabling it, I ran another test like the Firestarter one. Of 5 restarts, 4 songs were modded, 1 was vanilla, and all the modded songs worked. However, later, while doing crime spree, I got another silent song 3 heists in. I don't see anyone reporting errors like this on the comments for that mod. I also don't see any errors from beardlib on the BLT log except for it complaining a couple songs are missing bustin.mov, but those songs have worked anyway with the exception being the silent song glitch.

**Comment by Luffyyy** [comment]
Check if the last commit fixed this issue. I was able to confirm issue #337 which might be related to this issue.
