### ISSUE TITLE
Crash on clicking heist with custom crimenet callout

### ISSUE THREAD

**Issue by VxWolf** [simon-wh/PAYDAY-2-BeardLib#324]
The game crashes if you use custom audio to definite a crime net callout, then click on the heist on crime.net

Steps to reproduce:

- Define a custom sound, with .ogg
- Set the narrative's crimenet callout as that sound
- Hover over the heist in crime.net when it appears. If you then click on the heist, or hover over another heist/the same heist, you get a crash similar to the following:

```
Application has crashed: C++ exception
[string "core/lib/utils/corecode.lua"]:100: attempt to call method 'alive' (a nil value)



SCRIPT STACK

post_event() lib/managers/menu/menucomponentmanager.lua:4597
update_job_gui() lib/managers/crimenetmanager.lua:4665
update_all_job_guis() lib/managers/crimenetmanager.lua:4867
mouse_moved() lib/managers/crimenetmanager.lua:4848
mouse_moved() lib/managers/menu/menucomponentmanager.lua:2145
mouse_moved() @mods/base/lua/MenuComponentManager.lua:34
mouse_moved() lib/managers/menu/menurenderer.lua:428
mouse_move() lib/managers/menu/menuinput.lua:265
lib/managers/mousepointermanager.lua:321
```

**Comment by Luffyyy** [comment]
No time to fix this, if you can get anyone to contribute and add a pull request to fix it, I'll gladly accept it.

**Comment by Luffyyy** [comment]
Including a project for issues relating to maps and such will save me (or any other programmer) time and allow me to fix it if I have time.
