### ISSUE TITLE
Beardlib missing textures.

### ISSUE THREAD

**Issue by Cyberguard25** [simon-wh/PAYDAY-2-BeardLib#325]
When i started the game up today i saw a bunch of missing textures https://imgur.com/a/yqNK5Rq I tried updating all of my mods (including Beardlib) yet nothing helped. I haven't touched Payday 2 since before the Tijuana heist update so i'm not sure if the update broke it or if a different update broke it.

**Comment by Luffyyy** [comment]
No idea what to say sadly. I don't have time to test this but last time I checked it worked, even on Linux. You may need to try a complete clean install and install things one by one.

**Comment by Luffyyy** [comment]
Very likely a random issue caused by other things. If it still persists, you can re-open the issue.
