### ISSUE TITLE
Custom heists not being detected properly.

### ISSUE THREAD

**Issue by bepri** [simon-wh/PAYDAY-2-BeardLib#327]
I saw someone on crime.net playing deepwater and figured I'd try out a custom heist finally. I click their name and beardlib prompts me to download deepwater off of modworkshop. I agree, it downloads, it properly appears in my "Maps" folder and I restart my game for safe measure. I get back in, see the same guy playing deepwater, and click again to join. Again, beardlib asks me to install deepwater. I check again, it's still in the Maps folder. I check the beardlib menu, it's being detected as installed.

Nothing I do seems to allow me to join this person. Beardlib just keeps asking me to install the map when I click. I've tried restarting numerous times, disabling updates, disabling/re-enabling the map in the beardlib menu, reinstalling the map manually without beardlib, and no dice every time.

**Comment by Luffyyy** [comment]
Try with a different map. I cannot test it right now to confirm it. You generally should **not** restart after downloading the map via crime.net as it is supposed to automatically refresh in-game when the map is finished downloading. It's possible that the map is not setup correctly.
