### ISSUE TITLE
Crash when player joins while bots use custom weapons

### ISSUE THREAD

**Issue by segabl** [simon-wh/PAYDAY-2-BeardLib#33]
`Application has crashed: C++ exception
mods/BeardLib/Classes/utils.lua:256: attempt to index local 'wep' (a nil value)`

This happens when you use custom weapons on bots and a player drops in midgame.

**Comment by Luffyyy** [comment]
Sorry for taking long to answer:
Does the issue still persist?

**Comment by segabl** [comment]
Not sure, I'm currently on the desync beta. I'd have to check.

**Comment by gribbely** [comment]
Issue still persist. At least for me too. Specifically, I give my bots Galil ACE and L115, didn't test with other custom guns.

**Comment by Luffyyy** [comment]
https://github.com/simon-wh/PAYDAY-2-BeardLib
Please try the latest github version if it's good then I'll release it.
btw, a crash that might occur(I'm not sure if it's connected to my changes): string "core/lib/managers/coresequencemanager.lua"]:4002: attempt to index local 'body' (a nil value)
It happened to my friend while we were testing the fix but weirdly enough when I tried recreating the same thing when he's the host / other pc as host I did not crash and I tried with custom weapons and without.
I'm hoping this solves it so I can try looking at the roots of the coresequencemanager crash.
