### ISSUE TITLE
[BUG] Custom multi-day narratives crash clients.

### ISSUE THREAD

**Issue by SOMNUSNOVUS** [simon-wh/PAYDAY-2-BeardLib#332]
As titled.

Clients playing on a custom level crash when it proceeds to day 2/3/etc., confirmed to occur in vanilla play as well (so it's not a resmod issue.)

The following is the log:

Application has crashed: C++ exception
[string "core/lib/utils/dev/editor/coreworlddefinition..."]:910: attempt to index a nil value

SCRIPT STACK

create() core/lib/utils/dev/editor/coreworlddefinition.lua:522
create_world() core/lib/utils/dev/editor/worldholder.lua:110
init_game() lib/setups/gamesetup.lua:653
core/lib/setups/coresetup.lua:422

**Comment by Luffyyy** [comment]
The only thing I can suggest is trying to find the exact lines of this crash (from source) by pasting the decompiled coreworlddefinition in the head of the hooked file in BeardLib and then crashing again. This could at least give me or any other developer some clue. I don't have time to test it myself atm.

**Comment by Luffyyy** [comment]
Should be fixed by pull #359
