### ISSUE TITLE
CTD when attempting to enter safehouse

### ISSUE THREAD

**Issue by JackDarkZero** [simon-wh/PAYDAY-2-BeardLib#334]
Application has crashed: C++ exception
mods/BeardLib/Hooks/UI/MenuManager.lua:52: attempt to index a nil value

SCRIPT STACK

callback_func() lib/managers/menu/pages/customsafehouseguipagemap.lua:476
button_pressed() lib/managers/dialogs/dialog.lua:58
button_pressed_callback() lib/managers/dialogs/genericdialog.lua:351
mouse_press() lib/managers/dialogs/genericdialog.lua:115
lib/managers/mousepointermanager.lua:345

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlInitializeCriticalSectionEx                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

**Comment by Luffyyy** [comment]
Cannot reproduce. Tried both old and new.

**Comment by Luffyyy** [comment]
Still happens?

**Comment by Luffyyy** [comment]
No response, reopen issue if it still happens with the last commit on GitHub.
