### ISSUE TITLE
Custom music's stealth sections are not played

### ISSUE THREAD

**Issue by VirusMS** [simon-wh/PAYDAY-2-BeardLib#337]
When starting a heist with any addon (non-replacer) music, stealth sections seem to be not working. Instead, a preview assault section keeps playing (the one I hear when choosing the song in the menu)

Mod list:
**AdaptiveStreamingChunkSize
AFSF2 (Auto fire sound fix)
CreateEmptyLobby
Fading Contour
HideClearProgress U198 (hides the 'clear progress' button in the options)
Iter
Meth Helper Updated
Moveable Intimidated Cop
No duplicated bullets
Poco Crimenet Standalone
SteamInventoryInLobby
ThrowablesInTeamLoadout
WolfHUD**

relevant mod_overrides mods:

**No Mask
L4D2 Nick for Tony
Wrench as Joy**

I checked the logs but nothing related to this issue was found (no entries containing serious warnings or any errors whatsoever).
Any idea?

**Comment by Luffyyy** [comment]
You can check if the last commit has improved the situation (by downloading through GitHub)
