### ISSUE TITLE
game crashes due to access violation

### ISSUE THREAD

**Issue by TacBan** [simon-wh/PAYDAY-2-BeardLib#339]
something in the script stack mentioned beardlib, and i didn't get much help from reddit, so i thought this place could help.
game crashes around 50 seconds after startup.
SIDENOTE: i restarted my computer earlier, and it ran Payday 2 fine the first time. after that, it started crashing again.

     Comment: 'Application has crashed: access violation

      -------------------------------

      Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

       -------------------------------

     Current thread: Main
     Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:169  
                   LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:191  
                   unit_data()  @mods/BeardLib/Hooks/CoreSystem.lua:62              
                                core/lib/managers/coresequencemanager.lua:681       

      -------------------------------

     System information:
	Application version : 1.96.909
	CPU : AMD A10-6700 APU with Radeon(tm) HD Graphics (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : AMD Radeon HD 8670D / aticfx32.dll[8.17.10.1433]
	Language : english
	Memory :     12029MB 804KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (2- High Definition Audio Device))

**Comment by Luffyyy** [comment]
Delete mods that may use BeardLib.

**Comment by TacBan** [comment]
NEVERMIND THIS, i found out i had both Custom Attachment Points and WeaponLib installed and it was causing Classic Weapon Animations to shit itself. Disregard this thread.
