### ISSUE TITLE
Missing file and the download manager cant update it

### ISSUE THREAD

**Issue by MercifulGryphon** [simon-wh/PAYDAY-2-BeardLib#340]
Please help, i cant figure out why it wont work
![image](https://user-images.githubusercontent.com/71197123/93006592-fcc4c280-f555-11ea-9f0e-af3cd1c62fc3.png)

![image](https://user-images.githubusercontent.com/71197123/93006599-0e0dcf00-f556-11ea-9340-bd367ddabad9.png)

Any idea whats wrong?

**Comment by ChildishGiant** [comment]
Sounds like you're trying to use [BeardLib-Editor](https://github.com/Luffyyy/BeardLib-Editor) but didn't follow the [install instructions](https://github.com/Luffyyy/BeardLib-Editor#installation) properly 😉 You need to download [this](https://modworkshop.net/mod/25270) and put it in the BeardLib-Editor folder in mods.

**Comment by MercifulGryphon** [comment]
Thanks!
