### ISSUE TITLE
Custom Packages using shortcuts prints error logs

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib#341]
Using addfile shortcuts (eg. here `unit_obj`) prints errors in logs when using the custom packages feature.
They do load and spawn just fine ingame.

Add.xml:
`<unit_obj path="units/pd2_mod_owp/editor_tools/dev_nav_splitter/dev_nav_splitter_2x3m" />`

Log on startup:
`Lua: [BeardLib-Editor] [ERROR][ReadCustomPackageConfig] File does not exist! Maps/open_world/assets/units/pd2_mod_owp/editor_tools/dev_nav_splitter/dev_nav_splitter_2x3m.unit_obj`

**Comment by Luffyyy** [comment]
Editor issue.
