### ISSUE TITLE
BL-Base crashes upon reloading Akimbo

### ISSUE THREAD

**Issue by FMHikari** [simon-wh/PAYDAY-2-BeardLib#343]
Occurs when reloading any akimbo, although i discovered the crash while trying out the Para SMG akimbo.

[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5261484/crashlog.txt)

**Comment by Luffyyy** [comment]
Cannot reproduce with clean BeardLib installation. Tried with the weapon you discovered the crash with.

**Comment by Luffyyy** [comment]
If this still happens try removing some mods. If you are sure this is BeardLib causing we'll need to test it together in Discord.
