### ISSUE TITLE
Beardlib crashes every time I click on "Contract Broker" 

### ISSUE THREAD

**Issue by Viskkerk** [simon-wh/PAYDAY-2-BeardLib#344]
It could only be beardlib since if I remove it from the mods folder, it allows me to click on it. However if when I install it back it the game freezes, then crashes.

**Comment by Luffyyy** [comment]
Sounds like a map you have causing it. Possibly not installing all of its requirements such as custom contractors. And no, it's the same as saying as soon as I remove BLT, the game stops crashing. Only if truly the game crashes with only BeardLib without anything that could use it, then it can be the cause.

**Comment by Luffyyy** [comment]
Reopen issue if it persists.
