### ISSUE TITLE
Game crashes with Beardlib

### ISSUE THREAD

**Issue by FishGaming** [simon-wh/PAYDAY-2-BeardLib#345]
Hello I'm reported a crash with Beardlib. Went to update my beardlib and superBLT so that I can play since the latest update. Current date is 9/26/2020. With superBLT and all my mods that are not dependent on Beardlib the game loads fine. I take all my mods out and put only Bardlib in (with SuperBLT downloaded and working of course) and it crashed my game every time. Please help or just test to make sure it's working with the latest version!

**Comment by Luffyyy** [comment]
Include a crashlog. Are you 100% sure no mods you have use BeardLib?

**Comment by FishGaming** [comment]
Right after posting I found that my mod override folder had Bearlib mods in
it! That is the issue.

Thanks for the quick reply!

Talmadge
