### ISSUE TITLE
Dialogue crashes

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#346]
https://modworkshop.net/mod/25979 <- My project.
crash.txt file;
`Application has crashed: C++ exception
[string "lib/managers/dialogmanager.lua"]:115: attempt to index field '_current_dialog' (a nil value)

SCRIPT STACK

_callback() lib/units/dramaext.lua:68
callback() @mods/BeardLib/Classes/MixedSoundSource.lua:44
next_in_queue() @mods/BeardLib/Classes/MixedSoundSource.lua:53
update() @mods/BeardLib/Classes/MixedSoundSource.lua:140
update() @mods/base/req/xaudio/XAudio.lua:34
func() @mods/base/req/xaudio/XAudio.lua:43
Call() @mods/base/req/core/Hooks.lua:109
original() @mods/base/lua/GameSetup.lua:6
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

Callstack:

     payday2_win32_release  (???)     ???                                                 
     payday2_win32_release  (???)     ???                                                 
                       ???  (???)     ???                                                 
Current thread: Main

-------------------------------`

This is a random crash that is happening pretty frequently when playing. I have no idea how to replicate it, it just does crash in certain moments when Voice line is beeing played / changed / stopped. All Voice Lines are played with Dialogue Element.

**Comment by MiamiCenterPL** [comment]
Due to update of my map, you have to remove the 
`Hooks:PreHook(DialogManager,"finished", "fix_it_MAYBE", function(self, ...)
	if not self._current_dialog then
		log("fix it.")
		self._current_dialog = {
			id = id,
			params = params
		}
	end
end)`
from dialogmanager.lua.
This part of script is just an temporary fix. With it game does not crash, but play two voice lines at a time sometimes.

**Comment by Luffyyy** [comment]
I've changed something that fixed the following issue #324 could you check if the issue still happens with this change implemented?

**Comment by Luffyyy** [comment]
Hello?

**Comment by MiamiCenterPL** [comment]
I will test it tommorow, I had no PC for two months.

**Comment by Luffyyy** [comment]
Alright.

**Comment by MiamiCenterPL** [comment]
Seems fixed.
