### ISSUE TITLE
Weapons that are based_on a different weapon slot sync wrongly in crew setup, and show up as default AMCAR/Chimano ingame

### ISSUE THREAD

**Issue by morerokk** [simon-wh/PAYDAY-2-BeardLib#347]
Scenario: me (the host) and the client (the screenshotter) both had [Vanilla Mod Pack - Volume Two](https://modworkshop.net/mod/28248) installed. I was using the secondary shotgun in this pack, which is `based_on` the M1014, a *primary* weapon.

Despite both of us having the mod installed, in Crew Setup, it showed me as actually using the Benelli M4 rather than the real weapon icon.
![image](https://user-images.githubusercontent.com/5961617/94851362-a1854200-0428-11eb-85e1-8b1b2565a233.png)

When we were ingame, all he saw was me holding the default Chimano 88. It seems like weapon syncing doesn't quite work well if the based_on weapon is in a different weapon slot than the real weapon.

**Comment by segabl** [comment]
Is this still an issue in the current BeardLib version?
