### ISSUE TITLE
Instant crash on load

### ISSUE THREAD

**Issue by ThetopNOOB** [simon-wh/PAYDAY-2-BeardLib#348]
so whenever i load on whitehouse with beardlib i instantly crash i removed all my mods and modoverrides without anything i can normally load but if i only but beardlib in my mods folder i instantly crash assoon as i loaded in whitehouse i would rly like a fix for that cuz many gud mods need beardlib to function

**Comment by Luffyyy** [comment]
Crashlog missing.

**Comment by RdmGuyBehindYou** [comment]
Idk why but i dont get any crashlog but im 100% sure that its beardlib 
I tried both version this one and the one from the modworkshop both testet without any other mods or modoverrides both crash and i get no crashlog.

**Comment by Luffyyy** [comment]
Cannot reproduce

**Comment by Luffyyy** [comment]
You'll have to test around. It's possible it's a memory limit issue dunno.

**Comment by Rq52** [comment]
I have a problem similar to that which happens when loading into a game that is in loud when there are tons of objects and chaos happening. Im guessing its maybe memory but i dunno?
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5851815/crash.txt)

**Comment by Luffyyy** [comment]
It could be but I don't think this is inherently BeardLib's fault. Try removing mods that might be taxing on memory. Could also be a bug in the game itself.
