### ISSUE TITLE
crash while game starting

### ISSUE THREAD

**Issue by mynameismynamelol** [simon-wh/PAYDAY-2-BeardLib#349]
the game always crashes when i try to start it help please
[2020_10_05_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5329496/2020_10_05_log.txt)

**Comment by Luffyyy** [comment]
I need crashlog not BLT log
%localappdata%/payday 2 in the file crash.txt

**Comment by mynameismynamelol** [comment]
sorry here
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5333428/crash.txt)

**Comment by Luffyyy** [comment]
Doesn't seem like something BeardLib itself causes. Remove some mods until the problem resolves itself.
