### ISSUE TITLE
won't create mod_overrides folder when installed

### ISSUE THREAD

**Issue by Sinaro2** [simon-wh/PAYDAY-2-BeardLib#353]
my friend told me that I should delete my old mod_overrides folder and install beardlib, which creates a new one. This didn't happen. What did I do wrong?

**Comment by Luffyyy** [comment]
Not sure why your friend told you that, BeardLib doesn't create mod overrides folder. iirc it creates the Maps folder and that's it. You need to manually create the folder and drop your mods there
