### ISSUE TITLE
Crash report.

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#355]
Application has crashed: C++ exception
mods/BeardLib/Hooks/Network/NetworkMatchmakingSteam.lua:110: attempt to index a nil value

SCRIPT STACK

Call() @mods/base/req/core/Hooks.lua:109
set_attributes() @mods/BeardLib/Hooks/Network/NetworkMatchmakingSteam.lua:16
set_server_attributes() lib/network/matchmaking/networkmatchmakingsteam.lua:1041
update_matchmake_attributes() lib/managers/menumanager.lua:3252
next_stage() lib/managers/jobmanager.lua:1256
at_enter() lib/states/ingamelobbymenu.lua:173
trans_func() lib/states/gamestate.lua:22
_do_state_change() core/lib/utils/game_state_machine/coregamestatemachine.lua:124
end_update() core/lib/utils/game_state_machine/coregamestatemachine.lua:104
end_update() lib/setups/setup.lua:926
end_update() lib/setups/gamesetup.lua:794
end_update() lib/setups/networkgamesetup.lua:33
core/lib/setups/coresetup.lua:600

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlSetLastWin32Error                                
                         ntdll  (???)     LdrLoadEnclaveModule                                
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Situation: I finished FunBank: Specials heist with my friends, and the game crashed at the Level menu (where it adds XP).

**Comment by saladofstones** [comment]
Current thread: Main
Script stack:
WorldDefinition_load_continent_package()  core/lib/utils/dev/editor/coreworlddefinition.lua:184  
WorldDefinition_load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:81  
     _load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:81  
                    original()  core/lib/utils/dev/editor/coreworlddefinition.lua:298  
           _insert_instances()  @mods/base/req/core/Hooks.lua:188                   
            parse_continents()  core/lib/utils/dev/editor/coreworlddefinition.lua:286  
        WorldDefinition_init()  core/lib/utils/dev/editor/coreworlddefinition.lua:44  
        WorldDefinition_init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  lib/utils/dev/editor/worlddefinition.lua:6          
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  core/lib/utils/dev/editor/worldholder.lua:49        
                         new()  core/lib/utils/coreclass.lua:35                     
                   init_game()  lib/setups/gamesetup.lua:653                        
                                core/lib/setups/coresetup.lua:422

**Comment by Luffyyy** [comment]
@MiamiCenterPL Can you confirm this issue still happens?

@saladofstones Context?
