### ISSUE TITLE
Game crashes when I buy Buluc's Mansion in the contract broker

### ISSUE THREAD

**Issue by MatthewCAbel** [simon-wh/PAYDAY-2-BeardLib#356]
Here is the log: 

Application has crashed: C++ exception
mods/BeardLib/Hooks/UI/MenuManager.lua:52: attempt to index a nil value

SCRIPT STACK

yes_func() lib/managers/menumanager.lua:2881
show_confirm_buy_premium_contract() @mods/VanillaHUD Plus/lua/MenuTweaks.lua:1001
callback() lib/managers/menumanager.lua:2861
trigger() core/lib/managers/menu/items/coremenuitem.lua:150
core/lib/managers/menu/coremenulogic.lua:286
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
original() lib/managers/menumanagerpd2.lua:20
update() @mods/base/req/core/Hooks.lua:265
original() lib/setups/setup.lua:863
update() @mods/base/req/core/Hooks.lua:188
update() lib/setups/menusetup.lua:352
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                       atcuf32  (???)     AtcQueryRegion                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.97.918
	CPU : AMD Ryzen 5 3600 6-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1660 / nvldumd.dll[27.21.14.5730]
	Language : english
	Memory :     16313MB 916KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Cannot reproduce. Only because BeardLib shows up on top, doesn't mean it's the culprit.

**Comment by Luffyyy** [comment]
Reopen issue if still persists and that you've confirm it is Beardlib causing. Try removing other mods until the problem is solved.
