### ISSUE TITLE
BeardLib not working at all.

### ISSUE THREAD

**Issue by Juggernaut2442** [simon-wh/PAYDAY-2-BeardLib#357]
I have installed BeardLib and put it into my mods file but unfortunately it refuses to work. My SuperBLT is fully updated to the latest version. No logs are appearing in the mods/logs file. Using any BeardLib required mods crashes my game. It shows up in SuperBLT mods list but the BeardLib symbol does not show up in the main menu.

**Comment by Luffyyy** [comment]
If it doesn't show anything in the log, then you're definitely not installing something correctly. Are you sure you are installing BeardLib from modworkshop in the *mods* folder?

**Comment by Juggernaut2442** [comment]
I have properly installed everything, seems like the reason was me not running the game as administrator. Unless I do that BeardLib just does not want to work. I checked now and realized that my "mods" file was accesible to only administrators so Payday 2 wasn't able to access BeardLib. Weirdly enough  SuperBLT and mods that require only SuperBLT was working just fine. Sorry to bother.
