### ISSUE TITLE
game crash when loading Buluc's Mansion

### ISSUE THREAD

**Issue by Endergamer98** [simon-wh/PAYDAY-2-BeardLib#358]
Application has crashed: C++ exception
[string "core/lib/managers/coresequencemanager.lua"]:5019: attempt to index local 'obj' (a nil value)

SCRIPT STACK

load_element_data() core/lib/managers/coresequencemanager.lua:905
core/lib/units/coreunitdamage.lua:862

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlSetLastWin32Error                                
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     LdrCallEnclave                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

**Comment by Luffyyy** [comment]
Proof that BeardLib causes that? It's very generic crash that could be caused by many mods. For example, pdmods.

**Comment by Rq52** [comment]
I have the same crash. Very generic meaning that it will most likely be a mod_overrides! YAY!!

**Comment by Luffyyy** [comment]
If you have this kind of crash just try removing mods until it's solved.
