### ISSUE TITLE
No texts for Hispanoamerica location

### ISSUE THREAD

**Issue by demydemise** [simon-wh/PAYDAY-2-BeardLib#364]
Basically when the game is in the Latin American language, Bearlib looks like this, without texts:

![20201124231640_1](https://user-images.githubusercontent.com/21368953/100174803-edde8280-2eab-11eb-9128-69b6a314440c.jpg)

In European Spanish it works correctly.

**Comment by Luffyyy** [comment]
Thanks for reporting. The next update should make it fallback to European Spanish. If necessary, anyone can do a Latin American Spanish localization for BeardLib. Just copy english.yaml in localization and name it latam.yaml, translate and make a pull request.
