### ISSUE TITLE
Problem starting the game

### ISSUE THREAD

**Issue by PastorNapas13** [simon-wh/PAYDAY-2-BeardLib#365]
Help the game crashes on startup !!! it's Beardlib's fault what should I do? all mods checked the problem in it is 100%

**Comment by Luffyyy** [comment]
This tells me nothing. I highly doubt BeardLib causes a crash by itself. As a start, I'd like to see a crashlog. You can find it in %localappdata%/payday 2 crash.txt

**Comment by PastorNapas13** [comment]
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5598625/crash.txt)

**Comment by Luffyyy** [comment]
You've installed a custom weapon and did not install the dependencies of it. Make sure to read the what mods each requires. However, in this situation, you need to install WeaponLib https://modworkshop.net/mod/29987

**Comment by PastorNapas13** [comment]
thank you very much

**Comment by PastorNapas13** [comment]
the game still does not start

**Comment by Luffyyy** [comment]
I recommend going to MWS discord. Post the new crashlog and someone hopefully will help. Otherwise, you can try uninstalling mods one by one until it works.
