### ISSUE TITLE
Modded weapon skins (mod_overrides) stopped working

### ISSUE THREAD

**Issue by jaredcarmes** [simon-wh/PAYDAY-2-BeardLib#366]
With the latest update of BeardLib, as of seconds ago, all of my custom skins have stopped working. They are not selectable within the skins section, as if they were not even installed. The two skins are [BUFF Universal Skin](https://modworkshop.net/mod/24358) and [The Golden Immortal Pack](https://modworkshop.net/mod/22937). I've confirmed that downgrading BeardLib resolves this issue.

**Comment by Luffyyy** [comment]
Is it still a problem? I'm not really sure about these things since who is in charge of the changes for that system is @connieprice via this pull https://github.com/simon-wh/PAYDAY-2-BeardLib/pull/361

**Comment by connieprice** [comment]
Could you please check the weapon color menu as I moved universal skins to that system as highlighted within pull #361

**Comment by Luffyyy** [comment]
Assuming this isn't an actual issue, closing.
