### ISSUE TITLE
Game crashes after selecting heist (coreworlddefinition issue)

### ISSUE THREAD

**Issue by piodof** [simon-wh/PAYDAY-2-BeardLib#368]
Game opens as usual but crashes while selecting specific custom heist like: Harvest & Trustee Southern Branch or Hardware Store. It happens right after selecting heist before preplanning. Reproduced without any other mods installed except Super BLT.
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5612565/crash.txt)

**Comment by Luffyyy** [comment]
Try to uninstall BeardLib and install it from modworkshop. Make sure you don't accidentally have 2 installations of BeardLib.

**Comment by piodof** [comment]
Unfortunately it still doesn't work. I reinstalled BeardLib including base folder and SuperBLT with those downloaded from modworkshop. Removed all custom maps and left only Harvest and Trustee Southern Branch. I'm attaching mods/logs file.
[2020_12_01_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5619388/2020_12_01_log.txt)

**Comment by ilrathCXV** [comment]
Currently having the same problem as well. Tried The Hanger and H&T Southern Branch as well. Getting the same error. Here is the crash log. Also noted in the SuperBLT logs that I am getting this string of errors at the end of the log for Southern Branch:

12:39:04 AM Lua: [BeardLib][ERROR] File does not exist! Maps/Harvest and Trustee - Southern Branch/assets/units/pku_kitcoin/pku_kitcoin.cooked_physics
12:39:05 AM Lua: Loading mod settings : nil
12:39:10 AM Lua: [BeardLib][ERROR] Failed reading file 'Maps/Harvest and Trustee - Southern Branch/levels/tj_htsb/world.world', are you trying to load a file with different format?
12:39:12 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:57) CURL CLOSED
12:39:12 AM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\xaudio\XAudio.cpp:137) Closing OpenAL XAudio API

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5994641/crash.txt)

**Comment by Luffyyy** [comment]
Confirm if it still happens as of last commit.

**Comment by ilrathCXV** [comment]
I am having a similar problem. I closed my bug report after the problem maps started working after I did a clean re-install of Windows. I kept all of my many mods intact and maps were working. But, as of today, the problem as happened once again. Tried it with the latest release on MWS as well.

As I stated in my previous report, the maps that don't work almost exclusively use " type="binary" " for their level files, while the maps that do work mainly use either "generic_xml" or "custom_xml" with a few "binary" as well. Here is my crash file that was created a few minutes ago: 
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6148207/crash.txt)

Before I did the clean re-install for Windows, I did try uninstalling all mods (and mod_overrides) excluding SuperBLT, BeardLib, and the map I tried (Proving Grounds). Had all settings down to minimum and map would not start. Hoping this might help in some sort of way.

**Comment by Luffyyy** [comment]
Dunno what to say. If there was an actual issue a lot more people would've reported it. I tried loading the map and to no one's surprise it loaded without a hitch. The crash has nothing to do with memory limit and indicates that either something is missing or something isn't loading right. Are you sure you're running purely SuperBLT, BeardLib and that map? Have you tried verifying your game? If this issue happens only to select few like you I'll need to test with you through a place like Discord.

**Comment by ilrathCXV** [comment]
> Dunno what to say. If there was an actual issue a lot more people would've reported it. I tried loading the map and to no one's surprise it loaded without a hitch. The crash has nothing to do with memory limit and indicates that either something is missing or something isn't loading right. Are you sure you're running purely SuperBLT, BeardLib and that map? Have you tried verifying your game? If this issue happens only to select few like you I'll need to test with you through a place like Discord.

I went back to test it with nothing but SuperBLT, BeardLib (updated), and Proving Grounds and it still results in the same crash (settings set to very low and streaming chunks set to 128 iirc). I also restarted my account progression to ensure anything left over from the mods that I uninstalled were not present. Also had Steam validate PAYDAY 2 and no errors were found. No overlays of any kind were on (ShadowPlay/Discord/Steam). I will put in the mods log as well as the crash log:
[2021_03_16_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6152749/2021_03_16_log.txt)
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6152750/crash.txt)

One thing I will check is to see if the drive I have PD2 installed on has any issues itself then get back to you. But so far, this is what I have found.

**Comment by PONYMODZ** [comment]
I have a similar issue also did multiple clean installs but nothing helped so far
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6159477/crash.txt)

**Comment by Luffyyy** [comment]
> I have a similar issue also did multiple clean installs but nothing helped so far
> [crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6159477/crash.txt)
> 

This crash is not the same. Make a new issue. Detail what map crashes specifically.

**Comment by Luffyyy** [comment]
Unfortunately these kind of issues require me to debug with you guys so if you want to, add me on discord Luffy#4754. When I'll be free, I'll send you code to test and see what's going on exactly. I saw in your log loading failures which is not a good sign.

**Comment by ilrathCXV** [comment]
> Unfortunately these kind of issues require me to debug with you guys so if you want to, add me on discord Luffy#4754. When I'll be free, I'll send you code to test and see what's going on exactly. I saw in your log loading failures which is not a good sign.

Will do. I am busy during this week so I may follow up with you during the weekend. I will message you around Friday or so. Thanks in advance for the help.
