### ISSUE TITLE
my game crashes when i log into crime.net

### ISSUE THREAD

**Issue by MrDispenser** [simon-wh/PAYDAY-2-BeardLib#369]
I removed all of my mods and tried again but it still crashes, the crashlog looks like this:
Application has crashed: C++ exception
[string "lib/units/beings/player/huskplayermovement.lua"]:997: attempt to index a nil value

SCRIPT STACK

lib/units/beings/player/huskplayermovement.lua:1015

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     LdrCallEnclave                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???

**Comment by Luffyyy** [comment]
How do you know it's BeardLib's fault?

**Comment by Luffyyy** [comment]
No response, closing.
