### ISSUE TITLE
Causing Host to crash

### ISSUE THREAD

**Issue by SirCatInaHat** [simon-wh/PAYDAY-2-BeardLib#37]
Unless there is an update that recently happened I've been getting this issue for a few weeks but got nowhere, How do I know it's Beardlib? I used a fresh install of BLT and Beardlib and joined a random lobby and I sometimes manage to get into a game for a short period of time, The weird thing though is when I was recently playing SC's mod as you should know it requires Beardlib, No issues what so ever as a client.

This has gotten annoying because I use HoloUI, Restoration and Perfect View Model to complete my HUD fixing

**Comment by Luffyyy** [comment]
This is gonna be difficult to fix without a proper crashlog, could you generate one?(ex: play with a friend that has no beardlib and ask for a crashlog)

**Comment by SirCatInaHat** [comment]
OK I'll ask a friend to help, Should be simple enough

**Comment by SirCatInaHat** [comment]
https://pastebin.com/wiJdDrSd

Here is one from NICEGUY1337

**Comment by SirCatInaHat** [comment]
I got someone else if you need another log

**Comment by Luffyyy** [comment]
Any info you could provide like custom weapons used? heist?

**Comment by SirCatInaHat** [comment]
For me? I had no custom weapons installed at the time nor any mods like HoloUI or Perfect View model as for the heist it really didn't matter we tried jewelry store on normal

**Comment by SirCatInaHat** [comment]
It's been 2 weeks and still nothing? IS there anything I forgot to mention?

**Comment by Luffyyy** [comment]
Dunno I'm pretty busy with other stuff and because it never happened to me I'm unable to fix it, sorry.

**Comment by SirCatInaHat** [comment]
:(, Any suggestions on what I should do?
