### ISSUE TITLE
Game crash upon intro after startup loading 

### ISSUE THREAD

**Issue by Exercutioner828** [simon-wh/PAYDAY-2-BeardLib#370]
Can someone explain why Beardlib on my pc doesn't work? Here's the crash log:

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5719249/crash.txt)

**Comment by Luffyyy** [comment]
Does this still happen?

**Comment by Luffyyy** [comment]
No response, closing.
