### ISSUE TITLE
Game crashed when i played safe house raid.

### ISSUE THREAD

**Issue by FL1K4** [simon-wh/PAYDAY-2-BeardLib#372]
The crash log is this and it all points to lib and Beardlib and the menu.
Application has crashed: C++ exception
[string "lib/managers/menu/crimespreemissionsmenucompo..."]:791: attempt to compare nil with number

SCRIPT STACK

update_info_text() lib/managers/menu/crimespreemissionsmenucomponent.lua:679
init() lib/managers/menu/crimespreemissionsmenucomponent.lua:464
new() core/lib/utils/coreclass.lua:35
_setup() lib/managers/menu/crimespreemissionsmenucomponent.lua:93
init() lib/managers/menu/crimespreemissionsmenucomponent.lua:31
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:4957
set_active_components() lib/managers/menu/menucomponentmanager.lua:490
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
original() lib/setups/setup.lua:863
update() @mods/base/req/core/Hooks.lua:188
update() lib/setups/gamesetup.lua:737
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.98.924
	CPU : Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 1030 / nvldumd.dll[27.21.14.5730]
	Language : english
	Memory :     8118MB 52KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (Realtek(R) Audio))

**Comment by FL1K4** [comment]
Also i have a insane amount of mods and it is
ApdativeStreamingChunksize
Beardlib
Better melee animation
Cheater kicker
Colorpicker
crime.net performance improvement
customfov
Depth of field removal
Enhanced hitmarks
Enhanced-fast.net-master
Force start with chat command
Low violence mode
Meth helper updated
Money in hud
No ads recoil animations
No confirm dialogs v2
No contract broker images
No post processing fps boost
No prints
pd2-hoplib-master
pd2-kill-feed-master
Safe house raid often be raided (i dont really grind it anymore)
Simplecrosshair
Steam profile redirection
Stop the crimespree loss on crash
Viewmodel tweak 
Wolfhud-master
And oh boy theres more and it is the mod overrides
Better black gloves
Better skeletal gloves
Break the rules vocal only
Brutal bloodied taxman
Chains in the house
Compressed medic
Compressed russians
Compressed ZEALS
Dallas mask reduced wear
Enhanced hitmarks
Federal inventory
Flame performance 2 effect boogalo
Hall of fame 
Heister gloves
LC_MACROPACK_SMOKE
Loud bois bexico (these names are terrible)
Loud bois dozer
Loud bois gang
Loud bois taser
Loud bois gang
Loud bois taser
Medium bois
Miami heat jacket
No blood impact decals
No dirt camera
Old lobby animations
Old menu poses
Pre-Update 199.5 First person sleeves 
Remix cod Soundtrack pd2
Rookcolormenu
Senpai dozer - all dozers 
Silent killer -old model
Spin_of_god
Tactical bdu rework
tense1983smashingfail 
Unmasked
I know alot of these are not related but i dont know man

**Comment by Luffyyy** [comment]
Sorry for the late response but how are you sure this is BeardLib? Have you tried removing other mods and have it happen with only BeardLib installed?

**Comment by Luffyyy** [comment]
Not response. Open issue again if issue still persists.
