### ISSUE TITLE
Game crashes when clicking Crew Management

### ISSUE THREAD

**Issue by Jigsaw159** [simon-wh/PAYDAY-2-BeardLib#373]
Whenever I try to use Crew Management, game hard crashes
Here is error log:
Application has crashed: C++ exception
[string "lib/managers/menu/crewmanagementgui.lua"]:910: attempt to index field 'data' (a nil value)

SCRIPT STACK

select_index() lib/managers/menu/crewmanagementgui.lua:896
init() @mods/Bot Weapons/lua/crewmanagementgui.lua:304
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:5128
set_active_components() lib/managers/menu/menucomponentmanager.lua:490
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
original() lib/setups/setup.lua:863
update() @mods/base/req/core/Hooks.lua:188
update() lib/setups/menusetup.lua:354
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

**Comment by Luffyyy** [comment]
Are you sure BeardLib is causing it?

**Comment by Jigsaw159** [comment]
Turns out it was a mod that I removed that stuck around for some reason, but it was all corolating back to Beardlib for some reason
