### ISSUE TITLE
lobbies hidden

### ISSUE THREAD

**Issue by hiimagamer** [simon-wh/PAYDAY-2-BeardLib#376]
when i log into crime.net i can only see a single lobby with someone else that also has beardlib, my filters are fine and the issue was fixed when i changed the cannot disable option in the mod file to false and disabled it from superblt

**Comment by Luffyyy** [comment]
This is a BeardLib Editor thing. Uninstall the mod in order to play online (the reason for this problem is in the FAQ of the mod)

**Comment by hiimagamer** [comment]
mb thought it was beardlib itself
