### ISSUE TITLE
Game Crashes when entering BLT Mods Menu, or Mod Updater.

### ISSUE THREAD

**Issue by AlAlvarez1992** [simon-wh/PAYDAY-2-BeardLib#378]
As the title says, the screen freezes, sometimes for a bit, sometimes for a lot, then CTD. No idea what to do.

**Comment by Luffyyy** [comment]
How is that a BeardLib issue?

**Comment by Luffyyy** [comment]
Did not get a response. Closing it with assumption that this is not a BeardLib issue.
