### ISSUE TITLE
Crashing when firing akimbo weapons

### ISSUE THREAD

**Issue by UnderwhelmingShaft** [simon-wh/PAYDAY-2-BeardLib#38]
I can run every thing fine but when i fire my akimbo weapons the game just straight crashes. They are base game akimbos, i haven't tried mod akimbos because i don't want to waste my hard earned cash.

Any help is appreciated. Thanks.

**Comment by Luffyyy** [comment]
Can you include a crashlog

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Luffyyy** [comment]
Can you include a crashlog

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
