### ISSUE TITLE
Can't Join in lobby

### ISSUE THREAD

**Issue by StopidChild** [simon-wh/PAYDAY-2-BeardLib#380]
"steam could not authenticate steam id for host"
After deleting Beardlib, this thing disappears, Game don't Crash, Only this error.
If this question seems stupid, sorry

**Comment by StopidChild** [comment]
In crashlog.txt and crash.txt nothing about this

**Comment by Luffyyy** [comment]
It's not the first time I hear about this kind of issue but it's very hard to know the cause of it. It'll require me to test around with you bunch of code and even then I don't know if it'll help as much.

**Comment by StopidChild** [comment]
> It's not the first time I hear about this kind of issue but it's very hard to know the cause of it. It'll require me to test around with you bunch of code and even then I don't know if it'll help as much.

Is there anything I can do to help solve this problem?

**Comment by Luffyyy** [comment]
Add me on Discord and we'll try to debug it. If it happens constantly while testing I can look into what might be causing it.
-> Luffy#4754

**Comment by TheTrashOtaku04** [comment]
Is there already a solution to this issue?

**Comment by Luffyyy** [comment]
> 
> 
> Is there already a solution to this issue?

Nope. It's a very hard problem to fix as it's inconsistent as I said in the previous reply, I may be able to help debug it with someone that has the issue, but I can't promise this will be fixed.

**Comment by TheTrashOtaku04** [comment]
> Nope. It's a very hard problem to fix as it's inconsistent as I said in the previous reply, I may be able to help debug it with someone that has the issue, but I can't promise this will be fixed.

could you help me solve the problem? or at least try?

**Comment by Luffyyy** [comment]
> 
> > Nope. It's a very hard problem to fix as it's inconsistent as I said in the previous reply, I may be able to help debug it with someone that has the issue, but I can't promise this will be fixed.
> 
> could you help me solve the problem? or at least try?

Read my reply above, I offered people to add me on discord to attempt to fix it.

**Comment by Luffyyy** [comment]
This issue is one of the oldest issues that has been finally fixed, I still have no idea why a select few got this issue but this is confirmed fixed or at least we discovered where this happens. I will update on whether this works for custom heists too (as what caused this was a function to make them work, I had to rethink the way it worked)
Related issues: #73, #212, #286, #390.

**Comment by Luffyyy** [comment]
Custom heists confirmed working.
