### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by DULACHE** [simon-wh/PAYDAY-2-BeardLib#382]
Hi i have a problem if i install beardlib i can't buy any mission on the menu, can you help me?
My crash log in payday is :

Application has crashed: C++ exception
[string "lib/managers/menu/contractbrokergui.lua"]:721: attempt to index field 'data' (a nil value)

SCRIPT STACK

sort() =[C]
filters_clbk() lib/managers/menu/contractbrokergui.lua:720
_setup_filters() lib/managers/menu/contractbrokergui.lua:477
setup() lib/managers/menu/contractbrokergui.lua:126
init() lib/managers/menu/contractbrokergui.lua:68
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:5309
set_active_components() lib/managers/menu/menucomponentmanager.lua:490
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
original() lib/setups/setup.lua:863
update() @mods/base/req/core/Hooks.lua:188
update() lib/setups/menusetup.lua:354
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.100.931.
	CPU : Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 630 / nvldumd.dll[23.21.13.9135]
	Language : spanish
	Memory :     8133MB 624KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VB-Audio Software (VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)

Sorry for my bad english ;(

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/5998132/crash.txt)

**Comment by Luffyyy** [comment]
Do you have any other mods that use BeardLib? maps, addons, etc?

**Comment by DULACHE** [comment]
> Do you have any other mods that use BeardLib? maps, addons, etc?

No i doesn't have any map or addon in BeardLib.

**Comment by Luffyyy** [comment]
From my checks this crash isn't supposed to happen without a custom map installed. Are you 100% sure you don't have anything installed? I recommend removing the 'Maps' folder entirely and deleting a few mods.

**Comment by DULACHE** [comment]
Hi i have removed my map folder and now it's solved but i doesn't install any map the folders witch i have in there was : cj_apartments, cj_bank, cj_fourstores, cj_gallery, cj_jewelstore, cj_mansion, cj_red, cj_taxman.
Those folders are there from when i have installed the game.

**Comment by Luffyyy** [comment]
I don't really understand what you mean but it seems you had a map there that might have not been installed correctly or the map by itself was broken. Make sure to read the instructions of mods properly to make sure that you don't crash. If the map is broken you can report the bug to the map creators.

**Comment by DULACHE** [comment]
No ,i'm saying that i doesn't install any of those maps and i thought that are installed from payday. In any case thx.
