### ISSUE TITLE
Crash at start up

### ISSUE THREAD

**Issue by Unknownuser443** [simon-wh/PAYDAY-2-BeardLib#384]
Soon as I add beard lib to the mods folder and I open PD2 it crashes. I know its beard lib because when I removed Beard lib from the mods folder payday ran 

I HAVE Super BLT installed

**Comment by Luffyyy** [comment]
Hello, BeardLib is a library so it does little by itself. Make sure to check every mod you installed that requires BeardLib. It's most likely that they cause the issue and not BeardLib. Additionally, please provide a crashlog.

**Comment by Luffyyy** [comment]
No response, closing.
