### ISSUE TITLE
[Feature Request] Custom Heist filter [crime.net]

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#396]
Sometimes I want to play Custom Heist with other people, but it's hard to find custom heists lobbies on crime.net.

A filter option to display only Custom Heists on Crime.Net would be really good, just a button "Show only Custom Heists" here;
https://i.imgur.com/H2h2dtT.jpg

**Comment by Luffyyy** [comment]
Sounds good, will probably do

**Comment by Luffyyy** [comment]
Note: only BeardLib 4.4 and up will support this, meaning if the host 4.3 or below, they won't show up.
