### ISSUE TITLE
Cannot Play Payday.

### ISSUE THREAD

**Issue by SuperLuigi54321** [simon-wh/PAYDAY-2-BeardLib#40]
My Payday 2 Beardlib cannot be used because of BLT. And because I have attachments with Beardlib, I cannot play Payday 2 because the game crashes because Beardlib cannot support the attachments. Help? 
Here is the crashlog:

Application has crashed: C++ exception
mods/base/req/json-0.9.lua:372: Unexpected character at Line 1 character 1: 

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.73.269
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970M / nvd3dum.dll[21.21.13.6909]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     12151MB 784KB
	OS : 6.1.7600 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
A mod you installed has an error that's it, find it and remove it.
Please don't report issues that are not BeardLib's fault.
