### ISSUE TITLE
[Request] CustomXML Sequence Manager

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#400]
**Is your feature request related to a problem? Please describe.**
As map makers, we can now make an custom units with all kind of stuff like custom animations etc.
The only thing we're annoyed about that is - we have to use Sequence Manager in Binnary, which simply sucks when you're working on new units.

**Describe the solution you'd like**
What we need is an option to set file type in add.xml or something like that, soo we can use custom_xml format instead of Binnary for Sequence Manager. I already found a solution on how to use custom_xml sequence managers but it's kinda dumb and it should've been easier.

**Describe alternatives you've considered**
This portion of main.xml stuff does what I want, but it's not really professional to override custom files with yet another custom files .
`		<script_data_mods directory="scriptdata">
			<mod replacement="objectives.objective" replacement_type="custom_xml" target_ext="objective" target_path="gamedata/objectives">
				<options merge_mode="add" mode="add"/>
			</mod>
			<mod replacement="train_doors.sequence_manager" replacement_type="custom_xml" target_ext="sequence_manager" target_path="units/pd2_mod_hungergames/props/train_doors/train_doors"/>
			<mod replacement="chest.sequence_manager" replacement_type="custom_xml" target_ext="sequence_manager" target_path="units/pd2_mod_hungergames/props/chest/chest"/>
		</script_data_mods>`

**Additional context**
Setting beardlib to read Custom_xml aswel will speed up development process, debugging process and will make it much easier for us to work with Sequences.

**Comment by Luffyyy** [comment]
I already added it for a different purpose (replacing the level module's include) lol. Lemme commit it

**Comment by Luffyyy** [comment]
Usage: add the file as usual, just add script_data_type="custom_xml", this should load the file using scriptdata replacement.
