### ISSUE TITLE
Custom heist crashes upon trying to buy a contract

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#401]
**Describe the bug**
With latest version of BeardLib upon buying any custom-heist contract the game crashes with following crash.txt file;
https://pastebin.com/gFAAFpgL
There are no errors in console whatsoever.

Second bug I have is related to BeardLib editor, but I am pretty sure it's caused by BeardLib changes;
https://cdn.discordapp.com/attachments/416663315503251476/832571613995335710/20210416130157_1.jpg

**To Reproduce**
Just launch payday 2 and try yourself, it's easy to reproduce :P

**Comment by Luffyyy** [comment]
Do not report 2 bugs in one issue. The 2nd issue was fixed already. I cannot reproduce the 1st. It might be caused by the syntax error I fixed so before reporting always update your BeardLib.

**Comment by MiamiCenterPL** [comment]
I was pretty sure I had latest version of BL, I just tried again with fresh latest version and it's all fine.
