### ISSUE TITLE
Crash upon loading any custom heist

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#402]
**Describe the bug**
Game is crashing upon loading any custom heist with Editor (It does work with old versions of BeardLib tho.)
`Application has crashed: C++ exception
mods/BeardLib-Editor/Hooks/MissionManager.lua:529: attempt to index local 'mission' (a nil value)

SCRIPT STACK

create_element() @mods/BeardLib-Editor/Hooks/MissionManager.lua:494
_create_elements() @mods/BeardLib-Editor/Hooks/MissionManager.lua:475
original() core/lib/managers/mission/coremissionmanager.lua:403
init() @mods/base/req/core/Hooks.lua:188
new() core/lib/utils/coreclass.lua:35
_add_script() core/lib/managers/mission/coremissionmanager.lua:113
_load_mission_file() @mods/BeardLib-Editor/Hooks/MissionManager.lua:113
parse() @mods/BeardLib-Editor/Hooks/MissionManager.lua:40
init_game() lib/setups/gamesetup.lua:681
core/lib/setups/coresetup.lua:422

------------------------------`

**To Reproduce**
Try to load any custom heist with latest ble and bl

**Comment by Luffyyy** [comment]
Cannot reproduce, I stashed changes I had so I essentially have latest BLE & BL and still nothing.

**Comment by MiamiCenterPL** [comment]
Might be something on my end then. I am using GitHub Desktop for updating BeardLib and that might broke something.
