### ISSUE TITLE
Icons Aren't Showing Up

### ISSUE THREAD

**Issue by ScoffingAtol** [simon-wh/PAYDAY-2-BeardLib#408]
My icons aren't showing, I can use them in-game and see them on my gun but icons just won't show up. 
![Ekran Görüntüsü (212)](https://user-images.githubusercontent.com/83156220/115983852-7755c600-a5ac-11eb-8d41-0d170278f360.png)

Here's one of my "main.xml"s 

<table name="Asimov Weapon Color">
	<Localization default="english.json" directory="localization"/>

	<WeaponSkin id="asi" is_a_color_skin="true" global_value="scoffingatol">
		<color_skin_data
			base_default="asi_weapon_color/base_gradient"
			base_metal="units/pd2_dlc_wcc/weapon_colors/base_gradient/base_gradient_wcc_pattern_metal"
			base_plastic="units/pd2_dlc_wcc/weapon_colors/base_gradient/base_gradient_wcc_pattern_plastic"
			base_half="units/pd2_dlc_wcc/weapon_colors/base_gradient/base_gradient_wcc_pattern_half"
			base_half_02="units/pd2_dlc_wcc/weapon_colors/base_gradient/base_gradient_wcc_pattern_half_02"
			base_detail="units/pd2_dlc_wcc/weapon_colors/base_gradient/base_gradient_wcc_pattern_details"
			base_variation="units/pd2_dlc_wcs/weapon_colors/base_gradient/wcs_black_df"
			pattern_default="asi_weapon_color/pattern"
			gradient_default="asi_weapon_color/gradient"
		/>
	</WeaponSkin>

	<AddFiles directory="assets">
		<dds path="guis/dlcs/mod/textures/pd2/blackmarket/icons/weapon_color/asi"/>
		<dds path="asi_weapon_color/pattern"/>
		<dds path="asi_weapon_color/gradient"/>
		<dds path="asi_weapon_color/base_gradient"/>
	</AddFiles>
</table>

**Comment by Luffyyy** [comment]
This seems to be caused by the use of 'mod' as the texture bundle folder, I recommend changing to the standard "mods" naming so instead of guis/dlcs/mod/textures/pd2/blackmarket/icons/weapon_color/asi it's guis/dlcs/mod**s**/textures/pd2/blackmarket/icons/weapon_color/asi

That being said, I will try to consider older mods that still use the old naming.

**Comment by ScoffingAtol** [comment]
I did chang "/mod" into "/mods" but it still doesn't appear.

**Comment by Luffyyy** [comment]
Did you change the contents of main.xml AND folders in the OS?

**Comment by ScoffingAtol** [comment]
OS?

**Comment by Luffyyy** [comment]
In explorer, ya know the files themselves.

**Comment by ScoffingAtol** [comment]
Oh, it is working now

**Comment by ScoffingAtol** [comment]
Thank you so much
