### ISSUE TITLE
Payday 2 BeardLib Mods Don't Work

### ISSUE THREAD

**Issue by bmhell** [simon-wh/PAYDAY-2-BeardLib#41]
I Installed Beard Lib And Ok,But When I Put A Mod In Mod_Overrides(a mod which need Beard Lib) this mod not work in game,don't appear or don't make any differency in game.

Sorry for my bad english...

**Comment by Luffyyy** [comment]
Have you installed BLT with BeardLib?
What mod are you talking about? since BeardLib has mods that have to be put inside mods or even Maps folder.
