### ISSUE TITLE
Crash when loading a heist

### ISSUE THREAD

**Issue by i-pasha** [simon-wh/PAYDAY-2-BeardLib#411]
Hi ^^. After updating to the latest bearlib version i can't load a heist anymore. More specifically an offline holdout. Here are the logs:
---
Wed Apr 28 17:24:13 2021

Application has crashed: C++ exception
mods/BeardLib/Classes/Managers/PackageManager.lua:149: attempt to call local 'use_clbk' (a string value)

SCRIPT STACK

LoadPackage() @mods/BeardLib/Classes/Managers/PackageManager.lua:43
load() @mods/BeardLib/Hooks/CoreSystem.lua:95
load_packages() lib/setups/gamesetup.lua:431
core/lib/setups/coresetup.lua:323

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------
---
thanks in advance :)

**Comment by Luffyyy** [comment]
Was fixed by #407 Update will be released shortly.
