### ISSUE TITLE
Custom main menu music not playing

### ISSUE THREAD

**Issue by HauntOfTheEagle** [simon-wh/PAYDAY-2-BeardLib#412]
Using this music template: https://modworkshop.net/mod/18106
Started happening with the latest update.

Custom heist music seems fine though.

**Comment by Luffyyy** [comment]
I recommend using these templates https://modworkshop.net/mod/21651 That being said, I'll investigate this.

**Comment by segabl** [comment]
So this only affects menu music? Are you using ogg or movie? Can you post your main.xml?

**Comment by HauntOfTheEagle** [comment]
Well, the thing about those templates.... a couple years ago I tried using those templates to import the entire soundtracks from the hotline miami games, soon as I booted up the game, the loading circle kept spinning forever and then it eventually crashed. Couldn't even get to the intro video. Probably memory overload or something.

segabl, yes it only affects the menu music. I'm using movie. Won't let me post a xml file here, do you want a screenshot?

**Comment by segabl** [comment]
just put the content in a code tag. or better yet, upload the mod somewhere so I can have a look at it

**Comment by HauntOfTheEagle** [comment]
https://www.mediafire.com/file/1j69ehh33uypgvc/A+New+Morning+(Menu+Track).zip/file

Here's the link to the mod.

**Comment by segabl** [comment]
Should be fixed with https://github.com/simon-wh/PAYDAY-2-BeardLib/pull/413
Strongly recommend using the new MenuMusic module though.

**Comment by HauntOfTheEagle** [comment]
Will you eventually stop supporting the old module?
I would use the new one but like I said, you could only have so many music tracks to the point were it will crash on startup.
Using the old module I have 200+ menu and heist music tracks with no issues.

**Comment by Luffyyy** [comment]
Generally no, but all new features and whatnot are generally only available in the ogg version. Maybe one day SBLT will improve that limit.

**Comment by segabl** [comment]
> 
> 
> Will you eventually stop supporting the old module?
> I would use the new one but like I said, you could only have so many music tracks to the point were it will crash on startup.
> Using the old module I have 200+ menu and heist music tracks with no issues.

make sure you have enabled optimized music load, then music should only be loaded when it's actually played so you shouldn't have any issues with the new ogg mods
