### ISSUE TITLE
Update 207.1 -- Missing Grenade + Grenade Launcher Crashes

### ISSUE THREAD

**Issue by ScrapDragon2** [simon-wh/PAYDAY-2-BeardLib#416]
**Describe the crash**
This is pretty much as simple as it gets. Using any Grenade Launcher or Underbarrel Grenade Launcher after the 207.1 update (to be clear, only happens when firing the weapon) causes a crash from BeardLib.

The throwable stun grenade is also missing from the game, even after a validation check.

**To Reproduce**
Equip a Grenade Launcher or Underbarrel Grenade Launcher with Frag rounds or the new electric rounds and shoot the weapon. Game crashes.

**Crashlog**
Application has crashed: C++ exception
[string "lib/units/weapons/projectiles/projectilebase.lua"]:357: attempt to index a nil value

SCRIPT STACK

throw_projectile() lib/units/weapons/projectiles/projectilebase.lua:300
_fire_raycast() lib/units/weapons/projectileweaponbase.lua:45
fire() lib/units/weapons/raycastweaponbase.lua:479
trigger_pressed() lib/units/weapons/raycastweaponbase.lua:378
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:4859
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:954
update() lib/units/beings/player/states/playerstandard.lua:435
original() lib/units/beings/player/playermovement.lua:272
@mods/base/req/core/Hooks.lua:265

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.106.15
	CPU : Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 750 / nvldumd.dll[27.21.14.5730]
	Language : english
	Memory :     16332MB 776KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Are you sure this isn't caused by weaponlib? try running pure beardlib.

**Comment by Alcat101** [comment]
you most likely are running some very old underbarrel/GL mod
mod like this: https://modworkshop.net/mod/19429
completely crash you, since it override vanilla GL code that upd 207 have changed.

updated WeaponLib have no problem running custom GL.

in general, remove any old mod that modifies GL without WeaponLib dependency.

**Comment by Luffyyy** [comment]
I'm gonna assume what alcat was the reason.
