### ISSUE TITLE
Crashing whenever I use the grenade launcher on the new gun.

### ISSUE THREAD

**Issue by genericname1233** [simon-wh/PAYDAY-2-BeardLib#417]
**Describe the crash**
Whenever I use the underbarrel grenade launcher on the new assault rifle, I crash.

**To Reproduce**
Equip the new assault rifle and use the underbarrel grenade launcher on it.(frag rounds still make it crash)

**Crashlog**
Application has crashed: C++ exception
[string "lib/units/weapons/projectiles/projectilebase.lua"]:305: attempt to index local 'tweak_entry' (a nil value)

SCRIPT STACK

_fire_raycast() lib/units/weapons/weaponunderbarrellauncher.lua:54
fire() lib/units/weapons/raycastweaponbase.lua:479
fire() @mods/BeardLib/Hooks/Fixes.lua:375
trigger_pressed() lib/units/weapons/raycastweaponbase.lua:378
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:4859
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:954
update() lib/units/beings/player/states/playerstandard.lua:435
original() lib/units/beings/player/playermovement.lua:272
@mods/base/req/core/Hooks.lua:265

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.106.15
	CPU : Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2070 / nvldumd.dll[27.21.14.6647]
	Language : english
	Memory :     16299MB 580KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Realtek Digital Output (Realtek(R) Audio))

**Comment by ScrapDragon2** [comment]
Oh good, it isn't just me that's crashing with this.

**Comment by genericname1233** [comment]
> Oh good, it isn't just me that's crashing with this.
> 
> Edit: Do you have any mods on that touch ProjectileBase or ProjectileTweakData? If so, that's what is causing it. One of the mods I made needed to be updated and the problem was solved.

I'm not exactly sure. I removed some of my mods that affect weapons and I am still crashing. I'll keep removing some mods and see if it works. A

**Comment by Luffyyy** [comment]
Seems like not an issue specific to BeardLib.
