### ISSUE TITLE
out of online mod

### ISSUE THREAD

**Issue by Baltazhar11** [simon-wh/PAYDAY-2-BeardLib#420]
when I'm using that mod , game will be out of online , why ? IDK , but i know when mod is deleted, game will be online . lmao
I think it's old mod and need to update  . fix the problem pls , every old mod need this mod .

**Comment by Luffyyy** [comment]
This is like saying "I removed BLT and the issue was fixed", this is not only missing a lot of info, I'm also sure this isn't in any way beardlib's fault. Maybe you installed some mod _that uses_ beardlib and ignored something in the description.

**Comment by Baltazhar11** [comment]
No I'd tested this mod . I removed all of installed mods except this one
Are u cannot test it ???

در تاریخ شنبه ۲۹ مهٔ ۲۰۲۱،‏ ۰۳:۳۴ Luffy ***@***.***> نوشت:

**Comment by Luffyyy** [comment]
Many people use this mod and it is updated regularly around each month or two. No one has reported this issue in the last month. I did test and it was working just fine. I'm pretty sure something else is causing it. 

Anyway, you explained the issue very poorly. What is the issue? Do you not see servers in crime.net? Do you get disconnected with some message?

**Comment by MiamiCenterPL** [comment]
Aren't you using BeardLib Editor by any chance? This mod does disable online and it is intentional.
