### ISSUE TITLE
WREN error

### ISSUE THREAD

**Issue by Lisu2137** [simon-wh/PAYDAY-2-BeardLib#424]
![obraz_2021-06-09_191906](https://user-images.githubusercontent.com/85639862/121400175-8f648780-c957-11eb-86f4-d5ec9767ccc9.png)
when i start up the game this shows up
help?

**Comment by Luffyyy** [comment]
Do you have the editor by chance

**Comment by Luffyyy** [comment]
No reply + no one reported this issue aside you so I'm assuming this isn't caused by BeardLib.
