### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by JakieTankkilla** [simon-wh/PAYDAY-2-BeardLib#428]
I installed the latest SuperBLT and BeardLib downloads. BLT worked fine and even allowed my mods, but when I tryed using Beard, it just crashes. Fresh install on both and still won't work. Any insights?

_______________________________________________________________________

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:208  
                      Update()  @mods/BeardLib/Classes/Managers/FileManager.lua:253  
                        func()  @mods/BeardLib/Core.lua:209                         
                        Call()  @mods/base/req/core/Hooks.lua:109                   
                      update()  @mods/base/lua/MenuSetup.lua:6                      
                                core/lib/setups/coresetup.lua:557                   

-------------------------------

System information:
	Application version : 1.107.22
	CPU : Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1660 Ti / nvldumd.dll[27.21.14.6679]
	Language : english
	Memory :     16289MB 648KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek(R) Audio))

**Comment by Luffyyy** [comment]
You're using some mod that's causing the crash. BeardLib by itself does load files, but I can say they haven't crashed anyone for a while. Try uninstalling some mods.

**Comment by JakieTankkilla** [comment]
So make a fresh install of Super and Beard again and see if it works? Deleting the mod folder and the .dll etc, then redone loading both? I’m not too clever when it comes to PD mods 😅

**Comment by JakieTankkilla** [comment]
Redownload*

**Comment by JakieTankkilla** [comment]
still didn't work, so I've uninstalled the game and am trying on a fresh install on another drive to see if it fixes or not, will keep updated and cheers for response 👍

**Comment by JakieTankkilla** [comment]
Can ignore this now, I downloaded from the GitHub link instead of ModWorkshop and works perfect...... thanks for the mod
