### ISSUE TITLE
causing voicelines to play for no concieveable reason

### ISSUE THREAD

**Issue by juusha** [simon-wh/PAYDAY-2-BeardLib#431]
**Describe the bug**
A clear and concise description of what the bug is. Screenshots are applicable.
 i've tried completely wiping my mods folder, but this only happens when i have beardlib installed, i tried deleting beardlib and reinstalling to no avail. ive looked around for anyone else with this problem. but i cant seem to find anyone with this problem. the voice line in question goes something like this: 'we are (amount i dont remember) richer now. but what about bain (dont remember) well you will just have to find the secret (dont remember)' sorry i have a terrible memory. ive tried changing my settings to the point where all sounds are 0%, still hear it. i have no clue what the problem could link to. but this makes the game almost completely unplayable, blasting my ears whenever it happens.

**To Reproduce**
whenever a police assault is happening, the problem happens. no issue in stealth

**Comment by Luffyyy** [comment]
The mods folder isn't the only place containing mods, please make sure Maps and mod_overrides mods are gone too. Beardlib isn't supposed to play anything by itself, generally.

**Comment by juusha** [comment]
sorry, the problem was actually something i put mistakenly into my maps folder
