### ISSUE TITLE
Payday 2 Crash!

### ISSUE THREAD

**Issue by RealShear** [simon-wh/PAYDAY-2-BeardLib#44]
I uninstalled the game 3 times and reinstall it again, it crashes when i try to open the menu.

Application has crashed: C++ exception
[string "lib/managers/weaponfactorymanager.lua"]:1473: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlGetCurrentServiceSessionId                       

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 820M / nvldumd.dll[22.21.13.8476]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     6027MB 52KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Conexant (Speakers (Conexant SmartAudio HD))

**Comment by Luffyyy** [comment]
https://steamcommunity.com/app/218620/discussions/8/2592234299573958403/#c2592234299573989341
Tip: use google.
