### ISSUE TITLE
Missing mod options

### ISSUE THREAD

**Issue by JackTheRipper2004** [simon-wh/PAYDAY-2-BeardLib#440]
**Describe the bug**
A clear and concise description of what the bug is. Screenshots are applicable.

**To Reproduce**
There was a update beardlib and when i reopen my mod options its gone only the non mod options its still intact

**Comment by JackTheRipper2004** [comment]
Please fix this problem?

**Comment by Luffyyy** [comment]
![image](https://user-images.githubusercontent.com/11510099/127747626-5955ea16-2425-421d-b720-b66b9843d7c8.png)
Clearly works? Please send your BLT log.

**Comment by JackTheRipper2004** [comment]
and how do i check the blt log?

**Comment by Luffyyy** [comment]
mods/logs/

**Comment by JackTheRipper2004** [comment]
do i need to send the log or i have to do it? cause mod options its there but wolfhud options and much more cant be tweak

**Comment by Luffyyy** [comment]
Yes I need the log so I can see if there's something wrong that's causing issues

**Comment by JackTheRipper2004** [comment]
im sending it the latest or the previous?

**Comment by JackTheRipper2004** [comment]
[2021_07_31_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6912155/2021_07_31_log.txt)
[2021_08_01_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6912156/2021_08_01_log.txt)

**Comment by Luffyyy** [comment]
Not sure if this has anything to do with Beardlib but seems like menu backgrounds has some issue, delete its save file in mods/saves

**Comment by JackTheRipper2004** [comment]
ok and try launch the game?

**Comment by Luffyyy** [comment]
Yes

**Comment by JackTheRipper2004** [comment]
yes it work thanks man!
