### ISSUE TITLE
Have some crash with v4.5

### ISSUE THREAD

**Issue by Blake-HUI** [simon-wh/PAYDAY-2-BeardLib#441]
**Describe the crash**
After update the Beardlib from v4.4 to v4.5, my Kill Log mod ( https://modworkshop.net/mod/14856 ) will crash the game.

**To Reproduce**
Update to v4.5, try kill anybody in the level, the game crash. But this mod work fine in v4.4

**Crashlog**
Application has crashed: C++ exception
mods/kill log/PlayerManager.lua:2: attempt to index field 'Box' (a nil value)

SCRIPT STACK

on_killshot() @mods/base/req/core/Hooks.lua:268
chk_killshot() lib/units/enemies/cop/copdamage.lua:2469
damage_bullet() lib/units/enemies/cop/copdamage.lua:526
give_impact_damage() lib/units/weapons/raycastweaponbase.lua:2239
on_collision() lib/units/weapons/raycastweaponbase.lua:2152
_fire_raycast() lib/units/weapons/shotgun/shotgunbase.lua:289
fire() lib/units/weapons/raycastweaponbase.lua:479
trigger_pressed() lib/units/weapons/raycastweaponbase.lua:378
fs_original_playerstandard_checkactionprimaryattack() lib/units/beings/player/states/playerstandard.lua:4859
_check_action_primary_attack() @mods/Input Optimize/playerstandard.lua:260
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:954
fs_original_playerstandard_update() lib/units/beings/player/states/playerstandard.lua:435
update() @mods/Input Optimize/playerstandard.lua:6
original() lib/units/beings/player/playermovement.lua:272
@mods/base/req/core/Hooks.lua:265

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.107.25
	CPU : Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 / nvldumd.dll[27.21.14.6627]
	Language : schinese
	Memory :     8034MB 308KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (扬声器 (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Send BLT log

**Comment by Blake-HUI** [comment]
> Send BLT log. It's possible your SBLT is outdated, make sure it's updated.

Problem fixed after update BLT, thank u!
