### ISSUE TITLE
Crash after I finish heist

### ISSUE THREAD

**Issue by payday2enjoyer** [simon-wh/PAYDAY-2-BeardLib#442]
**Describe the crash**
I finish the heist and then i crash.

**To Reproduce**
Finish a heist and go to lobby

**Crashlog**
Application has crashed: C++ exception
mods/BeardLib/Hooks/Network/NetworkPeer.lua:394: attempt to index field '_last_beardlib_extra_outfit_sections' (a nil value)

SCRIPT STACK

done_extra_outfit_string_beardlib() @mods/BeardLib/Hooks/Network/NetworkPeer.lua:385
func() @mods/BeardLib/Hooks/Network/NetworkPeer.lua:222
Call() @mods/base/req/core/Hooks.lua:109
ProcessAllPeers() @mods/base/req/core/Networking.lua:189
ProcessChatString() @mods/base/req/core/Networking.lua:176
func() @mods/base/req/core/Networking.lua:165
Call() @mods/base/req/core/Hooks.lua:109
original() @mods/base/lua/ChatManager.lua:12
_receive_message() @mods/base/req/core/Hooks.lua:265
original() lib/managers/chatmanager.lua:71
receive_message_by_peer() @mods/base/req/core/Hooks.lua:265
lib/network/base/handlers/connectionnetworkhandler.lua:663

**Comment by Luffyyy** [comment]
Fixed by #443
