### ISSUE TITLE
BeardLib doesn't close files which can cause crashing if a lot of mods are loaded

### ISSUE THREAD

**Issue by sirben99** [simon-wh/PAYDAY-2-BeardLib#449]
**Describe the crash**
Hey, ive had couple of crashes with 4.5 version of beardlib. Im not sure if these are caused by beardlib per say, but i thought it would help since im not sure what could be causing it (Atleast the seacond one).
These crashes dont always happen, but about 95% of the time when trying to go to a heist. Sometimes when trying to go to main menu. Theyr very random it seems
There might be more crashing mods but i have over 700 of them so yeah

The first one is related to Cable Ties and Hostages mod (https://modworkshop.net/mod/31101)
Ive already send the author the crash report, but thought id send it here too just incase it brings something new to the table, but its probably for the author to fix

The seacond one i had while chanching the loadouts, and im not sure at all what could cause it.

The third one is related to WolfHud crashing (Not the official, but a fork of it: https://github.com/jaondayko/WolfHUD)
Should i report this crash there?

**To Reproduce**
Try to go to a heist

**Crashlog**
WolfHud: 
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6917742/crash.txt)

Changing loudout:
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6917775/crash.txt)

Cable Ties and Hostages:
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6917793/crash.txt)

**SuperBLT logs**
WolfHud:
[2021_08_02_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6917751/2021_08_02_log.txt)

Changing loudout:
[2021_08_02_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6917782/2021_08_02_log.txt)

Cable Ties and Hostages:
[2021_08_02_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6917794/2021_08_02_log.txt)

Sorry about the mess of a report. Ill be downgrading to 4.4 since the new Beardlib has been **very** unfriendly to my mods folders, 4.4 and 4.4.1 dint have any issues.

**Comment by Luffyyy** [comment]
Thanks for including logs. I changed something that should fix something to do with a lot of mods, this bug has existed for a while in BeardLib it seems. Mind clearing your logs, trying the last version in GitHub and sending new logs?

**Comment by sirben99** [comment]
Hey!

Ofc! Ill test the new version and see if any of the above things happen anymore!

**Comment by sirben99** [comment]
Hey!

I dint have any crashes and everything seem to be working as expected!
Heres the log just incase you want to take a look, but everything seem to work as intented. I quit to main menu, and went to the same heist 3 times in a row. No crashes.
[2021_08_02_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6918632/2021_08_02_log.txt)

If any more issues come up that i havent experienced before, is it okay that i update this threath? And if you need me to test anything else let me know! (I do have over 700 mods so do keep that in mind)

Ben

**Comment by Luffyyy** [comment]
If you get new issues just make a new issue, I'll rename this issue to something else as this issue is important enough. This has been a somewhat invisible bug since the beginning of the library.
