### ISSUE TITLE
Beardlib crashing when I join game as client, set_xxxxx_carry() ?

### ISSUE THREAD

**Issue by Edgarhighmen** [simon-wh/PAYDAY-2-BeardLib#45]
Current thread: Main
Script stack:
                                @mods/BeardLib/Hooks/CoreSystem.lua:24              
                            ()  =(tail                                              
                      call):-1  _create_carry_unit()                                
lib/units/beings/player/huskplayermovement.lua:399  set_visual_carry()                                  
lib/units/beings/player/huskplayermovement.lua:371  set_synced_carry()                                  
lib/managers/playermanager.lua:2801                                                      
lib/network/handlers/unitnetworkhandler.lua:2292

**Comment by Luffyyy** [comment]
Does it still happen?
