### ISSUE TITLE
Gloves issues

### ISSUE THREAD

**Issue by SlainLBS** [simon-wh/PAYDAY-2-BeardLib#450]
Between Tailor Expansion and BWE, we experience some glove issues while trying to use the new variant of gloves for bots and LAS character mods. There's no way on changing variant colors on Bots and using a Character with LAS with normal hands (not using custom hands) it duplicates the hands, using the character hands and the default hands awkwarly. Is there any fix you can look on??

**Comment by Luffyyy** [comment]
@connieprice

**Comment by connieprice** [comment]
As far as I can tell I fixed this in the latest LAS update 4.1.8/4.1.9.

**Comment by SlainLBS** [comment]
@Luffyy @Connieprice the owners of TE and BWE said that the BeardLib need a new code that helps to change the variant color of the gloves almost like outfit ones. Oh and btw, there's also an issue when selecting the armor skin for the bots too, they seem missing and cant be selected if im using LAS, without it works fine but with it does not, check that out

**Comment by connieprice** [comment]
As far as I am aware it's Bot, Weapons & Equipment that should be implementing a fix on their end.

**Comment by connieprice** [comment]
I've provided a basic functionality fix for Hoppip, and we're both working through including the more specific BWE features.

**Comment by connieprice** [comment]
The latest release of Bot Weapons & Equipment should have this fixed now.

**Comment by SlainLBS** [comment]
I saw that, thx for your attention

**Comment by connieprice** [comment]
No Problem, @Luffyyy this can be closed now.
