### ISSUE TITLE
Most Mods & Mod Overrides not working after Beardlib Update

### ISSUE THREAD

**Issue by Metal-Invitine** [simon-wh/PAYDAY-2-BeardLib#451]
**Describe the bug**
After the 4.5 update I was having issues with one of my mods that being "CustomFOV" + decided to do a clean reinstall of all of my mods and overrides, afterwards 100% of my overrides mods ceased to work and a bunch of lua mods stopped working. Mod Options, no matter what I try appears blank except for almost every mod except one. I've made sure everything is in their correct spots and I've tried every recommended fix to no prevail. I have not experienced any crashes related to Beardlib after the update, I have only experience the aforementioned missing "Mod Options" and Beardlib not recongizing all of my mod overrides.

**To Reproduce**
Updated Beardlib to it's most recent patch (older versions of Beardlib managed to fix some mods exluding "CustomFOV and some other quality of life mods) and after accidentally resetting my fov when changing resolution, realised I had no Mod Options, reinstalled mods to find out all my mods broke, including mod overrides - downgrading managed to fix most mods but CustomFOV and all override mods (to my knowledge) do not work + all lua mods (except one mod) don't show up in Mod Options.
[2021_08_03_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6921458/2021_08_03_log.txt)
[2021_08_02_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6921462/2021_08_02_log.txt)

Don't have any crashlogs related to beardlib other than crashes caused by me trying to fix individual mods.

Just as a reference these are the only things I have installed plus things I know for sure 100% don't work no more:

Somewhat Functional and Working: https://cdn.discordapp.com/attachments/503352312585256961/872001369836507136/unknown.png

Completely Broken/ Unexplained: https://cdn.discordapp.com/attachments/503352312585256961/872001619338883092/unknown.png

**Comment by Luffyyy** [comment]
I'm not sure why, but for some reason menu bgs (old) started causing issues. Please update it to version 6 https://modworkshop.net/mod/17160 That's what I assume is causing issues

**Comment by Luffyyy** [comment]
I find it weird also as menu bgs and beardlib prior to version 6 had no relation whatsoever.

**Comment by Metal-Invitine** [comment]
I'll see if the new bgs makes a difference.

**Comment by Metal-Invitine** [comment]
Yep it fixed it, that's just strange

**Comment by Metal-Invitine** [comment]
Well, almost fixed all the mods are working now, it's now just overrides that still don't work at all.

**Comment by Luffyyy** [comment]
Which override mods mind giving me examples?

**Comment by Luffyyy** [comment]
Override mods that just replace textures shouldn't have issues. Some mods like gloves are a known issue atm, you might also want to try updating your LAS if you have it.

**Comment by Metal-Invitine** [comment]
Don't use LAS, the only texture mods I have are related to props and cops.

**Comment by Luffyyy** [comment]
Give me a link of a mod that's not working, I'll check it

**Comment by Metal-Invitine** [comment]
https://modworkshop.net/mod/24256 Using Fbi (Tan) only.
https://modworkshop.net/mod/25894 Entire Mod
https://modworkshop.net/mod/24291 Using LIght Fbi Swat, Light and Heavy Blue Swat, Heavy Zeal Swat, Murkywater and all Special retextures.
https://modworkshop.net/mod/23901 Using Light Zeal Swat.
https://modworkshop.net/mod/12710 V.1.2.7z Without Menu and Mouse Cursor.

It's a tad complicated.

**Comment by Luffyyy** [comment]
![20210803120151_1](https://user-images.githubusercontent.com/11510099/127988820-4010d283-7d83-4a5b-9053-f4c5ac9f4f66.jpg)
Retexture mod seems to work? As I said I'm not sure how BeardLib could cause simple mod overrides to stop working. Haven't tried others yet.

**Comment by Metal-Invitine** [comment]
I'm not sure either, I just did a clean install of all the other texture mods excluding the one you tested and I can safely say on my end that they still don't work. 

I'll reinstall Re-Texture Project and see if it actually works on my end, if not I'll be stumped.

**Comment by Metal-Invitine** [comment]
Actually I wonder if this'll fix it cause I think the pathing broke cause the folder order seems a bit off.

**Comment by Metal-Invitine** [comment]
Fixed the pathing, and all the overrides are now working fine, no clue what messed it up though.
