### ISSUE TITLE
Crash when a heist is restarted.

### ISSUE THREAD

**Issue by AJAL8000** [simon-wh/PAYDAY-2-BeardLib#453]
**Describe the crash**
Since the last update you guys made. When I host a game online and then restart. The game crash.

Now here comes the weird. This only happens if there are a large number of mods installed. I don't know how many are necessary for the crash to happen. But currently I have about 86 mods (Yes, many and that I was removing several to find out which one was causing the crash).

I know that BearbLib is the cause of the crash since I then did a test with a folder that I had as a backup where I had more than 100 mods, I put them all in the game and updated them (but I did not update BearbLib) and the game did not crash when restarting the game (In this case, all the tests were between the Heist of Alesso and the Big Bank). Later, I updated BearbLib, went back in, restarted a game with the same conditions and the game crashed.

For now, it seems that this only happens when I host online, but offline does not seem to be an error.

So in conclusion, the new version is the problem that causes the crash when there are many mods installed and restarting a heist.

For now I will be using the older version of BearbLib as it does not cause me any problems. But I would like you to fix that problem in a future update.

Oh and if you ask. Yes, obviously the first thing I saw before doing countless tests between various combinations of mods, is the crash log. I will attach it here, but as you will see, it does not help much to know what the problem is exactly. And yes, whenever it crashes due to the conditions I mentioned above, the crash log always sends me this same result.

Considering the large number of mods and the specific condition of hosting online. Besides that the crash log does not help almost anything. It seems to me that this error is very difficult to find, so it would not surprise me that few have realized what causes it. Hopefully more people could corroborate these results.

(All this was written with the help of Google Translate since I do not speak English very well, I am sorry if something is not completely well written)

**To Reproduce**
1-Install a lot of mods (as more 86, but I do not know the exact amount required)
2-Open Payday 2.
3-Make sure you have the latest version of Bearblib.
4-Start an online game being host.
5-When the Heist is already initiated, go to the "Restart" button and restart the Heist.

This should cause a crash.

**Crashlog**
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.107.25
	CPU : Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2060 / nvldumd.dll[27.21.14.5671]
	Language : spanish
	Memory :     16251MB 456KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (22MP55 (NVIDIA High Definition Audio))

**Comment by MiamiCenterPL** [comment]
By removing BeardLib you also disable most of your mods with it, just because BeardLib a requirement for many mods.
This is most likely one of your mods that is using BeardLib.
The crash.txt you provided tells only that game tried to use something that either doesn't exist, is corrupted or many others.
Please install all the mods you want to use and provide the logs file (you can find it in mods/logs folder)

Also check the crash.txt, if it is different next you crash, please include that one too :)

**Comment by AJAL8000** [comment]
> By removing BeardLib you also disable most of your mods with it, just because BeardLib a requirement for many mods.
> 
> I am aware that it might worked fine with older version but devs need to know more precisely where the issue actually is.
> 
> This is most likely one of your mods that is using BeardLib.
> The crash.txt you provided tells only that game tried to use something that either doesn't exist, is corrupted or many others.
> Please install all the mods you want to use and provide the logs file (you can find it in mods/logs folder)
> 
> Also check the crash.txt, if it is different next you crash, please include that one too :)

In all the test cases I did, I always had an active Bearblib version, so all mods that have dependencies with Bearblib were active. But as I said, only the last version causes me the problem, the previous version of Bearblib does not.

And as mentioned above, the crash.txt always turns out to be the same or almost the same. I will attach 3 times more where the crash has happened.

Also check 3-4 times that the files of the game are in good condition, with the help of the Steam verifier.
----------------------------------------------------------------------

Tue Aug 03 13:20:57 2021


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.107.25
	CPU : Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2060 / nvldumd.dll[27.21.14.5671]
	Language : spanish
	Memory :     16251MB 456KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (22MP55 (NVIDIA High Definition Audio))



----------------------------------------------------------------------

Tue Aug 03 13:27:51 2021


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.107.25
	CPU : Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2060 / nvldumd.dll[27.21.14.5671]
	Language : spanish
	Memory :     16251MB 456KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (22MP55 (NVIDIA High Definition Audio))



----------------------------------------------------------------------

Tue Aug 03 13:33:27 2021


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.107.25
	CPU : Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2060 / nvldumd.dll[27.21.14.5671]
	Language : spanish
	Memory :     16251MB 456KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (22MP55 (NVIDIA High Definition Audio))

**Comment by MiamiCenterPL** [comment]
I also asked for logs, can you include them too?
(PAYDAY 2/mods/logs)

**Comment by AJAL8000** [comment]
> I also asked for logs, can you include them too?
> (PAYDAY 2/mods/logs)

Oh sorry. Would you like me to generate a new log? The one I currently have looks quite long and I don't know how many times it will have counted the logs. If it is too much trouble for you to see all that, let me know to generate a new log, this time trying to make only the crash.

[2021_08_03_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6927015/2021_08_03_log.txt)

**Comment by MiamiCenterPL** [comment]
You can try to generate a new log file, however you will have to wait for Luffy to look deeper into it anyways.

**Comment by MiamiCenterPL** [comment]
There's one more thing I will ask you to do, maybe that will magically fix this issue, worth giving a try;
Make sure all your mods are up to date,
Update SuperBLT manually, link:
https://superblt.znix.xyz/

**Comment by AJAL8000** [comment]
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6927203/crash.txt)
[2021_08_02_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6927205/2021_08_02_log.txt)
Here is the log with only the actions done to cause the crash and the crash.txt that the game gave me when it crashed.
I hope it helps, and later I will try to install the SuperBLT again. Although I highly doubt that that will solve the problem xd.

**Comment by Luffyyy** [comment]
Try using the latest commit from BeardLib, although I don't see the same logs as I saw in #449, it might help.

**Comment by Luffyyy** [comment]
Also to make sure: by latest commit I mean download from GitHub.

**Comment by AJAL8000** [comment]
> Also to make sure: by latest commit I mean download from GitHub.

I did this and also reinstalled SuperBLT manually. However, the error is still there, the crash.txt gave me the same as always and this is the resulting log.
[2021_08_03_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6928256/2021_08_03_log.txt)
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6928259/crash.txt)

**Comment by AJAL8000** [comment]
Now I just put the old version of BeardLib in and not crashed when restarting a heist. 

There is certainly something in the new BeadLib that is causing the problem. I already gave all the data and did the things you asked me to do. And it doesn't appear to be interference from mods either. It seems that simply downgrading BeardLib "fixes" the problem.

So yeah, for now I'll be using the older version of BeardLib that I luckily keep. You guys should put a section to access previous versions just in case xd. (Or maybe you have already done it but I have not found it yet, it would be helpful if you linked it here)

**Comment by Luffyyy** [comment]
Try the latest commit, your issue was most likely fixed.

**Comment by AJAL8000** [comment]
> Try the latest commit, your issue was most likely fixed.

Dude, you did it! the crash no longer happens when restarting the heist as a host. I will be testing it for a while more but for now I have not seen problems.

Thanks. 😃
