### ISSUE TITLE
Hair Physics Broken with New Update

### ISSUE THREAD

**Issue by Damroscche** [simon-wh/PAYDAY-2-BeardLib#454]
**Bug Description:**
Hair physics are broken in heists, as of the new update. Everything looks fine in menus, but whenever you load into a heist, any character with hair physics (Jimmy and Clover, for example) appear as if their models are wearing masks, even before masking up. This means their hair is squished and, in some cases (Clover, notably), experiencing other texture issues on parts of the head that would be covered by a mask. Seems like the game falsely thinks all characters started the heist masked up, even if they didn't. Affects both players and bots, not heist-specific, very easily replicable.

I confirmed it's definitely caused by this update - a clean install was fine, and SuperBLT was fine after installation, but the moment I installed BeardLib the bug came back.

**Bug Replication:**

As I said above, this seems very easily replicable - just do your own clean install of the game, add SuperBLT, then add this. Upon installing the current version of BeardLib, the bug should be noticable on any heist where you start in stealth. (_Probably._ Never know if it's a system-specific issue. I'm on Windows 10 and can provide specs if needed, but I doubt they're applicable.)

EDIT: Just checked, and the issue is removed by rolling back to 4.4. So, it's definitely something with 4.5 that's causing the issue.

**Additional Files, Logs, Etc:**
See the following screenshots of [Jimmy](https://user-images.githubusercontent.com/88429652/128158660-a9fd6a0d-de8b-4fd5-9cd2-f4c62373c57a.jpg) and [Clover](https://user-images.githubusercontent.com/88429652/128158716-082944c1-6916-4af7-8550-6d491ea62558.jpg), for examples of the bug in action. Clover in particular is a hell of a sight now, lol.

I'm also attaching the BLT log, as requested in that announcement from 3 days ago. This bug does not cause a crash, so my most recent crashlog is irrelevant, and from before the clean reinstall. If I can provide further information or logs, or do anything else to help with testing, feel free to let me know. Thanks for your work with developing this. :)

[2021_08_04_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6930229/2021_08_04_log.txt)

**Comment by Luffyyy** [comment]
This is caused by LAS afaik. @connieprice might be already aware of it.

**Comment by connieprice** [comment]
I might've broken it in the latest LAS update, but I am aware now, I'll investigate later.

**Comment by Damroscche** [comment]
Just FYI, this is still broken with the latest update. On further testing, it's not so much physics that are broken - rather, it seems to be rendering every character's "mask is on" head model at all times, including when masks are off. Not sure what would cause that, but yeah, figured I'd let y'all know.
