### ISSUE TITLE
Github Updates

### ISSUE THREAD

**Issue by Makowo** [simon-wh/PAYDAY-2-BeardLib#458]
**Is your feature request related to a problem? Please describe.**
Would like to use github updating like the editor does, to keep beardlib up to date.

**Describe the solution you'd like**
Either an option to switch between github latest and mws release, or replacing the mws update with github for the repo and reverting it back to mws for releases.

**Comment by Luffyyy** [comment]
Implemented in https://github.com/simon-wh/PAYDAY-2-BeardLib/commit/5d5b3c002f8e1c92243d8f501938b205bee835d4
