### ISSUE TITLE
Scanner in Boiling Point doesn't work

### ISSUE THREAD

**Issue by karahunkantaja** [simon-wh/PAYDAY-2-BeardLib#459]
Yesterday the scanner in Boiling Point worked, but today, after I downloaded the latest update for BeardLib and then started to play Boiling Point, the scanner didn't accept bodies anymore. Everything else was normal up until the point where I was supposed to start scanning. The body bags just stayed on the scanner and the scanner didn't want them. I asked around forums, and someone said that the latest BeardLib update might be the problem, so I moved BeardLib and other mods that require it out from my mods, started Boiling Point again and this time the scanner accepted the bodies and I could continue playing. I took a screenshot of the scanner not doing its job. I hope the next update fixes the problem as some of my favorite mods require BeardLib.

![20210806160743_1](https://user-images.githubusercontent.com/88443037/128537830-2b3fbb51-11ce-4738-bd27-3534052321c7.jpg)

**Comment by Damroscche** [comment]
I can also confirm this is broken, as of testing just now on a vanilla install (plus BeardLib and SuperBLT). The scanner objective in Boiling Point won't register the bodies that it's looking for no matter what you do, making the mission impossible to complete with BeardLib's current patch.

What's weird is that it _definitely_ worked the day before yesterday (08/04/21), as - by sheer coincidence - I happened to play Boiling Point that afternoon. I suspect the issue may have been introduced in yesterday's patch. 4.5.4, I think?

No crashes from this, the mission's just impossible to finish and goes forever. My BLT log didn't save for some reason, but I can redo the heist later tonight and get a log if it'll help. It's easily reproduceable, though. I just did it for the first time to test this report.

**Comment by karahunkantaja** [comment]
> I can also confirm this is broken, as of testing just now on a vanilla install (plus BeardLib and SuperBLT). The "Scan the Test Subjects" objective in Boiling Point won't register the bodies that it's looking for no matter what you do, making the mission impossible to complete on BeardLib's current patch.
> 
> What's weird is that it _definitely_ worked the day before yesterday (08/04/21), as - by sheer coincidence - I happened to play Boiling Point that afternoon (for the first time in years, lol). I suspect the issue may have been introduced in yesterday's patch. 4.5.4, I think?
> 
> No crashes from this, the mission's just softlocked. My BLT log didn't save for some reason, but I can redo the heist later tonight and get a log if it'll help. It's easily reproduceable, though. Just run the heist, you'll see what I mean.
> 
> **EDIT:** Actually, I'd bet money this is the same issue behind #457 since the test subjects in Boiling Point are counted as "Person"s. Would the fix for #457 fix this issue as well? (If so, definitely worth pushing the hotfix.)

Boiling Point has worked normally during this week when I've played it (I play it a lot lol). Today I just installed the newest patch which then bugged out the scanner. As you pointed out the other issue, it could be that the patch messed the body bags (= persons) up, making securing them possible when it should not be and in the other hand making securing them impossible in Boiling Point. It makes a lot more sense. Good thing that you connected these two issues.

I played Boiling Point couple of times in a row trying to find the reason behind the scanner not working before I moved BeardLib away, but I didn't check my BLT logs (I often just forget that it exists). If you could get the log, it would be nice.

**Comment by tanjilk** [comment]
After update of beardlib, it is not possible to complete the boiling point, it's happening the same for me too

**Comment by Luffyyy** [comment]
Please confirm if the latest commit works for you guys

**Comment by MiamiCenterPL** [comment]
I confirm it's working with latest commit. Every body bag removing map scripts works fine
