### ISSUE TITLE
[DEV build] mod options sub menu not showing

### ISSUE THREAD

**Issue by SirCatInaHat** [simon-wh/PAYDAY-2-BeardLib#46]
I downloaded and installed the Dev version for Quackertree's heists all was swell until after I rebooted the game to sort out my HUD, Now although I stated that the sub menu for mod options is not loading it also goes a bit further and out right disables some mods (in my case, Menu backrounds and Fast.net)

**Comment by Luffyyy** [comment]
I don't really understand what's the problem but could you provide your BLT log?

**Comment by MotherFlowers** [comment]
Wow, I was literally about to post the same issue. As far as I can tell the mods seem to still be working, but anything menu-related just doesn't show up.

**Comment by Luffyyy** [comment]
But I'll assume you both have some outdated mod(either HoloUI or PVM which are both going to be updated when this version goes live)

**Comment by MotherFlowers** [comment]
PVM I don't use I am however using the latest version of HoloUI from Paydaymods, guess I should try the dev version? And my BLT log: https://pastebin.com/a3w7Jvbk

Gold Star if you actually see anything useful in there...

**Comment by SirCatInaHat** [comment]
Um, Not sure how the log would help but here is the log and a screenshot of the issue
[2017_07_18_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1157157/2017_07_18_log.txt)
![20170718211307_1](https://user-images.githubusercontent.com/29586610/28337636-297d759a-6bfe-11e7-8d40-05a23d51cc5f.jpg)

**Comment by Luffyyy** [comment]
Yes, the log gives info.

@MotherFlowers 09:09:08 PM FATAL ERROR: mods/Holo/Classes/OptionsMenu.lua:85: attempt to index local 'panel' (a nil value)
@SirCatInaHat 09:04:34 PM FATAL ERROR: mods/Holo/Classes/OptionsMenu.lua:85: attempt to index local 'panel' (a nil value)

Install the dev version of HoloUI if you have any issue report it there instead.
