### ISSUE TITLE
Cant buy certain modded weapons

### ISSUE THREAD

**Issue by sirben99** [simon-wh/PAYDAY-2-BeardLib#467]
**Describe the bug**
Hey!

Im not sure where to report this per say, but since beardlib is reguired ill report it here.
I have a problem where i cant seem to buy some modded weapons i have installed.

I have a screenshot here showing the weird symbol: 
![20210812203414_1](https://user-images.githubusercontent.com/32977052/129242774-30bf3c52-80ee-454a-8a0c-21f5aece327c.jpg)

If you know what that means and why i cant buy them please let me know! And please re-direct me to the right place if you know where to report this.

**Blt Logs**
[2021_08_12_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/6977447/2021_08_12_log.txt)

**Comment by sirben99** [comment]
The issue is fixable by putting the weapon unlock lvl to 0 in main.xml. Credit goes to Just Rex for suggsecting this solution.
Still not sure why it happened, and even after i first made this post it was locked untill this manual fix. Might be something to look at, if beardlib could be causing it.

**Comment by Luffyyy** [comment]
I need a mod that I can test

**Comment by sirben99** [comment]
Sorry for the late answe, this is one of the mods that did this: https://modworkshop.net/mod/19128

**Comment by Luffyyy** [comment]
So first this mod already has unlock_level and secondly with or without I am able to buy the pistol 🤔 This issue could be related to something else or is just random/related to the save file.

**Comment by sirben99** [comment]
I had to put the unlock_level to 0 instead of 35, else it would be lvl locked and i coudnt buy it. 

Good to hear that you can buy it regardsless, it means its possibly something bizarre in my end, but i wasnt sure before.
Thank you for testing it! If you reguire more info let me know, but it looks like beardlib its not the issue per say.

**Comment by segabl** [comment]
Doesn't appear to be a BeardLib issue, might be another mod messing with unlock levels
