### ISSUE TITLE
BeardLib and 'spoofing' custom barrel & magazine part

### ISSUE THREAD

**Issue by Alcat101** [simon-wh/PAYDAY-2-BeardLib#47]
So after Update 150 (Desync/3rd Person Anim)
3rd Person model can now detach and drop their weapon's magazine.

Before update 150, mod that adds in new custom magazine to existing pd2 weapon works perfectly and it wont cause any problem to other client/player. Be it hosting or to client.
After update 150, this is not the case anymore, as the game now expect weapon's magazine data or some sort to be thrown to other client. This result in all existing BeardLib mod that adds in new type of magazine attachment, to crash other client be it on lobby or in heist (I've tested in heist, the moment the weapon that uses custom magazine reloads, the player that uses the custom magazine mod will disconnect, possibly crashing anyone's game).
>:3 told me that since BeardLib doesn't 'spoof' this custom magazine, this issue occur.

This doesn't happen with completely new, custom weapon standalone mod.

Is it possible to have BeardLib workaround this issue?

**Comment by Luffyyy** [comment]
In the future maybe but not now sorry.

**Comment by Alcat101** [comment]
Understandable
Just pointing out the issue, since I have to go to through the trouble of updating all of my custom magazine mods xd

**Comment by Alcat101** [comment]
Deleted the old issue here: https://github.com/simon-wh/PAYDAY-2-BeardLib/issues/9

Both the above link and this custom magazine have the same problem on playing with other client online.

The client game's expect to receive id of custom barrel and magazine part or some sort, from the custom weapon user game. If not, the client crash/dc.

**Comment by Nepgearsy** [comment]
**Understandable**

😂😂😂😂😂🖕🖕🖕🖕🖕🖕

**Comment by Luffyyy** [comment]
Stop shitposting on my thread

**Comment by VxWolf** [comment]
Understanda🅱le, have a great day.
