### ISSUE TITLE
U210 sight' changes lead to crashes.

### ISSUE THREAD

**Issue by MrVavlo** [simon-wh/PAYDAY-2-BeardLib#470]
Game immediately crashes in heist after black screen with one of the sights installed on weapons:

Military Dot Sight (unconfirmed by me)
Milspec Scope
Compact Tactical Box Sight
...And there might be more, I don't know what sights Overkill touched.

Any mod but BeardLib being removed doesn't solve the problem.

Here's a [crashlog](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/7108230/crash.txt).

**Comment by Luffyyy** [comment]
Installed all sights on CAR-4 and did not experience any crashes. Could you confirm this is happening in the latest commit?

**Comment by MrVavlo** [comment]
Alright, I checked it right now with the latest commit, and seems like this was a false call. This time it worked, just with BeardLib.

(and then I found the mod that cause that)

My apologies...
