### ISSUE TITLE
Gamecrash while joining heists

### ISSUE THREAD

**Issue by kobalium23** [simon-wh/PAYDAY-2-BeardLib#477]
**Describe the crash**
Gamecrash while joining (only sometimes)

**To Reproduce**
join any hosted game wait while joining appears in lobby crash happens around 98% joined

**Crashlog**
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/7164719/crash.txt)

**Comment by Luffyyy** [comment]
Unfortunately tells me nothing useful and whether or not BeardLib is the cause of it even.
