### ISSUE TITLE
cant enable it and it just randomly disabled

### ISSUE THREAD

**Issue by voidikin** [simon-wh/PAYDAY-2-BeardLib#478]
one day i just opened the game and beardlib was gone and disabled without any option to enable it
the disabable says its false while my mods that work are set to true but blt is set to false for some reason
does anyone know how to fix this?

**Comment by Luffyyy** [comment]
I'm not sure why that would happen generally, but you can forcibly re-enable it by deleting mods/saves/blt_data.txt. If it still happens tell me.

**Comment by voidikin** [comment]
Where is that

**Comment by voidikin** [comment]
nevermind

**Comment by voidikin** [comment]
its still not enabled

**Comment by Luffyyy** [comment]
Send your logs (mods/logs)
