### ISSUE TITLE
2click safehouse is no more with updated BeardLib

### ISSUE THREAD

**Issue by Dushess** [simon-wh/PAYDAY-2-BeardLib#480]
**Describe the bug**
I had version 3.0x and also sBLT via WSOCK version unknown, but with CRC64 = 0C5209610E211FCB
After update this mod stopped working by unknown reason. It has access line from main memu, now line is gone.

**To Reproduce**
Update to BeardLib ver.4.56 and sBLT ver.R031-3.3.2

May be related to my modpack overall, but not sure, can you check?

**Comment by Luffyyy** [comment]
Considering how old BL 3.x at this point, I'm almost certain you should just find these mods again (preferably updated ones)

**Comment by Dushess** [comment]
Just if it exists now, this mod is removed from MWS. Then, what I should look into, to make it work for now? mostly what might be broken mod-side? To fix myself...

**Comment by Luffyyy** [comment]
Dunno I'm sure someone in mws discord knows an alternative

**Comment by Dushess** [comment]
Okay, but I need to check first if some other mod is screwed up. 
For this one seems to be menu change or something from base functions, okey...

**Comment by Dushess** [comment]
If so, entire mod options panel is empty now, there was HUD options, Fade rework options, all other option panel usually located there.

**Comment by Dushess** [comment]
FIXED by rebuilding modpack.
