### ISSUE TITLE
Game freezes up and sometimes crashes, log indicates BeardLib is responsible.

### ISSUE THREAD

**Issue by HDnexus700** [simon-wh/PAYDAY-2-BeardLib#482]
The custom weapon's models don't load in for some reason, and only has a "load circle" spinning.
When i choose "modify" on a custom gun the game freezes up completely and i'm forced to forcefully shut it down.
If i equip a custom weapon and start a heist as host or just joining one, the game crashes.

At first i thought it was due to a conflict between WeaponLib and Custom Attachment Points but removing CAP didn't change anything, so i decided to check the log as for some reason it didn't show up in the crash log.

But here's the full log, so i don't accidentally leave anything regarding this issue/bug out on accident:
[2021_09_29_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/7251266/2021_09_29_log.txt)

**Comment by Luffyyy** [comment]
Reinstall your BeardLib (entirely, delete the folder befote installing again), it contains old files for some reason.

**Comment by HDnexus700** [comment]
reinstalled it, completely. still same issue.
cleaned out all non-necessary mods apart from the mods needed to see if the issue persisted with custom weapons, this also made the log much shorter.

To me (who's not a coder or modder) it looks somehow like the scripts/code from BeardLib doesn't load, but i could be wrong on that.

dropping new log text and screenshot of what i meant it looked like, also it's not only on custom weapons but also on all custom attachments and mod-added skins. though i can join a heist with custom attachments on, but they also have that "loading circle" spinning.
[2021_09_29_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/7252825/2021_09_29_log.txt)
![Capture](https://user-images.githubusercontent.com/91604146/135292081-5df26e22-d1da-4a28-a5a6-b40dd4e01d84.PNG)

**Comment by Luffyyy** [comment]
I'm not sure where you are downloading from, but "mods/BeardLib/Modules/AddFilesModule.lua" hasn't been in BeardLib since version **4.0**. You are downloading an old version or merging with an old version. Make sure you don't have anything left, and that you are downloading straight from modworkshop.

**Comment by HDnexus700** [comment]
that's what i have been doing though, and i haven't merged it either. and it is from ModWorkShop, that's why it's so damn weird.
Would it fix if i remove that AddFilesModule.lua or is there an easy fix that can be done like that? or should i just try and find a newer version of BeardLib, though i should have the most recent as i downloaded it yesterday.
