### ISSUE TITLE
Game crashing?

### ISSUE THREAD

**Issue by Okidoki69420** [simon-wh/PAYDAY-2-BeardLib#484]
**Describe the crash**
A clear and concise description of what the crash is.Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:236  
                   LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:258  
                   unit_data()  @mods/BeardLib/Hooks/CoreSystem.lua:62              
                                core/lib/managers/coresequencemanager.lua:681       
             reload_textures()                                                      
                          =[C]  GetModImage()                                       
                                @mods/base/req/BLTMod.lua:311                       
                        init()                                                      
@mods/base/req/ui/BLTUIControls.lua:267  new()                                               
                                @mods/base/req/utils/UtilsClass.lua:26              
                       setup()                                                      
@mods/base/req/ui/BLTDownloadManagerGui.lua:35  _setup()                                            
                                @mods/base/req/ui/BLTCustomComponent.lua:31         
                        init()                                                      
@mods/base/req/ui/BLTCustomComponent.lua:20  new()                                               
                                @mods/base/req/utils/UtilsClass.lua:26              
                      create()                                                      
@mods/base/req/core/MenuHelper.lua:719  set_active_components()                             
                                lib/managers/menu/menucomponentmanager.lua:490      
       set_active_components()                                                      
@mods/base/lua/MenuComponentManager.lua:19  core/lib/managers/menu/coremenulogic.lua:89         
       _execute_action_queue()  core/lib/managers/menu/coremenulogic.lua:54         
                      update()  core/lib/managers/menu/coremenulogic.lua:64         
                      update()  core/lib/managers/menu/coremenumanager.lua:155      
                      update()  lib/managers/menumanagerpd2.lua:20                  
                    original()  lib/setups/setup.lua:877                            
                      update()  @mods/base/req/core/Hooks.lua:188                   
                      update()  lib/setups/menusetup.lua:358                        
                      update()  @mods/base/lua/MenuSetup.lua:5                      
                    original()  core/lib/setups/coresetup.lua:557                   
                                @mods/base/req/core/Hooks.lua:265                   

-------------------------------

System information:
	Application version : 1.110.43
	CPU : AMD Ryzen 3 2300X Quad-Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : AMD Radeon(TM) RX 560 Series / aticfx32.dll[27.20.14535.3005]
	Language : english
	Memory :     16314MB 396KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Advanced Micro Devices (4 - NS-32D311NA17 (AMD High Definition Audio Device))

**To Reproduce**

**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)                         not quite sure why it keeps crashing new to modding can someone help me out

**Comment by Luffyyy** [comment]
Not enough information. Remove mods you have installed until it fixes itself.
