### ISSUE TITLE
If i click Crew AI management will crash

### ISSUE THREAD

**Issue by Dreamsnow13579** [simon-wh/PAYDAY-2-BeardLib#490]
Tue Oct 19 20:47:55 2021

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main
Script stack:
                    original()  @mods/pd2-bot-weapons-master/lua/menuscenemanager.lua:37  
        set_henchmen_loadout()  @mods/base/req/core/Hooks.lua:265                   
           reset_crew_outfit()  lib/managers/menu/crewmanagementgui.lua:135         
                        init()  @mods/pd2-bot-weapons-master/lua/crewmanagementgui.lua:34  
                         new()  core/lib/utils/coreclass.lua:35                     
                      create()  lib/managers/menu/menucomponentmanager.lua:5149     
       set_active_components()  lib/managers/menu/menucomponentmanager.lua:490      
       set_active_components()  @mods/base/lua/MenuComponentManager.lua:19          
                                core/lib/managers/menu/coremenulogic.lua:89         
       _execute_action_queue()                                                      
core/lib/managers/menu/coremenulogic.lua:54  update()                                            
                                core/lib/managers/menu/coremenulogic.lua:64         
                      update()                                                      
core/lib/managers/menu/coremenumanager.lua:155  original()                                          
                                lib/managers/menumanagerpd2.lua:20                  
                      update()                                                      
@mods/base/req/core/Hooks.lua:265  original()                                          
                                lib/setups/setup.lua:879                            
                      update()                                                      
@mods/base/req/core/Hooks.lua:188  update()                                            
                                lib/setups/menusetup.lua:358                        
                     _update()                                                      
@mods/base/lua/MenuSetup.lua:5  update()                                            
                                @mods\PocoHud3\poco\common.lua:310                  
core/lib/setups/coresetup.lua:557  
Please fix it.

**Comment by segabl** [comment]
Indeed not a BeardLib issue, iirc this was a temporary issue with Bot Weapons and Equipment which I fixed
