### ISSUE TITLE
Weapon crash

### ISSUE THREAD

**Issue by Dreamsnow13579** [simon-wh/PAYDAY-2-BeardLib#496]
Application has crashed: C++ exception
[string "lib/units/weapons/raycastweaponbase.lua"]:1996: attempt to index a nil value

SCRIPT STACK

play_tweak_data_sound() lib/units/weapons/raycastweaponbase.lua:1974
stop_shooting() lib/units/weapons/raycastweaponbase.lua:378
destroy() lib/units/weapons/raycastweaponbase.lua:2007
destroy() lib/units/weapons/newraycastweaponbase.lua:2316
original() lib/units/weapons/newnpcraycastweaponbase.lua:417
@mods/base/req/core/Hooks.lua:188

**Comment by Luffyyy** [comment]
Not enough information. I need BLT log and context. It's likely not BeardLib itself causing it and I recommend swapping out mods until it resolves itself.

**Comment by Dreamsnow13579** [comment]
Sun Oct 31 11:37:34 2021


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???

         payday2_win32_release  (???)     ???

         payday2_win32_release  (???)     ???

         payday2_win32_release  (???)     ???



-------------------------------

Current thread: Main
Script stack:
                        load()  @mods/BeardLib/Hooks/CoreSystem.lua:99

               load_packages()  lib/setups/menusetup.lua:95

                                core/lib/setups/coresetup.lua:323

I think must be BeardLib problem

Luffy ***@***.***> 於 2021年10月30日 週六 上午4:19寫道：

**Comment by Luffyyy** [comment]
This doesn't help me at all, I can't do much with random crashlogs. I'm sorry but you will need to delete mods that might be causing it. If you believe it's beardlib causing, please report it properly with detailed information. That includes when the issue happens, crashlog and blt log found in mods/logs. That being said, in most situations it's not beardlib to blame, but other reasons like not installing mods correctly or even completely unrelated issues that beardlib isn't cause of.

**Comment by Dreamsnow13579** [comment]
Sat Oct 16 19:03:38 2021


Application has crashed: C++ exception
mods/BeardLib/Hooks/CoreSystem.lua:81: attempt to index field 'File' (a nil
value)



SCRIPT STACK

get_texture_path() lib/tweak_data/achievementstweakdata.lua:64
init() lib/tweak_data/achievementstweakdata.lua:2813
new() core/lib/utils/coreclass.lua:35
init() lib/tweak_data/tweakdata.lua:615
new() core/lib/utils/coreclass.lua:35
lib/tweak_data/tweakdata.lua:3291
require() =[C]
OrigRequire() @mods/base/base.lua:181
require() @mods/BeardLib/Core.lua:363
lib/setups/setup.lua:37
require() =[C]
OrigRequire() @mods/base/base.lua:181
require() @mods/BeardLib/Core.lua:363
lib/setups/menusetup.lua:1
require() =[C]
OrigRequire() @mods/base/base.lua:181
require() @mods/BeardLib/Core.lua:363
lib/entry.lua:13
require() =[C]
OrigRequire() @mods/base/base.lua:181
require() @mods/BeardLib/Core.lua:363
core/lib/coreentry.lua:19


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???

         payday2_win32_release  (???)     ???

         payday2_win32_release  (???)     ???

                      KERNEL32  (???)     BaseThreadInitThunk

                         ntdll  (???)     RtlGetAppContainerNamedObjectPath

                         ntdll  (???)     RtlGetAppContainerNamedObjectPath

         payday2_win32_release  (???)     zip_get_name



-------------------------------

Current thread: Main
Script stack:
            get_texture_path()  lib/tweak_data/achievementstweakdata.lua:64

                        init()
 lib/tweak_data/achievementstweakdata.lua:2813
                         new()  core/lib/utils/coreclass.lua:35

                        init()  lib/tweak_data/tweakdata.lua:615

                         new()  core/lib/utils/coreclass.lua:35

                                lib/tweak_data/tweakdata.lua:3291

                     require()

                          =[C]  OrigRequire()

                                @mods/base/base.lua:181

                     require()

   @mods/BeardLib/Core.lua:363  lib/setups/setup.lua:37

                     require()  =[C]

                 OrigRequire()  @mods/base/base.lua:181

                     require()  @mods/BeardLib/Core.lua:363

                                lib/setups/menusetup.lua:1

                     require()

                          =[C]  OrigRequire()

                                @mods/base/base.lua:181

                     require()

   @mods/BeardLib/Core.lua:363  lib/entry.lua:13

                     require()  =[C]

                 OrigRequire()  @mods/base/base.lua:181

                     require()  @mods/BeardLib/Core.lua:363

                                core/lib/coreentry.lua:19

Luffy ***@***.***> 於 2021年10月31日 週日 下午1:51寫道：

**Comment by Dreamsnow13579** [comment]
小瑀 ***@***.***> 於 2021年10月31日 週日 下午6:20寫道：
