### ISSUE TITLE
Crash on White House

### ISSUE THREAD

**Issue by PN474** [simon-wh/PAYDAY-2-BeardLib#497]
**Describe the crash**
When I try to join White House Heist, the Game Crashes
**To Reproduce**
Steps to reproduce the behavior: Go to White House in Crime.net, Select the heist and Join. Then you crash

**Crashlog**
Application has crashed: C++ exception
Archive::checked_read() Attempt to read past end of archive 'mods/BeardLib/Assets/units/default_cp.cooked_physics'

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
WorldDefinition_load_continent_package()  core/lib/utils/dev/editor/coreworlddefinition.lua:184  
WorldDefinition_load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:93  
     _load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:93  
            parse_continents()  core/lib/utils/dev/editor/coreworlddefinition.lua:263  
        WorldDefinition_init()  core/lib/utils/dev/editor/coreworlddefinition.lua:44  
        WorldDefinition_init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  lib/utils/dev/editor/worlddefinition.lua:6          
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  core/lib/utils/dev/editor/worldholder.lua:49        
                         new()  core/lib/utils/coreclass.lua:35                     
                   init_game()  lib/setups/gamesetup.lua:684                        
                                core/lib/setups/coresetup.lua:422                   

-------------------------------

System information:
	Application version : 1.113.57
	CPU : Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) UHD Graphics 620 / igdumdim32.dll[27.20.100.8853]
	Language : english
	Memory :     8078MB 244KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound: Realtek Semiconductor Corp. (Speaker / Headphone (Realtek(R) Audio))

**Comment by segabl** [comment]
this looks like a faulty beardlib installation or a faulty mod, if it still happens, feel free to reopen
