### ISSUE TITLE
Not sure how to read this.

### ISSUE THREAD

**Issue by AnadorableStrayCat** [simon-wh/PAYDAY-2-BeardLib#501]
I have no idea if this is relating to beardlib or something else. What does this crashlog mean?

It occurs whenever my friend joins the lobby and I have no clue what caused it.
![image_2021-11-21_211837](https://user-images.githubusercontent.com/94814154/142791432-c104f448-a740-4d8b-a482-e341dbfc4838.png)

**Comment by Luffyyy** [comment]
Try to use the latest commit on GitHub.

**Comment by ytani31** [comment]
hello I wanted to ask so I installed beardlib I run payday 2 and my progress is lost tell me how to enable it

**Comment by Luffyyy** [comment]
> hello I wanted to ask so I installed beardlib I run payday 2 and my progress is lost tell me how to enable it

I have no idea, this isn't a help forum, go to mws discord for help.

**Comment by ytani31** [comment]
where to find your discord

**Comment by Luffyyy** [comment]
https://discord.gg/zxnBzSsg

**Comment by segabl** [comment]
This should have been fixed with https://github.com/simon-wh/PAYDAY-2-BeardLib/commit/bf71feedf754561901cd3acc478be0f5035ee07f
