### ISSUE TITLE
DependenciesModule called to early (mod_overrides doesn't get detected)

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib#502]
**Describe the bug**
Any mod_overrides dependencies are not detected by the Dependency Module because it's called to early (when things from mods folder load, but things from mod_overrides haven't).
The script is all fine though, it's just called before BeardLib load mod_overrides.

**To Reproduce**
Add this to main.xml;
`
<Dependencies>
		<Dependency name="Hazzalaw_Narrator_Pack" type="mod_overrides" id="25986" provider="modworkshop"/>
	</Dependencies>
`
@Makowo :kitteh:

**Comment by Makowo** [comment]
Caused by items in maps/mods loading before mod_overrides. not sure how to fix this besides sidestepping the loading and checking folder names for mod_override types.

**Comment by MiamiCenterPL** [comment]
@Luffyyy is that even possible to fix? I am stuck in development of one thing because of that, and would really appreciate the fix :D

**Comment by Luffyyy** [comment]
Shouldn't the check be called after all mods get loadef? @Makowo

**Comment by MiamiCenterPL** [comment]
What Mako said on discord was that if it were executed later, the module wouldn't disable the map if dependency wasn't found
¯\_(ツ)_/¯

**Comment by Makowo** [comment]
Yeah, at least to my understanding. Need to do it before hooks for the mod are loaded since if a hook requires a dependency, crash goes the payday.

**Comment by Luffyyy** [comment]
I changed the way stuff load slightly, letting all frameworks fetch their mods and only then kick-start the loading of their mods. I'll need testing for the dependencies module and also in general wait some while before introducing this change to everyone. 
It's possible I'll make an update without this change due to the time that has passed since the last update.
