### ISSUE TITLE
Unable to load into game.

### ISSUE THREAD

**Issue by ADarkOne** [simon-wh/PAYDAY-2-BeardLib#509]
Hello, thank you for taking the time to read this.

I've been playing payday 2 for a while on pc, and absolutely loved the mods the we're allowed in via Beardlib, however, recently a problem has popped up where it seems like either Beardlib is crashing something, or my weapon mods are crashing something.

Before i can even get in to press start, my game just stops entirely.

I've deducted that:

-4+ weapon/attachment mods breaks the game

- Beardlib versions dont make a difference

-And the final thing i can notice is that, no matter what weapon mod it is, its gonna break the game

-Here's today's crashlog, any help would be appreciated!
[2022_01_07_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/7830529/2022_01_07_log.txt)

I've tried messing with the initial Dll's that make beardlib work, that didnt work

i've tried my redistributables, nothing

And as a last ditch effort, i reset my pc, and still nothing

Have a wonderful day to you and the Beardlib team!

**Comment by MiamiCenterPL** [comment]
Try these things;
Rename Payday2 Beardlib 4.2 to just BeardLib (directory name)
Remove AR-C folder from mod_overrides as it's outputting errors

**Comment by ADarkOne** [comment]
updated beardlib to 4.6, removed the AR-C folder and its still not working, this is todays crash lo
[2022_01_09_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/7836665/2022_01_09_log.txt)
g

**Comment by ADarkOne** [comment]
[2022_01_11_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/7848140/2022_01_11_log.txt)
So, moving forward with my problem, its now saying i dont have "mods/saves/blt_data.txt"

**Comment by segabl** [comment]
did you try a completely fresh install of superBLT (removing the base and saves folders from mods)?

**Comment by Jdog5g** [comment]
I have the same problem but when I try to fresh install BeardLib it doesn't work still.
