### ISSUE TITLE
New Update Crash on Boot

### ISSUE THREAD

**Issue by Thirtytree** [simon-wh/PAYDAY-2-BeardLib#51]
Just updated beardlib and the game is crashing on boot, uninstalling all mods other than BLT and beardlib right now, just wanted to know if others are having this issue.

**Comment by Luffyyy** [comment]
If you have HoloUI or PVM update them manually if that's not the issue then uninstall mods and see which does it(look first for ones that use BeardLib) also please include crash logs when you crash.

**Comment by DrDevinRX** [comment]
With only BeardLib installed, I am also crashing on startup.
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1166521/crash.txt)

**Comment by Thirtytree** [comment]
Sorry about not including the crash log, uninstalling every mod did the trick. So beardlib itself is completely fine

**Comment by Luffyyy** [comment]
Okay
