### ISSUE TITLE
Hello. Report crash errors.

### ISSUE THREAD

**Issue by NolzapanMalzapan** [simon-wh/PAYDAY-2-BeardLib#511]
**Describe the crash**
A clear and concise description of what the crash is.

It seems to crash when shooting with an LMG weapon or minigun.

**To Reproduce**

1. Equip an LMG or minigun.
2. Shoot with the equipped weapon.
3. A crash occurs after an unspecified amount of time has elapsed.
4. 
**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)

Application has crashed: C++ exception
mods/base/req/xaudio/XAudioSource.lua:131: XAudio Error at C:\projects\payday2-superblt\src\xaudio\XASource.cpp:171 : alErr : 40963

SCRIPT STACK

set_position() @mods/base/req/xaudio/XAudioSource.lua:131
update() @mods/BeardLib/Classes/MixedSoundSource.lua:101
update() @mods/base/req/xaudio/XAudio.lua:34
func() @mods/base/req/xaudio/XAudio.lua:43
Call() @mods/base/req/core/Hooks.lua:104
update() @mods/base/lua/GameSetup.lua:5
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
                         ntdll  (???)     RtlDosSearchPath_Ustr                               

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.117.74
	CPU : Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1660 SUPER / nvldumd.dll[27.21.14.5751]
	Language : english
	Memory :     16296MB 648KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : C-MEDIA Inc. (스피커(3- USB Audio Device))

I'm really sorry. I don't know how to speak English. This article was written with a translator.

**Comment by MiamiCenterPL** [comment]
This looks like issue with custom weapon sounds mod to me. Do you have any sound enhacements mod installed?

**Comment by segabl** [comment]
This is not a BeardLib issue, either a mod using XAudio wrong or a SuperBLT issue. If it happens again, please open an issue on whatever mod is using custom sounds
