### ISSUE TITLE
CANT USE BEARDLIB

### ISSUE THREAD

**Issue by latnN** [simon-wh/PAYDAY-2-BeardLib#512]
When i download Beardlib all my mods dissapear and i cant use them in game .

![image](https://user-images.githubusercontent.com/99300365/153099872-588d9871-90f3-4767-bd33-1f7dd660c076.png)

**Comment by segabl** [comment]
There is probably another mod breaking the mod options, check the BLT log for any errors

**Comment by segabl** [comment]
Closing due to lack of information
