### ISSUE TITLE
Letting me use the Winter Ghosts Tailor Pack outfits and tracksuit without owning it

### ISSUE THREAD

**Issue by nikola4002** [simon-wh/PAYDAY-2-BeardLib#513]
When in the loadout screen if i use my  middle mouse button to scroll through  the outfits it lets me equip the following : Dogsled Master,Dead of Winter and the Tracksuit,

Open a loadout, equip any outfit and back out, then use middle mouse button to scroll through the outfits and it will let you equip the outfits

**Comment by connieprice** [comment]
Fixed in #606
