### ISSUE TITLE
Loading too many .ogg files causes OutOfMemory error

### ISSUE THREAD

**Issue by pioleg** [simon-wh/PAYDAY-2-BeardLib#514]
## Problem description

I am experiencing crashes after loading too many music mods (while switching music, not on startup).
I did some testing and it looks like:

- only mods that use ogg files cause problems
- **loading ogg mods takes up a lot of memory (~5x more than their space on disk, i.e. loading 50MB mod can  use ~250MB of RAM)**
- **after loading ogg mods memory is never freed**
- **game freezes when loading ogg files** (usually it's just a quick stutter, but for bigger mods it can last for more than 1 second (files are loaded from SSD))
- issues above don't occur when loading mods with .movie files

Tests were done using **heist** music mods (to fill memory faster than with menu music). Game was crashing on different mods (error isn't specific to only one song). Tests were done with and without other mods that can control music (used mods: Music Control, Custom OST and PocoHUD3), results were the same in both cases (crash.txt and 2022_02_16_log.txt are from crash without mods).
BeardLib has 'Optimized music load' option enabled.

## To Reproduce

1. Start Payday 2 with music mods
2. (optional) Start heist to use more memory (less music needed to crash the game)
3. Start loading music by selecting tracks in 'Custom Heist Playlist' in  Options>Sound or switching Custom Track in pre-heist menu
4. ~400-450MB of music should crash the game from main menu, ~300-350MB on Buluc's Mansion

## Crashlog

**2022_02_16_log.txt** in 'mods/logs' directory ends with:
```
03:14:46 PM Log:  (C:\projects\payday2-superblt\src\http\http.cpp:57) CURL CLOSED
03:14:46 PM Log:  (C:\projects\payday2-superblt\src\xaudio\XAudio.cpp:137) Closing OpenAL XAudio API
```

**crash.txt**
```
Application has crashed: C++ exception
mods/base/req/xaudio/XAudioBuffer.lua:7: blt.xaudio.loadbuffer: OutOfMemory



SCRIPT STACK

init() @mods/base/req/xaudio/XAudioBuffer.lua:7
new() @mods/base/req/utils/UtilsClass.lua:26
LoadBuffers() @mods/BeardLib/Modules/Addons/MenuMusicModule.lua:6
play() @mods/BeardLib/Hooks/MusicManager.lua:219
attempt_play() @mods/BeardLib/Hooks/MusicManager.lua:202
original() @mods/BeardLib/Hooks/MusicManager.lua:48
post_event() @mods/base/req/core/Hooks.lua:288
callback() lib/managers/menumanager.lua:8655
trigger_back() core/lib/managers/menu/coremenunode.lua:243
core/lib/managers/menu/coremenulogic.lua:200
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
original() lib/managers/menumanagerpd2.lua:20
update() @mods/base/req/core/Hooks.lua:288
original() lib/setups/setup.lua:879
update() @mods/base/req/core/Hooks.lua:288
update() lib/setups/menusetup.lua:358
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.117.74
	CPU : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[30.0.14.7212]
	Language : english
	Memory :     16348MB 772KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))
```

**Comment by segabl** [comment]
Fixed in https://github.com/simon-wh/PAYDAY-2-BeardLib/commit/aee1955a3dd53bdab59c2069bced3184a8ccc9bf
