### ISSUE TITLE
Crashing when try to restart

### ISSUE THREAD

**Issue by qek123** [simon-wh/PAYDAY-2-BeardLib#515]
**Describe the crash**

When I try to restart (Mission), the game is going to crash and given the same crash log

**To Reproduce**

Just try to restart the mission

**Crashlog**

Application has crashed: C++ exception
mods/base/req/xaudio/XAudioSource.lua:85: Cannot use closed resource!

SCRIPT STACK

set_buffer() @mods/base/req/xaudio/XAudioSource.lua:85
update() @mods/BeardLib/Classes/MixedSoundSource.lua:139
update() @mods/base/req/xaudio/XAudio.lua:34
func() @mods/base/req/xaudio/XAudio.lua:43
Call() @mods/base/req/core/Hooks.lua:104
update() @mods/base/lua/GameSetup.lua:5
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.118.83
	CPU : Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 950 / nvldumd.dll[30.0.15.1179]
	Language : english
	Memory :     8141MB 32KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by segabl** [comment]
This appears to be an issue with either an audio mod or a custom weapon mod that utilizes custom sounds. Check for a mod like that and see if removing it helps.

**Comment by segabl** [comment]
Closing this assuming it has been resolved
