### ISSUE TITLE
try to load game crashes instantly says Beardlib

### ISSUE THREAD

**Issue by MCRMSnow** [simon-wh/PAYDAY-2-BeardLib#517]
i get no crash file but in log it says

02:54:51 AM Log:  (C:\projects\payday2-superblt\src\debug\blt_debug.cpp:124) Command line: "C:\STEAM ONLY HITMAN\steamapps\common\PAYDAY 2\payday2_win32_release.exe"
02:54:51 AM Log:  (C:\projects\payday2-superblt\platforms\w32\signatures\signatures.cpp:352) Scanning for signatures in payday2_win32_release.exe
02:54:51 AM Log:  (C:\projects\payday2-superblt\platforms\w32\signatures\signatures.cpp:405) Scanned for 57 signatures in 0 milliseconds with 0 cache misses
02:54:51 AM Log:  (C:\projects\payday2-superblt\src\dbutil\DB.cpp:127) Start loading DB info
02:54:52 AM Log:  (C:\projects\payday2-superblt\src\dbutil\DB.cpp:242) Finished loading DB info: 254677 files in 303 ms
02:54:52 AM Log:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:43) [WREN ERR] <unknown>:-1 ] Non-tweak element in mod_overrides mod in assets/mod_overrides/BeardLib:<wren>: wren
02:54:52 AM Log:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:43) [WREN ERR] base/private/xml_loader:387 ] load_supermod_file(_,_,_)
02:54:52 AM Log:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:43) [WREN ERR] base/private/xml_loader:356 ] init()
02:54:52 AM Log:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:43) [WREN ERR] base/private/xml_loader:487 ] (script)
02:54:52 AM Log:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:43) [WREN ERR] base/base:2 ] (script)
02:54:52 AM Log:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:43) [WREN ERR] __root:1 ] (script)
02:54:52 AM FATAL ERROR:  (C:\projects\payday2-superblt\src\tweaker\wrenloader.cpp:506) Wren init failed: compile or runtime error!
i have even tried taking beardlib out of Mod Overrides and it still does it just put it in to test

**Comment by Luffyyy** [comment]
>  i have even tried taking beardlib out of Mod Overrides and it still does it just put it in to test
Also looking from the logs, it doesn't seem like that's a BeardLib issue, it's possible you have an outdated SBLT. 
https://superblt.znix.xyz
