### ISSUE TITLE
Meltdown crash

### ISSUE THREAD

**Issue by TheCale51** [simon-wh/PAYDAY-2-BeardLib#518]
**Describe the crash**
A clear and concise description of what the crash is.

The game crashes when I load Meltdown

**To Reproduce**
1.Buy the contract (Overkill)
2.Start the heist
**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
WorldDefinition_load_continent_package()  core/lib/utils/dev/editor/coreworlddefinition.lua:184  
WorldDefinition_load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:93  
     _load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:93  
                    original()  core/lib/utils/dev/editor/coreworlddefinition.lua:298  
           _insert_instances()  @mods/base/req/core/Hooks.lua:288                   
            parse_continents()  core/lib/utils/dev/editor/coreworlddefinition.lua:286  
        WorldDefinition_init()  core/lib/utils/dev/editor/coreworlddefinition.lua:44  
        WorldDefinition_init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  lib/utils/dev/editor/worlddefinition.lua:6          
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  core/lib/utils/dev/editor/worldholder.lua:49        
                         new()  core/lib/utils/coreclass.lua:35                     
                   init_game()  lib/setups/gamesetup.lua:692                        
                                core/lib/setups/coresetup.lua:422                   

-------------------------------

**Comment by segabl** [comment]
This is unlikely to be a BeardLib issue, does this consistently happen?

**Comment by segabl** [comment]
Closing due to lack of information
