### ISSUE TITLE
Beardlib crash to desktop on launch

### ISSUE THREAD

**Issue by Ind3gL0** [simon-wh/PAYDAY-2-BeardLib#52]
So I've been getting this as a crashlog from a week ago when I try to start up the game with Beardlib installed:

Sat Jul 15 17:59:17 2017

Application has crashed: C++ exception
[string "core/lib/utils/coretable.lua"]:32: bad argument #1 to 'pairs' (table expected, got number)

SCRIPT STACK
-------------------------------
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                             

So I figured I'd wait. Got the Beardlib update today, verified the game, tried loading it with just Beardlib installed, still the same thing.

Fri Jul 21 18:52:31 2017

Application has crashed: C++ exception
[string "core/lib/utils/coretable.lua"]:32: bad argument #1 to 'pairs' (table expected, got number)

SCRIPT STACK
-------------------------------
Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???      

I don't know if there's a simple fix or if it's just me running into this problem or not, but I'm hoping that I can hear back about this as soon as possible.

**Comment by Luffyyy** [comment]
Can you give me your blt log?(mods/logs/dateOfCrash.txt) Do you have any mods inside mod overrides?

**Comment by Ind3gL0** [comment]
I'm sorry to have to say this, but my hard drive seems to have become corrupted recently. I'll try it again with just Beardlib installed and nothing in mod_overrides when I can.
