### ISSUE TITLE
Addfiles module directory incompatable with shortcuts

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib#525]
**Describe the bug**
Attempting to use add directory="path/to" with a shortcut meta name doesnt seem to function.
![image](https://user-images.githubusercontent.com/26837908/159117762-a5204cef-2a26-4523-b176-59231e0404d9.png)

**To Reproduce**
Note: This was done in a package. I am not completely sure if that is partly the issue.
```
<add directory="units/pd2_mod_id/prop/gen_unit_folder">
          <unit_mat path="gen_unit_here" />
</add>
```

**Comment by Luffyyy** [comment]
Tried to fix, but the change might break mods. Need some testing with existing mods
