### ISSUE TITLE
Modules module doesnt function (when using XML Module)

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib#527]
**Describe the bug**
Modules module doesnt work at all in the main.xml, copying the custom module to beardlib addons makes it functional.

**To Reproduce**
```
<Modules directory="modules">
	<module file="SpecialEquipmentsModule.lua" name="SpecialEquipmentsModule" type_name="SpecialEquipments"/>
</Modules>
```

```
SpecialEquipmentsModule = SpecialEquipmentsModule or BeardLib:ModuleClass("SpecialEquipments", ModuleBase)
-- Adds an equipments to tweak_data.equipments.specials

function SpecialEquipmentsModule:init(...)
    self.required_params = table.add(clone(self.required_params), {"id"})
	return SpecialEquipmentsModule.super.init(self, ...)
end

function SpecialEquipmentsModule:Load()
    if not self._config.id then
        self:Err("Equipments does not contain a definition for id!")
        return
    end
    TweakDataHelper:ModifyTweak(table.merge({custom = true}, self._config), "equipments", "specials", self._config.id)
end
```

**Comment by Luffyyy** [comment]
It's possible your mod needs a high priority

**Comment by RexTheWho** [comment]
> It's possible your mod needs a high priority

Changing priority doesnt seem to fix the issue.

**Comment by RexTheWho** [comment]
Issue discovered, but not completely resolved.
Modules is non-functional in the XML module.

Test project for any future attempts at fixing this issue.

[ModulesTestProject.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/8355509/ModulesTestProject.zip)

**Comment by segabl** [comment]
Is this still relevant?
