### ISSUE TITLE
Develop mode tooltip shows error string

### ISSUE THREAD

**Issue by sooooosh** [simon-wh/PAYDAY-2-BeardLib#528]
**Describe the bug**
In the mod settings in the beardlib mod list, hovering over "Develop Mode" shows an error string in the tooltip. 
![unknown](https://user-images.githubusercontent.com/37846872/160894501-144ddc36-faa7-47cd-b90d-25348985575d.png)

`beardlib_mod_developer_mode` is probably the string that was supposed to be used but isn't.

**Comment by segabl** [comment]
Fixed in https://github.com/simon-wh/PAYDAY-2-BeardLib/commit/d4251baba928a20b80623f9c557f260762421cc1
