### ISSUE TITLE
Mod settings tab not showing up

### ISSUE THREAD

**Issue by IcaroArrigoni** [simon-wh/PAYDAY-2-BeardLib#53]
The mod settings tab in the settings menu, are not showing up! I'm guessing this is a Beardlib issue but if you have any other guesses, please inform.

**Comment by Luffyyy** [comment]
When you crash -> crashlog
When your game has a weird issue -> blt log(mods/log/dateOfTheIssue.txt)

**Comment by IcaroArrigoni** [comment]
[2017_07_22_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1167403/2017_07_22_log.txt)

**Comment by IcaroArrigoni** [comment]
I don't understand a lot about code, so I send it over to you. But it has happened only since the update yesterday. I have not found anything on google or the forums. (Oops forgot to hit "comment")

**Comment by Luffyyy** [comment]
It shouldn't be hard to search for errors in the log file the issue is with HoloUI, however it's probably because you haven't updated BeardLib also(update released today), if you did update try manually updating BeardLib because that's the issue.
