### ISSUE TITLE
Crash on startup when opening Payday 2

### ISSUE THREAD

**Issue by Canpake59** [simon-wh/PAYDAY-2-BeardLib#54]
Whenever I open up payday 2 the game crashes to desktop. I know its a problem with this mod because I removed just this mod and it opened up fine. Help would be greatly appreciated .

**Comment by Luffyyy** [comment]
I can't help you without a crash log. 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Canpake59** [comment]
This was what was in my crash log: Application has crashed: C++ exception
bad allocation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                      Exists()  86                                                  
                        Load()  31                                                  
                        init()  10                                                  
                        init()  7                                                   
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  @mods/BeardLib/BeardLibCore.lua:65                  
                                @mods/BeardLib/BeardLibInit.lua:36                  
                      dofile()                                                      
                          =[C]  call_require_hook()                                 
                                @mods/base/base.lua:126                             
                     require()                                                      
       @mods/base/base.lua:140  core/lib/coreentry.lua:14

**Comment by Canpake59** [comment]
Nevermind, I'm good now. Something in mod overrides was crashing it
