### ISSUE TITLE
Beardlib Host Crash

### ISSUE THREAD

**Issue by ReiyoTheRice** [simon-wh/PAYDAY-2-BeardLib#540]
**Describe the crash**
A clear and concise description of what the crash is.
So, every time one of my friends or me hosts lobby (and he has beardlib installed) we always crash on few maps (from what i rember its Rats day 3, Big bank and No mercy, but there is more wich i cant rember) if someone else in lobby has beardlib also installed. Ive tried this with me as host, with friend as host and with the second friend as host. Every time if someone besides host has beardlib it crashes his game with same crashlog. However this doesnt occur if host doesnt have beardlib installed but other players in lobby do.
**To Reproduce**
Not sure if its ours internet settings but basically have beardlib installed, and other player joining the game does too. Its best tested on big bank (it always crashes on 45th or 50th second of the heist). Just start the heist and around 45th second it should automatically crash.
**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)
Application has crashed: C++ exception
[string "lib/network/handlers/unitnetworkhandler.lua"]:61: attempt to call method 'synch_equipped_weapon' (a nil value)

SCRIPT STACK

@mods/BeardLib/Hooks/Network/NetworkHooks.lua:94

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

(as already mentioned, me and both my friends has the same crashlog)

**Comment by segabl** [comment]
are all of you using the most recent version of beardlib (the version from github?)

**Comment by ReiyoTheRice** [comment]
> are all of you using the most recent version of beardlib (the version from github?)

Yes, we all have most recent verision of beardlib.

**Comment by segabl** [comment]
I have seen this crash before though following the stack doesn't seem like it is a BeardLib issue unless it somehow desyncs units and therefore tries to synchronize a weapon on a unit that doesn't have one. If you can reliably reproduce this issue I'd be more than happy to give you a modified version of BeardLib to track down what's causing this.

**Comment by ReiyoTheRice** [comment]
Like i said, its easy for me to reproduce it, i just have to host lobby with friend who has beardlib on one of few maps (rats day 3, big bank, and some others i cant rember).

**Comment by segabl** [comment]
If you could use [this](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/8832855/PAYDAY-2-BeardLib.zip) attached custom version of BeardLib and report back with the log once the issue happens (It will prevent the crash and print a message in chat), that would be helpful.

**Comment by ReiyoTheRice** [comment]
Surely! Sadly i'm not currently home so I'll have to test it on Sunday afternoon.

**Comment by ReiyoTheRice** [comment]
Well, i can't replicate that crash, cause im currently facing another issue, my friend can't join me and neither can't I him.

**Comment by ReiyoTheRice** [comment]
Well even better, i found out that issue is somehow in Super BLT, when i remove it he can normally join me

**Comment by segabl** [comment]
> Well, i can't replicate that crash, cause im currently facing another issue, my friend can't join me and neither can't I him.

might be using some mod that locks matchmaking?

**Comment by ReiyoTheRice** [comment]
> > Well, i can't replicate that crash, cause im currently facing another issue, my friend can't join me and neither can't I him.
> 
> might be using some mod that locks matchmaking?

well, i tought that too, i've removed all modification of the game except beardlib and SuperBLT, and still he cloudnt join, but the moment i removed BLT, he cloud, so its some problem with BLT.

**Comment by segabl** [comment]
And you're not also running BeardLib Editor by chance?

**Comment by ReiyoTheRice** [comment]
> And you're not also running BeardLib Editor by chance?

No, I don't, like i said even with no modifications to base game, as long as i have BLT installed friend cant join me.
