### ISSUE TITLE
Invisible Hands

### ISSUE THREAD

**Issue by Xerogh** [simon-wh/PAYDAY-2-BeardLib#542]
https://reddit.com/r/paydaytheheist/comments/uyy05u/need_help_fixing_invisible_hands_glitch_more_info/
^ Reddit post concerning my bug.

In addition, I also tried installing just SuperBLT and I didnt experience the glitch, then installed BeardLib and subsequently experienced the glitch again.

https://imgur.com/a/fkRq9wo

It's also worth noting that when someone joins the lobby it isn't a 100% chance my hands will disappear, but by the time the 3rd or 4th person joins, its almost certain my hands are gone.

**Comment by segabl** [comment]
this should probably be fixed in https://github.com/simon-wh/PAYDAY-2-BeardLib/pull/606, if not feel free to reopen this issue
