### ISSUE TITLE
Access violation crash when loading custom map

### ISSUE THREAD

**Issue by nmarin-dedalord** [simon-wh/PAYDAY-2-BeardLib#543]
**Describe the crash**
I select the custom heist "A Touch of Class" from Crimenet. It loads as normal but as soon as it reaches the point the preplanning screen should load up, the game crashes to desktop. It seems to happen with this one custom heist, although I wouldn't discard the possibility of it happening with others.

**To Reproduce**
Download "A Touch of Class" from it's ModWorkshop link, drop it in the "maps" folder, boot up the game and try to load the heist itself.

**Crashlog**
Application has crashed: access violation

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

Current thread: Main
Script stack:
```
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:236  
                      Update()  @mods/BeardLib/Classes/Managers/FileManager.lua:281  
                        func()  @mods/BeardLib/Core.lua:219                         
                        Call()  @mods/base/req/core/Hooks.lua:104                   
                      update()  @mods/base/lua/GameSetup.lua:5                      
                      update()  lib/setups/networkgamesetup.lua:21                  
                    original()  core/lib/setups/coresetup.lua:557                   
                                @mods/base/req/core/Hooks.lua:288
```

**Comment by segabl** [comment]
If it only happens with this heist, then its probably an issue with an asset from that, not BeardLib itself.

**Comment by nmarin-dedalord** [comment]
I agree but I feel there should be (if possible) a check that prevents this crash from happening since it didn't JUST happen with this heist. It was just an example.

**Comment by segabl** [comment]
There's not really a way to check if an asset is invalid or incorrectly set up, that's the responsibility of the mod author that made the asset.

**Comment by nmarin-dedalord** [comment]
Alright. I figured it could be checked if it didn't exist somehow. I've had to add that check in a few places in the code of a couple of hooks, but if it can't be done in this case I may as well close this.
