### ISSUE TITLE
Playing in multiplayer causes infinite black loading screens

### ISSUE THREAD

**Issue by stormytuna** [simon-wh/PAYDAY-2-BeardLib#544]
I have BeardLib installed, along with another friend. We can play heists perfectly fine with each other and with a second friend who doesn't have BeardLib. When the second friend installs BeardLib, it causes either me or the first friend to not be able to load into heists - We get an infinite black loading screen and have to Alt+F4 out of the game

Not sure how to reproduce, it's literally only happened with this one person and I can't test with anyone else

**Comment by segabl** [comment]
Can you attach your BLT log (mods/logs/) from a game where this happens?

**Comment by segabl** [comment]
Hmm, not seeing any obvious in the logs, though I'm assuming this might be outfit related. Are any of you using custom outfits/gloves/etc?

**Comment by MiamiCenterPL** [comment]
I suggest trying out this:
https://modworkshop.net/mod/37308

**Comment by stormytuna** [comment]
None of us are using custom outfits or gloves, using that Anti Blackscreen mod doesn't work either

**Comment by segabl** [comment]
When you say unable to load into heists, do you mean the screen stays black after the heist starts?

**Comment by stormytuna** [comment]
No, the first loading screen that's just black with "Loading" in the top left is where we get stuck

**Comment by stormytuna** [comment]
This issue has spread to happening with just me and the first friend as well, neither of our mods list has been changed since last night and now we can't play together with BeardLib enabled

**Comment by segabl** [comment]
Can you check if this still happens when both of you remove ALL mods and mod_overrides except SuperBLT and BeardLib?

**Comment by stormytuna** [comment]
Yeah it does. Tested with me and third friend, can test with all 3 and with just second friend later

**Comment by segabl** [comment]
Hmm, not sure what could be causing this then, can you check your streaming chunks size settings in the game options?

**Comment by segabl** [comment]
Is this still happening to you?

**Comment by stormytuna** [comment]
Played a little bit recently with only me having BeardLib and a few mods that depend on it and it worked fine. Not sure what the issue was but it isn't happening now

**Comment by segabl** [comment]
Alright, feel free to re-open with further info if it happens again.
