### ISSUE TITLE
Infamy Card won't show up in lobby

### ISSUE THREAD

**Issue by RainbowFishcakes** [simon-wh/PAYDAY-2-BeardLib#545]
When in a lobby before the heist starts, players with BeardLib will always show their weapons out as if they have a skin, when most of the time they don't.
Image below is using only SuperBLT and BeardLib, no other mods or mod_overrides
![20220602131434_1](https://user-images.githubusercontent.com/106787237/171763447-e0983fd9-b525-440d-b195-acd209ad8441.jpg)
By deleting BaseNetworkSection.lua in Hooks\Network and lines 118-128 of MenuManager.lua in Hooks\UI (shown below), the infamy card will show up again
![wCq5rDB](https://user-images.githubusercontent.com/106787237/171764023-88f11b05-1e31-4df7-b14c-f6f0151cf54e.png)
Image below is using SuperBLT, BeardLib, mods, and mod_overrides
![20220602140545_1](https://user-images.githubusercontent.com/106787237/171764551-bad272c1-e953-4d64-96b0-5dc80402df4d.jpg)

**Comment by connieprice** [comment]
I've got a fix for it anyway, the way BeardLib's outfit reloading works wasn't correctly getting the rank for the local peer.

**Comment by segabl** [comment]
> I've got a fix for it anyway, the way BeardLib's outfit reloading works wasn't correctly getting the rank for the local peer.

thanks for fixing this so quickly
