### ISSUE TITLE
Beardlib crash with a wolfhud profile menu

### ISSUE THREAD

**Issue by Abraxas97** [simon-wh/PAYDAY-2-BeardLib#549]
Application has crashed: C++ exception
mods/BeardLib/Classes/Utils/Sync.lua:141: attempt to index local 'fac_part' (a nil value)

SCRIPT STACK

CleanOutfitString() @mods/BeardLib/Classes/Utils/Sync.lua:244
func() @mods/BeardLib/Hooks/Network/NetworkPeer.lua:51
Call() @mods/base/req/core/Hooks.lua:104
send() @mods/BeardLib/Hooks/Network/NetworkPeer.lua:101
_send_queued() lib/network/base/networkpeer.lua:1124
send_after_load() lib/network/base/networkpeer.lua:1131
send_to_peers_loaded() lib/network/base/basenetworksession.lua:733
check_send_outfit() lib/network/base/basenetworksession.lua:1347
original() lib/managers/menumanagerpd2.lua:690
_update_outfit_information() @mods/base/req/core/Hooks.lua:288
original() lib/managers/multiprofilemanager.lua:122
load_current() @mods/base/req/core/Hooks.lua:288
set_current_profile() lib/managers/multiprofilemanager.lua:151
callback() @mods/VanillaHUD Plus/lua/ProfileMenu.lua:96
trigger() core/lib/managers/menu/items/coremenuitem.lua:161
core/lib/managers/menu/coremenulogic.lua:286
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
original() lib/managers/menumanagerpd2.lua:20
update() @mods/base/req/core/Hooks.lua:288
original() lib/setups/setup.lua:885
update() @mods/base/req/core/Hooks.lua:288
update() lib/setups/menusetup.lua:358
update() @mods/base/lua/MenuSetup.lua:5
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlRestoreLastWin32Error                            
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                   steamclient  (???)     CreateInterface                                     
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                   steamclient  (???)     CreateInterface                                     
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.123.108
	CPU : Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960 / nvldumd.dll[30.0.15.1259]
	Language : english
	Memory :     8117MB 880KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by segabl** [comment]
WolfHUD is heavily outdated, try VanillaHUD+ instead

**Comment by Abraxas97** [comment]
> WolfHUD is heavily outdated, try VanillaHUD+ instead

it is vanillahud+ but vanillahud+ uses modified code from wolfhud. I think it's a profile menu thing so I'll explore more.

**Comment by Abraxas97** [comment]
update; it was a conflict with a lasers mod
