### ISSUE TITLE
Beardlib Mod Manager not showing mods

### ISSUE THREAD

**Issue by Wolfito141** [simon-wh/PAYDAY-2-BeardLib#551]
It says i have updates available but when i click it it doesn't show anything, just the menu with theSettings, custom achievments and etc.

**Comment by segabl** [comment]
can you show a screenshot of how the menu looks for you?

**Comment by Wolfito141** [comment]
Sure, it looks like that. It used to show a list of mods before, i dunno what happened.

![20220619042916_1](https://user-images.githubusercontent.com/107775196/174470570-80e5d17d-4dac-4a6e-ae67-4ee9d80545bd.jpg)

**Comment by Wolfito141** [comment]
Hi, sorry for taking so long to answer. I went to see if +blt had updates but the only site i found it was in modworkshop and it said i don't have permission to see it so i guess it's not updated anymore... I'll try removing it and see what happens
