### ISSUE TITLE
Border Crossing Crash

### ISSUE THREAD

**Issue by Hungerdunger** [simon-wh/PAYDAY-2-BeardLib#553]
My game crashes in the loading screen of Border Crossing. The Game does not crash when playing Border Crystals.

[2022_06_22_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/8953185/2022_06_22_log.txt)

**Comment by segabl** [comment]
Can you post the actual crash.txt from %localappdata%/Payday 2 please? Also I'm seeing a lot of errors in your BLT logs from broken mods, you might want to sort those out.

**Comment by Hungerdunger** [comment]
I'll probably have to do some work with them. Still have less then in old days.

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/8956628/crash.txt)

**Comment by Hungerdunger** [comment]
Thank you. I couldn't find that out. Have a great day/night : ).
