### ISSUE TITLE
Big heists crash on entry

### ISSUE THREAD

**Issue by thatwolfrio** [simon-wh/PAYDAY-2-BeardLib#555]
**Describe the crash**
Whenever I load into a big heist (big as in size), it crashes. It either crashes on the 2nd loadout selection area right before you go into the heist, or the screen as your loading in where it flashes the difficulty and you get a little dialogue. I'm not sure if this matters, but I'm on Arch Linux and I use the Windows version through Steam Proton. I tried changing the Proton version, as well as re-installing the game, and re-downloading BeardLib.

**To Reproduce**
Steps to reproduce the behavior: I purchased the contract and re-ran the heist, and each time I did I removed a mod from my mods folder until I was left with BeardLib, and once I removed that it ran fine. I ran it on Henry's Rock while narrowing down which mod caused it, but the crash did occur on a couple other heists, all of which were either from a DLC or came in a later update.

**Crashlog**
For some reason it never wrote a crash log for this crash, even though I tried it a million times.

**Comment by segabl** [comment]
iirc crash logs on linux are saved to the mods/logs folder, unlike windows. without a log there's not much we can do about this.

**Comment by thatwolfrio** [comment]
[2022_06_30_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/9023748/2022_06_30_log.txt)
Here's my log file but I looked at it myself and there's nothing in there that seems to matter. It kind of looks like somebody ALT+F4s the game as soon as it loads into the level. I tried some more fixes, mainly clearing my mod_overrides folder again to see if that fixes it, but that didn't do anything.

**Comment by segabl** [comment]
Hmm no, that's just the BLT log, there should be an actual crash log somewhere.
