### ISSUE TITLE
Mask on sequences bug

### ISSUE THREAD

**Issue by firebirddie** [simon-wh/PAYDAY-2-BeardLib#556]
With beardlib installed there's heisters who have multiple head/hair meshes depending if they're masked up or not. For example with Jimmy his hair is squished down like if he was wearing a mask even though he's unmasked. By default without beardlib he should have his hair as normal until he masks up it squishes down. (Pictures below the post)

I found out inside PlayerStyleGloveHooks.lua if you were to delete the hook for "BeardLibUpdateCharacterVisualState" everything functions as normal. So the culprit that causes this issue is probably in there.

Here's a picture of Jimmy when he's unmasked.
![218620_20220704221045_1](https://user-images.githubusercontent.com/8610949/177153213-d1ee3f19-4a22-4c87-ac3e-0c3ea533b52e.png)

Here's another picture of how he should look like when unmasked.
![218620_20220704221008_1](https://user-images.githubusercontent.com/8610949/177153475-2c0f5405-3910-44dd-b02a-5fd67f618ca5.png)

I'm really poor at explaining stuff so i hope this was enough for you to understand there's something up.

**Comment by segabl** [comment]
Sorry to ping you again @connieprice but this might be another thing you know how to fix since it's your code. It seems there is no check for mask on/off sequences in this custom set outfit function.

**Comment by connieprice** [comment]
Fixed in #606
