### ISSUE TITLE
Game crashes on newer heists with beardlib

### ISSUE THREAD

**Issue by Stratdan** [simon-wh/PAYDAY-2-BeardLib#557]
**Describe the crash**
I wanted to try out some newer heists, but when it loads at the briefing the game crashes. I tried removing all my mods, even mod_overrides, reinstalling superblt and beardlib then the game but nothing worked. Only removing beardlib

**To Reproduce**
-Join a newer heist (for example: Ukranian prisoner and dragon heist)
-Wait for it to load
-Game crashes

**Crashlog**
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/9046526/crash.txt)
Or pastebin: [crash](https://pastebin.com/d36fwrWK)

**Comment by segabl** [comment]
Is this still happening to you? I cannot reproduce this on my end and these heists work fine. Possibly caused by another mod.
