### ISSUE TITLE
Application has crashed: C++ exception [string "lib/units/enemies/cop/actions/full_body/copac..."]:515: attempt to index field 'direction_vec' (a nil value)

### ISSUE THREAD

**Issue by BeeTrippie** [simon-wh/PAYDAY-2-BeardLib#559]
**Describe the crash**
when loading into mission the game crashes

**To Reproduce**
trying to load into mission

**Crashlog**
Application has crashed: C++ exception
[string "lib/units/enemies/cop/actions/full_body/copac..."]:515: attempt to index field 'direction_vec' (a nil value)

**Comment by segabl** [comment]
This is not an issue caused by BeaardLib and most likel either caused by an AI mod or a custom map
