### ISSUE TITLE
Crashing when entering a friend's lobby

### ISSUE THREAD

**Issue by Komaedave** [simon-wh/PAYDAY-2-BeardLib#56]
As the title says, this is my crashlog:

Sun Jul 23 17:16:25 2017

Application has crashed: C++ exception
[string "lib/network/base/networkpeer.lua"]:287: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

**Comment by Luffyyy** [comment]
Does it still happen? Are you sure this is BeardLib causing? Does it happen specifically on your friend's lobby?

**Comment by Komaedave** [comment]
Yeah, happened only with him, but since then it has fixed itself. So, don't worry.

**Comment by Luffyyy** [comment]
Alright
