### ISSUE TITLE
[Music Module] Heist tracks making 'pauses' before looping

### ISSUE THREAD

**Issue by MrVavlo** [simon-wh/PAYDAY-2-BeardLib#561]
**Bug description:**
Whenever the track goes on the loop, for some milliseconds it goes silent before playing the part again, thus creating an uncomfortable effect for the ears on each loop. 

It also presents in the scenario when the intro part transmission into the loop part, but I suppose it's unevadable.

In the picture below is a soundwaves' comparison of the game recordings with same track, with the same part, of BeardLib and CustomOST (as an example, didn't bother to put a PAYDAY track into BeardLib):
![image](https://user-images.githubusercontent.com/34880333/179488200-60494cae-28b8-4bbd-8232-fd34df73e013.png)

And here is the archive of the recordings above:
[Tracks Comparison.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/9131114/Tracks.comparison.zip)

This issue is not relevant to the menu tracks - they loop without those pauses, from what I hear.

**Comment by segabl** [comment]
Can you maybe attach the track you used for testing?

**Comment by MrVavlo** [comment]
Alright. Here it is:
[Test.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/9132159/Test.zip)
