### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Zyrusssz** [simon-wh/PAYDAY-2-BeardLib#563]
Hello, could you please help me, I have a problem with BeardLib that I had downloaded following the steps on your page and it worked for me and I was able to download my textures well, the problem is that it did not let me enter the public games and they did not load, so I uninstalled BeardLib and now it would allow me to join public games and join the game but my textures were lost... so I reinstalled BeardLib and when I installed it it wouldn't let me use it. I deleted the mod_overrides folder and made a new one with the same name and nothing, and I go into the game and go to BeardLib4.x and where it says Disable:_false
Allow safe mode:_false
y y go to mod BerdLib-editor
says Disable:_true
Allow safe mode:_true and I don't know what it means please help me I don't know much about 
![Mod](https://user-images.githubusercontent.com/110212536/181676708-cf0e739d-bce0-4b1e-b25b-eb4516366256.jpg)
![mod2](https://user-images.githubusercontent.com/110212536/181676721-f13dbbe5-2bab-4acc-9036-f856dc2be7f9.jpg)
![mod3](https://user-images.githubusercontent.com/110212536/181677022-f37fdcc7-ef80-4d1b-a9c5-406838a76d74.jpg)

**Comment by Luffyyy** [comment]
Please make sure to read descriptions of mods you download, beardlib **editor** disables matchmaking, this is totally intended to avoid crashing people. Remove the editor when you wish to play matchmaking.

**Comment by Zyrusssz** [comment]
Hello again, thank you very much for helping me now I can play with other people, but how can I play using my textures? I have BeardLib but it won't let me use the textures that I had downloaded before
![Mod](https://user-images.githubusercontent.com/110212536/181799926-7210af76-8228-4907-80f6-c7f306a1c73f.jpg)
What does that mean, I'm sorry I don't know much and I don't speak much English, I hope you understand me
![help](https://user-images.githubusercontent.com/110212536/181800852-433016a7-e3a8-4819-9887-cc4f87dae492.jpg)

**Comment by Luffyyy** [comment]
Reinstall the textures? In general beardlib just doesn't allow disbabling in game to avoid issues, safe mode I sorta forgot what it means so likely unimportant.

**Comment by Zyrusssz** [comment]
I have 2 downloaded textures and it should appear in outfits and it doesn't appear and I have BeardLib inside the mods folder as the guide says, in conclusion I can no longer use textures?
![bip](https://user-images.githubusercontent.com/110212536/181807375-360a4fe7-992e-409b-8140-0696a2140dcc.jpg)
![mods](https://user-images.githubusercontent.com/110212536/181807388-521f15de-86a7-4e6e-ade4-73972ef21263.png)
![mods2](https://user-images.githubusercontent.com/110212536/181807395-00d5708f-cd63-4241-8924-727327c10f38.png)
ures?

**Comment by Luffyyy** [comment]
You are missing legendary armour skins https://modworkshop.net/mod/24006 
I'd recommend going to MWS discord for further help.

**Comment by Zyrusssz** [comment]
Thank you very much, I am missing legendary armor skins, now I can enjoy my textures, thanks for your time friend
