### ISSUE TITLE
Cashing

### ISSUE THREAD

**Issue by 420vapemaster** [simon-wh/PAYDAY-2-BeardLib#565]
**Describe the bug**
It's want to load be but can't
FATAL ERROR:  (C:\projects\payday2-superblt\src\InitiateState.cpp:248) mods/BeardLib/Classes/UI/Dialogs/MenuDialog.lua:29: attempt to index field 'Options' (a nil value)
stack traceback:
        mods/BeardLib/Classes/UI/Dialogs/MenuDialog.lua:29: in function 'init'
        [string "core/lib/utils/coreclass.lua"]:35: in function 'new'
        mods/BeardLib/Classes/Managers/MenuDialogManager.lua:22: in function 'create_items'
        mods/BeardLib/Classes/UI/MenuUI/MenuUI.lua:74: in function 'init'
        mods/BeardLib/Classes/UI/MenuUI/MenuUI.lua:6: in function 'func'
        mods/base/req/core/Hooks.lua:104: in function 'Call'
        mods/base/lua/MenuManager.lua:88: in function '_base_process_menu'
        mods/base/lua/MenuManager.lua:65: in function <mods/base/lua/MenuManager.lua:42>
        [C]: in function 'pcall'
        mods/base/lua/MenuManager.lua:42: in function 'func'
        mods/base/req/core/Hooks.lua:104: in function 'Call'
        mods/base/lua/MenuManager.lua:10: in function 'init'
        [string "core/lib/utils/coreclass.lua"]:35: in function 'new'
        [string "lib/setups/setup.lua"]:401: in function 'init_managers'
        [string "lib/setups/gamesetup.lua"]:645: in function 'init_managers'
        [string "lib/setups/networkgamesetup.lua"]:10: in function 'init_managers'
        [string "core/lib/setups/coresetup.lua"]:399: in function <[string "core/lib/setups/coresetup.lua"]:293>

**Comment by segabl** [comment]
can you post the crash.txt

**Comment by 420vapemaster** [comment]
> can you post the crash.txt
got it How to get it to a .txt?

**Comment by segabl** [comment]
Enter "%localappdata%/Payday 2" in your file explorer address bar and attach the crash.txt here

**Comment by segabl** [comment]
Closing for lack of information
