### ISSUE TITLE
Black Screen with custom Music

### ISSUE THREAD

**Issue by greyyzilla** [simon-wh/PAYDAY-2-BeardLib#567]
**Describe the bug**
There is a bug within BeardLib's music module that makes it so whoever is the host and is using a custom music, people with custom music or not are also affected. The black screen issue is not applicable for players who joined in an existing game whose heist has been already started, or to the game host himself.

This is also applicable for client who joined in lobby, then starts the heist.

**To Reproduce**
1. Host starts the heist with a music that is added through BeardLib's MusicModule.
2. The black screen issue starts to take effect to clients connect to the host who has custom music selected.

OR

1. Host starts a heist, but join as client.
2. Client, or you, gets a blackscreen when starting with a custom music.

The log attached may or may not be of use
[2022_08_17_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/9358629/2022_08_17_log.txt)

**Comment by segabl** [comment]
This is most likely an issue with large custom music files and loading them during the blackscreen that we currently don't have control about since SuperBLT loads all of it at once which has the chance to cause desync during the blackscreen intro. Currently the best way to prevent this is select the custom music you want to listen to before heist start so it will be loaded before starting.

**Comment by greyyzilla** [comment]
> large custom music files

Are there any way or a guide on how to make the music files less larger? All I've known was to reduce the quality through Audacity. Is there also a recommended maximum file size for the music files?

**Comment by segabl** [comment]
well ogg quality on export is the main factor 5 or lower should still be fine but in the end it just reduces the chance of the blackscreen bug, not completely gets rid of it. This is something that needs to be improved on SuperBLT side.

**Comment by greyyzilla** [comment]
> well ogg quality on export is the main factor 5 or lower should still be fine but in the end it just reduces the chance of the blackscreen bug, not completely gets rid of it.

i have music mods that seem to be very light in file size, i dont think it feels like it has reduced the chances for the blackscreen bug to happen. 

> This is something that needs to be improved on SuperBLT side.

im looking forward to this nonetheless!
