### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by lollaMeow** [simon-wh/PAYDAY-2-BeardLib#57]
Application has crashed: C++ exception
bad allocation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                      Exists()  86                                                  
                        Load()  31                                                  
                        init()  10                                                  
                        init()  7                                                   
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  @mods/BeardLib/BeardLibCore.lua:65                  
                                @mods/BeardLib/BeardLibInit.lua:36                  
                      dofile()                                                      
                          =[C]  call_require_hook()                                 
                                @mods/base/base.lua:126                             
                     require()                                                      
       @mods/base/base.lua:140  core/lib/coreentry.lua:14                           

-------------------------------

**Comment by lollaMeow** [comment]
i also tried:
manually update PVM
manually update holoUI
manually update BeardLib
reinstalling BLT hook
also not crashing without BeardLib

any help ?

**Comment by Luffyyy** [comment]
Remember you have mod overrides also, so please go and check them, this includes any custom weapons, weapon mods, masks, music, etc anything that requires BeardLib. 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lollaMeow** [comment]
-Trijicon ACOG TA31F-RMR Scope
-Sniper Rifles Iron Sights
-StatTrak
-DMR Mag for AK
-AK12
-AKU-94
-IWI Tavor X95
-No Weapon
all other mods is cosmetical and not requires BeardLib

**Comment by Luffyyy** [comment]
No don't list them disable one by one and tell me which causes it, i currently cannot play but of you give me the exact mod I might pinpoint a reason for that. Either way one of those mods should be the reason you're crashing. 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lollaMeow** [comment]
i did so... and looks like some simple retexture cause it crash
like "red body bags". its sad :c
