### ISSUE TITLE
Mask on sequence makes outfit contour disappear temporarily

### ISSUE THREAD

**Issue by RainbowFishcakes** [simon-wh/PAYDAY-2-BeardLib#573]
When the heist goes loud or when a peer joins in, there is a period where the contour of the outfit the peer/bot is wearing does not exist, and only the head, hands, and wrist contour appear. This only happens once per heist as you can just walk to them and have the contour reappear again, but it does get annoying when you notice it a lot.

Note: I am using the latest version of BeardLib from this repository

This screenshot comes from a test session where I am using BLT and mod_overrides mods and even a PDMOD, but no BeardLib
![20220920203757_1](https://user-images.githubusercontent.com/106787237/191397211-868103a0-9759-488c-bdcd-26f430fdacd1.jpg)

This screenshot comes from a test session where I am using NO MODS (INCLUDING THE PDMOD) AND ONLY BEARDLIB
![20220920205734_1](https://user-images.githubusercontent.com/106787237/191397290-4b2dd005-d0f0-49f0-b265-92a00cac78c9.jpg)

**Comment by connieprice** [comment]
Fixed in #606
