### ISSUE TITLE
Game Randomly freezes when I use BeardLib

### ISSUE THREAD

**Issue by popoqw43** [simon-wh/PAYDAY-2-BeardLib#581]
whenever I launch a heist and the game loads it will sometimes just randomly freeze and never unfreeze it does not happen when I have 
BeardLib disabled and it still happens when I have every other mod disabled and it also happens when I restart sometimes.

**To Reproduce**
no clue

**Comment by Luffyyy** [comment]
It's hard to really pinpoint the issue in this case, you should try uninstalling mods that may be causing it that use BeardLib. Remember that this is a library, it doesn't do too much by itself.
