### ISSUE TITLE
Payday 2 Randomly Crashing when I kill an enemy, I theorize that it relates to Total Crackdown

### ISSUE THREAD

**Issue by Spartan-the-Avatar** [simon-wh/PAYDAY-2-BeardLib#582]
*The Crash* 
After loading into a Heist, I'm able to play the game for a bit, But sometimes when I kill an enemy, the Game Hard-Crashes, not even back to the menu, just out of the game entirely

**To Reproduce**
Unfortunately I'm not entirely sure what causes it However I have a theory it relates to the fact I have the Total Crackdown mod, because when I'm shooting one of the enemies added by the mod, that's when it crashes

**Crashlog**
Application has crashed: C++ exception
mods/BeardLib/Classes/Utils/JSON.lua:311: Unexpected character at Line 1 character 1: 

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlGetCurrentServiceSessionId                       
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.129.133
	CPU : Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1650 / nvldumd.dll[30.0.15.1215]
	Language : english
	Memory :     16248MB 324KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek(R) Audio))

**Comment by segabl** [comment]
This looks like some other mod is trying to load a faulty json file, not directly caused by beardlib itself. One way to check is to (temporarily) remove all files from mods/saves and see if that fixes it, if so then one of the save files for a mod is corrupted. If that doesn't fix it, then the faulty json file is part of another mod, possibly Crackdown in this case.

**Comment by Spartan-the-Avatar** [comment]
Y'know... I'm just going to cut my Losses and start from Scratch
