### ISSUE TITLE
ModWorkshop Updates not working due to outdated API link

### ISSUE THREAD

**Issue by Makowo** [simon-wh/PAYDAY-2-BeardLib#584]
**Describe the bug**
Auto updates from MWS will not work due to the API link in BeardLib no longer being valid (due to the brutal murder of modwork.shop)
The http req data will be longer than the maximum length due to downloading an entire HTML from the replacement site. 

**To Reproduce**
force an update by setting back the version on any MWS updated mod, no update will show in the menu.

**Comment by Luffyyy** [comment]
Totally my bad and I should've prepared, but the idea to stop paying for the domain was my idea and I completely forgot that BeardLib uses it. I'm waiting on our sysadmin to change the link to api.modworkshop.net, unfortunately this means anyone with the old link won't be able to update.

**Comment by regulargithub** [comment]
how do you manually update beardlib?

**Comment by Luffyyy** [comment]
> how do you manually update beardlib?

By downloading from mws.

**Comment by regulargithub** [comment]
oh okay thanks

**Comment by regulargithub** [comment]
it didnt work, the menu when you try to buy primaries crashes

**Comment by Luffyyy** [comment]
> it didnt work, the menu when you try to buy primaries crashes

Has nothing to do with the issue in hand

**Comment by regulargithub** [comment]
oh okay

thanks
