### ISSUE TITLE
heists continuously crashing before I can load in

### ISSUE THREAD

**Issue by spectywecty** [simon-wh/PAYDAY-2-BeardLib#586]
**Describe the crash**
Over the past few days I seem to keep crashing whenever I try to play some heists like White House or Shacklethorn Auction. I've never run into any issues with any heists until only recently and the crash always occurs before I can get into the briefing menu.

**To Reproduce**
Buy a heist contract and load into the heists. However, before you can get to the briefing menu it crashes

**Crashlog**
Application has crashed: C++ exception
bad allocation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
WorldDefinition_load_continent_package()  core/lib/utils/dev/editor/coreworlddefinition.lua:184  
WorldDefinition_load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:93  
     _load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:93  
            parse_continents()  core/lib/utils/dev/editor/coreworlddefinition.lua:263  
        WorldDefinition_init()  core/lib/utils/dev/editor/coreworlddefinition.lua:44  
        WorldDefinition_init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  lib/utils/dev/editor/worlddefinition.lua:6          
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  core/lib/utils/dev/editor/worldholder.lua:49        
                         new()  core/lib/utils/coreclass.lua:35                     
                   init_game()  lib/setups/gamesetup.lua:718                        
                                core/lib/setups/coresetup.lua:422

**Comment by segabl** [comment]
This seems like an issue with the game running out of memory. Can you try and check if it still happens when you set your textures to low? You might also have mods using a lot of memory.

**Comment by spectywecty** [comment]
> This seems like an issue with the game running out of memory. Can you try and check if it still happens when you set your textures to low? You might also have mods using a lot of memory.

No luck when setting my textures to Low, I'm not too sure what mod it could be that's using so much memory as I've never had this issue before and have barely added any new mods since.

**Comment by segabl** [comment]
It's not necessarily an out of memory issue, could also be related to anything modifying or adding custom maps. In terms of memory CustomOST is usually one of the culprits

**Comment by spectywecty** [comment]
> It's not necessarily an out of memory issue, could also be related to anything modifying or adding custom maps. In terms of memory CustomOST is usually one of the culprits

I don't have CustomOST installed nor do I have anything related to adding new custom maps, the only one I do have however is Proving Grounds which from what I can tell doesn't have any issue with the other heists as well. Sorry if this seems like a weirdly specific crash but it's been bugging me since I've been meaning to try and do the White House.

**Comment by segabl** [comment]
can you confirm it doesnt happen without BeardLib?

**Comment by spectywecty** [comment]
tried testing the same heists without beardlib, ended up getting an infinite load.

**Comment by segabl** [comment]
then that seems like it's cause by one of your mod_override mods that requires beardlib

**Comment by spectywecty** [comment]
oh my god thank you, because you mentioned that I remembered that I had moved another mod of mine from mods to mod_overrides and turns out that had been causing the issue. The mod was the "Visual Fixes" mod by Dorpenka and when I had updated it the mod told me to put it in overrides and I placed it thinking it wouldn't do anything.

**Comment by segabl** [comment]
glad you could solve the issue, I'll close this.
