### ISSUE TITLE
Some access violation crash after I formated my computer

### ISSUE THREAD

**Issue by AD-Pudim** [simon-wh/PAYDAY-2-BeardLib#593]
The Crash happens everytime I get to the loading screen just before getting ready to start a heist, it was working fine

1- Start a Contract (it wasn't a custom one it was normal bank heist cash)
2- Start the Contract
3- Crashes on loading screen

This is the crashlog
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                    KERNELBASE  (???)     SleepEx                                             
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  @mods/BeardLib/Hooks/CoreSystem.lua:99              
WorldDefinition_load_world_package()  core/lib/utils/dev/editor/coreworlddefinition.lua:125  
WorldDefinition_load_world_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:42  
         _load_world_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:42  
        WorldDefinition_init()  core/lib/utils/dev/editor/coreworlddefinition.lua:20  
        WorldDefinition_init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  lib/utils/dev/editor/worlddefinition.lua:6          
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  core/lib/utils/dev/editor/worldholder.lua:49        
                         new()  core/lib/utils/coreclass.lua:35                     
                   init_game()  lib/setups/gamesetup.lua:726                        
                                core/lib/setups/coresetup.lua:424                   

-------------------------------

System information:
	Application version : 1.133.154
	CPU : Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1660 SUPER / nvldumd.dll[31.0.15.2698]
	Language : english
	Memory :     16300MB 492KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Alto-falantes (Realtek High Definition Audio))

**Comment by segabl** [comment]
does this happen on every heist?
did you install any mod_overrides mods lately?

**Comment by AD-Pudim** [comment]
apperently is in some specific heists, Bank Heist, Scarface Mansion, didn't check any others, and not to my knowledge.

**Comment by segabl** [comment]
if it happens only on specific heists it might be a mod changing something on those heists. most likely caused by a different mod and not beardlib itself anyways.
