### ISSUE TITLE
coresequencemanager.lua crash while using a custom static vehicle model in PAYDAY2

### ISSUE THREAD

**Issue by cpmodding** [simon-wh/PAYDAY-2-BeardLib#596]
**Describe the crash**
I have created a custom model with textures to be replacing a vanilla static vehicle in game. The problem is while host invited players to join a session. In the meantime of joining, game crashes.
As I can see in the decompliled LUA scripts, `core/lib/managers/coresequencemanager.lua` line 2519 and below has that code:

```
function UnitElement:has_sequence_name(sequence_name)
	return self._sequence_elements[sequence_name] ~= nil
end
```

which may cause a crash. I am not sure it's possible or not to decompile vanilla sequence manager file for this vehicle `str_vehicle_car_modernsedan.sequence_manager`. Sequences may contain some variations like body paint and alarm states.

**To Reproduce**
1. Install the mod to assets\mod_overrides, mod link: https://file.io/ppypn6oEYArN
2. Other player has to install this mod aswell.
3. Run and host the game.
4. Invite the player and wait for crash while player is joining.

**Crashlog**

```
Application has crashed: C++ exception
[string "core/lib/managers/coresequencemanager.lua"]:2519: attempt to index a nil value



SCRIPT STACK

core/lib/units/coreunitdamage.lua:749
drop_in() =[C]
chk_drop_in_peer() lib/network/base/hostnetworksession.lua:465
on_peer_finished_loading_outfit() lib/network/base/hostnetworksession.lua:974
lib/network/base/handlers/connectionnetworkhandler.lua:646


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

```

**Comment by cpmodding** [comment]
Thanks for reply. Now I've redone the model, including the original meshes, just scaled to be very tiny. I'll let you know about the success or failure of this method in the next days.

**Comment by segabl** [comment]
you can delete the meshes entirely and just keep empties with the original names and it should work just fine. anyways, closing this as like I said earlier, it is not specifically a beardlib issue.
