### ISSUE TITLE
Crashing when playing with other people

### ISSUE THREAD

**Issue by Wolfito141** [simon-wh/PAYDAY-2-BeardLib#598]
My game crashes when playing with other people (AI works just fine), happens when people join my game or if i join other people's games. Dunno what triggers it exactly, bearlib is mentioned in the log so i guessed i should ask here.

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/10255015/crash.txt)

**Comment by segabl** [comment]
Looks like an issue with either a custom weapon or outdated Beardlib

**Comment by Wolfito141** [comment]
deleted some mods and it worked, also had beardlib outdated. Thanks.
