### ISSUE TITLE
Game Crashes on startup on Linux

### ISSUE THREAD

**Issue by OwnSample-hash** [simon-wh/PAYDAY-2-BeardLib#602]
**Describe the crash**
A clear and concise description of what the crash is.
During game start up the game crashes with BeardLib on Linux.

**To Reproduce**
Have BeardLib enabled during game start up!

**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/10327867/crash.txt)
[lua_crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/10327868/lua_crash.txt)

**Comment by segabl** [comment]
Not too familiar with modding on linux but it looks like some functionality of BLT is missing which makes beardlib not fully load. do you have the latest superblt for linux?

**Comment by OwnSample-hash** [comment]
Yes I do.

**Comment by OwnSample-hash** [comment]
I redid [this](https://modworkshop.net/mod/36557) and nothing changed. 

Then I reread `lua_crash.txt` and checked [mods/BeardLib/Classes/Managers/FileManager.lua:150](https://github.com/simon-wh/PAYDAY-2-BeardLib/blob/master/Classes/Managers/FileManager.lua#L150) what is here and i got an idea that what If there is no wren installed, after installing wren it works as it should be.
