### ISSUE TITLE
Crash when I update mod with blt

### ISSUE THREAD

**Issue by smz202000** [simon-wh/PAYDAY-2-BeardLib#605]
Application has crashed: C++ exception
mods/base/req/BLTDownloadManager.lua:100: attempt to index global 'file' (a nil value)

SCRIPT STACK

mouse_pressed() @mods/base/req/ui/BLTUIControls.lua:394
@mods/base/req/ui/BLTCustomComponent.lua:192
run_return_on_all_live_components() lib/managers/menu/menucomponentmanager.lua:349
mouse_pressed() lib/managers/menu/menucomponentmanager.lua:1769
mouse_pressed() @mods/base/lua/MenuComponentManager.lua:23
mouse_pressed() lib/managers/menu/menurenderer.lua:375
mouse_press() lib/managers/menu/menuinput.lua:662
lib/managers/mousepointermanager.lua:345

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.134.165
	CPU : Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1650 / nvldumd.dll[31.0.15.1694]
	Language : schinese
	Memory :     16319MB 12KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (扬声器 (High Definition Audio Device))

**Comment by Luffyyy** [comment]
And why do you think BeardLib is the cause?

**Comment by MazHunter537** [comment]
This is the problem for me too, and I think it's because if I delete BeardLib, the game works

**Comment by segabl** [comment]
If it is fine without BeardLib then you might have some mod that breaks something that only loads with beardlib. Check your mods and mod_overrides for mods that have a main.xml file

**Comment by JoysSekai** [comment]
I removed all my mods and then I started progressively adding then back. It started fine with SuperBLT but as soon as I add BeardLib (no other mods) the game crashes immediately with the same error code as OP.

**Comment by Luffyyy** [comment]
> I removed all my mods and then I started progressively adding then back. It started fine with SuperBLT but as soon as I add BeardLib (no other mods) the game crashes immediately with the same error code as OP. 

Can you confirm it happens with *only* sblt and beardlib installed?
