### ISSUE TITLE
Crash when enemies get killed by the host in a crimespree lobby

### ISSUE THREAD

**Issue by IKillerwolfI** [simon-wh/PAYDAY-2-BeardLib#61]
(I have biglobby installed, but I don't know if this has anything to do with this)
(and ofc I'm joining a friend who has the same mods)

So when I join a normal lobby everything is fine but when I join a crimespree lobby this happens:

Fri Jul 28 04:54:15 2017

Application has crashed: C++ exception
[string "lib/managers/menu/crimespreemissionsmenucom..."]:776: attempt to compare nil with number

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDecodeSystemPointer                              
                         ntdll  (???)     RtlDecodeSystemPointer                              
                         ntdll  (???)     RtlInitializeCriticalSection                        
                         ntdll  (???)     RtlQueryPerformanceCounter                          

-------------------------------

**Comment by Luffyyy** [comment]
Not really sure for now, I can't do a thing about it since you're using biglobby, the support for that mod isn't the best right now because both modify network functions, I'm not sure if i'll fix it.

You should test this also without biglobby.

**Comment by IKillerwolfI** [comment]
Ok without biglobby I can get in the lobby but when enemies get killed by my mate this happens:


Sat Jul 29 04:16:01 2017


Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                  spawn_unit()  @mods/BeardLib/Hooks/CoreSystem.lua:24              
          _spawn_head_gadget()  lib/units/enemies/cop/copdamage.lua:1881            
                                lib/units/enemies/cop/copdamage.lua:2075            
                            ()  =(tail                                              
                      call):-1  ()                                                  
                        =(tail                                                      
                      call):-1  sync_damage_bullet()                                
                                @mods/base/req/hooks.lua:258                        
lib/network/handlers/unitnetworkhandler.lua:322  
-------------------------------

**Comment by IKillerwolfI** [comment]
Nevermind this was caused by Evil Bob's enemy skins. Also, the original crash with biglobby has a workaround if someone is interested: https://github.com/polarathene/biglobby/issues/37
