### ISSUE TITLE
Custom heists not showing up in contact broker

### ISSUE THREAD

**Issue by Mr-Sir-XXIII-Esq** [simon-wh/PAYDAY-2-BeardLib#610]
Not sure why it's happening but some time before the Christmas event they just stopped appearing in the game. Not sure when it happened either as it may have taken a while for me to notice since I don't play custom heists much. First noticed at the start of the event and thought it might just be disabling custom heists but when it ended they weren't back.

**Comment by segabl** [comment]
Can you check or upload the output from the BLT log found in mods/logs please?

**Comment by Mr-Sir-XXIII-Esq** [comment]
[2023_01_16_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/10449850/2023_01_16_log.txt)
Did this upload properly?

**Comment by segabl** [comment]
it looks like your beardlib got corrupted or something, did you try removing it and its save files from mods/saves and downloading it fresh? also you have a few mods in the wrong folder (the ones where the log says it could not find a mod.txt), likely not the reason for your issue but felt like I sbould note that.

**Comment by Mr-Sir-XXIII-Esq** [comment]
Before I do that is there a way to (without keeping corrupt files) save my mod settings so I don't have to spend an hour on vanilla hud plus and ai weapons again?

**Comment by segabl** [comment]
your other mod settings are safe, just remove the `BeardLib_Options.txt` file from the saves folder
mods without mod.txt go into mod_overrides

**Comment by Mr-Sir-XXIII-Esq** [comment]
Fixed. Sorry I took so long to respond. Thanks for your help
