### ISSUE TITLE
UI Alignment causes a 54% increase in bootup time.

### ISSUE THREAD

**Issue by connieprice** [simon-wh/PAYDAY-2-BeardLib#615]
So I did a bit of profiling to identify possible sources of bootup to optimise and discovered that UI alignment increase my boot time from 7.275s to 11.27s.

I feel like spending 3-4 whole seconds on UI alignment is an insane thing to do whilst the game is still booting.

I've narrowed this down to primarily being caused by the auto-alignment system, which causes 1355 more calls to AlignItems to be made.

Auto-Alignment Default On: 1610 AlignItems Calls
Auto-Alignment Default Off: 255 AlignItems Calls

I don't really see how the UI system needs to be making so many aligning-related calls, especially during boot time.

**Comment by connieprice** [comment]
I forgot to add, I am actively looking into ways to reduce this call count, but I thought I'd document it here too.

**Comment by Luffyyy** [comment]
Likely one of the UI elements need it off and just called once at the end of rendering/change

**Comment by connieprice** [comment]
Okay, this seems to be an issue with the BLE UI, I'll move this there.
