### ISSUE TITLE
Crash with VR mode

### ISSUE THREAD

**Issue by leo0215** [simon-wh/PAYDAY-2-BeardLib#623]
**Describe the crash**
A clear and concise description of what the crash is.

vr game version:1.1.1

when I choose heist and hit start button,it just crashed

**To Reproduce**

Open PD2 vr via steamVR
game loaded
choose heist via crime.net
select difficult and hit start
*crash
move any folder with main.xml away from mod and mod_override folder
restart
game loaded
choose heist via crime.net
select difficult and hit start
*still crash
**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/10825646/crash.txt)

Application has crashed: access violation

-------------------------------

Callstack:

                       WSOCK32  (???)     socket                                              
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
      payday2_win32_release_vr  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                        bcrypt  (???)     BCryptResolveProviders                              
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                         d3d11  (???)     CreateDirect3D11SurfaceFromDXGISurface              
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                       close()  @mods/base/req/xaudio/XAudioBuffer.lua:25           
                       Close()  @mods/BeardLib/Classes/Managers/SoundManager.lua:274  
                        func()  @mods/BeardLib/Hooks/OtherHooks.lua:144             
             unload_packages()  @mods/base/req/core/Hooks.lua:269                   
   gather_packages_to_unload()  lib/setups/menusetup.lua:122                        
                  block_exec()  lib/setups/setup.lua:1170                           
                                core/lib/setups/coresetup.lua:637

**Comment by segabl** [comment]
this is an issue with superBLT currently. until it is fixed, use the dll from here: https://ci.appveyor.com/project/ZNix/payday2-superblt/builds/46323903/artifacts
