### ISSUE TITLE
Custom Music can cause a blackscreen when selecting it in Briefing(with optimised load)

### ISSUE THREAD

**Issue by RuntyFlame53268** [simon-wh/PAYDAY-2-BeardLib#626]
When using optimised music load, selecting a custom song in briefing causes the audio preview to load and play like normal, then it unloads when readying/selecting a different tab in briefing forcing it to load the track back in as the heist starts, causing a blackscreen glitch which requires rejoin

I'm using custom music for my menu track as well

**Comment by segabl** [comment]
Are you using the latest BeardLib version? this issue should be super rare now with the recent music changes

**Comment by segabl** [comment]
Closing since if this is still happening with the latest version nothing more can really be done about it except for a change in SuperBLT to actually stream audio.
