### ISSUE TITLE
Beardlib makes my game tab out during loading screens

### ISSUE THREAD

**Issue by ClemOnGH** [simon-wh/PAYDAY-2-BeardLib#627]
**Describe the bug**
For some reason, as long as I have Beardlib loaded and as long as another window is either opened or at least minimized, it'll automatically tab out to the last focused window (Beardlib will focus back on Discord for e.g).

**To Reproduce**
Have at least one other program open/minimized and load any heist/join a lobby.

**Preview with Beardlib:**
https://user-images.githubusercontent.com/64258651/223319018-eeac36c0-8885-4659-972b-8cf1785729cf.mp4

**Preview without Beardlib:**
https://user-images.githubusercontent.com/64258651/223319022-a35295bb-d9bd-4ef0-8cd3-3a03c649f377.mp4

*I also very rarely catch some cmd quickly opening and closing right after it tabs out but it's too quick for me to see what it does or if it's even related to this bug.*

**Comment by segabl** [comment]
Are you using the latest version from GitHub or the GitHub release/MWS version?

**Comment by ClemOnGH** [comment]
I'm using the one that automatically gets updated through SuperBLT, got it from the GitHub release tab though.

**Comment by segabl** [comment]
can you check ingame if github updates for beardlib are enabled? go to beardlib mods and check the settings

**Comment by ClemOnGH** [comment]
It says "Beta GitHub Updates" and it's enabled, should I disable it ?

**Comment by ClemOnGH** [comment]
Welp I don't notice any black screen or other unwanted alt+tab so thanks for the help!
