### ISSUE TITLE
XML parse error

### ISSUE THREAD

**Issue by Foxhie** [simon-wh/PAYDAY-2-BeardLib#629]
Since updating to 4.84, game now consistently crashes with a parse error. I first had used the in-game updater, but after this error I removed the files and manually reinstalled. However, the issue persists. Despite directing me to check the log, it has not generated one on any of my launches. Attached below is an image of the error popup.

![parseerror](https://user-images.githubusercontent.com/127699677/224581196-1c722cd5-a57a-440b-a443-74707542f486.png)

**Comment by Luffyyy** [comment]
Likely caused by #624

**Comment by Foxhie** [comment]
Got it, I will use an earlier version for now

**Comment by Foxhie** [comment]
[2023_03_18_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11009260/2023_03_18_log.txt)

**Comment by segabl** [comment]
Ah looks like some malformed XML in Vanilla Modpack.
The changes in Beardlib have been reverted for now due to too many mods having problematic XML files
