### ISSUE TITLE
Can't see other player models after the update.

### ISSUE THREAD

**Issue by Koipix** [simon-wh/PAYDAY-2-BeardLib#631]
We used to see other player custom models by having the same custom models downloaded and installed with "Legendary Armor Skins " Mod before the latest update but after the update 3 days ago, it doesn't work anymore and can't seem to load other player (tested with my friends) models with this new update. 

Can I have the previous Beardlib version before the latest update while you guys work on this?

Thank you!

**Comment by Hater-mater** [comment]
V4.85 has issues with custom suit variants and custom costumes in general.
Use V4.83 until sync issue is fixed.

https://github.com/simon-wh/PAYDAY-2-BeardLib/archive/refs/tags/4.83.zip

**Comment by Koipix** [comment]
Thank you for the response! Hopefully it'll get fixed soon.

**Comment by segabl** [comment]
If you set BeardLib to update from github in its options, this should hopefully be fixed

**Comment by Koipix** [comment]
Thanks! We just did update through Github and it works fine now.
