### ISSUE TITLE
PlayerStyleVariantModule tries to reference PlayerStyleModule before it's loaded

### ISSUE THREAD

**Issue by SwooshyCueb** [simon-wh/PAYDAY-2-BeardLib#632]
I get the following error in my terminal and log file when I launch the game:
```
10:34:16 PM FATAL ERROR:  (/usr/src/debug/superblt-git/superblt/src/InitiateState.cpp:320) mods/BeardLib/Modules/Addons/PlayerStyleVariantModule.lua:10: attempt to index global 'PlayerStyleModule' (a nil value)
stack traceback:
	mods/BeardLib/Modules/Addons/PlayerStyleVariantModule.lua:10: in main chunk
	[C]: in function 'dofile'
	mods/BeardLib/Core.lua:141: in function 'LoadModules'
	mods/BeardLib/Core.lua:146: in function 'LoadModules'
	mods/BeardLib/Core.lua:47: in function 'Init'
	mods/BeardLib/Core.lua:409: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:177: in function 'RunHookFile'
	mods/base/base.lua:165: in function 'RunHookTable'
	mods/base/base.lua:197: in function 'require'
	[string "core/lib/coreentry.lua"]:14: in main chunk
```

It looks like `PlayerStyleVariantModule.lua` is trying to reference `PlayerStyleModule`
https://github.com/simon-wh/PAYDAY-2-BeardLib/blob/307b42024f68600112a902a170d5fa32eb1e100b/Modules/Addons/PlayerStyleVariantModule.lua#L10
before it is instantiated in `PlayerStyleModule.lua`
https://github.com/simon-wh/PAYDAY-2-BeardLib/blob/307b42024f68600112a902a170d5fa32eb1e100b/Modules/Addons/PlayerStyleModule.lua#L8

I think `BeardLib:LoadModules` is assuming that the tables/arrays returned from `FileIO:GetFiles`/`FileIO:GetFolders` will be in a predictable order, because I tried modifying `FileIO:GetFiles` and `FileIO:GetFolders` to sort the results before returning them, and it fixed the problem.

**Comment by segabl** [comment]
Interesting, module creation and inheritance is definitely made with the expectation that it is executed based on the alphabetical file order. What system are you running on?

**Comment by SwooshyCueb** [comment]
ext4

**Comment by SwooshyCueb** [comment]
Arch Linux, ext4 filesystem

**Comment by segabl** [comment]
ah right, figured it might not return files in order on linux, should be a simple fix
