### ISSUE TITLE
Custom Narratives setup outside of the `Maps` folder do not correctly setup the Lobby.

### ISSUE THREAD

**Issue by connieprice** [simon-wh/PAYDAY-2-BeardLib#635]
Seems to be related to `GetMapByJobId` only existing within `MapFramework` only allowing it to "see" narratives added via the `Map` folder.

**Comment by SOMNUSNOVUS** [comment]
+1 to this issue.  Overhaul mods like Crackdown, HEAT, ResMod, all use this feature, by loading custom narratives (and more) through a submods folder within the mod folder.

Additionally, I use this functionality in the mod seen here: https://modworkshop.net/mod/41851

Would love to see this issue fixed.  Other than this issue, levels loaded in this way function totally fine.

**Comment by segabl** [comment]
What actually IS the issue? Like, what isn't set up correctly?

**Comment by SOMNUSNOVUS** [comment]
Maps loaded from outside the 'maps' folder aren't correctly added to the narratives table in a way where they can be sync'd to other users from the lobby (IE: you can't see people hosting these levels on crimenet, and you're unable to join an active lobby/game if it's on one of these levels).

As said in the initial issue comment, it seems the logic for this only exists within MapFramework, so it doesn't get initialized for maps loaded outside of the 'maps' folder.

**Comment by connieprice** [comment]
> What actually IS the issue? Like, what isn't set up correctly?

Within `Hooks/Network/NetworkMatchmakingSteam.lua` there is a check that relies on `BeardLib.Frameworks.Map:GetMapByJobId`. This check is the gatekeeper for assigning custom narrative information to a lobby.

As this check fails, the `custom_map` flag is never set, causing the receiving end contained within a `_call_callback` hook in the same file to never correctly view this lobby as using a custom heist, because of this and because vanilla just dumps any levels it doesn't recognise, any custom levels defined outside of the Maps folder will never correctly be returned from lobby searches.

**Comment by segabl** [comment]
Ah so it doesn't show custom map lobbies even if the user has them?

**Comment by connieprice** [comment]
> Ah so it doesn't show custom map lobbies even if the user has them?

Specifically for narratives defined in non `Maps` folder mods.

**Comment by SOMNUSNOVUS** [comment]
Checking in.  Crackdown has been released and uses the same submods system as MapAdd, thus none of its levels get added to the narrative table (as stated in above comments), would still like to see this issue addressed.  Thanks!

**Comment by segabl** [comment]
@Luffyyy is this something you checked while working on BeardLib 5?

**Comment by Luffyyy** [comment]
> @Luffyyy is this something you checked while working on BeardLib 5?

I think so. I added the function to some utility class and changed the network code to check that there.

**Comment by Luffyyy** [comment]
BeardLib 5.0 merged the frameworks so this issue should be fixed.
