### ISSUE TITLE
Allow unit swapping for Beardlib player style outfit variants

### ISSUE THREAD

**Issue by Columbsus** [simon-wh/PAYDAY-2-BeardLib#641]
As of right now, it currently is not possible to be able to swap units (models) when swapping between variants. Some mods I've been creating recently exceeds the 65K vertices limit that the model tool can support, And I really would not like to clutter people's outfit inventory with dozens of outfits or characters. Hopefully this is possible within our own limits.

**Comment by connieprice** [comment]
The beardlib outfit logic should already be setup to allow for this. If you're not having success, it could be the case that the functionality has broken.
