### ISSUE TITLE
Game crashes after opening (C++ exception)

### ISSUE THREAD

**Issue by baikalbruh** [simon-wh/PAYDAY-2-BeardLib#644]
I've already tried removing all mods in "mods" and "mod_overrides" (except Beardlib), as well as checking the game files integrity, still crashes after opening the game.
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11413356/crash.txt)

**Comment by segabl** [comment]
Seems like you are using an outdated game version which is not supported by BeardLib
