### ISSUE TITLE
Payday 2 with Super BLT crashes with Beard Lib.

### ISSUE THREAD

**Issue by MegaBR1236** [simon-wh/PAYDAY-2-BeardLib#645]
Hi, firstly apologize me for my bad inglish.
I recently dowloaded payday 2 and installed Super BLT, after that i dowloaded and extracted the Beard Lib mod in the "mod" directory in my payday 2 files. 
The problem is that when i tried to run the game with Beard Lib my game don't launch. I tried both "WSOCK32.dll" and "IPHLPAPI.dll" files from Super BLT and it worked fine in both cases whitout Beard Lib, but the problem arrives again when i install Beard Lib again. 
Note: When i unistall Beard Lib from payday 2 the game works fine.
I hope that someone can help me with a solution, i would be very pleased.
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11413732/crash.txt)

**Comment by segabl** [comment]
See #644
