### ISSUE TITLE
Third Person Sound bug

### ISSUE THREAD

**Issue by Gandalf360one** [simon-wh/PAYDAY-2-BeardLib#648]
**Describe the bug**
I want to replace some sounds via BeardLib. My Problem is that the sound works perfect in first person but in third person (when someone shoot f.e.) I can hear the sound anywhere no matter how far I m away from that player. The volume will always stay the same.
Also tried to add parameters like "volume", "min_distance" and "max_distance" but they only work for first person.

**To Reproduce**
1. replacing a third person sound (chimano 88 f.e. "g17_npc1a_1shot").
2. getting a person to test.
3. telling the person to shoot when the person with the sound replacement is away from the helper person in different distances.

Mod:
https://www.dropbox.com/s/5smln7g27ulwqfq/Hawks%20Soundpack%20Reborn.zip?dl=0
Replaced the chimano 88 pistol shooting sound as an example

**Comment by segabl** [comment]
can you attach your mod so I can test this? I'm having no issues with another sound mod that does something similar

**Comment by Gandalf360one** [comment]
updated

**Comment by segabl** [comment]
Opening the sound in audacity shows me it is in stereo:
![](https://github.com/simon-wh/PAYDAY-2-BeardLib/assets/4538631/d140ce0a-d167-4aa0-a83e-1667f48656dd)

This is what it should look like:
![](https://github.com/simon-wh/PAYDAY-2-BeardLib/assets/4538631/9e15baf6-3365-448b-9407-ab1bb3015bde)

That can be achieved in Audacity by going to Tracks > Mix > Mix Stereo Down to Mono

**Comment by Gandalf360one** [comment]
ok thx for your help and sorry for wasteing your time.
tried it once with converting it to mono but seems like it didnt worked.
Worked this time perfectly great support thx!
