### ISSUE TITLE
No (Map) Fire Damage

### ISSUE THREAD

**Issue by Neko14789** [simon-wh/PAYDAY-2-BeardLib#649]
**Describe the bug**
When having BeardLib installed I don't get any fire damage, possibly also no tear gas damage

**To Reproduce**
Install BeardLib.
Go into Mallcrasher Heist and buy the Gas Can asset
Collect and place Gas Can
Stand in the fire
Observe if you are taking damage

**Comment by segabl** [comment]
Can not reproduce this, what version of BeardLib are you using?

**Comment by Neko14789** [comment]
I am sorry, it seems like I was using an outdated version somehow (4.8). Somehow, my game did not update the BeardLib mod. Manually downloading it again fixed it. Sorry for wasting time :(

**Comment by Neko14789** [comment]
Does BeardLib not auto update itself?

**Comment by segabl** [comment]
the update links changed at some point which required a manual update once, but should be fine now if you have the latest version.
