### ISSUE TITLE
Crash On Start Up

### ISSUE THREAD

**Issue by TOXICxSTRIKE** [simon-wh/PAYDAY-2-BeardLib#65]
When ever beardlib is installed it crashes my game plz help!!!

Application has crashed: C++ exception
mods/base/req/json-0.9.lua:372: Unexpected character at Line 1 character 1: 

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                      ucrtbase  (???)     o__mktime64                                         
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : AMD FirePro M4000 / aticfx32.dll[8.17.10.1404]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16315MB 504KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by Luffyyy** [comment]
Some beardlib mod has a bad json file find it and remove it(probably in mod overrides)

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
