### ISSUE TITLE
Game crashes when I attempt to launch

### ISSUE THREAD

**Issue by captinwill** [simon-wh/PAYDAY-2-BeardLib#653]
**Describe the crash**
Game crashes when I attempt to launch

**To Reproduce**
1.Install newest development version of superblt
2.install Beardlib
3.See crash

**Crashlog**

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11701555/crash.txt)

**Comment by segabl** [comment]
Fixed in 43b2609f24388162064a5d84a58ab5f778bf56de though there might be other issues
