### ISSUE TITLE
FileManager crash on _LoadAsset

### ISSUE THREAD

**Issue by rockymoto517** [simon-wh/PAYDAY-2-BeardLib#654]
**Describe the crash**
Seems like an issue with loading packages, specifically this line of code in dynamicresourcemanager.lua in test1's lua decomp

`PackageManager:package(package_name):load_temp_resource(resource_type, resource_name, complete_clbk and callback(self, DynamicResourceManager, "clbk_resource_loaded") or nil, true)`

I copied the function into a mod to find the specific line, so the mod appears on the top of script stack, else it would just show lib/managers/dynamicresourcemanager.lua on top

**To Reproduce**
Try to load a map with BeardLib

**Crashlog**
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11703148/crash.txt)

**Comment by segabl** [comment]
looks to be an incorrect signature in superblt still, in the meantime load from db has been disabled for the general assets beardlib loads to prevent this

**Comment by segabl** [comment]
This is fixed in the most recent version of SuperBLT
