### ISSUE TITLE
Game crash on startup

### ISSUE THREAD

**Issue by Luluita** [simon-wh/PAYDAY-2-BeardLib#656]
**Describe the crash**
I want to launch payday 2 with superblt and beardlib but it always crashes on the start up i get to where the game is loading and it closes when i played payday 2 like in 2 years ago i could use beardlib and superblt but i dont know why it doesnt work now

**To Reproduce**
Steps to reproduce the behavior: wanna launch the game but it crashes on the startup (if i dont have beardlib i can play the game)

**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11705101/crash.txt)
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11705102/crashlog.txt)

**Comment by segabl** [comment]
please download the latest beardlib from github, (click the code button on the main page of this repository)

**Comment by Luluita** [comment]
oh ty it works now

**Comment by thelostsaint-yt** [comment]
@Luluita  what all did you do cause i reinstalled the newest verison of superblt and beardlib and im still getting that same crash. i cleaned my mod list out, redownloaded it but im still getting the same crashlog you got 
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11705425/crash.txt)

**Comment by segabl** [comment]
https://github.com/simon-wh/PAYDAY-2-BeardLib/releases/tag/4.86
