### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by PotatKing** [simon-wh/PAYDAY-2-BeardLib#657]
**Describe the crash**
A clear and concise description of what the crash is.
When starting the game, it displays the loading icon in the topleft and then just crashes. 

**To Reproduce**
 I only have BeardLib and SuperBLT, mod overrides is also completly empty.

**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11705754/crash.txt)
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11705755/crashlog.txt)

**Comment by segabl** [comment]
See https://github.com/simon-wh/PAYDAY-2-BeardLib/issues/656
