### ISSUE TITLE
Game carshes on startup Epic Games Version

### ISSUE THREAD

**Issue by SiriusArtz** [simon-wh/PAYDAY-2-BeardLib#658]
Game crashes up on startup I installed the latest version of SuperBLT and Beardlib but its keep crashing

**Comment by segabl** [comment]
Check https://github.com/simon-wh/PAYDAY-2-BeardLib/issues/656, if it still happens attach crash.txt

**Comment by Fancy2209** [comment]
I also have this issue, it seems there is some steam specific stuff on the AchivementManager portion of BeardLib who does not work with EGS
[2023_06_09_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11706118/2023_06_09_log.txt)

**Comment by SiriusArtz** [comment]
> Collaborator

Application has crashed: C++ exception
mods/PAYDAY-2-BeardLib-master/Hooks/CoreSystem.lua:81: attempt to index field 'File' (a nil value)



SCRIPT STACK

get_texture_path() lib/tweak_data/achievementstweakdata.lua:64
init() lib/tweak_data/achievementstweakdata.lua:3068
new() core/lib/utils/coreclass.lua:35
init() lib/tweak_data/tweakdata.lua:618
new() core/lib/utils/coreclass.lua:35
lib/tweak_data/tweakdata.lua:3594
require() =[C]
OrigRequire() @mods/base/base.lua:196
require() @mods/PAYDAY-2-BeardLib-master/Core.lua:406
lib/setups/setup.lua:40
require() =[C]
OrigRequire() @mods/base/base.lua:196
require() @mods/PAYDAY-2-BeardLib-master/Core.lua:406
lib/setups/menusetup.lua:1
require() =[C]
OrigRequire() @mods/base/base.lua:196
require() @mods/PAYDAY-2-BeardLib-master/Core.lua:406
lib/entry.lua:13
require() =[C]
OrigRequire() @mods/base/base.lua:196
require() @mods/PAYDAY-2-BeardLib-master/Core.lua:406
core/lib/coreentry.lua:19


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        


-------------------------------

Current thread: Main
Script stack:
            get_texture_path()  lib/tweak_data/achievementstweakdata.lua:64         
                        init()  lib/tweak_data/achievementstweakdata.lua:3068       
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  lib/tweak_data/tweakdata.lua:618                    
                         new()  core/lib/utils/coreclass.lua:35                     
                                lib/tweak_data/tweakdata.lua:3594                   
                     require()                                                      
                          =[C]  OrigRequire()                                       
                                @mods/base/base.lua:196                             
                     require()                                                      
@mods/PAYDAY-2-BeardLib-master/Core.lua:406  lib/setups/setup.lua:40                             
                     require()  =[C]                                                
                 OrigRequire()  @mods/base/base.lua:196                             
                     require()  @mods/PAYDAY-2-BeardLib-master/Core.lua:406         
                                lib/setups/menusetup.lua:1                          
                     require()                                                      
                          =[C]  OrigRequire()                                       
                                @mods/base/base.lua:196                             
                     require()                                                      
@mods/PAYDAY-2-BeardLib-master/Core.lua:406  lib/entry.lua:13                                    
                     require()  =[C]                                                
                 OrigRequire()  @mods/base/base.lua:196                             
                     require()  @mods/PAYDAY-2-BeardLib-master/Core.lua:406         
                                core/lib/coreentry.lua:19                           

-------------------------------

System information:
	Application version : 1.139.193
	CPU : Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 930MX / nvldumd.dll[31.0.15.1669]
	Language : english
	Memory :     8083MB 212KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Hoparlör (USB PnP Audio Device))

**Comment by SiriusArtz** [comment]
keeps crashing

**Comment by segabl** [comment]
use the version attached here https://github.com/simon-wh/PAYDAY-2-BeardLib/releases/tag/4.86
dont update in game as it will download an outdated version
