### ISSUE TITLE
Steam Payday 2 Crashes after new update

### ISSUE THREAD

**Issue by Filichh** [simon-wh/PAYDAY-2-BeardLib#659]
**Describe the crash**
Beardlib crashes Payday 2 after the new steam update

**To Reproduce**
Update to the latest version on steam and add Beardlib mod

**Crashlog**

[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11706349/crash.txt)
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11706350/crashlog.txt)

**Comment by segabl** [comment]
make sure to manually update superblt and beardlib

**Comment by Filichh** [comment]
I updated SuperBLT to 3.3.8 and Beardlib to 4.76 and now it works fine
thanks
