### ISSUE TITLE
Payday 2 keeps crashing even after updating manually - Epic Games

### ISSUE THREAD

**Issue by TooruV** [simon-wh/PAYDAY-2-BeardLib#660]
**Describe the crash**
A clear and concise description of what the crash is.

**To Reproduce**

**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11707120/crash.txt)
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11707122/crashlog.txt)

**Comment by segabl** [comment]
There's an issue with BeardLib's achievement system on EGS currently that we are looking into

**Comment by segabl** [comment]
Could you also attach a fresh (delete the existing on, then start the game) BLT log please? you can find it in mods/logs

**Comment by DoctorKoKoDaYo** [comment]
> 您能否也附上一个新的（删除现有的，然后开始游戏）BLT日志？你可以在模组/日志中找到它

If you don't mind I'd like to give my logs(same crashing promblem)
[2023_06_09_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11707383/2023_06_09_log.txt)

**Comment by segabl** [comment]
[BeardLib.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11707671/BeardLib.zip)
can you see if this custom version fixes the issues?

**Comment by TooruV** [comment]
> [BeardLib.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11707671/BeardLib.zip) can you see if this custom version fixes the issues?

Yes, it's worked, the game starts normally, and asked to update Beardlib, but when I restarted, it didn't ask anymore...

Here the log if you want: 
[2023_06_09_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11707767/2023_06_09_log.txt)

**Comment by segabl** [comment]
use the attached beardlib zip here https://github.com/simon-wh/PAYDAY-2-BeardLib/releases/tag/4.86
dont update the mod ingame if it prompts you to, as it will download an old version
