### ISSUE TITLE
Mod kills itself when updating trough ingame

### ISSUE THREAD

**Issue by IRetr-0** [simon-wh/PAYDAY-2-BeardLib#662]
**Describe the crash**
Hard crash to desktop on game launch

**To Reproduce**
Install the latest release manually. Open the game. Update the mod trough the in game prompt. Close and reopen the game.

**Crashlog**
Application has crashed: C++ exception
mods/BeardLib/Hooks/Fixes.lua:688: attempt to index field 'network' (a nil value)

SCRIPT STACK

set_rich_presence() @mods/base/req/core/Hooks.lua:272
_set_presences() lib/network/matchmaking/networkaccountsteam.lua:80
init() lib/network/matchmaking/networkaccountsteam.lua:58
new() core/lib/utils/coreclass.lua:35
init() lib/network/base/networkmanager.lua:95
new() core/lib/utils/coreclass.lua:35
init_managers() lib/setups/menusetup.lua:304
core/lib/setups/coresetup.lua:401

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.139.195
	CPU : Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (5 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3080 / nvldumd.dll[31.0.15.3179]
	Language : english
	Memory :     32669MB 912KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (3- I'm Fulla Schiit))

My guess... it's getting the old version trough the GUI.

**Comment by Sraguv** [comment]
Replace **BeardLib** folder in the **mods** folder with this one:
[BeardLib.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11710741/BeardLib.zip)

**Comment by MiskiMiko** [comment]
Getting the same, tried using the zip file and still crashed before even reaching the opening cinematic

SCRIPT STACK

Call() @mods/base/req/core/Hooks.lua:86
func() @mods/base/lua/MenuManager.lua:5
init() @mods/base/req/core/Hooks.lua:272
new() core/lib/utils/coreclass.lua:35
init_managers_original() lib/setups/setup.lua:410
init_managers() @mods/VanillaHUD Plus/lua/WaypointsManager.lua:93
init_managers() lib/setups/menusetup.lua:294
core/lib/setups/coresetup.lua:401


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.139.195
	CPU : 12th Gen Intel(R) Core(TM) i5-12400F (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3060 Ti / nvldumd.dll[31.0.15.3118]
	Language : english
	Memory :     32616MB 216KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (USBFC1S-RGB))

**Comment by segabl** [comment]
Make sure to remove old beardlib versions, and od not update Beardlib ingame when it prompts you to as that will revert it to an old version

**Comment by MiskiMiko** [comment]
I tried that, using any mods still crashes it

**Comment by tillieho** [comment]
> Replace **BeardLib** folder in the **mods** folder with this one: [BeardLib.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11710741/BeardLib.zip)

What is actually changed in this one: 
BeardLib\Hooks\Fixes.lua - line 671-681 just removed. This one is rich presence, that cause crashing. I just removed it and it works!

**Comment by MiskiMiko** [comment]
Works up until loading into a heist before crashing. Tried removing those lines, updating through in-game.

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        


-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:236  
                   LoadAsset()  @mods/BeardLib/Classes/Managers/FileManager.lua:258  
             safe_spawn_unit()  @mods/BeardLib/Hooks/CoreSystem.lua:26              
        _create_statics_unit()  core/lib/utils/dev/editor/coreworlddefinition.lua:921  
                      create()  core/lib/utils/dev/editor/coreworlddefinition.lua:522  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:730                        
                                core/lib/setups/coresetup.lua:424                   

-------------------------------

System information:
	Application version : 1.139.195
	CPU : 12th Gen Intel(R) Core(TM) i5-12400F (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3060 Ti / nvldumd.dll[31.0.15.3118]
	Language : english
	Memory :     32616MB 216KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (USBFC1S-RGB))
This is crash log from just adding the file above but not updating or snipping code

**Comment by segabl** [comment]
Seems like your SuperBLT might not be up to date

**Comment by segabl** [comment]
This was caused by old BeardLib and SuperBLT versions after the Epic matchmaking update, both mods have been updated and are confirmed working.
