### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Copium4me** [simon-wh/PAYDAY-2-BeardLib#663]
**Describe the crash**
A clear and concise description of what the crash is.
I launch the game with nothing but beardlib in the modfolder and it crashes shortly thereafter
**To Reproduce**

**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11712797/crashlog.txt)

**Comment by Requlem** [comment]
This happened to me as well, the main issue for me was in Beardlibs/Classes/Managers and the Achievement manager is linked to steam however if you have it on epic games it doesn't work, if you delete it it should work fine, achievements might be buggy though.

**Comment by Requlem** [comment]
If anybody knows how to edit Achievement Manager LUA to work with epic instead of steam that would be fantastic

**Comment by E-Gulbis** [comment]
I have found a couple of issues that have plagued my PC.
Attached a log file straight from a recent run of PAYDAY 2.
[2023_06_10_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/11712975/2023_06_10_log.txt)

**Comment by Copium4me** [comment]
I have Payday 2 on steam :/

**Comment by E-Gulbis** [comment]
> I have Payday 2 on steam :/

Just like a huge majority of players.

**Comment by Copium4me** [comment]
yup. meant to quote the other guy, but I guess I forgot

**Comment by tillieho** [comment]
BeardLib\Hooks\Fixes.lua - line 671-681 just remove. This one is rich presence, that cause crashing and I don't think it's super important. I just removed it and it works!

**Comment by segabl** [comment]
Download the BeardLib.zip from the latest release on github and dont update via the ingame updater

**Comment by Copium4me** [comment]
I'm very sorry if I'm just being dumb, but I can't seem to find the Beardlib.zip download thingy. I try to go to modworkshop, but the site is down at least for me
