### ISSUE TITLE
Beardlib Corrupts on Ingame Update Attempt

### ISSUE THREAD

**Issue by Comradebass** [simon-wh/PAYDAY-2-BeardLib#664]
+ Platform:

Steam

+ Describe the crash:

Game flags all mods for update, including Beardlib. Upon attempting in-game update, game crashes mid-update and fails to re-launch

+ To Reproduce:

Grab the latest release from the Git Repository. Install the latest release manually. Open the game. Update the mod through the in-game prompt.

==============================================================================
Comment's:

I would love to attach a crash log, but I sadly don't know where it would be located. I also find it odd the bug is flagging ALL my Beardlib mods as needing a update not just BeardLib itself. Could possible be related to the modworkshop errors going on, though that might just be on my end.

**Comment by CaxTheA1** [comment]
crashlog.txt is in local appdata, if you're in windows press win+R and enter appdata then go to local,look for PAYDAY2 and you will see crash.txt and Crashlog.txt,the recent crashes are in the last lines of the log

**Comment by CaxTheA1** [comment]
A solution that i found is to download the last release from here and DONT uptade the beardlib using itself or uptade any other mod,the owner could make the mod uptade using github only,i just check the core.lua and here i can see the problem,it's the modworkshop

**Comment by segabl** [comment]
Yes, since modworkshop is currently down, updating via ingame menu will break BeardLib. As mentioned on the latest release, do not use the ingame updater for now, or switch to updating from github in the BeardLib settings.

**Comment by Comradebass** [comment]
Ah, sorry for the late reply. Timezones eh. Ok, so its a modworkshop issue that's causing the latest git repository to flag itself as needing a update.... then when you update it ingame it crashes. So I should ignore the update warning ingame... thank you for the advice

**Comment by segabl** [comment]
> Ah, sorry for the late reply. Timezones eh. Ok, so its a modworkshop issue that's causing the latest git repository to flag itself as needing a update.... then when you update it ingame it crashes. So I should ignore the update warning ingame... thank you for the advice

yes, you can also go to the beardlib settings and enable updates from github to get rid of the update warning and to keep up to date independently of mws

**Comment by Comradebass** [comment]
Perfect, this fixed my issue. I do hope whatever is causing the modworkshop issues is resolved, but this alleviates the annoying update pop-up flashing every time I enter the main menu.
