### ISSUE TITLE
Using HoloUI Turns my menu screen Grey when I use BeardLib.

### ISSUE THREAD

**Issue by thenatedog** [simon-wh/PAYDAY-2-BeardLib#67]
I confirmed this by removing it from my Mods folder and starting the game without it. But if this is an intended effect and I didn't read some paper then punch me through the screen.

**Comment by Luffyyy** [comment]
HoloUI has a grey background as a feature, you can either change the color or disable colored background in HoloUI's options, BeardLib is a library which HoloUI uses so by removing it you disable the mod.

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
