### ISSUE TITLE
Crash Murkywater

### ISSUE THREAD

**Issue by LMauc** [simon-wh/PAYDAY-2-BeardLib#677]
**Describe the crash**
Hello, I've been playing, and it seems that the mods that require beardlib with murkywater end up crashing, in "Hell's Island" it crashes almost instantly when entering the game, the truth is that this didn't happen before, and I still have the same mods , in "The White House", well if the lobby loads you I must say thanks

By the way, I tried to reduce textures and shadows and it didn't work, all the maps work perfectly, except for the hijacking maps, the san martin bank regularly crashes in hijacking, but in normal this doesn't happen.

Another thing to mention is that the mods I tried do not have a file in common to cause any problem.

**To Reproduce**
entering a map with murkywater, the ones I mentioned above are guaranteed to crash

**Comment by LMauc** [comment]
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/12051775/crash.txt)

**Comment by segabl** [comment]
Sorry for the late response, what do you mean by
> all the maps work perfectly, except for the hijacking maps
?

**Comment by LMauc** [comment]
this gamemode

![gamemode](https://github.com/simon-wh/PAYDAY-2-BeardLib/assets/33334792/73f77a24-6e75-49d1-8165-8dd88492f5ed)

**Comment by LMauc** [comment]
I update the crash.log in version 239.2
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/12373270/crash.txt)

**Comment by LMauc** [comment]
I update the crash.log in version 240
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/12600046/crash.txt)

**Comment by segabl** [comment]
you should check your mods, this is probably caused by one or more mods that modify murkywater enemy models

**Comment by LMauc** [comment]
I just checked and yes, it had a mod that changed Murkywater's styles, however what seemed strange to me is that when I published this post I had tried deleting that mod and the game still crashed, I will close the issue
