### ISSUE TITLE
crash when someone joins (most likely)

### ISSUE THREAD

**Issue by Berk-Rider** [simon-wh/PAYDAY-2-BeardLib#678]
**Describe the crash**
this has been happening a lot lately, whenever someone joins there's a chance that the game crashes and the log says it's beardlib's fault

**To Reproduce**
randomly when someone joins

**Crashlog**
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
             NetworkPeerSend()  lib/network/base/networkpeer.lua:1101               
                        send()  @mods/BeardLib/Hooks/Network/NetworkPeer.lua:109    
                _flush_queue()  lib/network/base/networkpeer.lua:1270               
       _chk_flush_msg_queues()  lib/network/base/networkpeer.lua:1175               
                 set_synched()  lib/network/base/networkpeer.lua:996                
                                lib/network/base/hostnetworksession.lua:252

**Comment by Luffyyy** [comment]
BeardLib in logs not necessarily means it's BeardLib's fault.
