### ISSUE TITLE
Crash after new OVK Hotfix 04.08.17

### ISSUE THREAD

**Issue by xHCx47** [simon-wh/PAYDAY-2-BeardLib#68]
Hi,

the game crashes when I use BeardLib in combination with custom weapons. The error code from the crashlog is:

Application has crashed: C++ exception
[string "lib/managers/weaponfactorymanager.lua"]:54: table index is nil

The game loads all custom weapons in mod_overrides and then crashes after the last one. Removing BeardLib doesnt fix it, but removing the mod_overrides folder and deleting the savegame does.

**Comment by Luffyyy** [comment]
I can't do anything you have to find which mod does it specifically only then I can say if it's the mod or beardlib. 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
