### ISSUE TITLE
Online matchmaking doesn't work with BeardLib installed

### ISSUE THREAD

**Issue by SarinOxTg** [simon-wh/PAYDAY-2-BeardLib#681]
When i play with Beardlib installed - i cannot join in any game because host is marked as "joining" permanently. If i am host - nobody can join because i'm marked as "joining".

**To Reproduce**
Install Beardlib itself without any mods working on Beardlib.

**Comment by segabl** [comment]
Can not reproduce, are you using epic or Steam?

**Comment by SarinOxTg** [comment]
> 
Steam version

**Comment by segabl** [comment]
can you try putting `-steamMM` in your game launch options and see if that changes anything?

**Comment by SarinOxTg** [comment]
somehow it does now, earlier it didn't work as intended
