### ISSUE TITLE
Beardlib Not Working

### ISSUE THREAD

**Issue by Alexykiller951** [simon-wh/PAYDAY-2-BeardLib#684]
I have the latest version of SuperBLT installed and it works fine, but Beardlib says: Beardlib is out of date install Beardlib on the latest version of SuperBLT to work.
But the funny thing is that I have the latest version of SuperBLT and Beardlib, what does this have to do with it?

Screen
![изображение_2023-07-28_202741491](https://github.com/simon-wh/PAYDAY-2-BeardLib/assets/140842905/ef121bb8-6b53-4fcb-b02f-65e898018843)

**Comment by segabl** [comment]
This looks like you are using an old version of the BLT basemod, since this check does not exist in newer versions anymore. If you have already downloaded the latest DLL, just delete the "base" folder from mods and it will download the most recent version on game start.

**Comment by Alexykiller951** [comment]
Helped! Very Thanks!
