### ISSUE TITLE
This causes me to crash when loading into a lobby or on the next day of a heist

### ISSUE THREAD

**Issue by crazyboris06** [simon-wh/PAYDAY-2-BeardLib#685]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main
Script stack:
WorldDefinition_load_continent_package()  core/lib/utils/dev/editor/coreworlddefinition.lua:184  
WorldDefinition_load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:93  
     _load_continent_package()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:93  
            parse_continents()  core/lib/utils/dev/editor/coreworlddefinition.lua:263  
        WorldDefinition_init()  core/lib/utils/dev/editor/coreworlddefinition.lua:44  
        WorldDefinition_init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  @mods/BeardLib/Hooks/World/CoreWorldDefinition.lua:10  
                        init()  lib/utils/dev/editor/worlddefinition.lua:6          
                         new()  core/lib/utils/coreclass.lua:35                     
                        init()  core/lib/utils/dev/editor/worldholder.lua:49        
                         new()  core/lib/utils/coreclass.lua:35                     
                   init_game()  lib/setups/gamesetup.lua:730                        
                                core/lib/setups/coresetup.lua:424

**Comment by SamuraiBUPT** [comment]
I've met the same problem, after upgrading to the latest BeardLib and start the game. The first game is OK, but when switching to `the next day` or start another heist, the program got crashed.

Here is my crash logs:

```
Application has crashed: C++ exception
[File] Cannot read from file "E:\SteamLibrary\steamapps\common\PAYDAY 2\assets\all_21.bundle" => error code 998: 内存位置访问无效。 (d:\jenkins\shared-workspace\diesel\engine\dieselx\dieselx\blobs\../utility/Archive.cpp:2482)

SCRIPT_STACK

change_material_config() lib/managers/dynamicresourcemanager.lua:230
activate_callback() core/lib/managers/coresequencemanager.lua:4769
activate() core/lib/managers/coresequencemanager.lua:2023
activate_callback() core/lib/managers/coresequencemanager.lua:2820
activate() core/lib/managers/coresequencemanager.lua:2023
run_sequence() core/lib/managers/coresequencemanager.lua:2484
run_sequence() core/lib/units/coreunitdamage.lua:1224
run_sequence_simple3() core/lib/units/coreunitdamage.lua:1220
run_sequence_simple2() core/lib/units/coreunitdamage.lua:1216
run_sequence_simple() core/lib/units/coreunitdamage.lua:1212
run_sequence_safe() lib/managers/criminalsmanager.lua:514
set_character_visual_state() lib/managers/criminalsmanager.lua:561
original() lib/managers/criminalsmanager.lua:444
update_character_visual_state() @mods/base/req/core/Hooks.lua:264
_pre_beardlib_update_character_visual_state() lib/network/base/networkpeer.lua:2494
update_character_visual_state() @mods/BeardLib/Hooks/PlayerStyleGloveHooks.lua:1445
set_unit() lib/network/base/networkpeer.lua:2458
spawn_unit() lib/network/base/networkpeer.lua:2336
spawn_players() lib/network/base/basenetworksession.lua:1511
update() lib/states/ingamewaitingforplayers.lua:310
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
original() lib/setups/setup.lua:928
update() @mods/base/req/core/Hooks.lua:264
original() lib/setups/gamesetup.lua:804
update() @mods/base/req/core/Hooks.lua:264
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:559



-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        


-------------------------------

Current thread: Main
Script stack:
      change_material_config()  lib/managers/dynamicresourcemanager.lua:230         
           activate_callback()  core/lib/managers/coresequencemanager.lua:4769      
                    activate()  core/lib/managers/coresequencemanager.lua:2023      
           activate_callback()  core/lib/managers/coresequencemanager.lua:2820      
                    activate()  core/lib/managers/coresequencemanager.lua:2023      
                run_sequence()  core/lib/managers/coresequencemanager.lua:2484      
                run_sequence()  core/lib/units/coreunitdamage.lua:1224              
        run_sequence_simple3()  core/lib/units/coreunitdamage.lua:1220              
        run_sequence_simple2()  core/lib/units/coreunitdamage.lua:1216              
         run_sequence_simple()  core/lib/units/coreunitdamage.lua:1212              
           run_sequence_safe()  lib/managers/criminalsmanager.lua:514               
  set_character_visual_state()  lib/managers/criminalsmanager.lua:561               
                    original()  lib/managers/criminalsmanager.lua:444               
update_character_visual_state()  @mods/base/req/core/Hooks.lua:264                   
_pre_beardlib_update_character_visual_state()  lib/network/base/networkpeer.lua:2494               
update_character_visual_state()  @mods/BeardLib/Hooks/PlayerStyleGloveHooks.lua:1445  
                    set_unit()  lib/network/base/networkpeer.lua:2458               
                  spawn_unit()  lib/network/base/networkpeer.lua:2336               
               spawn_players()  lib/network/base/basenetworksession.lua:1511        
                      update()  lib/states/ingamewaitingforplayers.lua:310          
                      update()  core/lib/utils/game_state_machine/coregamestatemachine.lua:92  
                    original()  lib/setups/setup.lua:928                            
                      update()  @mods/base/req/core/Hooks.lua:264                   
                    original()  lib/setups/gamesetup.lua:804                        
                      update()  @mods/base/req/core/Hooks.lua:264                   
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:559                   

-------------------------------

System information:
	Application version : 1.141.213
	CPU : 13th Gen Intel(R) Core(TM) i7-13700H (10 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 4070 Laptop GPU / nvldumd.dll[31.0.15.3598]
	Language : schinese
	Memory :     16084MB 980KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (鎵０鍣?(Realtek(R) Audio))
```

**Comment by segabl** [comment]
This looks like there is some issue with a mod that adds/changes assets in the game

**Comment by crazyboris06** [comment]
> This looks like there is some issue with a mod that adds/changes assets in the game
any ideas on what mods (more specifically) that cause this?

**Comment by segabl** [comment]
I'm afraid not, you'll have to check what mods you installed that change models/textures or similar
