### ISSUE TITLE
crashes when loading a heist

### ISSUE THREAD

**Issue by crazyboris06** [simon-wh/PAYDAY-2-BeardLib#686]
Application has crashed: C++ exception
bad allocation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     zip_error_code_system                               
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main
Script stack:
                        load()  @mods/BeardLib/Hooks/CoreSystem.lua:99              
               load_packages()  lib/setups/gamesetup.lua:473                        
                                core/lib/setups/coresetup.lua:325

**Comment by Luffyyy** [comment]
BeardLib in the logs doesn't necessarily mean it is caused by it. You need to test with and without BeardLib (latest version) if the issue persists only when BeardLib is installed then we can reopen the issue.
