### ISSUE TITLE
Crash on custom heist restart if custom voice line is playing

### ISSUE THREAD

**Issue by Croqui42** [simon-wh/PAYDAY-2-BeardLib#689]
**Describe the crash**
Crash on custom heist restart if custom voice line is playing

**To Reproduce**
Restart custom heist while a custom voice line is playing

**Crashlog**
Application has crashed: C++ exception
mods/base/req/xaudio/XAudioBuffer.lua:21: XAudio Error at C:\projects\payday2-superblt\src\xaudio\XABuffer.cpp:97 : alErr : 40964

SCRIPT STACK

close() @mods/base/req/xaudio/XAudioBuffer.lua:21
Close() @mods/BeardLib/Classes/Managers/SoundManager.lua:283
func() @mods/BeardLib/Hooks/OtherHooks.lua:144
unload_packages() @mods/base/req/core/Hooks.lua:272
gather_packages_to_unload() lib/setups/gamesetup.lua:562
block_exec() lib/setups/setup.lua:1182
core/lib/setups/coresetup.lua:637

**Comment by Luffyyy** [comment]
Sorry for the delay, but I am not sure if this is relating to BeardLib or SBLT. Does it happen consistently with any audio?

**Comment by Croqui42** [comment]
Sure, it does happen in multiple one ,as long it seems to be using "Dialogue" element with .ogg file
- tested on both "Botched Bank" and "Fuel" (https://modworkshop.net/mod/40787 & https://modworkshop.net/mod/43544)
- restart on the mdidle of the voiceline palying
- crash as expected

Application has crashed: C++ exception
mods/base/req/xaudio/XAudioBuffer.lua:21: XAudio Error at C:\projects\payday2-superblt\src\xaudio\XABuffer.cpp:97 : alErr : 40964

SCRIPT STACK

close() @mods/base/req/xaudio/XAudioBuffer.lua:21
Close() @mods/BeardLib/Classes/Managers/SoundManager.lua:283
func() @mods/BeardLib/Hooks/GeneralHooks.lua:29
unload_packages() @mods/base/req/core/Hooks.lua:268
gather_packages_to_unload() lib/setups/gamesetup.lua:560
block_exec() lib/setups/setup.lua:1195
core/lib/setups/coresetup.lua:637

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath

**Comment by Croqui42** [comment]
i sohuld maybe add that you can interrupt older "custom sound" element playing .movie can be restarted nin hte middle without crash.

**Comment by Luffyyy** [comment]
I think it was happening due to xaudio sources using the buffer that we tried to unload forcibly so the solution is to first close them and then the buffers.
