### ISSUE TITLE
My Beardlib won't show contracts on crim.net Online what's happening no crashes though

### ISSUE THREAD

**Issue by Randomgamer11** [simon-wh/PAYDAY-2-BeardLib#69]

**Comment by Luffyyy** [comment]
Can you send your BLT log?

**Comment by Randomgamer11** [comment]
where can i find my blt log?

**Comment by Luffyyy** [comment]
mods/logs and today's/the issue's date.

**Comment by Randomgamer11** [comment]
[2017_08_06_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1203122/2017_08_06_log.txt)

**Comment by Luffyyy** [comment]
Well nothing is wrong in there that much, are you even sure that BeardLib causes it? have you checked any BeardLib mod that might be causing it? anything from custom weapons and maps? any other BLT mod?

**Comment by MasterJPixel** [comment]
I looked through the log. It looks like a problem with Silent Assassin or WolfHUD.
(I personally use Silent Assassin and it works fine, so probably WolfHUD's fault.)

**Comment by Luffyyy** [comment]
I'd recommend not using silent assassin
