### ISSUE TITLE
Too many decimals in the options menu

### ISSUE THREAD

**Issue by LT71** [simon-wh/PAYDAY-2-BeardLib#693]
**Too many decimals in the Beardlib-generated options menu**
I have noticed that recently the number options are showing too many decimals in the menu.
Instead of displaying 1 as 1, it displays it as 1.00000 and if it's intended is there any way to have it show fewer or no decimals at all?

**To Reproduce**
Make a number option for a mod and enter the options menu for it.

**Comment by segabl** [comment]
The `floats` paramter of a slider or textbox can be used to define the amount of decimal places (https://luffyyy.gitbook.io/beardlib/menuui/menuui-textbox)

**Comment by LT71** [comment]
I see, is there also a way to make this work for the menu created through XML? 
I have looked at the [wiki](https://luffyyy.gitbook.io/beardlib/modules/optionmodule
) and it doesn't seem to have a way to change the decimal value.

This is how the option looks like at the moment, I tried to see if floats would do anything but it doesn't at the moment. 
< option type="number" min="0" max="1" step="0.5" show_value="true" default_value="1" name="NumberOption"/>

**Comment by segabl** [comment]
Ah I see, for the options menu the parameter to change is `decimal_count` as it is a separate system from MenuUI

**Comment by LT71** [comment]
Okay, I didn't know about the other menu setup but adding this worked perfectly so I will close this as it's a lack of knowledge on my part.
