### ISSUE TITLE
Bank heist doesnt work

### ISSUE THREAD

**Issue by birbinabowtie** [simon-wh/PAYDAY-2-BeardLib#694]
if i have beardlib installed and try the bank heist it freezes this is a new problem and i have been using this for a year or two

**Comment by birbinabowtie** [comment]
i have also tried just having beardlb and superblt but no jazz

**Comment by segabl** [comment]
can you provide the log from mods/logs when this happens

**Comment by birbinabowtie** [comment]
how do i do that

**Comment by segabl** [comment]
just delete the log files in mods/logs, start up the game, start bank heist and then upload the log file that generated afterwards

**Comment by birbinabowtie** [comment]
i tried and it worked... idk why it didnt before
