### ISSUE TITLE
Can't select/click anything after interacting with BeardLib settings.

### ISSUE THREAD

**Issue by JimmyStyx** [simon-wh/PAYDAY-2-BeardLib#695]
When I go onto settings and click either the BeardLib Mod Manager or Custom Achievements tabs, I am no longer able to click or select anything on the game, though the game is running perfectly and isn't freezing or crashing. I can hit ESC to get out of the menus but I'm still have no way to go further.

**Comment by VortexGP** [comment]
Where's the solution? It's marked as completed. I also have this issue.
