### ISSUE TITLE
Crash when leaving options menu

### ISSUE THREAD

**Issue by Mattiator** [simon-wh/PAYDAY-2-BeardLib#697]
**Describe the crash**
Game crashes upon exiting the options menu to the main menu

**To Reproduce**
- Enter the "Options" menu
- Click on any setting
- Hit "Back"/Press ESC

**Crashlog**
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/12916929/crash.txt)

**Comment by whiteink0831** [comment]
Bro,did you fix it?Seems like we in the same problem and I don't know what to do
