### ISSUE TITLE
Audio Buffer Out of Memory crash on heist/day start

### ISSUE THREAD

**Issue by Mattiator** [simon-wh/PAYDAY-2-BeardLib#698]
**Describe the crash**
Game crashes due to audio buffer on heist start

**To Reproduce**
Install a BeardLib music mod that uses .ogg files (I've only been using these: https://modworkshop.net/mod/44022)
Begin a heist (seems to happen at random, haven't been able to nail exactly what triggers it)

**Crashlog**
If possible, include a crashlog (found in %localappdata%/payday 2 inside crash.txt)
[crash-musiclobby.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/12917001/crash-musiclobby.txt)

**Comment by segabl** [comment]
make sure dynamic music load is enabled in the beardlib settings. there's no way around this issue, if the game is out of memory, it's out of memory. loading large music files eats up a lot of memory and especially with dynamic load off it will quickly run out.
