### ISSUE TITLE
No more "mods options" and "mods keybinds" menu

### ISSUE THREAD

**Issue by kaizoku-kuma** [simon-wh/PAYDAY-2-BeardLib#70]
Hi, 
as mentioned in the title those menu disappeared after I've update Beardlib yesterday.

keep up the great work !

**Comment by Luffyyy** [comment]
Please post your log file from mods/logs

**Comment by kaizoku-kuma** [comment]
[2017_08_07_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1207992/2017_08_07_log.txt)

**Comment by kaizoku-kuma** [comment]
also I've noticed that a few mods won't work properly as before 
![218620_20170808142841_1_circle](https://user-images.githubusercontent.com/2505596/29072100-b1821060-7c46-11e7-8034-e5fda8c473de.png)

like this button on the screenshot only works in briefing and won't work in inventory.
I believe this is from "Wolfhud" or  "custom profile set".

If you are interested I haven't update beardlib since 07/07/17

**Comment by Luffyyy** [comment]
Start by updating your HoloUI, it's outdated, if that doesn't help remove keepers(or install announcer as it seems it needs it)
