### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SaaronReborn** [simon-wh/PAYDAY-2-BeardLib#703]
When I start the game it crashes, tell me if it's a mod or it's an issue with pd2 latest update.

Application has crashed: C++ exception
[string "lib/tweak_data/charactertweakdata.lua"]:5824: attempt to index a nil value

SCRIPT STACK

_set_overkill_290() lib/tweak_data/tweakdata.lua:344
lib/tweak_data/tweakdata.lua:208
init() lib/tweak_data/tweakdata.lua:2860
new() core/lib/utils/coreclass.lua:35
lib/tweak_data/tweakdata.lua:3639
require() =[C]
OrigRequire() @mods/base/base.lua:188
require() @mods/BeardLib/Core.lua:406
lib/setups/setup.lua:45
require() =[C]
OrigRequire() @mods/base/base.lua:188
require() @mods/BeardLib/Core.lua:406
lib/setups/gamesetup.lua:6
require() =[C]
OrigRequire() @mods/base/base.lua:188
require() @mods/BeardLib/Core.lua:406
lib/setups/networkgamesetup.lua:1
require() =[C]
OrigRequire() @mods/base/base.lua:188
require() @mods/BeardLib/Core.lua:406
lib/entry.lua:6
require() =[C]
OrigRequire() @mods/base/base.lua:188
require() @mods/BeardLib/Core.lua:406
core/lib/coreentry.lua:19

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.143.240
	CPU : AMD Ryzen 3 3200G with Radeon Vega Graphics (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3050 / nvldumd.dll[31.0.15.3623]
	Language : german
	Memory :     16332MB 608KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Altavoces (G635 Gaming Headset))

**Comment by offyerrocker** [comment]
This issue is not related to BeardLib, but to some other mod of yours after U240.3. Check overhauls or mods related to stats of characters/enemies.

**Comment by segabl** [comment]
This is caused by the weapon balance option in "Bot Weapons and Equipment", turn tit off until I can fix that.

**Comment by SaaronReborn** [comment]
thank you very much
