### ISSUE TITLE
Game keep crashing

### ISSUE THREAD

**Issue by C4pybara** [simon-wh/PAYDAY-2-BeardLib#705]
**To Reproduce**
Play a loud hiest

**Crashlog**
Application has crashed: C++ exception
mods/Fixmod/raycastweaponbase.lua:6: attempt to perform arithmetic on local 'v' (a table value)

SCRIPT STACK

_fire_raycast() lib/units/weapons/shotgun/shotgunbase.lua:304
fire() lib/units/weapons/raycastweaponbase.lua:644
fire() @mods/beardlib/Hooks/Fixes.lua:367
fire() lib/units/weapons/newraycastweaponbase.lua:2086
original() lib/units/weapons/raycastweaponbase.lua:532
trigger_held() @mods/base/req/core/Hooks.lua:264
fired_func() lib/units/weapons/newraycastweaponbase.lua:2071
_check_action_primary_attack() lib/units/beings/player/states/playerstandard.lua:5861
_update_check_actions() lib/units/beings/player/states/playerstandard.lua:1091
master_PlayerStandard_update() lib/units/beings/player/states/playerstandard.lua:464
update() @mods/CarryStackerReloaded/lua/hooks/playerstandard.lua:9
original() lib/units/beings/player/playermovement.lua:286
@mods/base/req/core/Hooks.lua:264

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        

-------------------------------

Current thread: Main

**Comment by segabl** [comment]
It tells you the issue right there, it's not an issue with BeardLib, but `mods/Fixmod`.
