### ISSUE TITLE
Crash when someone join my lobby

### ISSUE THREAD

**Issue by Hissdsd** [simon-wh/PAYDAY-2-BeardLib#706]
**Describe the crash**
Instant crash when someone join

**To Reproduce**
Just let someone join my lobby

**Crashlog**
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/13559544/crash.txt)

**Comment by segabl** [comment]
This is not a BeardLib issue itself most likely. There might be another mod trying to send invalid data.
