### ISSUE TITLE
Crashing after black screen intro on Buluc's Mansion

### ISSUE THREAD

**Issue by spellfork** [simon-wh/PAYDAY-2-BeardLib#708]
**Describe the crash**
When playing online I purchase the Heist and when the black screen intro ends and tries to load into the heist I CTD.

**To Reproduce**
I have only SuperBLT and BeardLib installed into the "mods" folder and I only have custom heist tracks in my "mod_overrides" folder, nothing else, no other mods. The total MB for all tracks add up to roughly 300MB, there are many tracks. The crash will happen even if I try to start it with the default music and just me by myself (online, set to "friends only") with no other players. I have not tested every heist but all the other heists I've tried work.

**Crashlog**
Application has crashed: C++ exception
[File] Cannot read from file "E:\Steam\steamapps\common\PAYDAY 2\assets\all_94.bundle" => error code 998: Invalid access to memory location. (d:\jenkins\shared-workspace\diesel\engine\dieselx\dieselx\blobs\../utility/Archive.cpp:2482)

SCRIPT_STACK

change_material_config() lib/managers/dynamicresourcemanager.lua:230
set_character_visual_state() lib/managers/criminalsmanager.lua:621
original() lib/managers/criminalsmanager.lua:444
update_character_visual_state() @mods/base/req/core/Hooks.lua:264
original() lib/managers/group_ai_states/groupaistatebase.lua:3285
set_unit_teamAI() @mods/base/req/core/Hooks.lua:264
spawn_one_teamAI() lib/managers/group_ai_states/groupaistatebase.lua:3062
fill_criminal_team_with_AI() lib/managers/group_ai_states/groupaistatebase.lua:3392
spawn_players() lib/network/base/basenetworksession.lua:1524
update() lib/states/ingamewaitingforplayers.lua:310
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
original() lib/setups/setup.lua:940
update() @mods/base/req/core/Hooks.lua:264
original() lib/setups/gamesetup.lua:802
update() @mods/base/req/core/Hooks.lua:264
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:559

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main
Script stack:
      change_material_config()  lib/managers/dynamicresourcemanager.lua:230         
  set_character_visual_state()  lib/managers/criminalsmanager.lua:621               
                    original()  lib/managers/criminalsmanager.lua:444               
update_character_visual_state()  @mods/base/req/core/Hooks.lua:264                   
                    original()  lib/managers/group_ai_states/groupaistatebase.lua:3285  
             set_unit_teamAI()  @mods/base/req/core/Hooks.lua:264                   
            spawn_one_teamAI()  lib/managers/group_ai_states/groupaistatebase.lua:3062  
  fill_criminal_team_with_AI()  lib/managers/group_ai_states/groupaistatebase.lua:3392  
               spawn_players()  lib/network/base/basenetworksession.lua:1524        
                      update()  lib/states/ingamewaitingforplayers.lua:310          
                      update()  core/lib/utils/game_state_machine/coregamestatemachine.lua:92  
                    original()  lib/setups/setup.lua:940                            
                      update()  @mods/base/req/core/Hooks.lua:264                   
                    original()  lib/setups/gamesetup.lua:802                        
                      update()  @mods/base/req/core/Hooks.lua:264                   
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:559                   

-------------------------------

System information:
	Application version : 1.143.243
	CPU : Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz (5 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 4070 Ti / nvldumd.dll[31.0.15.5123]
	Language : english
	Memory :     32685MB 868KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (DOQAUS CARE 1 Stereo))

**Comment by segabl** [comment]
Do you have any other mods? This crash implies either your game files are corrupted (validate the files through steam) or some outfit asset mod is broken.
