### ISSUE TITLE
Game crashes when a little bit into the heist 

### ISSUE THREAD

**Issue by MayutheKitunse** [simon-wh/PAYDAY-2-BeardLib#71]
This is the crash report i get

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                @mods/BeardLib/Hooks/CoreSystem.lua:24              
                            ()  =(tail                                              
                      call):-1  produce()                                           
lib/managers/mission/elementspawnenemydummy.lua:70  _try_spawn_unit()                                   
lib/managers/group_ai_states/groupaistatebesiege.lua:1397  _upd_group_spawning()                               
lib/managers/group_ai_states/groupaistatebesiege.lua:1479  clbk()                                              
lib/managers/group_ai_states/groupaistatebesiege.lua:179  _execute_queued_task()                              
lib/managers/enemymanager.lua:549  _update_queued_tasks()                              
lib/managers/enemymanager.lua:558  update()                                            
lib/managers/enemymanager.lua:49                                                      
  lib/setups/gamesetup.lua:655  ()                                                  
                        =(tail  call):-1                                            
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537                   
                            ()  =(tail                                              
                      call):-1  
-------------------------------

System information:
	Application version : 1.75.288.
	CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970M / nvd3dum.dll[21.21.13.6909]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8091MB 612KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : CREATIVE (Speakers (Sound Blaster Recon3Di))

**Comment by Luffyyy** [comment]
Why do I have to repeat it so many times..
https://github.com/GreatBigBushyBeard/PAYDAY-2-BeardLib/wiki/What-is-BeardLib%3F#my-game-is-crashing-and-the-script-stack-says-modsbeardlibhookscoresystemlua-lxx
