### ISSUE TITLE
Crash upon joining ongoing heist

### ISSUE THREAD

**Issue by LG2607** [simon-wh/PAYDAY-2-BeardLib#711]
Through Fast.Net, I tried to join the Brooklyn Bank heist on mayhem difficulty when the game suddenly crashed.

**To Reproduce**
-Go to Fast.Net
-select brooklyn bank heist on mayhem difficulty and join it
-crash when you're about to go in game

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        

-------------------------------

Current thread: Main
Script stack:
                      update()  lib/units/enemies/cop/actions/full_body/copactionhurt.lua:1386  
                _upd_actions()  lib/units/enemies/cop/copmovement.lua:848           
                _upd_actions()  lib/units/enemies/cop/huskcopmovement.lua:13        
                                lib/units/enemies/cop/copmovement.lua:773           

-------------------------------

System information:
	Application version : 1.143.243
	CPU : Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1650 / nvldumd.dll[31.0.15.4633]
	Language : english
	Memory :     32636MB 244KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (LG TV (NVIDIA High Definition Audio))

**Comment by MiamiCenterPL** [comment]
Not caused by BeardLib. It is most likely caused by Fast.Net mod, or other mod that changes enemy units anyhow (any game overhauls, custom enemy models, animations or behaviour etc.)
