### ISSUE TITLE
Crash when i joining online lobby with LAS mod 

### ISSUE THREAD

**Issue by Rowyag** [simon-wh/PAYDAY-2-BeardLib#713]
My game will crash when I joining online lobby thought Fast.Net (I haven't try the vanilla Crime.Net). It's not a 100% chance, it's a probability event. It often happens after I play a game. But sometimes it crashes when trying to joining public online lobby for the first time. Here's the crash log.

> [crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/14330228/crash.txt)

At most It can crash 17 times a day with the same crash log. When I check the mod log i found that many errors were reported in it and there were also some fatal errors reported. I really don't know how to fix it. Please help me ; - ;
The mod log is below

> [2024_02_19_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/14330416/2024_02_19_log.txt)

**Comment by segabl** [comment]
There's nothing specific pointing towards BeardLib being the issue, however i can see a bunch of LAS mods throwing errors in the BLT log so make sure those are in the right folders and not broken.

**Comment by Luffyyy** [comment]
You should play around with the mods until it fixes itself, if you have enough belief it's BeardLib itself reopen the issue.
