### ISSUE TITLE
PAYDAY 2 crashing

### ISSUE THREAD

**Issue by LG2607** [simon-wh/PAYDAY-2-BeardLib#714]
Cant figure out what's causing these crashes. They mostly occur mid game:

Tue Feb 20 09:53:47 2024

Application has crashed: C++ exception

[string "lib/units/enemies/cop/actions/lower_body/copa..."]:341: attempt to index field '_nav_path' (a nil value)

SCRIPT STACK

init() lib/units/enemies/cop/actions/lower_body/copactionwalk.lua:244

new() core/lib/utils/coreclass.lua:35

action_request() lib/units/enemies/cop/copmovement.lua:1353

_chk_start_queued_action() lib/units/enemies/cop/copmovement.lua:3281

_upd_actions() lib/units/enemies/cop/huskcopmovement.lua:14

lib/units/enemies/cop/copmovement.lua:773

-------------------------------

Callstack:

payday2_win32_release (???) ???

payday2_win32_release (???) ???

payday2_win32_release (???) ???

payday2_win32_release (???) ???

payday2_win32_release (???) ???

KERNEL32 (???) BaseThreadInitThunk

ntdll (???) RtlInitializeExceptionChain

ntdll (???) RtlClearBits

-------------------------------

Current thread: Main

-------------------------------

System information:

Application version : 1.143.243

CPU : Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2

DirectX : 12.0 

GPU : NVIDIA GeForce GTX 1650 / nvldumd.dll\[31.0.15.4633\]

Language : english

Memory :     32636MB 244KB

OS : 6.2.9200 () 0x300-0x1 (64 bits)

Physics : threaded

Renderer : DX9 threaded

Sound : NVIDIA Corporation (LG TV (NVIDIA High Definition Audio))

My mod list:
![Captura de tela 2024-02-20 101636](https://github.com/simon-wh/PAYDAY-2-BeardLib/assets/149631034/f7ec6da3-6d6c-49ae-8cba-382740bd4258)
![Captura de tela 2024-02-20 101645](https://github.com/simon-wh/PAYDAY-2-BeardLib/assets/149631034/6b71dc37-5ab8-45c2-83eb-b2644d12f813)

Ive already reinstalled, verified game files, and added the game to the exceptions list of my anti virus, btw

**Comment by segabl** [comment]
This seems to be a vanilla issue, not BeardLib related. You could try using "The Fixes" to prevent this.
