### ISSUE TITLE
This problem often occurs

### ISSUE THREAD

**Issue by LeeWinston0713** [simon-wh/PAYDAY-2-BeardLib#715]
Application has crashed: C++ exception
[string "lib/managers/menu/crimespreemissionsmenucompo..."]:686: attempt to index field 'level' (a nil value)

SCRIPT STACK

init() lib/managers/menu/crimespreemissionsmenucomponent.lua:464
new() core/lib/utils/coreclass.lua:35
_setup() lib/managers/menu/crimespreemissionsmenucomponent.lua:93
init() lib/managers/menu/crimespreemissionsmenucomponent.lua:31
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:5123
original() lib/managers/menu/menucomponentmanager.lua:520
set_active_components() @mods/base/req/core/Hooks.lua:264
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
original() lib/setups/setup.lua:909
update() @mods/base/req/core/Hooks.lua:264
original() lib/setups/menusetup.lua:363
update() @mods/base/req/core/Hooks.lua:264
core/lib/setups/coresetup.lua:559

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main

**Comment by segabl** [comment]
What makes you think BeardLib causes it? Did you verify if it happens without BeardLib?

**Comment by LeeWinston0713** [comment]
I don't know. I don't know much about these.

**Comment by segabl** [comment]
There is a vanilla game issue in crime spree so you might wanna try the crime spree fixes mod and see if that fixes your issue but as far as I can tell this is not a BeardLib issue
