### ISSUE TITLE
crashing when getting to the main menu after going through the loading screen

### ISSUE THREAD

**Issue by UnforseenDeath** [simon-wh/PAYDAY-2-BeardLib#716]
opening the game is fine until i get past the loading screen when you are first met when starting the game, once im shown the main menu where everything is my game just crashes

newest version of bearlib and base file that comes from superblt. these are the only files that are in my mods folder

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Main
Script stack:
      change_material_config()  lib/managers/dynamicresourcemanager.lua:230         
set_beardlib_character_visual_state()  @mods/BeardLib/Hooks/PlayerStyleGloveHooks.lua:420  
                        func()  @mods/BeardLib/Hooks/PlayerStyleGloveHooks.lua:576  
    update_character_visuals()  @mods/base/req/core/Hooks.lua:272                   
          _chk_load_complete()  lib/units/menu/menuarmourbase.lua:509               
       _load_cosmetic_assets()  lib/units/menu/menuarmourbase.lua:612               
                        func()  @mods/BeardLib/Hooks/PlayerStyleGloveHooks.lua:554  
  call_next_update_functions()  lib/setups/setup.lua:269                            
                    original()  lib/setups/setup.lua:901                            
                      update()  @mods/base/req/core/Hooks.lua:264                   
                    original()  lib/setups/menusetup.lua:363                        
                      update()  @mods/base/req/core/Hooks.lua:264                   
                                core/lib/setups/coresetup.lua:559

**Comment by segabl** [comment]
Does it work fine without BeardLib?

**Comment by UnforseenDeath** [comment]
> Does it work fine without BeardLib?

Yeah most of ecerythong works fine except the color picker mod, i noticed i got different errors with that and different crashes but it seems to just be an issue with beardlib

**Comment by UnforseenDeath** [comment]
![image](https://github.com/simon-wh/PAYDAY-2-BeardLib/assets/123546379/29fb2316-807c-43ed-b211-aeea7ed74309)

**Comment by UnforseenDeath** [comment]
Yeah i already found the issue, it seemed to be my tailor expansion file corrupted so i replace it with a new one and its working fine!
