### ISSUE TITLE
help, was it that my computer didn't reach requirements?

### ISSUE THREAD

**Issue by OhWow99Guns** [simon-wh/PAYDAY-2-BeardLib#72]
Application has crashed: C++ exception
[string "--mods/BeardLib/Classes/Menu/Menu.lua..."]:102: attempt to call method 'alive' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.55.43
	CPU : AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 10.0 
	GPU : AMD Radeon R7 Series / aticfx32.dll[8.17.10.1267]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     7113MB 104KB
	OS : 6.1.7600 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (2- Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
What mods do you have installed?

**Comment by OhWow99Guns** [comment]
(https://user-images.githubusercontent.com/30901640/29207660-9fb0dff4-7eb9-11e7-85cd-e66936ba9d8d.png)
(https://user-images.githubusercontent.com/30901640/29207689-b949daec-7eb9-11e7-9189-d0efffd96da2.png)

Is it because my computer can't handle these mods?

**Comment by OhWow99Guns** [comment]
https://user-images.githubusercontent.com/30901640/29207799-0e998ae2-7eba-11e7-8aac-a4104ab6f9a2.png
https://user-images.githubusercontent.com/30901640/29207803-0f748dea-7eba-11e7-978b-58abb73df375.png

Is it because my computer can't handle it?

**Comment by Luffyyy** [comment]
No that's a weird crash because I don't see any mod that might be causing it, try disabling some

**Comment by OhWow99Guns** [comment]
I believe that it was the Beardlib mod itself because when i read the crash report it said "[string "--mods/BeardLib/Classes/Menu/Menu.lua..."]:102: attempt to call method 'alive' (a nil value)"

**Comment by Luffyyy** [comment]
Well run the game without any mods(including mod overrides and maps) except beardlib I need confirmation that it's really beardlib causing.

**Comment by OhWow99Guns** [comment]
Ok

**Comment by OhWow99Guns** [comment]
https://user-images.githubusercontent.com/30901640/29242208-660a057a-7fbb-11e7-9bde-a12fad3a6e31.png
https://user-images.githubusercontent.com/30901640/29242212-7325602e-7fbb-11e7-9ae5-1f8731c0e7f9.png

Yup

**Comment by OhWow99Guns** [comment]
Maybe it's my PC, i'm getting a better one next month.

**Comment by Luffyyy** [comment]
Don't think so, have you tried removing the folder ans reinstalling?

**Comment by OhWow99Guns** [comment]
I'll give it a try

**Comment by OhWow99Guns** [comment]
It still crashes

**Comment by OhWow99Guns** [comment]
it's fine, i'll get a better computer and maybe i can run this great mod

**Comment by OhWow99Guns** [comment]
Oh btw you can close this now
