### ISSUE TITLE
[WARN] CloneClass is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by ZaharwinHM** [simon-wh/PAYDAY-2-BeardLib#721]
07:41:45 PM Lua: [WARN] CloneClass is deprecated and will be removed in a future version
stack traceback:
	mods/base/req/utils/UtilsCore.lua:369: in function 'CloneClass'
	mods/LessSimpleCrosshair/HudHitConfirm.lua:1: in main chunk
	[C]: in function 'dofile'
	mods/LessSimpleCrosshair/SimpleCrosshair.lua:13: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:169: in function 'RunHookFile'
	mods/base/base.lua:157: in function 'RunHookTable'
	mods/base/base.lua:189: in function 'OrigRequire'
	mods/BeardLib/Core.lua:406: in function 'require'
	[string "lib/managers/hudmanagerpd2.lua"]:26: in main chunk
	[C]: in function 'require'
	...
	mods/BeardLib/Core.lua:406: in function 'require'
	[string "lib/setups/networkgamesetup.lua"]:1: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:188: in function 'OrigRequire'
	mods/BeardLib/Core.lua:406: in function 'require'
	[string "lib/entry.lua"]:6: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:188: in function 'OrigRequire'
	mods/BeardLib/Core.lua:406: in function 'require'
	[string "core/lib/coreentry.lua"]:19: in main chunk

**Comment by segabl** [comment]
This is a superBLT warning about "LessSimpleCrosshair" using outdated functionality. Not an issue in itself but that functionality might get removed at some point, causing the mod to stop working if it isn't adjusted.
