### ISSUE TITLE
Issue with loading custom levels.

### ISSUE THREAD

**Issue by ZaharwinHM** [simon-wh/PAYDAY-2-BeardLib#722]
06:30:00 PM Lua: [End of an Era][ERROR] An error occurred on initilization of module: instance. Error:
nil
06:30:00 PM FATAL ERROR:  (C:\projects\payday2-superblt\src\InitiateState.cpp:248) mods/BeardLib/Modules/PD2/LevelModule.lua:264: attempt to index field '_loaded_instances' (a nil value)
stack traceback:
	mods/BeardLib/Modules/PD2/LevelModule.lua:264: in function 'init'
	[string "core/lib/utils/coreclass.lua"]:35: in function <[string "core/lib/utils/coreclass.lua"]:31>
	[C]: in function 'pcall'
	mods/BeardLib/Classes/ModCore.lua:185: in function 'AddModule'
	mods/BeardLib/Classes/ModCore.lua:160: in function 'InitModules'
	mods/BeardLib/Classes/ModCore.lua:131: in function 'PreInitModules'
	mods/BeardLib/Classes/Frameworks/FrameworkBase.lua:132: in function 'InitMods'
	mods/BeardLib/Core.lua:124: in function 'FullyLoadFrameworks'
	mods/BeardLib/Core.lua:98: in function 'Init'
	mods/BeardLib/Core.lua:411: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:169: in function 'RunHookFile'
	mods/base/base.lua:157: in function 'RunHookTable'
	mods/base/base.lua:189: in function 'require'
	[string "core/lib/coreentry.lua"]:14: in main chunk

**Comment by MiamiCenterPL** [comment]
I think you have installed the map onto mods folder, which does not support instances, if that's the case please move the map into Maps folder (if you don't have one - create one)

**Comment by ZaharwinHM** [comment]
> I think you have installed the map onto mods folder, which does not support instances, if that's the case please move the map into Maps folder (if you don't have one - create one)

I don't think so. i don't have any maps in mods folder.
