### ISSUE TITLE
GUI not compatible with Beardlib

### ISSUE THREAD

**Issue by Mayzone** [simon-wh/PAYDAY-2-BeardLib#724]
**Describe the bug**
I made a GUI without beardlib, the workspace, bitmaps work but text panels become visible/invisible when mouse is moved or alpha is changed when hovers over the sub panels with the mouse. I'm assuming im using the same method as beardlib for creating the gui but not using beardlib to do so. Also the mouse layer is changed from default it seems, because it's under the panels so it could be a layer problem overall.

**To Reproduce**
Create a workspace with Overlay:gui():create_screen_workspace(), make it a panel and bitmap 1280x720, add sub scroll panels within the main panel and have text within. All panels have alpha 1 black

**Comment by Luffyyy** [comment]
This has nothing to do with beardlib itself

**Comment by Mayzone** [comment]
I didn't say it's a problem with beardlib, it's incompatible with other guis, what causes this?

**Comment by Luffyyy** [comment]
I assume it's a layering issue. It's hard to tell without concrete code to look at/test. We changed the mouse layer to 9999999999 since the mouse shouldn't really be behind anything. There are some odd glitches with the "add" blend mode too sometimes.
