### ISSUE TITLE
Beardlib 5.0 doesn't play custom weapon sounds

### ISSUE THREAD

**Issue by vladald1** [simon-wh/PAYDAY-2-BeardLib#728]
It's in the title - 4.88 Beardlib plays custom weapon sounds correctly, but 5.0 only play distant gun sounds without playing shooting sound itself. Reload sounds work fine, though.

**Comment by Luffyyy** [comment]
Sorry for the delay, but after testing this with like 3 mods I couldn't replicate this. Could you maybe send your mods packed into a zip (as minimal as possible) so I could test it?

**Comment by vladald1** [comment]
It's too long, so I will say that it happened with these mods:
1) https://modworkshop.net/mod/48160
2) https://modworkshop.net/mod/48138

I will send also txt file of all my mods, since .zip file of mod_overrides folder would've been too big. 
[The Fixes Info.txt](https://github.com/user-attachments/files/16323614/The.Fixes.Info.txt)

[mods.zip](https://github.com/user-attachments/files/16323621/mods.zip)

**Comment by Luffyyy** [comment]
This was a weapon lib compatibility issue with beardlib 5. Fixed now
