### ISSUE TITLE
Cannot drop in any game using Beardlib

### ISSUE THREAD

**Issue by sgtpauljackson** [simon-wh/PAYDAY-2-BeardLib#73]
I can always join a lobby, but whenever I try to drop in, PAYDAY 2 says, "Steam could not authenticate the steam ID for the host". I have concluded that beardlib is the problem because it never does that without beardlib.

**Comment by Luffyyy** [comment]
Are you sure? You don't have any other mods? Does it happen even after I asked?

**Comment by sgtpauljackson** [comment]
Ok, so for some odd reason, Norton does not like BeardLib at all, and won't let me drop in any games. This did not happen with Norton without BeardLib, so Norton and BeardLib conflict with each other some how as I've tested.

**Comment by Luffyyy** [comment]
Then don't use it, I heard only bad things about that anti virus or disable network protection.
