### ISSUE TITLE
Crash when Executing MoveUnit element

### ISSUE THREAD

**Issue by Croqui42** [simon-wh/PAYDAY-2-BeardLib#730]
**Describe the crash**
The game crash when executing a MoveUnit element

**To Reproduce**
In old version the self._move_units table got created when register_move_unit was called, but not anymore.
_Execute a MoveUnit element from any custom heist._

**Crashlog**

Application has crashed: C++ exception
mods/BeardLib/Hooks/Maps/Hooks.lua:320: attempt to index field '_move_units' (a nil value)

SCRIPT STACK

register_move_unit() @mods/BeardLib/Classes/Elements/ElementMoveUnit.lua:71
f() @mods/BeardLib/Classes/Elements/ElementMoveUnit.lua:55
update() core/lib/utils/coreevent.lua:158
update() core/lib/managers/mission/coremissionmanager.lua:531
update() core/lib/managers/mission/coremissionmanager.lua:160
core/lib/setups/coresetup.lua:522
Callstack:

         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
                      KERNEL32  (???)     BaseThreadInitThunk
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath

**Comment by Luffyyy** [comment]
Sorry for the delay. I believe this should do the trick
