### ISSUE TITLE
Instant Crash Upon Opening Beardlib Mod Manager

### ISSUE THREAD

**Issue by ToxicZombie000** [simon-wh/PAYDAY-2-BeardLib#731]
**Describe the crash**

Whenever I open the Mod Manager, I crash to my desktop. 

**To Reproduce**

Clicking on the "Updates Required" Button on the main menu.
AND
Going to Options -> Beardlib Mod Manager

**Crashlog**

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_error_init                                      
         payday2_win32_release  (???)     zip_error_init                                      
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   

-------------------------------

Current thread: Renderer

-------------------------------

System information:
	Application version : 1.143.243
	CPU : AMD Ryzen 7 3800X 8-Core Processor (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2070 SUPER / nvldumd.dll[31.0.15.3623]
	Language : english
	Memory :     32675MB 988KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (Bose QC 45 Stereo))

**Comment by Luffyyy** [comment]
Doesn't happen to me. Try to manually update the mod https://modworkshop.net/mod/14924
