### ISSUE TITLE
Play pd2 then crash

### ISSUE THREAD

**Issue by Shadow-S0ldier** [simon-wh/PAYDAY-2-BeardLib#732]
Application has crashed: C++ exception
mods/BeardLib/Classes/UI/Dialogs/MenuDialog.lua:29: attempt to index field 'Options' (a nil value)

SCRIPT STACK

new() core/lib/utils/coreclass.lua:35
create_items() @mods/BeardLib/Classes/Managers/MenuDialogManager.lua:22
init() @mods/BeardLib/Classes/UI/MenuUI/MenuUI.lua:74
func() @mods/BeardLib/Classes/UI/MenuUI/MenuUI.lua:6
Call() @mods/base/req/core/Hooks.lua:109
init() @mods/base/lua/MenuManager.lua:10
new() core/lib/utils/coreclass.lua:35
original() lib/setups/setup.lua:415
init_managers() @mods/base/req/core/Hooks.lua:260
init_managers() lib/setups/menusetup.lua:296
core/lib/setups/coresetup.lua:401

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     ???

**Comment by Luffyyy** [comment]
Not enough information. Please do not ignore the templates.
