### ISSUE TITLE
Menu Background Crashing the game 

### ISSUE THREAD

**Issue by BacardiViper** [simon-wh/PAYDAY-2-BeardLib#733]
**Describe the crash**
Trying to change my background using the mod Menu Background, Also instaled HoloUI

**To Reproduce**
Enter the game, settings, mod settings, Background, change The Diamond background

**Crashlog**
Application has crashed: C++ exception
mods/BeardLib/Modules/Utils/OptionModule.lua:215: attempt to index local 'self' (a nil value)

SCRIPT STACK

callback() @mods/BeardLib/Modules/Utils/OptionModule.lua:645
trigger() core/lib/managers/menu/items/coremenuitem.lua:161
core/lib/managers/menu/coremenulogic.lua:286
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
original() lib/setups/setup.lua:909
update() @mods/base/req/core/Hooks.lua:260
original() lib/setups/menusetup.lua:363
update() @mods/base/req/core/Hooks.lua:260
core/lib/setups/coresetup.lua:559

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlInitializeExceptionChain                         
                         ntdll  (???)     RtlClearBits                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.143.243
	CPU : 13th Gen Intel(R) Core(TM) i7-13620H (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 4070 Laptop GPU / nvldumd.dll[32.0.15.6070]
	Language : latam
	Memory :     32471MB 520KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Altavoces (Logitech G733 Gaming Headset))

**Comment by Luffyyy** [comment]
Downgrade to 4.88. It will be fixed in 5.0.1

**Comment by Luffyyy** [comment]
Upgrade to 5.0.1.
