### ISSUE TITLE
Beardlib doesnt update in game

### ISSUE THREAD

**Issue by IWANTTOAST115** [simon-wh/PAYDAY-2-BeardLib#735]
Everytime I launch the game and or do a heist beardlib needs to update. When I do update it that means its not applying it. I can fix it by manually updating it from modworkshop.

to reproduce just launch the game or play a heist after updating it

**Comment by Shadow-S0ldier** [comment]
Same

**Comment by Dist1nctive** [comment]
I had that problem with it aswell so you can fix via update manually?

**Comment by Luffyyy** [comment]
I think it might be an issue with the version comparison. I'll release an update soon

**Comment by Luffyyy** [comment]
![image](https://github.com/user-attachments/assets/ab687ead-f800-4d43-babb-cecba197972b)
Sorry for the delay (really busy with college atm), but does it still happen?

**Comment by Dist1nctive** [comment]
sorry of answering late but i reinstall beardlib so i cant be sure

**Comment by Luffyyy** [comment]
Sorry for the long wait, fixed. This was an issue with mws's API.
