### ISSUE TITLE
Crash, randomly on any heist. (Beardlib-Editor)

### ISSUE THREAD

**Issue by ThatGuyFromThatPlace** [simon-wh/PAYDAY-2-BeardLib#74]
Application has crashed: C++ exception
[string "core/lib/managers/coreportalmanager.lua"]:597: attempt to index a number value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.75.290
	CPU : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1050 / nvldumd.dll[22.21.13.8528]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     12241MB 220KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Report editor issues here : https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/issues Also what do you mean by randomly? On restart? On loading? In editor mode?
