### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ELYARL** [simon-wh/PAYDAY-2-BeardLib#75]
`Application has crashed: C++ exception
[string "lib/managers/gameplaycentralmanager.lua"]:773: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.75.295
	CPU : AMD Athlon(tm) X4 840 Quad Core Processor (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 11.0 
	GPU : NVIDIA GeForce GT 730 / nvd3dum.dll[22.21.13.8494]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8135MB 512KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Динамики (Realtek High Definition Audio))`

**Comment by Luffyyy** [comment]
Information PLEASE
and why do you think BeardLib is the cause?

**Comment by Luffyyy** [comment]
No information given.
