### ISSUE TITLE
Bug on Golden Grin Casino stealth

### ISSUE THREAD

**Issue by xtakku** [simon-wh/PAYDAY-2-BeardLib#76]
When hosting GGC, opening the guitar case and taking gear before any of your clients can do so prevents them from interacting with the bag that provides the gear. They can still pick up the sleeping gas though, effectively breaking stealth for that run unless they reconnect.
Placement for guitar case was the lowermost option in preplanning, in case that matters somehow (which I doubt).

**Comment by Luffyyy** [comment]
Are you sure BeardLib is the cause?

**Comment by xtakku** [comment]
100%, I wouldn't be posting otherwise. To make sure I even deleted everything except BLT and BeardLib, and the issue persisted.

**Comment by xtakku** [comment]
... in case it wasn't obvious, I thought I might add that the issue was no longer present when I removed BeardLib (and nothing else).

**Comment by Luffyyy** [comment]
any mod_overrides mods?

**Comment by xtakku** [comment]
I was using a couple, yes. However, I can no longer verify if or which one of them might be related to the issue in question because it no longer happens. I'm not 100% sure why it stopped happening, but I now assume that it was actually a conflict between a client-side mod on the one hand and BeardLib being run by the host (me) on the other. I believe this to be the case because a couple of said client-side mods my friend was using during our tests have been updated, and ever since the issue no longer persists (neither with nor without BeardLib). If you care to know (maybe for future reference because I found another issue that does still persist), these mods have been updated in the few days since I started this thread. They are all auto-updated mods by TdlQ found on paydaymods.com:
- Bag Contour
- Civilian ! Marker for Drop-ins
- Filtered Camera Beeps

**Comment by xtakku** [comment]
PS: I'll do some more thorough testing before I open another issue thread, but the other issue I mention is the zip-line from the uppermost floor of the burning building in Goat Simulator day 1. Much like the issue described above, me (host) using the zip-line prevents my clients from using it.  
This only happens when I have BeardLib in use, however it doesn't happen when I remove my mod_overrides. Using other .lua mods with BeardLib does not seem to cause this issue. I'll try to do some more testing to see if this happens on other maps and hopefully which mod_overrides mod might cause this...

**Comment by xtakku** [comment]
Something more to add here. TdlQ says he can't imagine any of the mods I mentioned causing such a conflict, and even though I explained the reasons for my assumptions above I suppose he's more competent with these things than me. Since this still leaves me unable to reproduce this bug, I suppose this thread can stay closed for now.

**Comment by Luffyyy** [comment]
Remember that mod overrides have mods that use BeardLib.

**Comment by xtakku** [comment]
I'm fully aware, but I don't have any mod_overrides that use BeardLib, nor did I ever have any.
