### ISSUE TITLE
Game crashes when I try to join a friend.

### ISSUE THREAD

**Issue by HydraLord** [simon-wh/PAYDAY-2-BeardLib#77]
I have tried force updating on both ends and I was wondering waht i could do to fix it.

Wed Aug 16 22:25:44 2017

Application has crashed: C++ exception
[string "lib/network/base/networkpeer.lua"]:287: attempt to index field '?' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     NtQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.75.290
	CPU : AMD FX(tm)-8350 Eight-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE5
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1070 / nvd3dum.dll[21.21.13.7653]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     16366MB 116KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (Xbox One-C (NVIDIA High Definition Audio))

**Comment by Luffyyy** [comment]
Do you have any mods? does your friend have any mods? Anything including Maps and mod overrides are you positive that BeardLib is causing it?

**Comment by HydraLord** [comment]
we only have the skin workshop mod.

**Comment by Luffyyy** [comment]
did you try running the game without BeardLib? does it happen only with that person? can he play with others?
Sorry for asking many questions I cannot really tell why it's happening because for my point of view most people can join with no problem.

**Comment by HydraLord** [comment]
i have ran the game without mods and i still get crashes but it is a different crash and only happens when my friend hosts the casino map. but this crash has only stared once I installed mods.

**Comment by Luffyyy** [comment]
is the crash still present? have you found a solution?
