### ISSUE TITLE
BLT 2.0 Update manager is saying there's a beardlib update but I have the newest version?

### ISSUE THREAD

**Issue by Omen267901** [simon-wh/PAYDAY-2-BeardLib#79]
The update fails when attempted.

Also, attempting to auto-update beardlib mods is freezing the game, but I assume that's because they aren't using BLT 2.0.

**Comment by Gnupfo** [comment]
Having the exact same problem

**Comment by Alexandrosa** [comment]
Same problem here.

http://imgur.com/a/XxgCx

**Comment by Luffyyy** [comment]
Again this issue is not BeardLib's fault the updates(*for BeardLib not the mods of BeardLib) are delivered by paydaymods.
