### ISSUE TITLE
WeaponModModule: Problem with "based_on" ammo pickup calculation 

### ISSUE THREAD

**Issue by Pawcio1337** [simon-wh/PAYDAY-2-BeardLib#8]
Some weapons use fixed values for ammo pickup so based_on will give wrong values due its calculated from AMMO_MAX.

List of weapons with fixed values:
saw
m95
msr
r93
gre_m79
mosin
m32
model70
china

Possible solutions:
1) Based_on checks if its one of listed weapons and will use AMMO_PICKUP directly from that weapon.
2) Allow to configure ammo pickup values via xml.

**Comment by simon-wh** [comment]
If you're using the existing WeaponModule then you can include an override for the AMMO_PICKUP in a merge_data table.

For the WeaponModuleNew, I'll need to include an override for it.
