### ISSUE TITLE
It just doesn't work with BLT 2.0, trying to update in the new manager always fails

### ISSUE THREAD

**Issue by Gnupfo** [simon-wh/PAYDAY-2-BeardLib#80]
Title

**Comment by AddictiveGamer66** [comment]
i have exact same problem hopefully its fixed soon

**Comment by Luffyyy** [comment]
This is an issue with BLT itself try updating BLT and you'll see that it fails.
Download it manually through https://modworkshop.net/mydownloads.php?action=view_down&did=14924

**Comment by Gnupfo** [comment]
Tried that; doesn't work. BLT tries to update BeardLib, always fails. As a result all BeardLib mods are unusable

**Comment by Luffyyy** [comment]
Don't update then? It's an issue that they currently have.

**Comment by Gnupfo** [comment]
Thing is for some reason this makes BeardLib unusable

**Comment by Gnupfo** [comment]
I think this may as well just be general chaos after the lua update. I think they'll get that fixed really quickly, and you've done all you can. Thanks for the help anyways

**Comment by Luffyyy** [comment]
by unusable what do you mean?

**Comment by Gnupfo** [comment]
Mods that use it don't work
