### ISSUE TITLE
game crash when i join public lobbies

### ISSUE THREAD

**Issue by NicoTine34** [simon-wh/PAYDAY-2-BeardLib#83]
When i join a public lobby my game crash but if i host i dont have crashes

Application has crashed: C++ exception
[string "lib/managers/missionmanager.lua"]:288: attempt to call method 'client_on_executed' (a nil value)

SCRIPT STACK

lib/network/handlers/unitnetworkhandler.lua:568

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???

**Comment by Luffyyy** [comment]
Vanilla crash please don't instantly assume beardlib is the cause.
