### ISSUE TITLE
Newest Payday 2 update seems to have broken BeardLib

### ISSUE THREAD

**Issue by Chaos614** [simon-wh/PAYDAY-2-BeardLib#84]
My friend pointed it out to me as it came out that the Aldstone's Heritage update broke BeardLib as none of our mods seem to work (That required it). Just wanted to bring it to attention if it wasn't already, thank you in advance!

**Comment by SasiiDK** [comment]
The same happend to me. my beardlib needs to update but it says "Failed" and when i try start any random heist. my game crashes

**Comment by Luffyyy** [comment]
What version do you all have? latest is 2.29.
Please for the last time BLT's updating system is currently broken you can clearly see that BLT and other mods have that issue also.

**Comment by Chaos614** [comment]
Oh! I'm sorry, I hadn't noticed it was updated yesterday, my apologies
