### ISSUE TITLE
PAYDAY 2 Crashes on launch. Seems Beardlib is the culprit

### ISSUE THREAD

**Issue by RunDevilRun007** [simon-wh/PAYDAY-2-BeardLib#85]
Every time I attempt to launch PAYDAY 2, the game just immediately crashes. Checking the log seems to show it's Beardlib's doing:

04:20:07 AM FATAL ERROR:  (..\src\InitiateState.cpp:408) C++ exception
04:20:08 AM FATAL ERROR:  (..\src\InitiateState.cpp:408) [string "--mods/BeardLib/Classes/MapFramework.lua..."]:12: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	[string "--mods/BeardLib/Classes/MapFramework.lua..."]:12: in function 'RegisterHooks'
	mods/BeardLib/Hooks/PreTweakData.lua:12: in main chunk
	[C]: in function 'dofile'
	mods/BeardLib/BeardLibCore.lua:189: in main chunk
	[C]: in function 'dofile'
	mods/base/base.lua:120: in function 'RunHookFile'
	mods/base/base.lua:113: in function 'RunHookTable'
	mods/base/base.lua:142: in function 'require'
	[string "lib/tweak_data/tweakdata.lua"]:47: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:141: in function 'require'
	[string "lib/setups/setup.lua"]:23: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:141: in function 'require'
	[string "lib/setups/menusetup.lua"]:1: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:141: in function 'require'
	[string "lib/entry.lua"]:13: in main chunk
	[C]: in function 'require'
	mods/base/base.lua:141: in function 'require'
	[string "core/lib/coreentry.lua"]:19: in main chunk
04:20:10 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED

**Comment by Luffyyy** [comment]
when was the last time you updated?

**Comment by RunDevilRun007** [comment]
I just updated today, literally downloaded the latest version a few hours ago.

**Comment by Luffyyy** [comment]
Send me the full log please.

**Comment by RunDevilRun007** [comment]
[2017_09_02_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1272281/2017_09_02_log.txt)

**Comment by PootinPoopin** [comment]
yah so crashes on lauch, i have the latest update 2.41 and cant delete it because it says that i need permission from my own pc... so cant play

**Comment by Luffyyy** [comment]
You probably had some file opened somewhere and BLT wasn't able to delete it properly, anyway make a new issue report please.
