### ISSUE TITLE
BeardLib and Custom Barrel; other player crash in online play.

### ISSUE THREAD

**Issue by Alcat101** [simon-wh/PAYDAY-2-BeardLib#9]
So I'm not sure how to write this issue, since I doesn't really know what the technical cause of it...

I've been making custom weapon attachment with BeardLib, and I've hit some weird problem with it.
My newest custom weapon attachment: http://lastbullet.net/mydownloads.php?action=view_down&did=17680
It takes Brenner-21 LMG Foregrip (FG), and modded it as foregrip attachment for G3.
I can play with the weapon and said custom attachment just fine. Playing in safehouse, or play a game that I host myself.

Problem arise, that when I play online -with the G3 and the custom attachment- it seems I can't establish connection to other player/client on every kind of game I got into.
I'll be listing on all problems I got below:
- If I host, and use the G3 and said FG, any client can't connect to my game whatsoever. Both in lobby and in-game. Connecting in-game, the game's system would only tell that they are joining and disconnected momentarily, without any joining percentage happening.
- If I join another game, and use the G3 and said FG, I'll be disconnected from the game with the 'Can't connect to Host' message. 
  In lobby, I could see the host (indicated with host heister and weapon model loading up) but any other player won't load at all, then I got disconnected from the lobby.
  In in-game briefing screen, only Host would have READY status on them, all other client will have JOINING status without it ever changing, then I got disconnected from the game.
- If I Host or join another game, with weapon any other than G3 and said FG, I can connect to everyone just fine. But when I switch the weapon to G3 and said FG, Then I'll meet the same problem.
- Using G3 without said FG, any game I host/join works just fine.

Note here that I don't get crashes whatsoever with G3 and said FG. I can't just establish proper connection with other player when playing with the gun and custom attachment on.

Now some clarification on what my mod does:
The mod above takes Brenner-21 LMG Foregrip and modded them as available Foregrip G3 can use.
Since Brenner-21 Foregrip is built on 2 different parts (the barrel shroud/cover and the foregrip stuff [ironsight, handgrip, carry handle, little black box on the right side of barrel]) when modded in with base from any G3 foregrip, I must combine them into 1 object.
I delete the handgrip object, since G3 animation doesn't use them. Previously I have made mod that delete some object in a weapon model, and it works just fine.

I think that's what I can tell from my problem with BeardLib mod.
I could tell other things that I think might be the issue, but it stems mostly on how it'll look in-game and I don't think it'll cause problem with how BeardLib work, but should you need all the detail, I'll provide it ASAP.

**Comment by Alcat101** [comment]
So I'm not sure how to write this issue, since I doesn't really know what the technical cause of it...

I've been making custom weapon attachment with BeardLib, and I've hit some weird problem with it.
My newest custom weapon attachment: http://lastbullet.net/mydownloads.php?action=view_down&did=17680
It takes Brenner-21 LMG Foregrip (FG), and modded it as foregrip attachment for G3.
I can play with the weapon and said custom attachment just fine. Playing in safehouse, or play a game that I host myself.

Problem arise, that when I play online -with the G3 and the custom attachment- it seems I can't establish connection to other player/client on every kind of game I got into.
I'll be listing on all problems I got below:

- If I host, and use the G3 and said FG, any client can't connect to my game whatsoever. Both in lobby and in-game. Connecting in-game, the game's system would only tell that they are joining and disconnected momentarily, without any joining percentage happening.

- If I join another game, and use the G3 and said FG, I'll be disconnected from the game with the 'Can't connect to Host' message. 
In lobby, I could see the host (indicated with host heister and weapon model loading up) but any other player won't load at all, then I got disconnected from the lobby.
In in-game briefing screen, only Host would have READY status on them, all other client will have JOINING status without it ever changing, then I got disconnected from the game.

- If I Host or join another game, with weapon any other than G3 and said FG, I can connect to everyone just fine. But when I switch the weapon to G3 and said FG, Then I'll meet the same problem with point no 2.

- Using G3 without said FG, any game I host/join works just fine.

Note here that I don't get crashes whatsoever with G3 and said FG. I can't just establish proper connection with other player when playing with the gun and custom attachment on.


Now some clarification on what my mod does:
The mod above takes Brenner-21 LMG Foregrip and modded them as available Foregrip G3 can use.
Since Brenner-21 Foregrip is built on 2 different parts (the barrel shroud/cover and the foregrip stuff [ironsight, handgrip, carry handle, little black box on the right side of barrel]) when modded in with base from any G3 foregrip, I must combine them into 1 object.
I delete the handgrip object, since G3 animation doesn't use them. Previously I have made mod that delete some object in a weapon model, and it works just fine.

I think that's what I can tell from my problem with BeardLib mod.
I could tell other things that I think might be the issue, but it stems mostly on how it'll look in-game and I don't think it'll cause problem with how BeardLib work, but should you need all the detail, I'll provide it ASAP.

**Comment by Alcat101** [comment]
I think this is just a limitation from BeardLib end..

For now, I'll avoid making mod that tamper with weapon parts that weapon Barrel depends on.

**Comment by simon-wh** [comment]
It's a very unusual issue to experience, I would be very surprised if BeardLib is at fault. Could you give me the exact stuff you're using so I can try and replicate?

**Comment by Alcat101** [comment]
Yes, it's a consistent issue.

Noep (author of DMCWO) said that the weapon I mod (G3) have a peculiar characteristic. The barrel part of the weapon is attached to the foregrip and not the weapon body frame.
This make any kind of mod that give new stuff to foregrip to G3 unable to sync to other player, because the other player don't know my G3 weapon have a new stuff for foregrip and as a result the game for the player don't know where to attach the G3 barrel and disconnect.

Since I've also experienced problem on modding in new stuff for Barrel weapon part (other client can't sync and disconnect from me), I thought it's a plausible reason.


Here's the mod files.
I've re enable the problematic stuff on it, it's listed as Foregrip on G3.
[G3 to HK21 Conversion Kit (test).zip](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/533291/G3.to.HK21.Conversion.Kit.test.zip)

**Comment by simon-wh** [comment]
That shouldn't change anything though, the weapons don't have network sync. Everything is spawned locally when it comes to player weapons.

**Comment by Alcat101** [comment]
Well, from what I experienced on modding stuff directly with BeardLib..

Any mod that gives new stuff on Barrel parts to existing weapon seems to disconnect either me or anyone on lobby I joined or lobby I host.
