### ISSUE TITLE
new crash

### ISSUE THREAD

**Issue by chromKa** [simon-wh/PAYDAY-2-BeardLib#90]
Application has crashed: C++ exception
[string "--mods/BeardLib/Classes/BeardLibModsMenu.lua..."]:219: attempt to index field 'update_assets_module' (a nil value)

SCRIPT STACK

RunCallback() 315
MousePressed() 68
MousePressed() 154
MousePressed() 154
MousePressed() 154
mouse_press() 333
lib/managers/mousepointermanager.lua:308

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???

**Comment by Luffyyy** [comment]
fixed in 2.31
