### ISSUE TITLE
Game crashes after splash screen

### ISSUE THREAD

**Issue by GeneralDelphox** [simon-wh/PAYDAY-2-BeardLib#91]
I'm not exactly sure what's the cause, but this keeps happening. When I roll back to the last BeardLib version that works for me, version 2.2.8, everything works fine. Any recent versions I try to use would just crash my game.
[crash.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1273036/crash.txt)

**Comment by Luffyyy** [comment]
blt log?

**Comment by GeneralDelphox** [comment]
[2017_09_03_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib/files/1273163/2017_09_03_log.txt)

**Comment by Luffyyy** [comment]
please list all of your beardlib mods(custom content only)
