### ISSUE TITLE
Crashing right after start (Could be related to specific characters)

### ISSUE THREAD

**Issue by Antumarin** [simon-wh/PAYDAY-2-BeardLib#98]
I've recently downloaded a Music Module mod which contained the characters "копия" in the folder's name. That seemed to be enough to crash the game as soon as it starts.

The line in the log reads:

> 05:34:10 PM Lua: [BeardLib] [ERROR] Config file at path 'assets/mod_overrides/Step Right Up [Summer Sideshow KF2 Menu] - копия/main.xml' is not readable!

Adding those characters to any other type of Beardlib based mod (mods with a main.xml file) causes it to crash and removing said characters seems to solve the problem.

**Comment by Luffyyy** [comment]
> God those blt file functions are so broken
I'll try pushing an update tomorrow to fix that, in the way changing any blt file function and use overkill ones instead.
