### ISSUE TITLE
Restoration Mod Issue

### ISSUE THREAD

**Issue by WhyDoesGitHubLetYouHaveLongUsernames** [simon-wh/PAYDAY-2-BeardLib#99]
When starting up Restoration Mod with beardlib installed, a popup saying that I need to download beardlib for Restoration Mod pulls up. I hit download now and restart, as it asks me too but after relaunching the game the popup again shows up. I tried reinstalling BeardLib twice, both from the workshop and the github (which is why I'm here) but it still doesn't work. Any suggestions would be appreciated.

**Comment by Luffyyy** [comment]
this is a Restoration / BLT issue, for the time being restoration should remove libraries/dependencies from mod.txt because as of now, BLT doesn't count mods without an updater(BeardLib uses its own updater) a library.
